Repository toggl/mobileapp, pull requests merged in 2018-04, with the labels that each got.

#1827 Return int in the density conversion extension
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Autocomplete/TokenSpan.cs
  Toggl.Giskard/Bindings/ViewMarginTargetBinding.cs
  Toggl.Giskard/Extensions/NumberExtensions.cs
  Toggl.Giskard/Fragments/SelectBeginningOfWeekFragment.cs
  Toggl.Giskard/Fragments/SelectColorFragment.cs
  Toggl.Giskard/Fragments/SelectDateFormatFragment.cs
  Toggl.Giskard/Fragments/SelectDurationFormatFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Views/HueSaturationPickerView.cs
  Toggl.Giskard/Views/MainRecyclerViewSuggestionsViewHolder.cs
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
  Toggl.Giskard/Views/PieChartView.cs
  Toggl.Giskard/Views/ReportsRecyclerViewHolder.cs
  Toggl.Giskard/Views/SuggestionsRecyclerView.cs
  Toggl.Giskard/Views/SuggestionsRecyclerViewHolder.cs
Labels: android

#1822 Make sure all separators are correct
  Toggl.Daneel/ViewControllers/EditProjectViewController.xib
  Toggl.Daneel/ViewControllers/SelectClientViewController.xib
  Toggl.Daneel/ViewControllers/SelectTagsViewController.xib
  Toggl.Daneel/ViewControllers/SelectWorkspaceViewController.xib
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
  Toggl.Daneel/Views/EntityCreation/ClientViewCell.xib
  Toggl.Daneel/Views/EntityCreation/SelectableTagViewCell.cs
  Toggl.Daneel/Views/EntityCreation/SelectableTagViewCell.designer.cs
  Toggl.Daneel/Views/EntityCreation/SelectableTagViewCell.xib
  Toggl.Daneel/Views/EntityCreation/WorkspaceViewCell.xib
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.xib
  Toggl.Daneel/Views/Reports/ReportsHeaderView.xib
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.xib
  Toggl.Daneel/Views/StartTimeEntry/ProjectSuggestionViewCell.xib
  Toggl.Daneel/Views/StartTimeEntry/StartTimeEntryEmptyViewCell.xib
  Toggl.Daneel/Views/StartTimeEntry/StartTimeEntryViewCell.xib
  Toggl.Daneel/Views/StartTimeEntry/TagSuggestionViewCell.xib
  Toggl.Daneel/Views/StartTimeEntry/WorkspaceHeaderViewCell.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#1828 Calculate calendar height
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/ReportsCalendarFragment.axml
  Toggl.Giskard/Views/ReportsLinearLayout.cs
Labels: android, blocking

#1823 Add selection splash of color to calendar cells
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsCalendarFragmentDayCell.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/CalendarDayView.cs
Labels: android

#1824 Fix reports layout
  Toggl.Daneel/ViewSources/ReportsTableViewSource.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.xib
Labels: ios

#1840 Change create project button color
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
Labels: android

#1836 Start view UI fixes
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#1810 Add Licenses
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.cs
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.xib
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.cs
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.xib
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
  Toggl.Daneel/ViewSources/LicensesTableViewSource.cs
  Toggl.Daneel/Views/Settings/LicensesHeaderViewCell.cs
  Toggl.Daneel/Views/Settings/LicensesHeaderViewCell.designer.cs
  Toggl.Daneel/Views/Settings/LicensesHeaderViewCell.xib
  Toggl.Daneel/Views/Settings/LicensesViewCell.cs
  Toggl.Daneel/Views/Settings/LicensesViewCell.designer.cs
  Toggl.Daneel/Views/Settings/LicensesViewCell.xib
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/Toggl.Foundation.MvvmCross.csproj
  Toggl.Foundation.MvvmCross/ViewModels/Settings/AboutViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/LicensesViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/FoundationTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/AboutViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LicensesViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/Foundation.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Services/BaseLicenseProvider.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Multivac/License.cs
  Toggl.Ultrawave/Network/UserAgent.cs
Labels: foundation, ios

#1839 Token colors
  Toggl.Giskard/Autocomplete/ProjectTokenSpan.cs
  Toggl.Giskard/Autocomplete/TagsTokenSpan.cs
  Toggl.Giskard/Autocomplete/TokenSpan.cs
Labels: android

#1802 Reports client name
  Toggl.Daneel/Extensions/LabelExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.cs
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.designer.cs
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.xib
  Toggl.Foundation.Tests/Reports/ProjectSummaryReportTests.cs
  Toggl.Foundation.Tests/Reports/ReportsProviderTests.cs
  Toggl.Foundation/Reports/ChartSegment.cs
  Toggl.Foundation/Reports/ReportsProvider.cs
Labels: foundation, ios

#1807 Onboarding phase 1 - steps 2 and 3
  Toggl.Daneel/Onboarding/CreationView/DisabledConfirmationButtonOnboardingStep.cs
  Toggl.Daneel/Resources/Images.xcassets/icCheckGrey.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icCheckGrey.imageset/icCheckGrey.png
  Toggl.Daneel/Resources/Images.xcassets/icCheckGrey.imageset/icCheckGrey@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icCheckGrey.imageset/icCheckGrey@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: ios

#1842 Implement shortcut apis for Droid
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Giskard/ApplicationShortcutCreator.cs
  Toggl.Giskard/Helper/ApiAvailability.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android

#1855 Fixes problem with failing tests
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombinerTests.cs
Labels: bug

#1854 Onboarding: fix weak subscriptions
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#1853 Add animations for onboarding tooltips
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
Labels: ios

#1848 Fix the :bug: - once and for all
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/SelectProjectViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectProjectTableViewSource.cs
  Toggl.Daneel/ViewSources/StartTimeEntryTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/NestableObservableCollection.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: bug, ios

#1843 Splashing
  Toggl.Giskard/Activities/OnboardingActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/book.png
  Toggl.Giskard/Resources/drawable-hdpi/timer.png
  Toggl.Giskard/Resources/drawable-hdpi/toggl_logo.png
  Toggl.Giskard/Resources/drawable-mdpi/book.png
  Toggl.Giskard/Resources/drawable-mdpi/timer.png
  Toggl.Giskard/Resources/drawable-mdpi/toggl_logo.png
  Toggl.Giskard/Resources/drawable-xhdpi/book.png
  Toggl.Giskard/Resources/drawable-xhdpi/timer.png
  Toggl.Giskard/Resources/drawable-xhdpi/toggl_logo.png
  Toggl.Giskard/Resources/drawable-xxhdpi/book.png
  Toggl.Giskard/Resources/drawable-xxhdpi/timer.png
  Toggl.Giskard/Resources/drawable-xxhdpi/toggl_logo.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/book.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/timer.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/toggl_logo.png
  Toggl.Giskard/Resources/drawable/OnboardingGradient.xml
  Toggl.Giskard/Resources/layout/OnboardingActivity.axml
  Toggl.Giskard/Resources/layout/SplashScreen.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1869 Fix switch colors
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1871 Do not focus the description field by default
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
Labels: android

#1837 Send feedback
  Toggl.Daneel/Services/MailService.cs
  Toggl.Foundation/Services/IMailService.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Services/MailService.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: android

#1870 Fix date time picker colors
  Toggl.Giskard/Fragments/SelectDateTimeFragment.cs
  Toggl.Giskard/Resources/values/Styles.xml
Labels: android

#1867 Fix section margin for log
  Toggl.Giskard/Resources/layout/MainLogHeader.axml
Labels: android

#1858 Suggestion view fixes
  Toggl.Giskard/Resources/layout/MainSuggestions.axml
  Toggl.Giskard/Views/SuggestionsRecyclerViewHolder.cs
Labels: android

#1850 Calendar Shortcuts
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarBaseQuickSelectShortcut.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsCalendarFragment.axml
  Toggl.Giskard/Resources/layout/ReportsCalendarShortcutCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/CalendarShortcutsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1872 Update the layout of the logout button
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
Labels: android

#1856 Remove unused items for beta
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
Labels: android

#1849 Jupiter Hotfix #3 - 1.4.3 #2
  Toggl.Daneel/Info.plist
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/SelectProjectViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectProjectTableViewSource.cs
  Toggl.Daneel/ViewSources/StartTimeEntryTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/NestableObservableCollection.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: ios, wip

#1866 Fix main app navigation buttons
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/arrow_back.png
  Toggl.Giskard/Resources/drawable-mdpi/arrow_back.png
  Toggl.Giskard/Resources/drawable-xhdpi/arrow_back.png
  Toggl.Giskard/Resources/drawable-xxhdpi/arrow_back.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/arrow_back.png
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/SelectClientActivity.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivity.axml
  Toggl.Giskard/Resources/layout/SelectTagsActivity.axml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
Labels: android

#1868 Change tags button color
  Toggl.Giskard/Resources/layout/SelectTagsActivity.axml
Labels: android

#1874 Token reset screen
  Toggl.Giskard/Activities/TokenResetActivity.cs
  Toggl.Giskard/Presenters/TogglPresenter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/TokenResetActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1880 Configure Giskard PlayStore builds
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  build.cake
Labels: android

#1847 Add onboarding phase 3
  Toggl.Daneel/Onboarding/StartTimeEntryView/AddProjectOrTagOnboardingStep.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.PrimeRadiant.Tests/Onboarding/DismissableOnboardingStepTests.cs
  Toggl.PrimeRadiant.Tests/Toggl.PrimeRadiant.Tests.csproj
  Toggl.PrimeRadiant/Onboarding/DismissableOnboardingStep.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: ios

#1885 Fix paddings for main toolbar
  Toggl.Giskard/Resources/layout/MainActivity.axml
Labels: android

#1881 Browser Service implementation
  Toggl.Giskard/Services/BrowserService.cs
Labels: android

#1878 Outdated App View
  Toggl.Giskard/Activities/OutdatedAppActivity.cs
  Toggl.Giskard/Presenters/TogglPresenter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/ic_illustration_error_spider.png
  Toggl.Giskard/Resources/drawable-mdpi/ic_illustration_error_spider.png
  Toggl.Giskard/Resources/drawable-xhdpi/ic_illustration_error_spider.png
  Toggl.Giskard/Resources/drawable-xxhdpi/ic_illustration_error_spider.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/ic_illustration_error_spider.png
  Toggl.Giskard/Resources/layout/OutdatedAppActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1795 Polish the edit view to adapt size when billable is hidden
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
Labels: ios

#1825 Onboarding phase 2 - step 1
  Toggl.Daneel/Onboarding/MainView/EditTimeEntryOnboardingStep.cs
  Toggl.Daneel/Resources/Images.xcassets/emojiRaisedHands.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/emojiRaisedHands.imageset/emoji1.png
  Toggl.Daneel/Resources/Images.xcassets/emojiRaisedHands.imageset/emoji1@2x.png
  Toggl.Daneel/Resources/Images.xcassets/emojiRaisedHands.imageset/emoji1@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.designer.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: ios

#1873 Fix reports calendar sticking out
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
Labels: ios

#1896 Fix reports layout on iPhone X
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
Labels: ios

#1892 Simplify the remaining character counter and prevent bugs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/Views/EditTimeEntry/TextViewWithCharacterCounter.cs
Labels: bug, ios

#1879 Add AppStore link for iOS
  Toggl.Daneel/Services/BrowserService.cs
Labels: ios

#1904 Remove Resource.designer.cs
  Toggl.Giskard/Resources/Resource.designer.cs
Labels: android

#1902 Change cursor color to white
  Toggl.Giskard/Resources/drawable/EditTextWhiteCursor.xml
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1901 Fix the gap between items in reports
  Toggl.Giskard/Views/CalendarRecyclerView.cs
Labels: android

#1924 Onboarding phase 4
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/Onboarding/MainView/SwipeLeftOnboardingStep.cs
  Toggl.Daneel/Onboarding/MainView/SwipeRightOnboardingStep.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
Labels: blocking, ios

#1925 Fix picker issue when editing end time
  Toggl.Daneel/Binding/DatePickerDateTimeOffsetTargetBinding.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
Labels: ios

#1926 Refactor the way the tags are shown
  Toggl.Giskard/Adapters/TagsListRecyclerAdapter.cs
  Toggl.Giskard/Bindings/TextViewTagListTargetBinding.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/EditTimeEntryTagCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/TemplateSelectors/TagsListTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/TagsListRecyclerView.cs
Labels: android

#1877 Enable toggling tasks in Edit View
  Toggl.Giskard/Adapters/SelectProjectRecyclerAdapter.cs
  Toggl.Giskard/Adapters/StartTimeEntryRecyclerAdapter.cs
  Toggl.Giskard/Resources/layout/SelectProjectActivity.axml
  Toggl.Giskard/Views/SelectProjectWithExpandableTasksRecyclerViewHolder.cs
Labels: android

#1931 Fix border below tags editor
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#1936 Fix empty log tooltip
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
Labels: bug, ios

#1934 Skip swipe to continue step on iOS 10
  Toggl.Daneel/Onboarding/MainView/SwipeRightOnboardingStep.cs
Labels: ios

#1940 Make deadlock tests SUPER fast
  Toggl.Foundation.Tests/Sync/DeadlockTests.cs
Labels: blocking, foundation

#1939 Fix randomly failing unit tests
  Toggl.Foundation.MvvmCross/App.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
Labels: blocking, bug, foundation

#1319 Droid UI tests
  Toggl.Daneel.Tests.UI/AppExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel.Tests.UI/Toggl.Daneel.Tests.UI.csproj
  Toggl.Daneel.Tests.UI/packages.config
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard.Tests.UI/AppExtensions.cs
  Toggl.Giskard.Tests.UI/Configuration.cs
  Toggl.Giskard.Tests.UI/Toggl.Giskard.Tests.UI.csproj
  Toggl.Giskard.Tests.UI/packages.config
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Tests.UI/Extensions/LoginExtensions.cs
  Toggl.Tests.UI/Extensions/OnboardingExtensions.cs
  Toggl.Tests.UI/Helpers/Attributes.cs
  Toggl.Tests.UI/OnboardingTests.cs
  Toggl.Tests.UI/ReplTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
  Toggl.sln
  build.cake
Labels: android, snoozed

#1948 Register singleton under the interface type
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
Labels: crash

#1945 Make calendar shortcuts in reports appear to be scrollable
  Toggl.Daneel/ViewControllers/ReportsCalendarViewController.cs
  Toggl.Daneel/ViewControllers/ReportsCalendarViewController.xib
  Toggl.Daneel/ViewSources/ReportsCalendarQuickSelectCollectionViewSource.cs
  Toggl.Daneel/Views/Reports/ReportsCalendarQuickSelectViewCell.cs
Labels: ios, pending-review

#1950 Vertically center the description when a suggestion only has the description
  Toggl.Daneel/Views/Suggestions/SuggestionView.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.designer.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.xib
Labels: ios, pending-review

#1938 Fix updating the log when a TE is created
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
Labels: glitch, ios

#1933 Add swipe animation
  Toggl.Daneel/Converters/CollectionSizeToHeightConverter.cs
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/Extensions/TimeEntriesLogViewCellExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.xib
  Toggl.Daneel/Views/Suggestions/SuggestionsView.cs
Labels: ios

#1954 Projects view empty state copy updates
  Toggl.Daneel/ViewControllers/SelectProjectViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#1959 Fix randomly failing test
  Toggl.PrimeRadiant.Tests/RepositoryTests.cs
Labels: bug

#1951 :construction: Refactor StartTimeEntryViewModel initialization
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: bug

#1970 Remove resetting of the onboarding storage on logout
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
Labels: ios

#1964 📐Update constraints
  Toggl.Daneel/ViewControllers/EditDurationViewController.xib
  Toggl.Daneel/ViewControllers/EditProjectViewController.xib
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/ViewControllers/LoginViewController.xib
  Toggl.Daneel/ViewControllers/OutdatedAppViewController.xib
  Toggl.Daneel/ViewControllers/SelectBeginningOfWeekViewController.xib
  Toggl.Daneel/ViewControllers/SelectClientViewController.xib
  Toggl.Daneel/ViewControllers/SelectColorViewController.xib
  Toggl.Daneel/ViewControllers/SelectDateTimeViewController.xib
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.xib
  Toggl.Daneel/ViewControllers/SelectProjectViewController.xib
  Toggl.Daneel/ViewControllers/SelectTagsViewController.xib
  Toggl.Daneel/ViewControllers/SelectWorkspaceViewController.xib
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
  Toggl.Daneel/ViewControllers/TokenResetViewController.xib
Labels: ios

#1974 Onboarding phase 4: dismiss after doing the swipe right gesture
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/Extensions/TimeEntriesLogViewCellExtensions.cs
  Toggl.Daneel/Onboarding/MainView/SwipeLeftOnboardingStep.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Multivac/Extensions/ObservableExtensions.cs
Labels: blocking, ios

#1987 Remove unnecessary view models initialization
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
Labels: bug

#1976 :sparkles: Integrate AppCenter for Giskard
  Toggl.Giskard/Services/AnalyticsService.cs
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/packages.config
Labels: android

#1994 Rename the `IBaseModel` interface
  Toggl.Foundation/IRepositoryExtensions.cs
  Toggl.Foundation/Models/FoundationConstructors.tt
  Toggl.Foundation/Models/FoundationModels.tt
  Toggl.Multivac/Models/IClient.cs
  Toggl.Multivac/Models/IIdentifiable.cs
  Toggl.Multivac/Models/IPreferences.cs
  Toggl.Multivac/Models/IProject.cs
  Toggl.Multivac/Models/ITag.cs
  Toggl.Multivac/Models/ITask.cs
  Toggl.Multivac/Models/ITimeEntry.cs
  Toggl.Multivac/Models/IUser.cs
  Toggl.Multivac/Models/IWorkspace.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.tt
  Toggl.PrimeRadiant.Realm/Repository.cs
  Toggl.PrimeRadiant.Tests/TestModel.cs
  Toggl.Ultrawave/Models/ModelConstructors.tt
Labels: foundation, refactoring

#1996 Add IDeletable interface
  Toggl.Foundation.Tests/Mocks/MockTag.cs
  Toggl.Foundation.Tests/Sync/ConflictResolution/PreferNewerTests.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Models/Tag.cs
  Toggl.Foundation/Sync/ConflictResolution/PreferNewer.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/ClientSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/ISyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/ProjectSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/TagSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/TaskSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/TimeEntrySyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/UserSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/WorkspaceSyncSelector.cs
  Toggl.Multivac/Models/IClient.cs
  Toggl.Multivac/Models/IDeletable.cs
  Toggl.Multivac/Models/IProject.cs
  Toggl.Multivac/Models/ITag.cs
  Toggl.Multivac/Models/ITimeEntry.cs
  Toggl.Multivac/Models/IWorkspace.cs
  Toggl.PrimeRadiant.Realm/Database.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.PrimeRadiant.Realm/Models/RealmTag.cs
  Toggl.Ultrawave.Tests/Models/TagTests.cs
  Toggl.Ultrawave/Models/ModelConstructors.cs
  Toggl.Ultrawave/Models/Tag.cs
Labels: foundation, refactoring

#1997 Add `ILastChangedDatable` interface
  Toggl.Foundation.Tests/Mocks/MockWorkspace.cs
  Toggl.Foundation.Tests/Sync/ConflictResolution/PreferNewerTests.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Sync/ConflictResolution/PreferNewer.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/ClientSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/ISyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/ProjectSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/TagSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/TaskSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/TimeEntrySyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/UserSyncSelector.cs
  Toggl.Foundation/Sync/ConflictResolution/Selectors/WorkspaceSyncSelector.cs
  Toggl.Multivac/Models/IClient.cs
  Toggl.Multivac/Models/ILastChangedDatable.cs
  Toggl.Multivac/Models/IProject.cs
  Toggl.Multivac/Models/ITag.cs
  Toggl.Multivac/Models/ITask.cs
  Toggl.Multivac/Models/ITimeEntry.cs
  Toggl.Multivac/Models/IUser.cs
  Toggl.Multivac/Models/IWorkspace.cs
  Toggl.PrimeRadiant.Realm/Models/RealmWorkspace.cs
  Toggl.Ultrawave.Tests/Models/WorkspaceTests.cs
  Toggl.Ultrawave/Models/Workspace.cs
Labels: foundation, refactoring
