Repository toggl/mobileapp, pull requests merged in 2018-09, with the labels that each got.

#3129 Create the calendar notification properties in the user preferences storage
  Toggl.Daneel/Services/UserDefaultsStorage.cs
  Toggl.Giskard/Services/SharedPreferencesStorage.cs
  Toggl.PrimeRadiant.Tests/Settings/SettingsStorageTests.cs
  Toggl.PrimeRadiant/Settings/IKeyValueStorage.cs
  Toggl.PrimeRadiant/Settings/IUserPreferences.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: foundation, storage

#3028 Fix calendar time entry creation flows
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
Labels: foundation

#3136 Notification settings view model
  Toggl.Foundation.MvvmCross/Helper/UpcomingEventsOption.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectFromListParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectFromListViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/NotificationSettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/UpcomingEventsNotificationSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/NotificationSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectFromListViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: foundation

#3144 Add unit test for pull sync state
  Toggl.Foundation.Tests/Sync/States/Pull/PersistListStateTests.cs
Labels: foundation

#3146 Add package references for updated VS
  Toggl.Daneel.SiriExtension/Toggl.Daneel.SiriExtension.csproj
  Toggl.Daneel.SiriExtension/packages.config
Labels: ios

#3141 Add Calendar Notifications
  Toggl.Daneel/Presentation/Attributes/TabPresentationAttribute.cs
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Daneel/Services/NotificationService.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Foundation.MvvmCross/Services/PermissionAwareCalendarService.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.Tests/Interactors/Notifications/ScheduleEventNotificationsInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Foundation/ApplicationUrls.cs
  Toggl.Foundation/Interactors/Calendar/GetCalendarItemWithIdInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Calendar.cs
  Toggl.Foundation/Interactors/Notifications/ScheduleEventNotificationsInteractor.cs
  Toggl.Foundation/Services/ICalendarService.cs
  Toggl.Giskard/Services/CalendarService.cs
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
Labels: foundation, ios

#3150 :bug: Fix crash when creating a time entry
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#3119 Implement stop intent
  Toggl.Daneel.IntentBinding/ApiDefinition.cs
  Toggl.Daneel.IntentBinding/StructsAndEnums.cs
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Intents.intentdefinition
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.h
  Toggl.Daneel.IntentStaticLib/libToggl.Daneel.IntentStaticLib.a
  Toggl.Daneel.SiriExtension/Exceptions/NoRunningEntryException.cs
  Toggl.Daneel.SiriExtension/IntentHandler.cs
  Toggl.Daneel.SiriExtension/Models/TimeEntry.cs
  Toggl.Daneel.SiriExtension/StopTimerIntentHandler.cs
  Toggl.Daneel.SiriExtension/Toggl.Daneel.SiriExtension.csproj
Labels: ios

#3145 Scroll to current time when calendar opens
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#3151 Make the switches behave as they should
  Toggl.Daneel/Extensions/UIKitRxExtensions/UISwitchRxExtensions.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
Labels: bug, ios

#3163 Fix incorrect transitions when entity changes during creation sync
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: bug, foundation

#3138 Fix te stopping bug on slow networks
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/Models/TimeEntry.cs
Labels: android, crash, ios

#3132 Undo delete UI
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/MainActivity.cs
Labels: android

#3024 Resize calendar in the TE edit flow to show all dates
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
Labels: android

#3007 🚧 Refcatore signup
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Giskard/Activities/SignUpActivity.ViewBinds.cs
  Toggl.Giskard/Activities/SignUpActivity.cs
  Toggl.Giskard/Resources/layout/SignUpActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, foundation, ios, refactoring

#3169 Add two Do extension methods
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
  Toggl.Foundation/Extensions/SyncManagerExtensions.cs
  Toggl.Foundation/Sync/States/CheckServerStatusState.cs
  Toggl.Foundation/Sync/States/Push/ResetAPIDelayState.cs
  Toggl.Foundation/TimeService.cs
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
  Toggl.Multivac/Extensions/RxAction/RxAction.cs
Labels: foundation, refactoring

#3173 Fix reports opening on Giskard
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, bug, foundation

#3133 🚧 Report workspace button refresh
  Toggl.Daneel/Converters/LambdaConverter.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/FadeViewRxExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation/DataSources/Interfaces/IWorkspacesSource.cs
  Toggl.Foundation/DataSources/WorkspacesDataSource.cs
Labels: bug, foundation

#2665 Onboarding phase 4
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Giskard/Activities/MainActivity.Onboardings.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
  Toggl.Giskard/Extensions/OnboardingExtensions.cs
  Toggl.Giskard/Extensions/PopupWindowWithDefaultGravityExtenstions.cs
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
Labels: android, on-hold

#3045 Giskard custom feedback ui
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SendFeedbackViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/SendFeedbackActivity.ViewBinds.cs
  Toggl.Giskard/Activities/SendFeedbackActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Extensions/UIExtensions.cs
  Toggl.Giskard/Extensions/VisibilityExtensions.cs
  Toggl.Giskard/Resources/layout/SendFeedbackActivity.axml
  Toggl.Giskard/Resources/menu/SendFeedbackMenu.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Services/DialogService.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
Labels: android

#3166 Scroll calendar when editing an entry
  Toggl.Daneel/Extensions/ScrollViewExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewAutoScrollHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#3180 Pick item foreground color based on Luma
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Foundation.MvvmCross/Extensions/ColorExtensions.cs
Labels: ios

#3157 Notification settings UI
  Toggl.Daneel/Cells/Settings/UpcomingEventsOptionCell.cs
  Toggl.Daneel/Cells/Settings/UpcomingEventsOptionCell.designer.cs
  Toggl.Daneel/Cells/Settings/UpcomingEventsOptionCell.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Settings/NotificationSettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/NotificationSettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/NotificationSettingsViewController.xib
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
  Toggl.Daneel/ViewControllers/Settings/UpcomingEventsNotificationSettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/UpcomingEventsNotificationSettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/UpcomingEventsNotificationSettingsViewController.xib
  Toggl.Daneel/ViewSources/UpcomingEventsNotificationSettingsSource.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectFromListParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectFromListViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/NotificationSettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/UpcomingEventsNotificationSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/NotificationSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectFromListViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/UpcomingEventsNotificationSettingsViewModelTests.cs
  Toggl.Foundation/Extensions/CalendarNotificationsOptionExtensions.cs
  Toggl.Foundation/Extensions/IUserPreferencesExtensions.cs
  Toggl.Multivac/CalendarNotificationsOption.cs
Labels: foundation, ios

#3188 Update current time indicator every minute
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#3168 Add 3D touch actions to calendar notification
  Toggl.Daneel/Services/NotificationService.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Foundation/ApplicationUrls.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#3187 Add navigation bar titles to the calendar and notification settings
  Toggl.Daneel/ViewControllers/Settings/CalendarSettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/NotificationSettingsViewController.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#3190 Consider user preferences when scheduling notifications
  Toggl.Foundation.Tests/Interactors/Notifications/ScheduleEventNotificationsInteractorTests.cs
  Toggl.Foundation/Interactors/InteractorFactory.Notifications.cs
  Toggl.Foundation/Interactors/Notifications/ScheduleEventNotificationsInteractor.cs
Labels: foundation

#3186 Keep the item being edited on always on top
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewItemLayoutAttributes.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#3191 But wait! There's more... icons.
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/SendFeedbackActivity.cs
  Toggl.Giskard/Activities/SignUpActivity.cs
  Toggl.Giskard/Extensions/UIExtensions.cs
  Toggl.Giskard/Extensions/VisibilityExtensions.cs
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
  Toggl.Giskard/ViewHolders/MainLogSuggestionItemViewHolder.cs
  Toggl.Giskard/ViewHolders/WorkspaceSelectionViewHolder.cs
Labels: android

#3175 Extension ui
  Toggl.Daneel.ExtensionKit/Toggl.Daneel.ExtensionKit.csproj
  Toggl.Daneel.IntentBinding/ApiDefinition.cs
  Toggl.Daneel.IntentBinding/StructsAndEnums.cs
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Intents.intentdefinition
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.h
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.m
  Toggl.Daneel.IntentStaticLib/libToggl.Daneel.IntentStaticLib.a
  Toggl.Daneel.SiriExtension.UI/Entitlements.plist
  Toggl.Daneel.SiriExtension.UI/Info.plist
  Toggl.Daneel.SiriExtension.UI/IntentViewController.cs
  Toggl.Daneel.SiriExtension.UI/IntentViewController.designer.cs
  Toggl.Daneel.SiriExtension.UI/MainInterface.storyboard
  Toggl.Daneel.SiriExtension.UI/Toggl.Daneel.SiriExtension.UI.csproj
  Toggl.Daneel.SiriExtension/StopTimerIntentHandler.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.sln
Labels: ios

#3205 Make UI switches larger
  Toggl.Daneel/Extensions/ViewExtensions.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
Labels: ios

#3202 Fix crash when clicking workspaces headers
  Toggl.Giskard/Adapters/CreateSuggestionSegmentedRecyclerAdapter.cs
  Toggl.Giskard/Bindings/ViewUpsideDownTargetBinding.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/GuardedMvxRecyclerViewHolder.cs
Labels: android, crash

#3207 Make sure event notifications are scheduled only for enabled calendars
  Toggl.Foundation.Tests/Interactors/Notifications/ScheduleEventNotificationsInteractorTests.cs
  Toggl.Foundation/Interactors/Notifications/ScheduleEventNotificationsInteractor.cs
Labels: bug, foundation

#3181 Set `At` date when soft deleting a time entry
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/Models/TimeEntry.cs
Labels: bug, foundation

#3198 Clean the reports view model code
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
Labels: foundation

#3213 Stop auto scrolling when long press ends
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#3211 Giskard notifications
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Activities/TokenResetActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Extensions/ActivityExtensions.cs
  Toggl.Giskard/Helper/PersistentNotificationsHelper.cs
  Toggl.Giskard/Resources/drawable/ic_icon_notrunning.xml
  Toggl.Giskard/Resources/drawable/ic_icon_running.xml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
  Toggl.PrimeRadiant/Settings/IUserPreferences.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: android, blocking

#3210 Mark Ghost TEs and prevent user from continuing them
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
  Toggl.Giskard/ViewHelpers/MainRecyclerViewTouchCallback.cs
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
Labels: android

#3206 Siri cleanup logout
  Toggl.Daneel.ExtensionKit/SharedStorage.cs
  Toggl.Daneel.SiriExtension/StopTimerIntentHandler.cs
  Toggl.Daneel/Services/IntentDonationService.cs
  Toggl.Daneel/Services/PrivateSharedStorageService.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/Services/IIntentDonationService.cs
  Toggl.Foundation/Services/IPrivateSharedStorageService.cs
  Toggl.Giskard/Services/DummyIntentDonationService.cs
  Toggl.Giskard/Services/DummyPrivateSharedStorageService.cs
Labels: ios

#3215 Fix issues with hidden welcome back text on main view
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: ios

#3233 Disable backups in Android
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Startup/TogglApplication.cs
Labels: android

#3236 Bindings on steroids
  Toggl.Daneel/Extensions/Binders/ReactiveTableViewBinder.cs
  Toggl.Daneel/Extensions/Reactive/FadeViewExtensions.cs
  Toggl.Daneel/Extensions/Reactive/NSConstraintExtensions.cs
  Toggl.Daneel/Extensions/Reactive/NSObjectExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UIApplicationExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UIButtonExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UIControlExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UIDatePickerExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UILabelExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UISwitchExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UITextFieldExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UITextViewExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UIViewExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/FadeViewRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/NSConstraintRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIApplicationRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIButtonRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIControlRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIDatePickerRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UILabelRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UITableViewRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UITextFieldRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UITextViewRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIViewRxExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/NoWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Views/Rating/RatingView.cs
  Toggl.Foundation.MvvmCross/Reactive/IReactive.cs
  Toggl.Giskard/Activities/AboutActivity.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/SendFeedbackActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Activities/SignUpActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Extensions/Reactive/CompoundButtonExtensions.cs
  Toggl.Giskard/Extensions/Reactive/EditTextExtensions.cs
  Toggl.Giskard/Extensions/Reactive/JavaObjectExtensions.cs
  Toggl.Giskard/Extensions/Reactive/RecyclerAdapterExtensions.cs
  Toggl.Giskard/Extensions/Reactive/SwipeRefreshLayoutExtensions.cs
  Toggl.Giskard/Extensions/Reactive/TextViewExtensions.cs
  Toggl.Giskard/Extensions/Reactive/ViewExtensions.cs
  Toggl.Giskard/Extensions/UIExtensions.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/AutocompleteEditText.cs
Labels: android, ios, refactoring

#3244 Clamp calendar item cells between the time range
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#3242 Fix calendar item shadows when editing
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
Labels: ios

#3183 Daneel 1.10 - Cil
  Toggl.Daneel/Info.plist
Labels: ios, release

#3238 Fix calendar onboarding visibility glitch
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
Labels: glitch, ios

#3223 Reload calendar whenever user resumes the app from background
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
Labels: foundation

#3228 Siri start with description
  Toggl.Daneel.IntentBinding/ApiDefinition.cs
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Intents.intentdefinition
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StartTimerIntent.h
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StartTimerIntent.m
  Toggl.Daneel.IntentStaticLib/libToggl.Daneel.IntentStaticLib.a
  Toggl.Daneel.SiriExtension/StartTimerIntentHandler.cs
  Toggl.Daneel/Services/IntentDonationService.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Foundation.MvvmCross/Parameters/StartTimeEntryParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/Interactors/BaseInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Autocomplete/TextFieldInfo.cs
  Toggl.Foundation/Interactors/InteractorFactory.Definitions.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/CreateTimeEntryInteractor.cs
  Toggl.Foundation/Services/IIntentDonationService.cs
  Toggl.Giskard/Services/DummyIntentDonationService.cs
Labels: ios

#3255 Improve drag scrolling in calendar
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#3256 Fix edit hour indicator when duration is < 15 min
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/EditingHourSupplementaryView.xib
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewItemLayoutAttributes.cs
  Toggl.Foundation/Helper/Constants.cs
Labels: ios

#3220 Fix app freeze when opening from notification while app is in foreground
  Toggl.Foundation/ApplicationUrls.cs
  Toggl.Giskard/Helper/PersistentNotificationsHelper.cs
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android, bug

#3214 Neon - Giskard 1.4
  Toggl.Foundation/ApplicationUrls.cs
  Toggl.Giskard/Helper/PersistentNotificationsHelper.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Startup/TogglApplication.cs
Labels: android, release

#3267 Prevent having multiple query text spans and an crash
  Toggl.Daneel/Autocomplete/AutocompleteExtensions.cs
Labels: crash, ios

#3235 Add workspace selection into Reports view
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Giskard/Activities/ReportsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Adapters/ReportsRecyclerAdapter.cs
  Toggl.Giskard/Resources/drawable/workspace_white.xml
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/ReportsActivityHeader.axml
  Toggl.Giskard/Resources/layout/ReportsActivityWorkspaceName.axml
  Toggl.Giskard/Services/DialogService.cs
  Toggl.Giskard/TemplateSelectors/ReportsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/ListSelectionDialog.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
Labels: android

#3226 Add no workspace UI for giskard
  Toggl.Foundation.MvvmCross/Services/ErrorHandlingService.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Services/ErrorHandlingServiceTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/NoWorkspaceViewModelTests.cs
  Toggl.Giskard/Fragments/NoWorkspaceFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/NoWorkspaceFragment.cs
  Toggl.Giskard/Resources/color/BlueTextColor.xml
  Toggl.Giskard/Resources/drawable-hdpi/ic_illustration_error_workspace.png
  Toggl.Giskard/Resources/drawable-mdpi/ic_illustration_error_workspace.png
  Toggl.Giskard/Resources/drawable-xhdpi/ic_illustration_error_workspace.png
  Toggl.Giskard/Resources/drawable-xxhdpi/ic_illustration_error_workspace.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/ic_illustration_error_workspace.png
  Toggl.Giskard/Resources/layout/NoWorkspaceFragment.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.PrimeRadiant/Settings/IAccessRestrictionStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: android

#3272 Fix calendar item icons
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewAutoScrollHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: glitch, ios

#3278 Fix creating new tags and projects with emoji from the start time entry view
  Toggl.Daneel/Autocomplete/AutocompleteExtensions.cs
  Toggl.Foundation.MvvmCross/Extensions/AutocompleteExtensions.cs
  Toggl.Foundation.Tests/Autocomplete/AutocompleteExtensionsTests.cs
Labels: bug, ios

#3276 Prevent notification sounds in Oreo/Pie
  Toggl.Giskard/Extensions/ActivityExtensions.cs
Labels: android

#3280 Fix crash in edit time entry viewmodel (maybe)
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
Labels: foundation

#3277 Remove specific methods from the TimeEntriesDataSource
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/DeleteTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/StopTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/UpdateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation/DataSources/Interfaces/ITimeEntriesSource.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/DeleteTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/StopTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/UpdateTimeEntryInteractor.cs
  Toggl.Foundation/Sync/States/CleanUp/DeleteNonReferencedProjectGhostsState.cs
  Toggl.Foundation/Sync/States/CleanUp/DeleteOldEntriesState.cs
Labels: foundation, refactoring

#3287 Fix refresh header crash
  Toggl.Daneel/Extensions/Binders/ReactiveTableViewBinder.cs
  Toggl.Daneel/ViewSources/Generic/ReactiveSectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/SectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/CollectionChangesListBuilder.cs
  Toggl.Foundation.MvvmCross/Collections/ObservableGroupedOrderedCollection.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/ObservableGroupedOrderedListTests.cs
  Toggl.Giskard/Activities/MainActivity.Onboardings.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
Labels: crash

#3274 ⏰ refresh certain TE elements when significant time change detected
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Hints/ReloadLogHint.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/TimeServiceTests.cs
  Toggl.Foundation/ITimeService.cs
  Toggl.Foundation/TimeService.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/BroadcastReceivers/TimezoneChangedBroadcastReceiver.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, ios

#3285 Add better Hebrew rendering
  Toggl.Giskard/Resources/layout/MainLogCell.axml
Labels: android

#3196 Use swipe gestures to close modal views and open edit view for currently running TE
  Toggl.Daneel/Presentation/Transition/ModalPresentationController.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/IDismissableViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/SelectBeginningOfWeekViewController.cs
  Toggl.Daneel/ViewControllers/SelectClientViewController.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.cs
  Toggl.Daneel/ViewControllers/SelectDateFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectProjectViewController.cs
  Toggl.Daneel/ViewControllers/SelectTagsViewController.cs
  Toggl.Daneel/ViewControllers/SelectWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/Views/EditDuration/WheelForegroundView.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: ios

#3297 Avoid a crash by showing the emoji in the onboarding for api >= 23
  Toggl.Giskard/Resources/values-v23/Strings.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#3307 Add Sum extension method over Timespans
  Toggl.Daneel/Views/Log/TimeEntriesLogHeaderView.cs
  Toggl.Giskard/ViewHolders/MainLogSectionViewHolder.cs
  Toggl.Multivac.Tests/Extensions/EnumerableExtensions.cs
  Toggl.Multivac/Extensions/EnumerableExtensions.cs
Labels: foundation

#3303 Avoid a crash by showing the emoji in the onboarding for api >= 23
  Toggl.Giskard/Resources/values-v23/Strings.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#3304 Fix a crash when presenting a popup window and the activity is not running
  Toggl.Giskard/Extensions/OnboardingExtensions.cs
Labels: android

#3308 Add HashCode T4 template for variable number of type parameters
  Toggl.Multivac/HashCode.cs
  Toggl.Multivac/Toggl.Multivac.csproj
Labels: foundation

#3313 Fix calendar glitches introduced by iOS 12
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/HourSupplementaryView.xib
Labels: ios

#3299 Giskard main log diffutil
  Toggl.Daneel/Extensions/Binders/ReactiveTableViewBinder.cs
  Toggl.Daneel/ViewSources/Generic/ReactiveSectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/SectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/CollectionChangesListBuilder.cs
  Toggl.Foundation.MvvmCross/Collections/ObservableGroupedOrderedCollection.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/ObservableGroupedOrderedListTests.cs
  Toggl.Foundation.Tests/Toggl.Foundation.Tests.csproj
  Toggl.Giskard/Activities/MainActivity.Onboardings.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
  Toggl.Multivac.Tests/StringExtensionTests.cs
  Toggl.Multivac.Tests/Toggl.Multivac.Tests.csproj
  Toggl.Multivac/Extensions/EnumerableExtensions.cs
  Toggl.Multivac/HashCode.cs
  Toggl.Multivac/Toggl.Multivac.csproj
  Toggl.PrimeRadiant.Tests/Toggl.PrimeRadiant.Tests.csproj
  Toggl.Ultrawave.Tests.Integration/Toggl.Ultrawave.Tests.Integration.csproj
  Toggl.Ultrawave.Tests/Toggl.Ultrawave.Tests.csproj
Labels: android
