Repository toggl/mobileapp, pull requests merged in 2018-06, with the labels that each got.

#2341 Fix back button image glitch in iOS 10
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/icBack.png
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/icBack@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/icBack@3x.png
Labels: glitch, ios

#2357 Fetch two months of time entries
  Toggl.Foundation.Tests/Sync/States/Pull/FetchAllSinceStateTests.cs
  Toggl.Foundation/Sync/States/Pull/FetchAllSinceState.cs
Labels: foundation

#2351 Ghosts
  Toggl.Foundation.Tests/Sync/ConflictResolution/PreferNewerTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/CreateGhostProjectsStateTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Sync/ConflictResolution/PreferNewer.cs
  Toggl.Foundation/Sync/States/Pull/CreateGhostProjectsState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.PrimeRadiant/SyncStatus.cs
Labels: blocking, sync

#2368 Fix edit menu in start view
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
  Toggl.Daneel/Views/EditDuration/DurationField.cs
Labels: bug, ios

#2126 Adjust datetime fragment dialog window gravity
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
Labels: android

#2370 Fix sign up with Google button title
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Resources/layout/SignUpActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#2377 Create workspace API
  Toggl.Ultrawave.Tests.Integration/Helper/WorkspaceHelper.cs
  Toggl.Ultrawave.Tests.Integration/ProjectsApiTests.cs
  Toggl.Ultrawave.Tests.Integration/TagsApiTests.cs
  Toggl.Ultrawave.Tests.Integration/UserApiTests.cs
  Toggl.Ultrawave.Tests.Integration/WorkspaceFeaturesApiTests.cs
  Toggl.Ultrawave.Tests.Integration/WorkspacesApiTests.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IWorkspacesApi.cs
  Toggl.Ultrawave/ApiClients/UserApi.cs
  Toggl.Ultrawave/ApiClients/WorkspacesApi.cs
  Toggl.Ultrawave/Network/Endpoints/WorkspaceEndpoints.cs
Labels: api

#2371 Fix main log header date formatting
  Toggl.Foundation.MvvmCross/Converters/DateToTitleStringValueConverter.cs
  Toggl.Foundation.Tests/MvvmCross/Converters/DateToTitleStringValueConverterTests.cs
Labels: android

#2339 Fix TE description extraction method
  Toggl.Giskard/Autocomplete/TokenExtensions.cs
  Toggl.Giskard/Bindings/EditTextTextFieldInfoTargetBinding.cs
Labels: android

#2360 Load time pickers on DateTime Popup with fixed 24hrs mode
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
Labels: android

#2340 Put login inside a Storyboard
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Login.storyboard
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/LoginViewController.xib
  Toggl.Daneel/ViewControllers/Navigation/OnboardingFlowNavigationController.cs
Labels: ios, refactoring

#2380 Remove keyboard icon from timepicker
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
Labels: android

#2381 Cautiously detect 3D shortcut type
  Toggl.Daneel/Startup/AppDelegate.cs
Labels: ios

#2367 Fix duration formatting
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Giskard/Resources/layout/MainLogHeader.axml
Labels: android

#2384 Remove duplicated height convertion to dips
  Toggl.Giskard/Fragments/SelectColorFragment.cs
Labels: android

#2385 Fix workspace feature enabling logic
  Toggl.Foundation.Tests/Mocks/MockWorkspaceFeatureCollection.cs
  Toggl.Foundation/Interactors/Abstract/WorkspaceHasFeatureInteractor.cs
  Toggl.Foundation/Models/WorkspaceFeatureCollection.cs
  Toggl.Multivac/Extensions/WorkspaceFeatureCollectionExtensions.cs
  Toggl.Multivac/Models/IWorkspaceFeatureCollection.cs
  Toggl.PrimeRadiant.Realm/Models/RealmWorkspaceFeatureCollection.cs
  Toggl.Ultrawave.Tests/Models/WorkspaceFeaturesTests.cs
  Toggl.Ultrawave/Models/WorkspaceFeatureCollection.cs
  Toggl.Ultrawave/Serialization/PropertiesFilters/RequiresFeatureAttributeFilter.cs
Labels: foundation

#2359 Giskard 0.4 - Beryllium
  Toggl.Giskard/Properties/AndroidManifest.xml
Labels: android

#2390 Database operation failed exception with type
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.PrimeRadiant.Realm/BaseStorage.cs
  Toggl.PrimeRadiant.Tests/BaseStorageTests.cs
  Toggl.PrimeRadiant.Tests/RepositoryTests.cs
  Toggl.PrimeRadiant.Tests/SingleObjectStorageTests.cs
  Toggl.PrimeRadiant/Exceptions/DatabaseOperationException.cs
  Toggl.PrimeRadiant/Exceptions/EntityNotFoundException.cs
Labels: foundation

#2397 Add reports empty state
  Toggl.Giskard/Resources/drawable-hdpi/reports.png
  Toggl.Giskard/Resources/drawable-mdpi/reports.png
  Toggl.Giskard/Resources/drawable-xhdpi/reports.png
  Toggl.Giskard/Resources/drawable-xxhdpi/reports.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/reports.png
  Toggl.Giskard/Resources/layout/ReportsActivityHeader.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2391 Fix popup height when time entry is stopped.
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
Labels: android

#2403 Add firebase performance monitoring
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/packages.config
Labels: ios, metrics

#2394 Bind click in reports to hide calendar
  Toggl.Giskard/Resources/layout/ReportsActivityHeader.axml
Labels: android

#2405 Remove all Giskard's Resources.Designer.cs files
  .gitignore
Labels: android

#2399 Reports Calendar: Jump calendar page to selected view when selecting shortcut
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
Labels: android

#2362 Ghosts tracking
  Toggl.Foundation.Tests/Sync/States/Pull/CreateGhostProjectsStateTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Sync/States/Pull/CreateGhostProjectsState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
Labels: sync

#2355 Try fetch inaccessible projects
  Toggl.Foundation.Tests/Sync/States/Pull/ApiExceptionsCatchingPersistStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/TryFetchInaccessibleProjectsStateTests.cs
  Toggl.Foundation/Extensions/PersistStateExtensions.cs
  Toggl.Foundation/Models/Project.cs
  Toggl.Foundation/Sync/States/Pull/ApiExceptionsCatchingPersistState.cs
  Toggl.Foundation/Sync/States/Pull/TryFetchInaccessibleProjectsState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: sync

#2402 Fix project not opening bug
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: android

#2220 Avatar image
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Helper/ImageUtils.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
Labels: android

#2378 Simplify rivals resolution
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.PrimeRadiant.Realm/RealmAdapter.cs
Labels: storage

#2396 Refactor client model
  Toggl.Foundation/DataSources/ClientsDataSource.cs
  Toggl.Foundation/Models/Client.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Multivac/Ensure.cs
Labels: foundation

#2407 Add common extensions to core projects
  Toggl.Foundation.MvvmCross/Extensions/ObservableExtensions.cs
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
Labels: foundation, refactoring

#2409 Add initial Android binding helpers
  Toggl.Giskard/Activities/NonBindingAppCompatActivity.cs
  Toggl.Giskard/Adapters/BaseRecyclerAdapter.cs
  Toggl.Giskard/Adapters/SimpleAdapter.cs
  Toggl.Giskard/Extensions/UIExtensions.cs
  Toggl.Giskard/Resources/layout/SettingsActivityWorkspaceCell.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/BaseRecyclerViewHolder.cs
  Toggl.Giskard/ViewHolders/WorkspaceSelectionViewHolder.cs
Labels: android, refactoring

#2372 Integrate Firebase Performance
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/packages.config
Labels: android, metrics

#2408 Add initial iOS binding helpers
  Toggl.Daneel/Extensions/UIExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
Labels: ios, refactoring

#2387 Fix Edit View running TE stop/current time
  Toggl.Foundation.MvvmCross/Converters/StripAmPmValueConverter.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
Labels: android

#2414 Change splash screen
  Toggl.Giskard/Resources/drawable-hdpi/logo_splash.png
  Toggl.Giskard/Resources/drawable-mdpi/logo_splash.png
  Toggl.Giskard/Resources/drawable-xhdpi/logo_splash.png
  Toggl.Giskard/Resources/drawable-xxhdpi/logo_splash.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/logo_splash.png
  Toggl.Giskard/Resources/layout/SplashScreen.axml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2415 Fix feedback intent
  Toggl.Giskard/Services/MailService.cs
Labels: android

#2401 Refactor analytics service
  Toggl.Daneel/Services/AnalyticsService.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Foundation.MvvmCross/TrackingNavigationService.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ForgotPasswordViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/OnboardingViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/AnalyticsService/AnalyticsEventAttributeInitializerTests.cs
  Toggl.Foundation.Tests/Interactors/ContinueMostRecentTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ForgotPasswordViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/OnboardingViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/CreateGhostProjectsStateTests.cs
  Toggl.Foundation.Tests/Sync/SyncManagerTests.cs
  Toggl.Foundation/Analytics/AnalyticsEvent.cs
  Toggl.Foundation/Analytics/AnalyticsEventAttribute.cs
  Toggl.Foundation/Analytics/AnalyticsEventAttributeInitializer.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsEvent.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
  Toggl.Foundation/Interactors/TimeEntry/ContinueMostRecentTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/CreateTimeEntryInteractor.cs
  Toggl.Foundation/Sync/States/Pull/CreateGhostProjectsState.cs
  Toggl.Foundation/Sync/SyncManager.cs
  Toggl.Giskard/Services/AnalyticsService.cs
Labels: foundation

#2428 show keyboard when edit view appears
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
Labels: ios

#2427 Increase start button hitbox
  Toggl.Daneel/ViewControllers/MainViewController.xib
Labels: ios

#2423 Fix Google login
  Toggl.Giskard/Services/GoogleService.cs
Labels: android

#2438 Shake the email, password fields if invalid
  Toggl.Daneel/Extensions/ViewExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Login.storyboard
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/LoginViewController.designer.cs
Labels: ios

#2431 Fix `total duration` and `duration format` not updating
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
Labels: foundation, ios

#2424 Add ISyncState interface
  Toggl.Foundation.Tests/Sync/DeadlockTests.cs
  Toggl.Foundation.Tests/Sync/StateTreeTests.cs
  Toggl.Foundation.Tests/Sync/TestSyncState.cs
  Toggl.Foundation/Sync/ISyncState.cs
  Toggl.Foundation/Sync/States/CheckServerStatusState.cs
  Toggl.Foundation/Sync/States/InvalidTransitionState.cs
  Toggl.Foundation/Sync/States/Pull/ApiExceptionsCatchingPersistState.cs
  Toggl.Foundation/Sync/States/Pull/DeleteNonReferencedProjectGhostsState.cs
  Toggl.Foundation/Sync/States/Pull/DeleteOldEntriesState.cs
  Toggl.Foundation/Sync/States/Pull/FetchAllSinceState.cs
  Toggl.Foundation/Sync/States/Pull/IPersistState.cs
  Toggl.Foundation/Sync/States/Push/DeleteLocalEntityState.cs
  Toggl.Foundation/Sync/States/Push/Interfaces/IPushEntityState.cs
  Toggl.Foundation/Sync/States/Push/Interfaces/IPushState.cs
  Toggl.Foundation/Sync/States/Push/PushOneEntityState.cs
  Toggl.Foundation/Sync/States/Push/ResetAPIDelayState.cs
  Toggl.Foundation/Sync/States/Push/TryResolveClientErrorState.cs
  Toggl.Foundation/Sync/States/Push/UnsyncableEntityState.cs
  Toggl.Foundation/Sync/TransitionHandlerProvider.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: refactoring, sync

#2422 Add metrics to Edit View
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/EditViewTapSource.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: foundation, metrics

#2440 Shake the invalid fields for signup
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.designer.cs
  Toggl.Daneel/ViewControllers/SignupViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
Labels: ios

#2430 Show numpad only when user clicks on duration for edit view
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/Parameters/EditDurationParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: ios

#2398 Detect if no workspaces exist
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/Services/ErrorHandlingService.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.Tests/DataSources/TogglDataSourceTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/Services/ErrorHandlingServiceTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/NoWorkspaceExceptionsThrowingPersistStateTests.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Exceptions/NoWorkspaceException.cs
  Toggl.Foundation/Extensions/PersistStateExtensions.cs
  Toggl.Foundation/Services/IErrorHandlingService.cs
  Toggl.Foundation/Sync/States/Pull/NoWorkspaceExceptionsThrowingPersistState.cs
  Toggl.Foundation/Sync/SyncManager.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: sync

#2436 Rxfactor the SettingsViewModel
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/KeyboardAwareViewController.cs
  Toggl.Daneel/ViewControllers/ReactiveViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/IReactiveBindingHolder.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/Mocks/MockPreferences.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.User.cs
  Toggl.Foundation/Interactors/User/GetUserAvatarInteractor.cs
  Toggl.Giskard/Activities/ReactiveActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/layout/SettingsActivityWorkspaceCell.axml
  Toggl.Giskard/TemplateSelectors/SettingsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/WorkspaceSelectionViewHolder.cs
Labels: android, foundation, ios, refactoring

#2456 Show only one of AM/PM labels
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
Labels: android

#2463 Change adapter name for consistency
  Toggl.Giskard/Adapters/BaseRecyclerAdapter.cs
  Toggl.Giskard/ViewHolders/BaseRecyclerViewHolder.cs
Labels: android, refactoring

#2449 Inaccessible project display
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntryViewModelTests.cs
  Toggl.Foundation/Autocomplete/Suggestions/TaskSuggestion.cs
  Toggl.Foundation/Autocomplete/Suggestions/TimeEntrySuggestion.cs
  Toggl.Foundation/Extensions/ThreadSafeExtensions.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: foundation

#2448 Startview metrics
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/StartViewTapSource.cs
Labels: metrics, on-hold

#2468 Make status bars black where white status bars are used on pre-marshmallow
  Toggl.Giskard/Extensions/ActivityExtensions.cs
Labels: android

#2465 Rxfactor the About view
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.cs
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.designer.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/AboutViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/AboutViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
Labels: ios, refactoring

#2421 Track exceptions using AppCenter Crashes
  Toggl.Daneel/Services/AnalyticsService.cs
  Toggl.Foundation.Tests/Extensions/ExceptionExtensionsTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Extensions/ExceptionExtensions.cs
  Toggl.Giskard/Services/AnalyticsService.cs
  Toggl.Multivac/IsAnonymizedAttribute.cs
  Toggl.Ultrawave.Tests/Extensions/UriExtensionsTests.cs
  Toggl.Ultrawave/Exceptions/ApiException.cs
  Toggl.Ultrawave/Extensions/UriExtensions.cs
Labels: android, ios, metrics

#2464 Add means to bind lists on iOS
  Toggl.Daneel/Cells/BaseTableHeaderFooterView.cs
  Toggl.Daneel/Cells/BaseTableViewCell.cs
  Toggl.Daneel/Cells/SyncFailures/SyncFailureCell.cs
  Toggl.Daneel/Cells/SyncFailures/SyncFailureCell.designer.cs
  Toggl.Daneel/Cells/SyncFailures/SyncFailureCell.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/SyncFailuresViewController.cs
  Toggl.Daneel/ViewSources/ListTableViewSource.cs
  Toggl.Foundation.MvvmCross/ViewModels/SyncFailuresViewModel.cs
Labels: ios, refactoring

#2485 Complex event metrics
  Toggl.Foundation.Tests/AnalyticsService/ComplexEventsTrackingTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/ITrackableEvent.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
  Toggl.Foundation/Toggl.Foundation.csproj
Labels: metrics, refactoring

#2473 Fetch time entries created "today" on the initial pull sync
  Toggl.Foundation.Tests/Sync/States/Pull/FetchAllSinceStateTests.cs
  Toggl.Foundation/Sync/States/Pull/FetchAllSinceState.cs
  Toggl.Ultrawave.Tests.Integration/TimeEntriesApiTests.cs
Labels: sync

#2417 Fix text field title glitch on login screen
  Toggl.Daneel/Views/LoginTextField.cs
Labels: ios

#2466 Remove Giskard-like dependency from VM by RXFactorization
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.ViewBinds.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, refactoring

#1796 Handle UserIsMissingApiTokenException on Login & Signup
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/Login/LoginManagerTests.cs
  Toggl.Foundation/Extensions/LoginManagerExtensions.cs
  Toggl.Foundation/Login/LoginManager.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
Labels: foundation

#2479 Track when the user doesn't have a default workspace
  Toggl.Foundation.Tests/Sync/States/Pull/TrackNoDefaultWorkspaceStateTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Extensions/PersistStateExtensions.cs
  Toggl.Foundation/Sync/States/Pull/TrackNoDefaultWorkspaceState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: metrics, sync

#2508 Track missing api tokens
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/Login/LoginManagerTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/LoginSignupAuthenticationMethod.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
  Toggl.Foundation/Login/LoginManager.cs
Labels: metrics

#2499 Start time entry event with more data
  Toggl.Foundation.Tests/AnalyticsService/StartTimeEntryEventTests.cs
  Toggl.Foundation.Tests/Interactors/ContinueMostRecentTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/ITrackableEvent.cs
  Toggl.Foundation/Analytics/StartTimeEntryEvent.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
  Toggl.Foundation/Interactors/TimeEntry/ContinueMostRecentTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/CreateTimeEntryInteractor.cs
Labels: metrics

#2519 Fix setups missing WithLastTimeUsageStorage call
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: android, blocking, foundation, ios

#2525 Set the value of the version label correctly
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
Labels: glitch, ios

#2489 Rxfactor the Licenses view
  Toggl.Daneel/Cells/Settings/LicensesHeaderViewCell.cs
  Toggl.Daneel/Cells/Settings/LicensesHeaderViewCell.designer.cs
  Toggl.Daneel/Cells/Settings/LicensesHeaderViewCell.xib
  Toggl.Daneel/Cells/Settings/LicensesViewCell.cs
  Toggl.Daneel/Cells/Settings/LicensesViewCell.designer.cs
  Toggl.Daneel/Cells/Settings/LicensesViewCell.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.cs
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.xib
  Toggl.Daneel/ViewSources/LicensesTableViewSource.cs
  Toggl.Daneel/Views/Settings/LicensesHeaderViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/LicensesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LicensesViewModelTests.cs
Labels: ios, refactoring

#2516 Fix help button
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
Labels: bug, ios

#2527 Add long press to start time entry button
  Toggl.Daneel/Binding/ViewLongPressCommandTargetBinding.cs
  Toggl.Daneel/Extensions/ViewBindingExtensions.cs
  Toggl.Daneel/Startup/SetupTargetFactories.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: ios

#2532 Rainbow wheel
  Toggl.Daneel/Views/EditDuration/WheelForegroundView.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Multivac.Tests/MathTests.cs
  Toggl.Multivac/Extensions/ArrayExtensions.cs
  Toggl.Multivac/Math.cs
Labels: ios

#2533 Let the tags on the Edit TE view be clickable to open the tags selection view
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#2530 Logout to allow account selection
  Toggl.Daneel/Services/GoogleService.cs
  Toggl.Foundation/Login/IGoogleService.cs
  Toggl.Foundation/Login/LoginManager.cs
  Toggl.Giskard/Services/GoogleService.cs
Labels: android, ios

#2522 Add about view for Android
  Toggl.Giskard/Activities/AboutActivity.ViewBinds.cs
  Toggl.Giskard/Activities/AboutActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Resources/layout/AboutActivity.axml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2539 Uniformise Android settings UI Items
  Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
Labels: android

#2549 Bind top constraint to the safe area in the sign up view
  Toggl.Daneel/ViewControllers/SignupViewController.xib
Labels: glitch, ios

#2521 Revamp the tags toolbar
  Toggl.Foundation.MvvmCross/ViewModels/SelectTagsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTagsViewModelTests.cs
  Toggl.Giskard/Resources/layout/SelectTagsActivity.axml
Labels: android

#2535 Fix duration field ellipsis
  Toggl.Daneel/Views/EditDuration/DurationField.cs
  Toggl.Daneel/Views/EditDuration/DurationFieldTextFormatter.cs
  Toggl.Multivac.Tests/DurationHelperTests.cs
  Toggl.Multivac/DurationHelper.cs
Labels: glitch, ios

#2552 Move OnboardingSteps from Daneel to Foundation
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/Onboarding/CreationView/DisabledConfirmationButtonOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/EditView/CategorizeTimeUsingProjectsOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/MainView/EditTimeEntryOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/MainView/StartTimeEntryOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/MainView/StopTimeEntryOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/MainView/SwipeLeftOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/MainView/SwipeRightOnboardingStep.cs
  Toggl.Foundation.MvvmCross/Onboarding/StartTimeEntryView/AddProjectOrTagOnboardingStep.cs
Labels: foundation, ios

#2556 Add tooltip layouts for Droid
  Toggl.Giskard/Resources/drawable/TooltipShape.xml
  Toggl.Giskard/Resources/drawable/black_diamond.xml
  Toggl.Giskard/Resources/drawable/white_close.xml
  Toggl.Giskard/Resources/layout/TooltipWithCenteredBottomArrow.axml
  Toggl.Giskard/Resources/layout/TooltipWithLeftTopArrow.axml
  Toggl.Giskard/Resources/layout/TooltipWithRightBottomArrow.axml
  Toggl.Giskard/Resources/layout/TooltipWithRightTopArrow.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2555 Fix invalid cast
  Toggl.Daneel/Startup/AppDelegate.cs
Labels: crash, ios

#2497 Add metrics for checking status of entities push sync
  Toggl.Foundation.Tests/Sync/ITestAnalyticsService.cs
  Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BasePushEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/CreateEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/DeleteEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/TestModel.cs
  Toggl.Foundation.Tests/Sync/States/Push/UpdateEntityStateTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/SyncAnalyticsExtensions.cs
  Toggl.Foundation/Extensions/TypeExtensions.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Sync/PushSyncOperation.cs
  Toggl.Foundation/Sync/StateMachineOrchestrator.cs
  Toggl.Foundation/Sync/States/Push/BasePushEntityState.cs
  Toggl.Foundation/Sync/States/Push/CreateEntityState.cs
  Toggl.Foundation/Sync/States/Push/DeleteEntityState.cs
  Toggl.Foundation/Sync/States/Push/UpdateEntityState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: foundation, metrics, wip

#2565 Fix problems with the start button and the time entry card animations
  Toggl.Daneel/Extensions/AnimationExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/Extensions/ObservableExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Giskard/Activities/MainActivity.cs
Labels: blocking, ios
