Repository toggl/mobileapp, pull requests merged in 2018-02, with the labels that each got.

#1439 Sync error message in the edit view update
  Toggl.Daneel/Resources/Images.xcassets/icErrorEdit.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icErrorEdit.imageset/icErrorEdit.png
  Toggl.Daneel/Resources/Images.xcassets/icErrorEdit.imageset/icErrorEdit@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icErrorEdit.imageset/icErrorEdit@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/Views/EditTimeEntry/EditTimeEntryErrorView.cs
  Toggl.Daneel/Views/EditTimeEntry/EditTimeEntryErrorView.designer.cs
  Toggl.Daneel/Views/EditTimeEntry/EditTimeEntryErrorView.xib
Labels: ios

#1464 Remove unused TestFlight build config
  Toggl.Daneel.Tests.UI/Toggl.Daneel.Tests.UI.csproj
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.sln
  build.cake
Labels: ios

#1444 Client View
  Toggl.Foundation.MvvmCross/Parameters/SelectClientParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectClientViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableClientViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableColorViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableWorkspaceViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectClientViewModelTests.cs
  Toggl.Giskard/Activities/SelectClientActivity.cs
  Toggl.Giskard/Adapters/SelectClientRecyclerAdapter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/check.png
  Toggl.Giskard/Resources/drawable-mdpi/check.png
  Toggl.Giskard/Resources/drawable-xhdpi/check.png
  Toggl.Giskard/Resources/drawable-xxhdpi/check.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/check.png
  Toggl.Giskard/Resources/layout/SelectClientActivity.axml
  Toggl.Giskard/Resources/layout/SelectClientActivityCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelectClientTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/SelectClientRecyclerView.cs
Labels: android

#1482 Close Wheel view by tapping on background
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
Labels: ios

#1490 Use realm exception for crash reporting
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.PrimeRadiant.Realm/BaseStorage.cs
  Toggl.PrimeRadiant/Exceptions/EntityNotFoundException.cs
Labels: foundation

#1489 Fix reports calendar culture info
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: foundation

#1497 Fix task is removed when editing time entry
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
Labels: blocking, bug, ios

#1425 Status Bar colors
  Toggl.Giskard/Activities/BrowserActivity.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/OnboardingActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Extensions/ActivityExtensions.cs
  Toggl.Giskard/Helper/ApiAvailability.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1511 Fix creating duplicates in the time entries log
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
Labels: blocking, bug, critical, ios

#1505 Enable AppCenter Analytics
  Toggl.Daneel/Services/AnalyticsService.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/packages.config
Labels: ios

#1503 Add swipe actions
  Toggl.Daneel/ViewControllers/TimeEntriesLogViewController.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#1517 Fix select date issues in the creation view and edit view
  Toggl.Foundation.MvvmCross/Parameters/DateTimePickerParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: bug, critical, foundation

#1504 Fix incorrect tracking parameter
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
Labels: bug, foundation

#1518 Enable bouncing in the reports view
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
  Toggl.Daneel/ViewSources/ReportsTableViewSource.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.xib
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#1515 Hotfix 1.3.2
  Toggl.Daneel/Info.plist
  Toggl.Foundation.MvvmCross/Parameters/DateTimePickerParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: wip

#1531 Enable bouncing in the start view's autocomplete suggestions' list
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
Labels: ios

#1533 Enable bouncing in the onboarding scroll view
  Toggl.Daneel/ViewControllers/OnboardingViewController.xib
Labels: ios

#1353 Edit TE UI
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectDateTimeViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectDateTimeViewModelTests.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Bindings/TextViewTagListTargetBinding.cs
  Toggl.Giskard/Fragments/SelectDateTimeFragment.cs
  Toggl.Giskard/LinkerPleaseInclude.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditLayout.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/DurationEditText.cs
Labels: android, blocking, snoozed

#1506 Track sync errors
  Toggl.Daneel/Services/AnalyticsService.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/Sync/DeadlockTests.cs
  Toggl.Foundation.Tests/Sync/SyncManagerTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Sync/SyncManager.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.Giskard/Services/AnalyticsService.cs
Labels: ios

#1536 Preferences model
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Multivac/DurationFormat.cs
  Toggl.Multivac/Models/IPreferences.cs
  Toggl.Multivac/Models/IUser.cs
  Toggl.PrimeRadiant.Realm/Database.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.PrimeRadiant.Realm/Models/RealmUser.cs
  Toggl.Ultrawave.Tests.Integration/UserApiTests.cs
  Toggl.Ultrawave.Tests/Models/PreferencesTests.cs
  Toggl.Ultrawave.Tests/Models/UserTests.cs
  Toggl.Ultrawave/Models/ModelConstructors.cs
  Toggl.Ultrawave/Models/Preferences.cs
  Toggl.Ultrawave/Models/User.cs
Labels: foundation

#1548 Fix droid release compilation
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android

#1552 Use format structs in the preferences model
  Toggl.Multivac/Models/IPreferences.cs
  Toggl.Ultrawave.Tests/Models/PreferencesTests.cs
  Toggl.Ultrawave/Models/Preferences.cs
Labels: foundation

#1556 Tracking pages
  Toggl.Daneel/Services/AnalyticsService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/TrackingNavigationService.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: foundation, snoozed

#1554 Fix incorrect font size of the end time in the edit view
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
Labels: glitch, ios

#1547 Prevent race conditions when updating grouped tableviews
  Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs
Labels: crash, ios

#1553 Color view
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/SelectColorViewController.cs
  Toggl.Foundation.MvvmCross/Converters/ComplementValueConverter.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectColorViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectColorViewModelTests.cs
  Toggl.Giskard/Converters/DecimalToPercentageValueConverter.cs
  Toggl.Giskard/Fragments/SelectColorFragment.cs
  Toggl.Giskard/LinkerPleaseInclude.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable/ValueSliderThumb.xml
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Resources/layout/SelectColorFragment.axml
  Toggl.Giskard/Resources/layout/SelectColorFragmentCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelectColorTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/CircleView.cs
  Toggl.Giskard/Views/HueSaturationPickerView.cs
  Toggl.Giskard/Views/ValueSlider.cs
Labels: android

#1540 Api client for /me/preferences
  Toggl.Ultrawave.Tests.Integration/PreferencesApiTests.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IPreferencesApi.cs
  Toggl.Ultrawave/ApiClients/PreferencesApi.cs
  Toggl.Ultrawave/ITogglApi.cs
  Toggl.Ultrawave/Network/Endpoints/Endpoints.cs
  Toggl.Ultrawave/Network/Endpoints/PreferencesEndpoints.cs
  Toggl.Ultrawave/TogglApi.cs
Labels: blocking, foundation

#1560 Fix app crash when tapping projects/tags empty state
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewSources/StartTimeEntryTableViewSource.cs
Labels: blocking, crash, ios

#1558 Add preferences repository and data source
  Toggl.Foundation/DataSources/Interfaces/IPreferencesSource.cs
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Models/Preferences.cs
  Toggl.PrimeRadiant.Realm/Database.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.PrimeRadiant.Realm/Models/RealmPreferences.cs
  Toggl.PrimeRadiant.Realm/SingleObjectStorage.cs
  Toggl.PrimeRadiant.Tests/Realm/RealmSingleObjectStorageTests.cs
  Toggl.PrimeRadiant.Tests/Realm/TestAdapter.cs
  Toggl.PrimeRadiant/ISingleObjectStorage.cs
  Toggl.PrimeRadiant/ITogglDatabase.cs
  Toggl.PrimeRadiant/Models/IDatabasePreferences.cs
Labels: blocking

#1527 Add tags selection screen
  Toggl.Daneel/ViewSources/SelectTagsTableViewSource.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTagsViewModel.cs
  Toggl.Giskard/Activities/SelectTagsActivity.cs
  Toggl.Giskard/Adapters/SelectClientRecyclerAdapter.cs
  Toggl.Giskard/Adapters/SelectCreatableEntityRecyclerAdapter.cs
  Toggl.Giskard/Adapters/SelectTagsRecyclerAdapter.cs
  Toggl.Giskard/Bindings/TextViewTagListTargetBinding.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/checkbox_off.png
  Toggl.Giskard/Resources/drawable-hdpi/checkbox_on.png
  Toggl.Giskard/Resources/drawable-mdpi/checkbox_off.png
  Toggl.Giskard/Resources/drawable-mdpi/checkbox_on.png
  Toggl.Giskard/Resources/drawable-xhdpi/checkbox_off.png
  Toggl.Giskard/Resources/drawable-xhdpi/checkbox_on.png
  Toggl.Giskard/Resources/drawable-xxhdpi/checkbox_off.png
  Toggl.Giskard/Resources/drawable-xxhdpi/checkbox_on.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/checkbox_off.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/checkbox_on.png
  Toggl.Giskard/Resources/layout/EditLayout.axml
  Toggl.Giskard/Resources/layout/SelectTagsActivity.axml
  Toggl.Giskard/Resources/layout/SelectTagsActivityCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelectTagsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/SelectTagsRecyclerView.cs
Labels: android

#1559 Add datetime picker to the Wheel view
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/EditDurationViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditDurationViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
Labels: ios

#1567 Show username and email in settings
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android, blocking

#1570 Change the return value of the preferences API client Update method
  Toggl.Ultrawave/ApiClients/Interfaces/IPreferencesApi.cs
  Toggl.Ultrawave/ApiClients/PreferencesApi.cs
Labels: blocking, foundation

#1577 Convince linker to leave StringEnumConverter untouched
  Toggl.Daneel/LinkerPleaseInclude.cs
Labels: blocking, foundation

#1571 Add blank Projects screen
  Toggl.Giskard/Activities/SelectProjectActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditLayout.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, blocking

#1573 Add help to settings
  Toggl.Giskard/PlatformConstants.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#1580 Fix margins not updating on first pass
  Toggl.Giskard/Bindings/ViewMarginTargetBinding.cs
Labels: android

#1579 Display errors when adding projects
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#1584 Add cells for Select project UI
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/SelectProjectActivityProjectCell.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivityTaskCell.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivityWorkspaceHeader.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, blocking

#1582 Add 12/24 clock setting
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#1302 The Spider
  Toggl.Daneel/Binding/SpiderOnARopeViewIsVisibleTargetBinding.cs
  Toggl.Daneel/Extensions/ViewBindingExtensions.cs
  Toggl.Daneel/Resources/Images.xcassets/icJustSpider.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icJustSpider.imageset/icJustSpider.png
  Toggl.Daneel/Resources/Images.xcassets/icJustSpider.imageset/icJustSpider@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icJustSpider.imageset/icJustSpider@3x.png
  Toggl.Daneel/Startup/SetupTargetFactories.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/Views/SpiderOnARopeView.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
Labels: ios

#1585 Add scroll view to the settings view
  Toggl.Daneel/ViewControllers/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
Labels: ios

#1562 Add workspace selection in project creation
  Toggl.Giskard/Activities/EditProjectActivity.cs
  Toggl.Giskard/Bindings/TextViewFontWeightTargetBinding.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Fragments/SelectWorkspaceFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Resources/layout/SelectWorkspaceFragment.axml
  Toggl.Giskard/Resources/layout/SelectWorkspaceFragmentCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/TemplateSelectors/SelectWorkspaceTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1586 Extract task expandable project cell view holder
  Toggl.Giskard/Adapters/StartTimeEntryRecyclerAdapter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/SelectProjectWithExpandableTasksRecyclerViewHolder.cs
Labels: android, blocking

#1491 Track signup and login events
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation/Analytics/AuthenticationMethod.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
Labels: foundation

#1563 Pull preferences sync state
  Toggl.Foundation.Tests/Sync/ConflictResolution/OverwriteUnlessNeedsSyncTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistClientsStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistPreferencesStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistProjectsStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistTagsStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistTasksStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistTimeEntriesStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistWorkspaceFeaturesStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistWorkspacesStateTests.cs
  Toggl.Foundation/Sync/ConflictResolution/OverwriteUnlessNeedsSync.cs
  Toggl.Foundation/Sync/ConflictResolution/Resolver.cs
  Toggl.Foundation/Sync/States/Pull/FetchAllSinceState.cs
  Toggl.Foundation/Sync/States/Pull/FetchObservables.cs
  Toggl.Foundation/Sync/States/Pull/PersistPreferencesState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.Giskard/LinkerPleaseInclude.cs
Labels: blocking, foundation
