Repository toggl/mobileapp, pull requests merged in 2018-03, with the labels that each got.

#1600 Prevent NullReferenceException by switching order of initialization
  Toggl.Giskard/Adapters/StartTimeEntryRecyclerAdapter.cs
Labels: android

#1601 Parametric duration formatting
  Toggl.Foundation.MvvmCross/Combiners/DurationValueCombiner.cs
  Toggl.Foundation.MvvmCross/Converters/ParametricTimeSpanToDurationValueConverter.cs
  Toggl.Foundation.Tests/Extensions/TimeSpanExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/Combiners/DurationValueCombinerTests.cs
  Toggl.Foundation.Tests/MvvmCross/Converters/ParametricTimeSpanToDurationValueConverterTests.cs
  Toggl.Foundation/Extensions/TimeSpanExtensions.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: blocking, foundation

#1606 Fix jumping cursor
  Toggl.Daneel/Binding/TextFieldSecureTextEntryTargetBinding.cs
Labels: ios

#1609 Add time settings
  Toggl.Foundation.MvvmCross/ViewModels/SelectBeginningOfWeekViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableBeginningOfWeekViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/DTOs/EditUserDTO.cs
  Toggl.Foundation/DataSources/Interfaces/IUserSource.cs
  Toggl.Foundation/DataSources/UserDataSource.cs
  Toggl.Foundation/Models/User.cs
  Toggl.Giskard/Fragments/SelectBeginningOfWeekFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/SelectBeginningOfWeekFragment.axml
  Toggl.Giskard/Resources/layout/SelectBeginningOfWeekFragmentCell.axml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelectBeginningOfWeekTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, foundation

#1591 New timer page
  Toggl.Daneel/Binding/LayoutConstraintConstantTargetBinding.cs
  Toggl.Daneel/Converters/CollectionSizeToHeightConverter.cs
  Toggl.Daneel/Extensions/ViewBindingExtensions.cs
  Toggl.Daneel/Extensions/ViewBindingExtensions.tt
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/play.png
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/play@2x.png
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/play@3x.png
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/playIcon.png
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/playIcon@2x.png
  Toggl.Daneel/Resources/Images.xcassets/playIcon.imageset/playIcon@3x.png
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Startup/SetupTargetFactories.cs
  Toggl.Daneel/Startup/SetupTargetFactories.tt
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewControllers/SuggestionsViewController.cs
  Toggl.Daneel/ViewControllers/SuggestionsViewController.designer.cs
  Toggl.Daneel/ViewControllers/SuggestionsViewController.xib
  Toggl.Daneel/ViewControllers/TimeEntriesLogViewController.designer.cs
  Toggl.Daneel/ViewControllers/TimeEntriesLogViewController.xib
  Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/SuggestionsTableViewSource.cs
  Toggl.Daneel/ViewSources/SwipeToRefreshTableViewDelegate.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Daneel/Views/ActivityIndicatorView.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogEmptyStateViewCell.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogEmptyStateViewCell.designer.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogEmptyStateViewCell.xib
  Toggl.Daneel/Views/Log/TimeEntriesLogHeaderViewCell.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogHeaderViewCell.designer.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogHeaderViewCell.xib
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.xib
  Toggl.Daneel/Views/MainScrollView.cs
  Toggl.Daneel/Views/SpiderOnARopeView.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.designer.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.xib
  Toggl.Daneel/Views/Suggestions/SuggestionsEmptyViewCell.xib
  Toggl.Daneel/Views/Suggestions/SuggestionsView.cs
  Toggl.Daneel/Views/Suggestions/SuggestionsViewCell.cs
  Toggl.Daneel/Views/Suggestions/SuggestionsViewCell.designer.cs
  Toggl.Daneel/Views/Suggestions/SuggestionsViewCell.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SuggestionsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: foundation, ios

#1605 Current preferences observable
  Toggl.Foundation/DataSources/Interfaces/IPreferencesSource.cs
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
  Toggl.Foundation/Models/Preferences.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: blocking, foundation

#1621 Implement duration format settings editing
  Toggl.Foundation.MvvmCross/Converters/DurationFormatToStringValueConverter.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectDurationFormatViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableDurationFormatViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/DTOs/EditPreferencesDTO.cs
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
  Toggl.Foundation/Models/Preferences.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Fragments/SelectDurationFormatFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/SelectDurationFormatFragment.axml
  Toggl.Giskard/Resources/layout/SelectDurationFormatFragmentCell.axml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelectDurationFormatTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, blocking, foundation

#1630 Select duration format
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.designer.cs
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.xib
  Toggl.Daneel/ViewControllers/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
  Toggl.Daneel/ViewSources/DurationFormatsTableViewSource.cs
  Toggl.Daneel/Views/Settings/DurationFormatViewCell.cs
  Toggl.Daneel/Views/Settings/DurationFormatViewCell.designer.cs
  Toggl.Daneel/Views/Settings/DurationFormatViewCell.xib
Labels: ios

#1631 Use updated duration formatting in edit duration view and in the main view
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
Labels: ios

#1635 Use user's duration formatting preferences in reports
  Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation/Reports/ChartSegment.cs
Labels: ios

#1633 Use user's duration formatting preferences in the time entries' log
  Toggl.Daneel/Views/Log/TimeEntriesLogHeaderViewCell.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.cs
  Toggl.Foundation.MvvmCross/Collections/TimeEntryViewModelCollection.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntryViewModelCollectionTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntryViewModelTests.cs
Labels: ios

#1634 Convert from realm object to foundation object in preferences data source
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
Labels: blocking, ios

#1607 Google sign in
  Toggl.Giskard/ProGuard.cfg
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Services/GoogleService.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/google-services.json
  Toggl.Giskard/packages.config
  build.cake
  docs/env-vars.md
Labels: android

#1656 Add WorkspaceId to the WorkspaceGrouppedCollection
  Toggl.Foundation.MvvmCross/Collections/WorkspaceGroupedCollection.cs
  Toggl.Foundation.MvvmCross/Helper/AutocompleteExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
Labels: blocking, foundation

#1645 New droid timer view
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/SegmentedRecyclerAdapter.cs
  Toggl.Giskard/Adapters/TimeEntriesLogRecyclerAdapter.cs
  Toggl.Giskard/Fragments/TimeEntriesLogFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Giskard/Resources/layout/MainLogFooter.axml
  Toggl.Giskard/Resources/layout/MainLogHeader.axml
  Toggl.Giskard/Resources/layout/MainSuggestions.axml
  Toggl.Giskard/Resources/layout/MainSuggestionsCard.axml
  Toggl.Giskard/Resources/layout/TimeEntriesLogFragment.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/MainTemplateSelector.cs
  Toggl.Giskard/TemplateSelectors/SuggestionsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/MainRecyclerView.cs
  Toggl.Giskard/Views/MainRecyclerViewLogViewHolder.cs
  Toggl.Giskard/Views/MainRecyclerViewSuggestionsViewHolder.cs
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
  Toggl.Giskard/Views/SuggestionsRecyclerViewHolder.cs
  Toggl.Giskard/Views/TimeEntriesLogRecyclerView.cs
Labels: android, critical

#1637 Add value combiner for parametric date formatting
  Toggl.Foundation.MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombiner.cs
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombinerTests.cs
Labels: blocking, foundation

#1663 Time format combiner
  Toggl.Foundation.MvvmCross/Combiners/BaseTwoValuesCombiner.cs
  Toggl.Foundation.MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombiner.cs
  Toggl.Foundation.MvvmCross/Combiners/DateTimeOffsetTimeFormatValueCombiner.cs
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetTimeFormatValueCombinerTests.cs
Labels: blocking, foundation

#1632 Use parametric duration formatting for the duration input
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/Views/EditDuration/DurationField.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
Labels: blocking, ios

#1642 Push date format change
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
Labels: foundation

#1668 Fix misbehaving tests
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombinerTests.cs
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetTimeFormatValueCombinerTests.cs
Labels: blocking

#1644 First day of week settings
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/SelectBeginningOfWeekViewController.cs
  Toggl.Daneel/ViewControllers/SelectBeginningOfWeekViewController.designer.cs
  Toggl.Daneel/ViewControllers/SelectBeginningOfWeekViewController.xib
  Toggl.Daneel/ViewControllers/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
  Toggl.Daneel/ViewSources/BeginningOfWeekTableViewSource.cs
  Toggl.Daneel/Views/Settings/DayOfWeekViewCell.cs
  Toggl.Daneel/Views/Settings/DayOfWeekViewCell.designer.cs
  Toggl.Daneel/Views/Settings/DayOfWeekViewCell.xib
Labels: ios

#1658 Fix duration row cells margins
  Toggl.Daneel/Views/Settings/DurationFormatViewCell.xib
Labels: ios

#1659 Trigger force sync when tapping on the sync bar label when offline
  Toggl.Daneel/ViewSources/SwipeToRefreshTableViewDelegate.cs
Labels: ios

#1587 Persisting 24 hour time format settings
  Toggl.Daneel/ViewControllers/SettingsViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Multivac/TimeFormat.cs
Labels: foundation, ios

#1590 Sync preferences push state
  Toggl.Foundation.Tests/Sync/States/Push/Preferences/PushPreferencesStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/Preferences/UnsyncablePreferencesStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/Preferences/UpdatePreferencesStateTests.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Models/Preferences.cs
  Toggl.Foundation/Sync/States/Push/Preferences/PushPreferencesState.cs
  Toggl.Foundation/Sync/States/Push/Preferences/UnsyncablePreferencesState.cs
  Toggl.Foundation/Sync/States/Push/Preferences/UpdatePreferencesState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.Multivac/Extensions/PreferencesExtensions.cs
  Toggl.Multivac/Models/IPreferences.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.Ultrawave/Models/Preferences.cs
Labels: foundation

#1639 Avoid waiting for the storage in PreferencesDataSource constructor
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
Labels: foundation

#1669 Fix problem with manual mode text being truncated
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
Labels: ios

#1665 Parametric date time formatting
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: foundation, ios

#1648 Clear backstack when logging in/out
  Toggl.Giskard/Presenters/TogglPresenter.cs
Labels: android

#1672 Update displayed duration when editing is finished
  Toggl.Daneel/Views/EditDuration/DurationField.cs
Labels: blocking, ios

#1673 Queue preferences for push sync when updating
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
  Toggl.Foundation/Models/Preferences.cs
Labels: blocking, ios

#1682 Fix user model builder not copying user id
  Toggl.Foundation/Models/User.cs
Labels: bug, critical

#1484 Start time entry interactors
  Toggl.Daneel/Binding/AutocompleteTextViewTextInfoTargetBinding.cs
  Toggl.Foundation.MvvmCross/Autocomplete/BaseTextFieldInfoTargetBinding.cs
  Toggl.Foundation.MvvmCross/Collections/TimeEntryViewModelCollection.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SuggestionsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
  Toggl.Foundation.Tests/Autocomplete/AutocompleteProviderTests.cs
  Toggl.Foundation.Tests/Autocomplete/QueryInfoTests.cs
  Toggl.Foundation.Tests/Autocomplete/TextFieldInfoTests.cs
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/Generators/ViewModelGenerators.cs
  Toggl.Foundation.Tests/InteractorAwareTests.cs
  Toggl.Foundation.Tests/Interactors/StartTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Mocks/MockTimeEntryPrototype.cs
  Toggl.Foundation.Tests/MvvmCross/Autocomplete/BaseTextFieldInfoTargetBindingTests.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntryViewModelCollectionTests.cs
  Toggl.Foundation.Tests/Toggl.Foundation.Tests.csproj
  Toggl.Foundation/Autocomplete/TextFieldInfo.cs
  Toggl.Foundation/DataSources/Interfaces/ITimeEntriesSource.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Interactors/IInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.cs
  Toggl.Foundation/Interactors/Shared/CreateTimeEntryInteractor.cs
  Toggl.Foundation/Models/ITimeEntryPrototype.cs
  Toggl.Foundation/Suggestions/Suggestion.cs
  Toggl.Giskard/Bindings/EditTextTextFieldInfoTargetBinding.cs
  Toggl.Giskard/Services/GoogleService.cs
Labels: foundation

#1678 Queue updated user data for push sync
  Toggl.Foundation.Tests/DataSources/UserDataSourceTests.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/DataSources/UserDataSource.cs
  Toggl.Foundation/Models/User.cs
Labels: blocking, bug

#1685 Fix settings scrolling
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
Labels: ios

#1687 Add fade out for long suggestions
  Toggl.Daneel/Views/Suggestions/SuggestionView.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.designer.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.xib
Labels: blocking, ios

#1690 Fix operator precedence
  Toggl.Giskard/Adapters/StartTimeEntryRecyclerAdapter.cs
Labels: android, blocking, bug

#1694 Fix weird ui behavior when current time entry changes twice fast
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/FoundationTests.cs
  Toggl.Foundation.Tests/Generators/ConstructorTestData.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation/Foundation.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: bug, foundation

#1674 Update to Select Project ViewModel
  Toggl.Foundation.MvvmCross/Helper/AutocompleteExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
  Toggl.Multivac/Extensions/EnumerableExtensions.cs
Labels: blocking, foundation

#1693 Fix Droid project selection
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Giskard/Adapters/CreateSuggestionSegmentedRecyclerAdapter.cs
  Toggl.Giskard/Adapters/SelectProjectRecyclerAdapter.cs
  Toggl.Giskard/Resources/layout/SelectProjectActivity.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivityProjectCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelectProjectTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/SelectProjectRecyclerView.cs
Labels: android, blocking

#1686 Fix iOS project selection
  Toggl.Daneel/ViewControllers/SelectProjectViewController.cs
  Toggl.Daneel/ViewSources/CreateSuggestionGroupedTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectProjectTableViewSource.cs
Labels: blocking, ios

#1675 Support for multiple bundle ids
  Toggl.Daneel/Info.plist
  build.cake
Labels: ios, needs-design

#1657 Detect that user already has an account during sign up
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/LoginViewController.designer.cs
  Toggl.Daneel/ViewControllers/LoginViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Ultrawave.Tests.Integration/UserApiTests.cs
  Toggl.Ultrawave/ApiClients/UserApi.cs
  Toggl.Ultrawave/Exceptions/ApiException.cs
  Toggl.Ultrawave/Exceptions/EmailIsAlreadyUsedException.cs
Labels: foundation, ios

#1698 Fix separator and font size issue for first day of week settings view
  Toggl.Daneel/Views/Settings/DayOfWeekViewCell.xib
Labels: ios

#1700 Update reports calendar behavior
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
  Toggl.Daneel/ViewSources/ReportsTableViewSource.cs
Labels: ios

#1704 Update broken integration test
  Toggl.Ultrawave.Tests.Integration/UserApiTests.cs
Labels: bug

#1710 Change the save button
  Toggl.Daneel/Resources/Images.xcassets/doneGreen.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/doneGreen.imageset/doneGreen.png
  Toggl.Daneel/Resources/Images.xcassets/doneGreen.imageset/doneGreen@2x.png
  Toggl.Daneel/Resources/Images.xcassets/doneGreen.imageset/doneGreen@3x.png
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
Labels: ios

#1706 Improve GroupCollectionViewSource
  Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs
Labels: critical, ios

#1718 Fix settings crash
  Toggl.Daneel/ViewControllers/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/SettingsViewController.xib
Labels: ios

#1717 Use snackbars for showing sync errors
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
Labels: android

#1714 Fix main view for iOS 10
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
Labels: ios

#1707 Pull to refresh
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
Labels: android

#1723 Fix multiple enumerations
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
Labels: foundation

#1702 Allow time entry deletion in the log
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Extensions/NumberExtensions.cs
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
Labels: android

#1729 Set properties from fixed entity only when it is different
  Toggl.PrimeRadiant.Realm/RealmAdapter.cs
Labels: bug, critical

#1722 Add TransparentColor value converter
  Toggl.Giskard/Bindings/DrawableColorTargetBinding.cs
  Toggl.Giskard/Converters/TransparentColorValueConverter.cs
  Toggl.Giskard/Resources/layout/MainRunningTimeEntry.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: foundation

#1730 Add a selected project token
  Toggl.Giskard/Bindings/DrawableColorTargetBinding.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable/RoundedRectangle.xml
  Toggl.Giskard/Resources/layout/SelectProjectActivityProjectCell.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1735 Refactor the reset method
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
Labels: critical, foundation

#1740 Fix datepicker time format
  Toggl.Daneel/Converters/TimeFormatToLocaleValueConverter.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
Labels: ios

#1734 Make Interactor Aware tests use mocks
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/Interactors/BaseInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/StartTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation/Suggestions/Suggestion.cs
Labels: blocking, foundation

#1739 Fix 1password crash
  Toggl.Daneel/Services/AnalyticsService.cs
Labels: blocking, ios

#1732 Fix setting up initial state of preferences
  Toggl.Foundation/DataSources/PreferencesDataSource.cs
Labels: bug, foundation

#1742 Simplify time entries view source
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Daneel/Views/Log/TimeEntriesEmptyLogView.cs
  Toggl.Daneel/Views/Log/TimeEntriesEmptyLogView.designer.cs
  Toggl.Daneel/Views/Log/TimeEntriesEmptyLogView.xib
  Toggl.Daneel/Views/Log/TimeEntriesLogEmptyStateViewCell.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogEmptyStateViewCell.designer.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogEmptyStateViewCell.xib
  Toggl.Daneel/Views/Log/TimeEntryMockView.cs
  Toggl.Daneel/Views/Log/TimeEntryMockView.designer.cs
  Toggl.Daneel/Views/Log/TimeEntryMockView.xib
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
Labels: ios

#1756 Hide billable rates for free WSs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Giskard/Resources/layout/EditActivity.axml
Labels: android

#1755 Avoid inconsistent state of which time is edited
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
Labels: bug

#1757 Re-enable auto correction in the creation view
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
Labels: ios

#1758 Update the search icon
  Toggl.Daneel/Resources/Images.xcassets/search.imageset/search.png
  Toggl.Daneel/Resources/Images.xcassets/search.imageset/search@2x.png
  Toggl.Daneel/Resources/Images.xcassets/search.imageset/search@3x.png
Labels: ios

#1759 Update "n tasks" font settings
  Toggl.Daneel/Views/StartTimeEntry/ProjectSuggestionViewCell.xib
Labels: ios

#1763 Fix toolbar missing logo
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/logo.png
  Toggl.Giskard/Resources/drawable-mdpi/logo.png
  Toggl.Giskard/Resources/drawable-xhdpi/logo.png
  Toggl.Giskard/Resources/drawable-xxhdpi/logo.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/logo.png
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1762 Fix top margin for sign out button
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
Labels: android

#1760 Show confirmation dialog if there are changes in the edit TE view
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Services/DialogService.cs
Labels: android, ios

#1720 Onboarding services
  Toggl.Daneel/Services/DaneelOnboardingService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/FoundationTests.cs
  Toggl.Foundation.Tests/Generators/ConstructorTestData.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation/Foundation.cs
  Toggl.Foundation/Services/IOnboardingService.cs
  Toggl.Giskard/Services/GiskardOnboardingService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.PrimeRadiant/Onboarding/DismissableOnboardingStep.cs
  Toggl.PrimeRadiant/Onboarding/IDismissable.cs
  Toggl.PrimeRadiant/Onboarding/IOnboardingStep.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: android, blocking, ios

#1712 Add app shortcut handling
  Toggl.Daneel/ApplicationShortcutCreator.cs
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/FoundationTests.cs
  Toggl.Foundation.Tests/Interactors/ContinueMostRecentTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Login/LoginManagerTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/TimeEntryStartOrigin.cs
  Toggl.Foundation/ApplicationUrls.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.cs
  Toggl.Foundation/Interactors/Shared/ContinueMostRecentTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/Shared/CreateTimeEntryInteractor.cs
  Toggl.Foundation/Login/LoginManager.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Shortcuts/BaseApplicationShortcutCreator.cs
  Toggl.Foundation/Shortcuts/IApplicationShortcutCreator.cs
  Toggl.Foundation/Shortcuts/ShortcutType.cs
  Toggl.Giskard/ApplicationShortcutCreator.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Multivac/Extensions/EnumerableExtensions.cs
Labels: foundation, ios

#1765 Stop crashes once and for all
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
Labels: foundation

#1747 Reports summary
  Toggl.Daneel/Converters/ReportPercentageLabelValueConverter.cs
  Toggl.Daneel/Converters/ReportTimeSpanLabelValueConverter.cs
  Toggl.Foundation.MvvmCross/Converters/BaseReportPercentageLabelValueConverter.cs
  Toggl.Foundation.MvvmCross/Converters/BaseReportTimeSpanLabelValueConverter.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Adapters/ReportsRecyclerAdapter.cs
  Toggl.Giskard/Bindings/ViewWidthPercentageTargetBinding.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Converters/ReportPercentageLabelValueConverter.cs
  Toggl.Giskard/Converters/ReportTimeSpanLabelValueConverter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/drawable-hdpi/logo_icon.png
  Toggl.Giskard/Resources/drawable-hdpi/reports_total_chart.png
  Toggl.Giskard/Resources/drawable-mdpi/logo_icon.png
  Toggl.Giskard/Resources/drawable-mdpi/reports_total_chart.png
  Toggl.Giskard/Resources/drawable-xhdpi/logo_icon.png
  Toggl.Giskard/Resources/drawable-xhdpi/reports_total_chart.png
  Toggl.Giskard/Resources/drawable-xxhdpi/logo_icon.png
  Toggl.Giskard/Resources/drawable-xxhdpi/reports_total_chart.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/logo_icon.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/reports_total_chart.png
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/ReportsActivitySummary.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/TemplateSelectors/ReportsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/ReportsRecyclerView.cs
Labels: android

#1780 Remove save from basic color picker
  Toggl.Daneel/ViewControllers/SelectColorViewController.cs
Labels: ios

#1779 Refactor WorkspaceSource into Interactors
  Toggl.Foundation.MvvmCross/DataSourceExtensions.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectWorkspaceViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/DataSources/WorkspacesDataSourceTests.cs
  Toggl.Foundation.Tests/Interactors/BaseInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/ContinueMostRecentTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Project/IsBillableAvailableForProjectInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Project/ProjectDefaultsToBillableInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/AreCustomColorsEnabledForWorkspaceInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/AreProjectsBillableByDefaultInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/GetAllWorkspacesInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/GetDefaultWorkspaceInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/GetWorkspaceByIdInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/IsBillableAvailableForWorkspaceInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/WorkspaceAllowsBillableRatesInteractorTests.cs
  Toggl.Foundation.Tests/Mocks/MockWorkspaceFeature.cs
  Toggl.Foundation.Tests/Mocks/MockWorkspaceFeatureCollection.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTagsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectWorkspaceViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/Toggl.Foundation.Tests.csproj
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IWorkspacesSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/DataSources/WorkspacesDataSource.cs
  Toggl.Foundation/Interactors/Abstract/WorkspaceHasFeatureInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Definitions.cs
  Toggl.Foundation/Interactors/InteractorFactory.Project.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/InteractorFactory.Workspace.cs
  Toggl.Foundation/Interactors/InteractorFactory.cs
  Toggl.Foundation/Interactors/Project/IsBillableAvailableForProjectInteractor.cs
  Toggl.Foundation/Interactors/Project/ProjectDefaultsToBillableInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/ContinueMostRecentTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/CreateTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/Workspace/AreCustomColorsEnabledForWorkspaceInteractor.cs
  Toggl.Foundation/Interactors/Workspace/AreProjectsBillableByDefaultInteractor.cs
  Toggl.Foundation/Interactors/Workspace/GetAllWorkspacesInteractor.cs
  Toggl.Foundation/Interactors/Workspace/GetDefaultWorkspaceInteractor.cs
  Toggl.Foundation/Interactors/Workspace/GetWorkspaceByIdInteractor.cs
  Toggl.Foundation/Interactors/Workspace/IsBillableAvailableForWorkspaceInteractor.cs
  Toggl.Foundation/Interactors/Workspace/WorkspaceAllowsBillableRatesInteractor.cs
  Toggl.Giskard/Resources/Resource.designer.cs
Labels: blocking, foundation

#1790 Remove the onboarding service
  Toggl.Daneel/Services/DaneelOnboardingService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/FoundationTests.cs
  Toggl.Foundation/Foundation.cs
  Toggl.Foundation/Services/IOnboardingService.cs
  Toggl.Giskard/Services/GiskardOnboardingService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: ios

#1786 Hide billable field for starter users
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
Labels: ios

#1789 Pie Chart
  Toggl.Daneel/Views/Reports/PieChartView.cs
  Toggl.Foundation.Tests/Reports/ProjectSummaryReportTests.cs
  Toggl.Foundation/Reports/ChartSegment.cs
  Toggl.Foundation/Reports/ProjectSummaryReport.cs
  Toggl.Giskard/Adapters/ReportsRecyclerAdapter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsActivityHeader.axml
  Toggl.Giskard/TemplateSelectors/ReportsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/PieChartView.cs
Labels: android, blocking

#1797 Make the whole private switch row tappable in the edit project view
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.xib
Labels: ios

#1798 Reports UI update
  Toggl.Daneel/Resources/Images.xcassets/icChartEmpty.imageset/icChartEmpty.png
  Toggl.Daneel/Resources/Images.xcassets/icChartEmpty.imageset/icChartEmpty@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icChartEmpty.imageset/icChartEmpty@3x.png
  Toggl.Daneel/Views/Reports/PercentageView.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.designer.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#1791 Reset onboarding storage on logout
  Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: foundation

#1799 Reports legend
  Toggl.Foundation/Reports/ChartSegment.cs
  Toggl.Giskard/Adapters/ReportsRecyclerAdapter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/ReportsActivityHeader.axml
  Toggl.Giskard/Resources/layout/ReportsActivityItem.axml
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Startup/TogglBindingBuilder.cs
  Toggl.Giskard/TemplateSelectors/ReportsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/ReportsRecyclerViewHolder.cs
Labels: android

#1792 Improve forgot your password flow
  Toggl.Daneel/LinkerPleaseInclude.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Extensions/ViewExtensions.cs
  Toggl.Giskard/ProGuard.cfg
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#1787 Onboarding phase 1
  Toggl.Daneel/Onboarding/MainView/StartTimeEntryOnboardingStep.cs
  Toggl.Daneel/Services/UserDefaultsStorage.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Giskard/Services/SharedPreferencesStorage.cs
  Toggl.PrimeRadiant.Tests/Settings/SettingsStorageTests.cs
  Toggl.PrimeRadiant/Extensions/OnboardingStepExtensions.cs
  Toggl.PrimeRadiant/Onboarding/DismissableOnboardingStep.cs
  Toggl.PrimeRadiant/Onboarding/IOnboardingStep.cs
  Toggl.PrimeRadiant/Settings/IKeyValueStorage.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: blocking, ios

#1804 Calendar scroll behaviour
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Presenters/TogglPresenter.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/ReportsLinearLayout.cs
Labels: android, blocking

#1805 Calendar header logic
  Toggl.Daneel/ViewControllers/ReportsCalendarViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsCalendarViewModelTests.cs
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsCalendarFragment.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
Labels: android, blocking, on-hold

#1801 Add fade animation to reports
  Toggl.Daneel/Binding/ViewVisibilityWithFadeTargetBinding.cs
  Toggl.Daneel/Extensions/LayoutConstraintExtensions.cs
  Toggl.Daneel/Extensions/ViewBindingExtensions.cs
  Toggl.Daneel/Startup/SetupTargetFactories.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.designer.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.xib
Labels: ios

#1816 Fix invalid dialog buttons' texts
  Toggl.Giskard/Services/DialogService.cs
Labels: android, blocking

#1814 Fix EditTextFocusTargetBinding and make it two-way
  Toggl.Giskard/Bindings/EditTextFocusTargetBinding.cs
Labels: android, blocking

#1803 Client colors
  Toggl.Daneel/Views/StartTimeEntry/ProjectSuggestionViewCell.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#1811 Add managing UIView visibility to onboarding step
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: ios

#1821 Fix bug in EditDurationViewModel
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
Labels: blocking, foundation

#1820 Fix value converters' names
  Toggl.Daneel/ViewControllers/OnboardingViewController.cs
  Toggl.Daneel/Views/StartTimeEntry/ProjectSuggestionViewCell.cs
  Toggl.Foundation.MvvmCross/Converters/PaginationValueConverter.cs
  Toggl.Foundation.MvvmCross/Converters/TaskCountValueConverter.cs
Labels: foundation

#1819 Reports calendar
  Toggl.Daneel/ViewControllers/ReportsCalendarViewController.cs
  Toggl.Foundation.MvvmCross/Converters/IntToMonthNameValueConverter.cs
  Toggl.Giskard/Adapters/CalendarPagerAdapter.cs
  Toggl.Giskard/Adapters/CalendarRecyclerAdapter.cs
  Toggl.Giskard/Bindings/ViewPagerCurrentPageTargetBinding.cs
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsCalendarFragment.axml
  Toggl.Giskard/Resources/layout/ReportsCalendarFragmentDayCell.axml
  Toggl.Giskard/Resources/layout/ReportsCalendarFragmentPage.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Startup/SetupTargetFactories.tt
  Toggl.Giskard/TemplateSelectors/CalendarTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/CalendarRecyclerView.cs
  Toggl.Giskard/Views/ReportsLinearLayout.cs
Labels: android

#1815 Edit description update
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Bindings/EditTextFocusTargetBinding.cs
  Toggl.Giskard/Extensions/ViewExtensions.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditActivity.axml
  Toggl.Giskard/Views/DurationEditText.cs
Labels: android, blocking, foundation

#1817 Giskard edit delete button
  Toggl.Giskard/Bindings/EditTextFocusTargetBinding.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android, blocking

#1818 Edit view duration label
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android, blocking
