Repository toggl/mobileapp, pull requests merged in 2018-05, with the labels that each got.

#1961 Refactor metrics for reusability
  Toggl.Giskard/Extensions/ActivityExtensions.cs
  Toggl.Giskard/Fragments/SelectBeginningOfWeekFragment.cs
  Toggl.Giskard/Fragments/SelectColorFragment.cs
  Toggl.Giskard/Fragments/SelectDateFormatFragment.cs
  Toggl.Giskard/Fragments/SelectDurationFormatFragment.cs
Labels: android

#1999 `SinceParameterStorage` refactoring
  Toggl.Foundation/Models/SinceParameters.cs
  Toggl.PrimeRadiant.Realm/Database.cs
  Toggl.PrimeRadiant.Realm/Models/RealmSinceParameter.cs
  Toggl.PrimeRadiant.Realm/Models/RealmSinceParameters.cs
  Toggl.PrimeRadiant.Realm/SinceParameterStorage.cs
  Toggl.PrimeRadiant.Tests/Realm/TestAdapter.cs
  Toggl.PrimeRadiant.Tests/SinceParametersStorageTests.cs
  Toggl.PrimeRadiant/ISinceParameterRepository.cs
  Toggl.PrimeRadiant/Models/IDatabaseSinceParameters.cs
  Toggl.PrimeRadiant/Models/ISinceParameters.cs
Labels: refactoring

#2003 ✨Add Country model and endpoint
  Toggl.Multivac/Models/ICountry.cs
  Toggl.Ultrawave.Tests.Integration/CountriesApiTests.cs
  Toggl.Ultrawave.Tests/Models/CountryTests.cs
  Toggl.Ultrawave/ApiClients/CountriesApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ICountriesApi.cs
  Toggl.Ultrawave/ITogglApi.cs
  Toggl.Ultrawave/Models/Country.cs
  Toggl.Ultrawave/Models/ModelConstructors.cs
  Toggl.Ultrawave/Network/Endpoints/CountryEndpoints.cs
  Toggl.Ultrawave/Network/Endpoints/Endpoints.cs
  Toggl.Ultrawave/TogglApi.cs
  docs/endpoints.md
Labels: api

#2005 Fix T4 model generators
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/FoundationConstructors.tt
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Models/FoundationModels.tt
  Toggl.Foundation/Models/Preferences.cs
  Toggl.Multivac/Models/IPreferences.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.tt
  Toggl.PrimeRadiant.Realm/Models/RealmPreferences.cs
  Toggl.PrimeRadiant/Models/IDatabasePreferences.cs
  Toggl.Ultrawave/Models/ModelConstructors.cs
  Toggl.Ultrawave/Models/ModelConstructors.tt
  Toggl.Ultrawave/Models/Preferences.cs
Labels: refactoring

#2017 Fix hidden start time entry button
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: blocking, bug, ios

#2014 Fix crash when selecting No project
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Autocomplete/Suggestions/ProjectSuggestion.cs
Labels: blocking, bug, ios

#2016 Fix onboarding - Phase 2
  Toggl.Daneel/Onboarding/MainView/EditTimeEntryOnboardingStep.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: blocking, bug, ios

#2020 Forget the latest blocked card visibility change after using it
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: ios

#2008 Linker, no linking!
  Toggl.Giskard/LinkerPleaseInclude.cs
Labels: android, blocking

#2002 Abstraction of API clients methods
  Toggl.Foundation/Sync/PullingApiClientAdapter.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IClientsApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ICreatingApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IDeletingApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IPreferencesApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IProjectsApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IPullingApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IPullingChangedApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IPullingSingleApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ITagsApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ITasksApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ITimeEntriesApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IUpdatingApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IUserApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IWorkspaceFeaturesApi.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IWorkspacesApi.cs
Labels: refactoring

#2041 Fix misaligned carets in the settings view
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
Labels: ios, up-for-grabs

#2038 :triangular_ruler: Make back and close buttons tappable area bigger on custom toolbars
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/SelectClientActivity.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivity.axml
  Toggl.Giskard/Resources/layout/SelectTagsActivity.axml
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#2034 Increase tap area of reports date selector
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
Labels: android

#2006 Fix scroll issues with suggestions
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
Labels: android

#2010 DateTime popup - UI Interaction
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeParameters.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeResultsParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Giskard/Adapters/SelectTimePagerAdapter.cs
  Toggl.Giskard/Bindings/EditTextFocusTargetBinding.cs
  Toggl.Giskard/Extensions/ActivityExtensions.cs
  Toggl.Giskard/Extensions/StringExtensions.cs
  Toggl.Giskard/Extensions/ViewExtensions.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Fragments/TabHeaderUpdateManager.cs
  Toggl.Giskard/LinkerPleaseInclude.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/SelectDateTimeTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectTimeDurationPage.axml
  Toggl.Giskard/Resources/layout/SelectTimeFragment.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
Labels: android, blocking

#2064 Fix colors on the popup
  Toggl.Giskard/Resources/layout/SelectDateTimeTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
Labels: android

#2065 Open DateTime popup only if the time entry is stopped
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#2063 Integrate selecting time from start TE view
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#2059 Make sign up option tappable area bigger
  Toggl.Giskard/Resources/layout/OnboardingActivity.axml
Labels: android

#2032 Toolbar buttons tap area
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#2067 Prevent serialization exception leakage
  Toggl.Ultrawave.Tests/Serialization/ConcreteListTypeConverterTests.cs
  Toggl.Ultrawave.Tests/Serialization/JsonSerializerTests.cs
  Toggl.Ultrawave/Serialization/DeserializationException.cs
  Toggl.Ultrawave/Serialization/JsonSerializer.cs
  Toggl.Ultrawave/Serialization/SerializationException.cs
Labels: api

#2071 Fix task expansion overlapping
  Toggl.Giskard/Adapters/StartTimeEntryRecyclerAdapter.cs
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#2068 Reports scroll behavior improvements
  Toggl.Giskard/Views/CalendarRecyclerView.cs
  Toggl.Giskard/Views/ReportsLinearLayout.cs
Labels: android

#2015 Improve api exception
  Toggl.Ultrawave.Tests/Exceptions/ApiErrorResponsesTests.cs
  Toggl.Ultrawave/Exceptions/ApiException.cs
Labels: api

#1826 Remove date field
  Toggl.Foundation.MvvmCross/Converters/DateTimeToTimeValueConverter.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/TogglBindingBuilder.cs
Labels: android

#2088 Make date less prominent in Edit TE View
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/values/Colors.xml
Labels: android

#2085 Use user date/time format settings & co.
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeParameters.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeResultsParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Giskard/Bindings/ViewAlphaTargetBinding.cs
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Fragments/TabHeaderUpdateManager.cs
  Toggl.Giskard/Resources/drawable-hdpi/date_light.png
  Toggl.Giskard/Resources/drawable-mdpi/date_light.png
  Toggl.Giskard/Resources/drawable-xhdpi/date_light.png
  Toggl.Giskard/Resources/drawable-xxhdpi/date_light.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/date_light.png
  Toggl.Giskard/Resources/layout/SelectDateTimeDurationTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectDateTimeStartTimeTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectDateTimeStopTimeTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, blocking

#2086 Fix no-content bug in popup
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
Labels: android, blocking

#1956 Daneel 1.5 - Neptune
  Toggl.Daneel/ApplicationShortcutCreator.cs
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/Extensions/TimeEntriesLogViewCellExtensions.cs
  Toggl.Daneel/Info.plist
  Toggl.Daneel/Onboarding/MainView/EditTimeEntryOnboardingStep.cs
  Toggl.Daneel/Onboarding/MainView/SwipeLeftOnboardingStep.cs
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.Foundation/Autocomplete/Suggestions/ProjectSuggestion.cs
  Toggl.Multivac/Extensions/ObservableExtensions.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: ios

#2057 Track login and sign up errors
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/LoginErrorSource.cs
  Toggl.Foundation/Analytics/SignUpErrorSource.cs
Labels: foundation

#2060 Auto droid build number
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Startup/SplashScreen.cs
  build.cake
Labels: android

#2078 Get all non deleted time entries interactor
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/Interactors/ContinueMostRecentTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/GetAllNonDeletedInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation/DataSources/Interfaces/ITimeEntriesSource.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/ContinueMostRecentTimeEntryInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/GetAllNonDeletedInteractor.cs
Labels: foundation

#2062 Prevent one second initial delay
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
Labels: android, blocking

#2091 Manual mode for droid
  Toggl.Giskard/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#2098 Fix report lines ending abruptly
  Toggl.Giskard.Tests/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/layout/ReportsActivityItem.axml
Labels: android

#2112 Fix usage of disposable subscriptions
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SuggestionsViewModel.cs
Labels: foundation

#2122 Fixes for start time entry duration handling
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: android

#2117 Fix project placeholder
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#2124 Fix increase duration buttons behavior
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
Labels: foundation

#2109 Fix start view suggestions with partial content alignment
  Toggl.Giskard/Resources/layout/StartTimeEntryActivityTimeEntryWithPartialContentCell.axml
  Toggl.Giskard/TemplateSelectors/StartTimeEntrySuggestionsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2141 Fix sign up in Android
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation/Login/ILoginManager.cs
  Toggl.Foundation/Login/LoginManager.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IUserApi.cs
  Toggl.Ultrawave/ApiClients/UserApi.cs
Labels: android

#2134 Make navigation bar up to spec
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/icBack.png
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/icBack@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icBackNoPadding.imageset/icBack@3x.png
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Navigation/TogglNavigationController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
Labels: ios

#2123 Fix timezones in datetime popup
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
Labels: android

#2145 Sync failures interactor refactor
  Toggl.Foundation.Tests/Interactors/Sync/GetClientsThatFailedToSyncInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Sync/GetItemsThatFailedToSyncInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Sync/GetNumberOfItemsThatFailedToSyncInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Sync/GetProjectsThatFailedToSyncInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Sync/GetTagsThatFailedToSyncInteractorTests.cs
  Toggl.Foundation.Tests/Models/SyncFailureItemTests.cs
  Toggl.Foundation.Tests/Toggl.Foundation.Tests.csproj
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Sync.cs
  Toggl.Foundation/Interactors/Sync/GetItemsThatFailedToSyncInteractor.cs
  Toggl.Foundation/Interactors/Sync/GetNumberOfItemsThatFailedToSyncInteractor.cs
  Toggl.Foundation/Models/SyncFailureItem.cs
  Toggl.Foundation/Toggl.Foundation.csproj
Labels: foundation

#2146 Fix reports initial animation glitch
  Toggl.Giskard/Views/ReportsLinearLayout.cs
Labels: android

#2140 Fix invalid tag colors
  Toggl.Giskard/Resources/drawable/TagRoundedRectangle.xml
  Toggl.Giskard/Resources/layout/EditTimeEntryTagCell.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2136 Shortcut for manual entry
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
Labels: android

#2139 Forgot password
  Toggl.Daneel/Resources/Images.xcassets/Image.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/confirmation.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/confirmation.imageset/confirmation.png
  Toggl.Daneel/Resources/Images.xcassets/confirmation.imageset/confirmation@2x.png
  Toggl.Daneel/Resources/Images.xcassets/confirmation.imageset/confirmation@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/ForgotPasswordViewController.cs
  Toggl.Daneel/ViewControllers/ForgotPasswordViewController.designer.cs
  Toggl.Daneel/ViewControllers/ForgotPasswordViewController.xib
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/Views/LoginTextField.cs
  Toggl.Foundation.MvvmCross/Parameters/EmailParameter.cs
  Toggl.Foundation.MvvmCross/ViewModels/ForgotPasswordViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/NewLoginViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ForgotPasswordViewModelTests.cs
  Toggl.Foundation.Tests/TimeServiceTests.cs
  Toggl.Foundation/ITimeService.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/TimeService.cs
Labels: foundation, ios

#2164 Sync failures viewmodel
  Toggl.Foundation.MvvmCross/ViewModels/SyncFailuresViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SyncFailuresViewModelTests.cs
Labels: foundation

#2178 Fix cake script replacements for SplashScreen
  build.cake
Labels: android

#2037 Country selection UI
  Toggl.Daneel/Extensions/LayoutConstraintExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.designer.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.xib
  Toggl.Daneel/ViewSources/CountryTableViewSource.cs
  Toggl.Daneel/Views/CountrySelection/CountryViewCell.cs
  Toggl.Daneel/Views/CountrySelection/CountryViewCell.designer.cs
  Toggl.Daneel/Views/CountrySelection/CountryViewCell.xib
  Toggl.Foundation.MvvmCross/Parameters/SelectCountryParameter.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectCountryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableCountryViewModel.cs
  Toggl.Foundation.Tests/Interactors/Country/GetAllCountriesInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectCountryViewModelTests.cs
  Toggl.Foundation/Interactors/Country/GetAllCountriesInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Country.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Serialization/IJsonSerializer.cs
  Toggl.Foundation/Serialization/JsonSerializer.cs
  Toggl.Foundation/Toggl.Foundation.csproj
Labels: foundation, ios

#2189 Fix duration editing in popup
  Toggl.Giskard/Extensions/ViewExtensions.cs
  Toggl.Giskard/Resources/layout/SelectTimeFragment.axml
  Toggl.Giskard/Views/DurationEditText.cs
Labels: android

#2190 No zero duration on the running TE card
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
Labels: android, ios

#2195 Add location api
  Toggl.Multivac/Models/ILocation.cs
  Toggl.Ultrawave.Tests.Integration/LocationApiTests.cs
  Toggl.Ultrawave.Tests/Models/LocationTests.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ILocationApi.cs
  Toggl.Ultrawave/ApiClients/LocationApi.cs
  Toggl.Ultrawave/ITogglApi.cs
  Toggl.Ultrawave/Models/Location.cs
  Toggl.Ultrawave/Models/ModelConstructors.cs
  Toggl.Ultrawave/Network/Endpoints/Endpoints.cs
  Toggl.Ultrawave/Network/Endpoints/LocationEndpoints.cs
  Toggl.Ultrawave/TogglApi.cs
  docs/endpoints.md
Labels: api, blocking

#2174 Onboarding: replace the last screen with login page
  Toggl.Daneel/ViewControllers/OnboardingViewController.cs
  Toggl.Daneel/ViewControllers/OnboardingViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/OnboardingViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/OnboardingViewModelTests.cs
Labels: ios

#2185 Fix reports calendar row height calculation
  Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
Labels: android

#2203 Refactor bindings popup
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
  Toggl.Giskard/Bindings/DatePickerBoundariesTargetBinding.cs
  Toggl.Giskard/Bindings/DatePickerMaxExclusiveDateTargetBinding.cs
  Toggl.Giskard/Bindings/DatePickerMaxInclusiveDateTargetBinding.cs
  Toggl.Giskard/Bindings/DatePickerMinDateTargetBinding.cs
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
  Toggl.Multivac/DateTimeOffsetRange.cs
Labels: android

#2187 Add vibrations on popup temporal inconsistencies
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Helper/ApiAvailability.cs
  Toggl.Giskard/Helper/VibratorExtensions.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2186 Add "this week" default selection to the Reports Calendar VM
  Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsCalendarViewModelTests.cs
Labels: foundation

#2201 Fix reports calendar day cell masking layer
  Toggl.Daneel/Views/RoundedView.cs
Labels: ios

#2111 Various bugs and fixes in Start/Stop/Duration popup
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
  Toggl.Giskard/Bindings/DatePickerBoundariesTargetBinding.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Helper/ApiAvailability.cs
  Toggl.Giskard/Helper/VibratorExtensions.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Resources/layout/SelectDateTimeDurationTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
  Toggl.Multivac/DateTimeOffsetRange.cs
Labels: android

#2176 Sync failures views
  Toggl.Daneel/Resources/Images.xcassets/Image-2.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icWarning.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icWarning.imageset/icWarning.png
  Toggl.Daneel/Resources/Images.xcassets/icWarning.imageset/icWarning@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icWarning.imageset/icWarning@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/SyncFailuresViewController.cs
  Toggl.Daneel/ViewSources/ListTableViewSource.cs
  Toggl.Daneel/Views/SyncFailures/SyncFailureCell.cs
  Toggl.Daneel/Views/SyncFailures/SyncFailureCell.designer.cs
  Toggl.Daneel/Views/SyncFailures/SyncFailureCell.xib
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
Labels: foundation, ios

#2207 Fix login/signup
  Toggl.Foundation.MvvmCross/ViewModels/OnboardingViewModel.cs
Labels: android

#2206 Remove image from settings view
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
Labels: android

#2223 Filter deleted time entries and archived projects from suggestions
  Toggl.Foundation/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
Labels: foundation

#2239 Login by pressing return (next/done) key on the keyboard
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.cs
Labels: ios

#2208 Do not suggest deleted time entries and archived projects
  Toggl.Foundation.MvvmCross/DataSourceExtensions.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTagsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/Autocomplete/AutocompleteProviderTests.cs
  Toggl.Foundation.Tests/Interactors/AutocompleteSuggestions/BaseAutocompleteSuggestionsInteractorTest.cs
  Toggl.Foundation.Tests/Interactors/AutocompleteSuggestions/GetProjectsAutocompleteSuggestionsInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/AutocompleteSuggestions/GetTagsAutocompleteSuggestionsInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/AutocompleteSuggestions/GetTimeEntriesAutocompleteSuggestionsInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTagsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Autocomplete/AutocompleteProvider.cs
  Toggl.Foundation/Autocomplete/IAutocompleteProvider.cs
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Extensions/StringExtensions.cs
  Toggl.Foundation/Interactors/AutocompleteSuggestions/GetProjectsAutocompleteSuggestions.cs
  Toggl.Foundation/Interactors/AutocompleteSuggestions/GetTagsAutocompleteSuggestions.cs
  Toggl.Foundation/Interactors/AutocompleteSuggestions/GetTimeEntriesAutocompleteSuggestions.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.AutocompleteSuggestions.cs
Labels: foundation

#2218 Add 'x' to onboarding tooltips
  Toggl.Daneel/Extensions/OnboardingExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
Labels: ios

#2238 Dismiss onboarding step by swiping left reliably
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewSources/MainTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
Labels: ios

#2241 Protect the autocomplete provider from the mean linker
  Toggl.Foundation/Autocomplete/AutocompleteProvider.cs
Labels: blocking

#2227 Group small pie chart segments
  Toggl.Daneel/Views/Reports/PieChartView.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Views/PieChartView.cs
Labels: android, ios

#2222 Add location picking to signup
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.designer.cs
  Toggl.Daneel/ViewControllers/SignupViewController.xib
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectCountryParameter.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectCountryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.Tests/Interactors/Location/GetAllCountriesInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Location/GetCurrentLocationInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectCountryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Foundation/Interactors/Location/GetAllCountriesInteractor.cs
  Toggl.Foundation/Interactors/Location/GetCurrentLocationInteractor.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Toggl.Foundation.csproj
Labels: foundation, ios

#2179 Fix date picker bug
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/packages.config
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
Labels: ios

#2242 Extend touch areas of the end caps in the wheel view
  Toggl.Daneel/Views/EditDuration/WheelForegroundView.cs
Labels: ios

#2219 Do not display tooltips before the previous steps are finished
  Toggl.Daneel/Onboarding/MainView/SwipeLeftOnboardingStep.cs
  Toggl.Daneel/Onboarding/MainView/SwipeRightOnboardingStep.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: ios

#2246 Fix login button glitch
  Toggl.Daneel/Binding/ViewVisibilityWithFadeTargetBinding.cs
Labels: ios

#2247 Fix the way the spinner is displayed
  Toggl.Giskard/Resources/layout/LoginActivity.axml
Labels: android

#2256 Fix signup country picker button
  Toggl.Daneel/ViewControllers/SignupViewController.cs
Labels: bug, critical, ios

#2257 Update No project color
  Toggl.Foundation/Autocomplete/Suggestions/ProjectSuggestion.cs
  Toggl.Foundation/Helper/Color.cs
Labels: critical, glitch, ios

#2251 Fix reports being loaded twice on initialization
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: foundation, glitch

#2252 Terms of service pop up
  Toggl.Giskard/Fragments/TermsOfServiceFragment.cs
  Toggl.Giskard/Resources/drawable-hdpi/paws.png
  Toggl.Giskard/Resources/drawable-mdpi/paws.png
  Toggl.Giskard/Resources/drawable-xhdpi/paws.png
  Toggl.Giskard/Resources/drawable-xxhdpi/paws.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/paws.png
  Toggl.Giskard/Resources/layout/TermsOfServiceFragment.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2225 Fix duplicated segments in reports
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: android, bug

#2236 Implement country selection
  Toggl.Giskard/Activities/SelectCountryActivity.cs
  Toggl.Giskard/Resources/layout/SelectCountryActivity.axml
  Toggl.Giskard/Resources/layout/SelectCountryActivityCountryCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/SelecCountryTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/SelectCountryRecyclerView.cs
Labels: android, blocking

#2200 Track reports events
  Toggl.Foundation.MvvmCross/Parameters/DateRangeParameter.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarLastMonthQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarLastWeekQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarThisMonthQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarThisWeekQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarThisYearQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarTodayQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/QuickSelectShortcuts/CalendarYesterdayQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsCalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation.Tests/Reports/ProjectSummaryReportTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/ReportsSource.cs
  Toggl.Foundation/Reports/ProjectSummaryReport.cs
  Toggl.Foundation/Reports/ReportsProvider.cs
Labels: foundation

#2262 Close keyboard when tapping on background in new login/signup
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.cs
Labels: critical, ios

#2268 :construction: Make country id non-nullable for API calls
  Toggl.Foundation/Login/ILoginManager.cs
  Toggl.Foundation/Login/LoginManager.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IUserApi.cs
  Toggl.Ultrawave/ApiClients/UserApi.cs
Labels: android, api

#2264 Use support lib textfield with toggle password button
  Toggl.Giskard/Resources/layout/LoginActivity.axml
Labels: android

#2237 Integrate with Facebook
  Toggl.Daneel/Info.plist
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/packages.config
  build.cake
  docs/env-vars.md
Labels: ios

#2283 Isolate changing drawables
  Toggl.Giskard/Resources/drawable/LightBlueRoundedRectangle.xml
  Toggl.Giskard/Resources/drawable/ProjectRoundedRectangle.xml
  Toggl.Giskard/Resources/drawable/ReportsCalendarShortcutRoundedRectangle.xml
  Toggl.Giskard/Resources/layout/EditTimeEntryTagCell.axml
  Toggl.Giskard/Resources/layout/ReportsCalendarShortcutCell.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivityProjectCell.axml
  Toggl.Giskard/Resources/layout/SelectTimeDurationPage.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2271 Add autofill hint to avoid auto fill service suggestions
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#2266 Bind login button text color with LoginEnabled
  Toggl.Giskard/Converters/BoolToConstantOverrides.cs
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Resources/layout/SignUpActivity.axml
Labels: android

#2289 Fix Uranus
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: blocking

#2304 Fix bug with continuing time entries
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
Labels: bug, foundation

#2286 Fix tappable areas in Edit TE UI
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#2302 Fix singleton data store
  Toggl.Foundation.Tests/DataSources/SingletonDataSourceTests.cs
  Toggl.Foundation/DataSources/SingletonDataSource.cs
Labels: foundation

#2294 Fix time entry card visibility bug
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Hints/CardVisibilityHint.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Presenters/TogglPresenter.cs
Labels: android, ios

#2229 Fix new cursor position when adding tags/projects on start TE
  Toggl.Giskard/Bindings/EditTextTextFieldInfoTargetBinding.cs
  Toggl.Multivac/Extensions/StringExtensions.cs
Labels: android

#2290 Fix constraints to make nav bar shorter
  Toggl.Daneel/ViewControllers/Settings/AboutViewController.xib
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.xib
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
Labels: ios

#2287 Delete older time entries state
  Toggl.Foundation.Tests/DataSources/BaseDataSourceTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/DeleteOldEntriesStateTests.cs
  Toggl.Foundation/DataSources/BaseDataSource.cs
  Toggl.Foundation/DataSources/DataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IDataSource.cs
  Toggl.Foundation/DataSources/ObservableDataSource.cs
  Toggl.Foundation/Sync/States/Pull/DeleteOldEntriesState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: foundation

#2295 Add TextInputLayout with support to helper text
  Toggl.Giskard/Bindings/TextInputLayoutErrorAppearanceTargetBinding.cs
  Toggl.Giskard/Resources/layout/ForgotPasswordActivity.axml
  Toggl.Giskard/Resources/values/Attrs.xml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/TextInputLayoutWithHelperText.cs
Labels: android

#2317 Log in UI: change the padding from the top
  Toggl.Daneel/ViewControllers/LoginViewController.cs
Labels: critical, ios

#2315 Remove unnecessary generic params of data sources and push sync states
  Toggl.Foundation.Tests/Sync/States/Pull/PersistStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BasePushEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/CreateEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/DeleteEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/PushSingleStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/UpdateEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/UnsyncableEntityStateTests.cs
  Toggl.Foundation/DataSources/BaseDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IBaseDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IObservableDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IPreferencesSource.cs
  Toggl.Foundation/DataSources/Interfaces/ISingletonDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IUserSource.cs
  Toggl.Foundation/DataSources/SingletonDataSource.cs
  Toggl.Foundation/Sync/States/Pull/FetchAllSinceState.cs
  Toggl.Foundation/Sync/States/Pull/PersistState.cs
  Toggl.Foundation/Sync/States/Push/BasePushEntityState.cs
  Toggl.Foundation/Sync/States/Push/CreateEntityState.cs
  Toggl.Foundation/Sync/States/Push/DeleteEntityState.cs
  Toggl.Foundation/Sync/States/Push/Interfaces/IPushEntityState.cs
  Toggl.Foundation/Sync/States/Push/Interfaces/IPushState.cs
  Toggl.Foundation/Sync/States/Push/PushOneEntityState.cs
  Toggl.Foundation/Sync/States/Push/PushSingleState.cs
  Toggl.Foundation/Sync/States/Push/ResetAPIDelayState.cs
  Toggl.Foundation/Sync/States/Push/TryResolveClientErrorState.cs
  Toggl.Foundation/Sync/States/Push/UnsyncableEntityState.cs
  Toggl.Foundation/Sync/States/Push/UpdateEntityState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: foundation, refactoring

#2335 Fix autocorrect replacing suggesting with something else
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
Labels: critical, glitch, ios

#2326 Clean up app initialization logic
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/App.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/Toggl.Foundation.MvvmCross.csproj
  Toggl.Foundation.Tests/FoundationTests.cs
  Toggl.Foundation.Tests/Generators/ConstructorTestData.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/TogglFoundationTests.cs
  Toggl.Foundation/Foundation.cs
  Toggl.Foundation/TogglFoundation.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: foundation, refactoring

#2310 Implement 12/24 hours modes in start/stop/duration popup
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.Tests/Interactors/Preferences/GetPreferencesInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Preferences.cs
  Toggl.Foundation/Interactors/Preferences/GetPreferencesInteractor.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
Labels: android

#2284 Fetch last two months time entries
  Toggl.Ultrawave.Tests.Integration/TimeEntriesApiTests.cs
  Toggl.Ultrawave/ApiClients/Interfaces/ITimeEntriesApi.cs
  Toggl.Ultrawave/ApiClients/TimeEntriesApi.cs
  Toggl.Ultrawave/Network/Endpoints/TimeEntryEndpoints.cs
Labels: api, blocking

#2320 No default workspace
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/Interactors/Workspace/GetDefaultWorkspaceInteractorTests.cs
  Toggl.Foundation.Tests/Mocks/MockUser.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Interactors/Workspace/GetDefaultWorkspaceInteractor.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Models/User.cs
  Toggl.Multivac/Models/IUser.cs
  Toggl.PrimeRadiant.Realm/Database.cs
  Toggl.PrimeRadiant.Realm/Models/RealmUser.cs
  Toggl.Ultrawave.Tests.Integration/ClientsApiTests.cs
  Toggl.Ultrawave.Tests.Integration/Helper/SubscriptionPlanActivator.cs
  Toggl.Ultrawave.Tests.Integration/ProjectsApiTests.cs
  Toggl.Ultrawave.Tests.Integration/ProjectsSummaryReportsApiTests.cs
  Toggl.Ultrawave.Tests.Integration/TagsApiTests.cs
  Toggl.Ultrawave.Tests.Integration/TasksApiTests.cs
  Toggl.Ultrawave.Tests.Integration/TimeEntriesApiTests.cs
  Toggl.Ultrawave.Tests.Integration/UserApiTests.cs
  Toggl.Ultrawave.Tests.Integration/WorkspacesApiTests.cs
  Toggl.Ultrawave.Tests/Models/UserTests.cs
  Toggl.Ultrawave/Models/User.cs
Labels: critical, foundation

#2330 Fix reports grouping
  Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: critical, foundation, ios

#2313 Refactoring of Pull sync states using composition
  Toggl.Foundation.Tests/DataSources/SingletonDataSourceTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/ApiExceptionsCatchingPersistStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/FetchAllSinceStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistListStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistSingletonStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/PersistStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Pull/SinceDateUpdatingPersistStateTests.cs
  Toggl.Foundation/DataSources/BaseDataSource.cs
  Toggl.Foundation/DataSources/DataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IBaseDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/ISingletonDataSource.cs
  Toggl.Foundation/DataSources/SingletonDataSource.cs
  Toggl.Foundation/Extensions/PersistStateExtensions.cs
  Toggl.Foundation/Sync/States/Pull/ApiExceptionsCatchingPersistState.cs
  Toggl.Foundation/Sync/States/Pull/FetchObservables.cs
  Toggl.Foundation/Sync/States/Pull/IFetchObservables.cs
  Toggl.Foundation/Sync/States/Pull/IPersistState.cs
  Toggl.Foundation/Sync/States/Pull/PersistListState.cs
  Toggl.Foundation/Sync/States/Pull/PersistSingletonState.cs
  Toggl.Foundation/Sync/States/Pull/PersistState.cs
  Toggl.Foundation/Sync/States/Pull/SinceDateUpdatingPersistState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: blocking, foundation, refactoring

#2342 Reactive Dialogs
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.Giskard/Services/DialogService.cs
Labels: android, blocking, foundation, ios, refactoring

#2325 Show an error when the country is missing
  Toggl.Giskard/Resources/layout/SignUpActivity.axml
Labels: android

#2353 Add more reactive extension to multivac
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
Labels: foundation, refactoring

#2352 Explicit targetSdkVersion
  Toggl.Giskard/Properties/AndroidManifest.xml
Labels: android, critical

#2358 Add missing transition for pulling users failure
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: sync
