Repository toggl/mobileapp, pull requests merged in 2018-08, with the labels that each got.

#2784 Fix onboarding phase 3 tooltip positioning when ime changes
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
Labels: android, glitch

#2762 No workspace UI
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIControlRxExtensions.cs
  Toggl.Daneel/Resources/Images.xcassets/icIllustrationErrorWorkspace.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icIllustrationErrorWorkspace.imageset/icIllustrationErrorWorkspace.png
  Toggl.Daneel/Resources/Images.xcassets/icIllustrationErrorWorkspace.imageset/icIllustrationErrorWorkspace@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icIllustrationErrorWorkspace.imageset/icIllustrationErrorWorkspace@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/NoWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/NoWorkspaceViewController.designer.cs
  Toggl.Daneel/ViewControllers/NoWorkspaceViewController.xib
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/Services/ErrorHandlingService.cs
  Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs
Labels: ios

#2760 Add IsGhost to database entities
  Toggl.Foundation.Tests/Mocks/MockClient.cs
  Toggl.Foundation.Tests/Mocks/MockProject.cs
  Toggl.Foundation.Tests/Mocks/MockTag.cs
  Toggl.Foundation.Tests/Mocks/MockTask.cs
  Toggl.Foundation.Tests/Mocks/MockTimeEntry.cs
  Toggl.Foundation.Tests/Mocks/MockWorkspace.cs
  Toggl.Foundation/Models/Client.cs
  Toggl.Foundation/Models/FoundationModels.cs
  Toggl.Foundation/Models/TimeEntry.cs
  Toggl.PrimeRadiant.Realm/Database.cs
  Toggl.PrimeRadiant.Realm/Models/RealmClient.cs
  Toggl.PrimeRadiant.Realm/Models/RealmProject.cs
  Toggl.PrimeRadiant.Realm/Models/RealmTag.cs
  Toggl.PrimeRadiant.Realm/Models/RealmTask.cs
  Toggl.PrimeRadiant.Realm/Models/RealmTimeEntry.cs
  Toggl.PrimeRadiant.Realm/Models/RealmWorkspace.cs
  Toggl.PrimeRadiant/Models/IDatabaseClient.cs
  Toggl.PrimeRadiant/Models/IDatabaseProject.cs
  Toggl.PrimeRadiant/Models/IDatabaseTag.cs
  Toggl.PrimeRadiant/Models/IDatabaseTask.cs
  Toggl.PrimeRadiant/Models/IDatabaseTimeEntry.cs
  Toggl.PrimeRadiant/Models/IDatabaseWorkspace.cs
  Toggl.PrimeRadiant/Models/IGhostable.cs
Labels: foundation, sync

#2813 Detect losing access to workspace
  Toggl.Foundation.Tests/Sync/States/Pull/DetectLosingAccessToWorkspacesStateTests.cs
  Toggl.Foundation/Sync/States/Pull/DetectLosingAccessToWorkspacesState.cs
Labels: sync

#2806 Add new calendar item struct
  Toggl.Foundation/Calendar/CalendarItem.cs
  Toggl.Foundation/Calendar/CalendarItemSource.cs
Labels: foundation

#2807 Fix incorrect behaviour when closing VMs
  Toggl.Giskard/Presenters/TogglPresenter.cs
  Toggl.Giskard/Startup/QueryableMvxLifecycleMonitorCurrentTopActivity.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Startup/TogglApplication.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2808 Permissions service
  Toggl.Daneel/Info.plist
  Toggl.Daneel/Services/PermissionsService.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/Services/IPermissionsService.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Giskard/Services/PermissionsService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, ios

#2824 Calendar service
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/Services/ICalendarService.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Giskard/Services/CalendarService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: foundation

#2803 Switching workspaces in reports
  Toggl.Daneel/Converters/LambdaConverter.cs
  Toggl.Daneel/Resources/Images.xcassets/icWorkspace.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icWorkspace.imageset/icWorkspace.png
  Toggl.Daneel/Resources/Images.xcassets/icWorkspace.imageset/icWorkspace@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icWorkspace.imageset/icWorkspace@3x.png
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.designer.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Services/DialogService.cs
Labels: ios

#2831 Add CalendarViewModel
  Toggl.Foundation.MvvmCross/ViewModels/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
Labels: foundation

#2823 Fix duration input in the creation view
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
Labels: ios

#2835 Add CalendarViewController
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/CalendarViewController.cs
  Toggl.Daneel/ViewControllers/CalendarViewController.designer.cs
  Toggl.Daneel/ViewControllers/CalendarViewController.xib
Labels: ios

#2842 :calendar: Add IsCalendarFeatureEnabled observable
  Toggl.Daneel/Services/RemoteConfigService.cs
  Toggl.Foundation/Services/IRemoteConfigService.cs
  Toggl.Giskard/Services/RemoteConfigService.cs
Labels: foundation

#2837 Add calendar item view
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/CalendarItemView.cs
  Toggl.Daneel/Views/CalendarItemView.designer.cs
  Toggl.Daneel/Views/CalendarItemView.xib
  Toggl.Daneel/Views/ReactiveCollectionViewCell.cs
Labels: ios

#2853 Remote config fetching
  Toggl.Daneel/RemoteConfigDefaults.plist
  Toggl.Daneel/Services/RemoteConfigService.cs
  Toggl.Daneel/Startup/Setup.cs
Labels: crash, ios

#2849 Calendar interactor
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Foundation.Tests/Interactors/BaseInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Calendar/GetCalendarItemsForDateInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
  Toggl.Foundation/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Calendar.cs
  Toggl.Foundation/Interactors/InteractorFactory.Definitions.cs
  Toggl.Foundation/Services/ICalendarService.cs
  Toggl.Giskard/Services/CalendarService.cs
Labels: foundation

#2854 Add a way to navigate to CalendarViewModel
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
Labels: foundation

#2865 Move appcenter startup from SplashScreen to TogglApplication
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Startup/TogglApplication.cs
  build.cake
Labels: android

#2863 Add a button to navigate to the calendar view controller
  Toggl.Daneel/Resources/Images.xcassets/icCalendar.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icCalendar.imageset/icCalendar.png
  Toggl.Daneel/Resources/Images.xcassets/icCalendar.imageset/icCalendar@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icCalendar.imageset/icCalendar@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: foundation, ios

#2852 Fix grouped collection id update bug
  Toggl.Foundation.MvvmCross/Collections/GroupedOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/IGroupOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/ObservableGroupedOrderedCollection.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/GroupedOrderedCollectionTests.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/ObservableGroupedOrderedListTests.cs
Labels: android, crash, glitch, ios

#2864 Make FeedbackService optional
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
Labels: bug, ios

#2816 Fix bugs in NoWorkspaceViewModel related to syncManager
  Toggl.Foundation.MvvmCross/Services/ErrorHandlingService.cs
  Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
Labels: foundation, ios

#2744 Make Drivers safer
  Toggl.Daneel/Startup/IOSSchedulerProvider.cs
  Toggl.Daneel/Startup/NSRunLoopScheduler.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Foundation.MvvmCross/Extensions/ObservableExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/IReactiveBindingHolder.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/TestSchedulerProvider.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SendFeedbackViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/TogglFoundationTests.cs
  Toggl.Foundation/TogglFoundation.cs
  Toggl.Giskard/Startup/AndroidSchedulerProvider.cs
  Toggl.Giskard/Startup/HandlerScheduler.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
  Toggl.Multivac/ISchedulerProvider.cs
Labels: android, ios, refactoring

#2883 Add Interactor to read/fetch a list of all calendars
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/Services/IPermissionsService.cs
  Toggl.Foundation.Tests/Interactors/Calendar/GetUserCalendarsInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Calendar/SetEnabledCalendarsInteractorTests.cs
  Toggl.Foundation/Interactors/Calendar/GetUserCalendarsInteractor.cs
  Toggl.Foundation/Interactors/Calendar/SetEnabledCalendarsInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Calendar.cs
  Toggl.Foundation/Services/ICalendarService.cs
  Toggl.Giskard/Services/CalendarService.cs
Labels: foundation

#2891 Fix missing ISchedulerProvider injection
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
Labels: android, crash, ios

#2892 Add Feedback service back to Daneel
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/Services/IFeedbackService.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
Labels: bug, ios

#2908 Expose the calendar items from the view model
  Toggl.Foundation.MvvmCross/ViewModels/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
Labels: foundation

#2771 ✨ Add TabBarController
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Resources/Images.xcassets/icTime.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icTime.imageset/icTime.png
  Toggl.Daneel/Resources/Images.xcassets/icTime.imageset/icTime@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icTime.imageset/icTime@3x.png
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainTabBarController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Foundation.MvvmCross/App.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/AppStartTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
Labels: ios

#2910 Handle CalendarItem taps in the ViewModel
  Toggl.Foundation.MvvmCross/ViewModels/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
Labels: foundation

#2887 Calendar view
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.designer.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
  Toggl.Daneel/Cells/Calendar/CurrentTimeSupplementaryView.cs
  Toggl.Daneel/Cells/Calendar/CurrentTimeSupplementaryView.designer.cs
  Toggl.Daneel/Cells/Calendar/CurrentTimeSupplementaryView.xib
  Toggl.Daneel/Cells/Calendar/HourSupplementaryView.cs
  Toggl.Daneel/Cells/Calendar/HourSupplementaryView.designer.cs
  Toggl.Daneel/Cells/Calendar/HourSupplementaryView.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewItemLayoutAttributes.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Daneel/Views/Calendar/ICalendarCollectionViewLayoutDataSource.cs
  Toggl.Multivac/Ensure.cs
Labels: ios

#2917 🚧 Fix reports refreshing on every view did appear
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
Labels: glitch, ios

#2918 Increase tap area for the color picker button
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.xib
Labels: glitch, ios

#2913 Add an editor action to the login page password field
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Extensions/UIExtensions.cs
  Toggl.Giskard/Resources/layout/LoginActivity.axml
Labels: android

#2928 Fix flaky test of LoginViewModel
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
Labels: bug

#2935 Add bottom bar navigation
  Toggl.Daneel/ViewControllers/MainTabBarController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
Labels: foundation, ios

#2934 Do not hide a non existing rating view to avoid null ref
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: crash, ios

#2933 Fix a bug in presenting popups during sign up
  Toggl.Daneel/Presentation/TogglPresenter.cs
Labels: crash, ios

#2926 Remove animation to fix glitch in the reports calendar
  Toggl.Daneel/Binding/LayoutConstraintAnimatedConstantTargetBinding.cs
Labels: glitch, ios

#2938 Use AsDriver to manipulate with the undo snackbar on the UI thread
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
Labels: bug, ios

#2927 Bind the collection view with the calendar items collection
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.designer.cs
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.xib
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#2924 Improve custom feedback view model
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SendFeedbackViewModelTests.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
Labels: refactoring

#2944 Add calendar item tap handling
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#2858 Daneel Hotfix 1.8.1
  Toggl.Daneel/Info.plist
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/RemoteConfigDefaults.plist
  Toggl.Daneel/Services/RemoteConfigService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/ViewModels/Hints/ToggleRatingViewVisibilityHint.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs
Labels: ios

#2866 Giskard 1.3 - Fluorine
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2946 Calendar bind item view
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.designer.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
  Toggl.Daneel/Cells/Calendar/HourSupplementaryView.cs
  Toggl.Daneel/Resources/Images.xcassets/icCalendarSmall.imageset/Contents.json
  Toggl.Daneel/Resources/Images.xcassets/icCalendarSmall.imageset/icCalendarSmall.png
  Toggl.Daneel/Resources/Images.xcassets/icCalendarSmall.imageset/icCalendarSmall@2x.png
  Toggl.Daneel/Resources/Images.xcassets/icCalendarSmall.imageset/icCalendarSmall@3x.png
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Daneel/Views/ReactiveCollectionViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
Labels: ios

#2873 Move compiler macro to hide override when not on release
  Toggl.Giskard/Startup/TogglApplication.cs
Labels: android

#2957 🐞 Fix crashes caused by Mvx not being initialised yet
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android, crash

#2956 📐 Colorful Activity Indicator
  Toggl.Daneel/ViewControllers/ForgotPasswordViewController.cs
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/NoWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Daneel/Views/ActivityIndicatorView.cs
  Toggl.Daneel/Views/Log/RefreshControl.cs
Labels: ios

#2951 Time entry from span
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
  Toggl.Foundation/Extensions/TimeEntryExtensions.cs
Labels: foundation

#2966 Make the edit view awaitable
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
Labels: foundation

#2969 Reload data when switching tabs
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
Labels: ios

#2952 📐 address navigationbar glitch
  Toggl.Daneel/ViewControllers/LoginViewController.cs
Labels: ios

#2976 Add error states to the calendar item UI
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Foundation.Tests/CalendarItemTests.cs
  Toggl.Foundation.Tests/Interactors/Calendar/GetCalendarItemsForDateInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation/Calendar/CalendarIconKind.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
Labels: ios

#2968 Calendar tap and hold
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLongPressHelper.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
  Toggl.Multivac/Extensions/DateTimeOffsetExtensions.cs
Labels: ios

#2899 Mark workspaces as ghosts
  Toggl.Foundation.Tests/Sync/States/Pull/DetectLosingAccessToWorkspacesStateTests.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Foundation/Models/Workspace.cs
  Toggl.Foundation/Sync/States/Pull/DetectLosingAccessToWorkspacesState.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
Labels: sync

#2974 Fix app crash when updating UI after sync
  Toggl.Daneel/Extensions/Binders/ReactiveTableViewBinder.cs
  Toggl.Daneel/Extensions/SectionedIndexExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewSources/Generic/ReactiveSectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/SectionedListTableViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/AddRowCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/CollectionChangesListBuilder.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/ICollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/InsertSectionCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/MoveRowToNewSectionCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/MoveRowWithinExistingSectionsCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/ReloadCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/RemoveRowCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/Changes/UpdateRowCollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/CollectionChange.cs
  Toggl.Foundation.MvvmCross/Collections/GroupedOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/IGroupOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/ObservableGroupedOrderedCollection.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/GroupedOrderedCollectionTests.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/ObservableGroupedOrderedListTests.cs
Labels: blocking, crash, ios

#2977 Calendar y u so mean
  Toggl.Daneel/Services/CalendarService.cs
Labels: foundation, ios

#2986 🚧Remove translucency iOS 10 tabbar
  Toggl.Daneel/ViewControllers/MainTabBarController.cs
Labels: glitch, ios

#2989 Tazenda Hotfix #2
  Toggl.Daneel/Info.plist
  Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
Labels: ios

#2999 Fix'em giskard startup crashes
  Toggl.Giskard/Activities/AboutActivity.cs
  Toggl.Giskard/Activities/BrowserActivity.cs
  Toggl.Giskard/Activities/EditProjectActivity.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/ForgotPasswordActivity.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/OnboardingActivity.cs
  Toggl.Giskard/Activities/OutdatedAppActivity.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Activities/SelectClientActivity.cs
  Toggl.Giskard/Activities/SelectCountryActivity.cs
  Toggl.Giskard/Activities/SelectProjectActivity.cs
  Toggl.Giskard/Activities/SelectTagsActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Activities/SignUpActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Activities/TokenResetActivity.cs
  Toggl.Giskard/Resources/values-v23/Styles.xml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, crash

#3003 Add calendar settings view model
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelTests.cs
Labels: foundation

#2978 Visually distinguish ghost entries
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
  Toggl.Foundation.Tests/Mocks/MockTimeEntry.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntryViewModelTests.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
Labels: ios

#3006 🐛Make sure the heightConstraint is set to zero when scrolling
  Toggl.Daneel/Views/Log/RefreshControl.cs
Labels: glitch, ios

#2950 Fix giskard navigation while it doesn't have the MainTabBarViewModel implementation.
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Foundation.MvvmCross/App.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/NavigationService.cs
  Toggl.Foundation.MvvmCross/Services/IForkingNavigationService.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/AppStartTests.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.Foundation.Tests/TogglFoundationTests.cs
  Toggl.Foundation/PlatformInfo.cs
  Toggl.Foundation/TogglFoundation.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: android, blocking, foundation, ios

#3014 Add a way to open calendar settings
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
Labels: foundation, ios

#3008 Make calendar react to time entry/day changes
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation/Extensions/DataSourceExtensions.cs
Labels: foundation

#3020 Fix glitch when scrolling in the calendar view
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#3026 Calendar item view needs some love
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.designer.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
Labels: ios

#3040 Calendar: Fix the app for iOS 10
  Toggl.Daneel/Services/CalendarService.cs
Labels: ios

#2993 Allow long pressing for changing the offset of a time entry
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.designer.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/UpdateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
  Toggl.Foundation/Extensions/CalendarItemExtensions.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/UpdateTimeEntryInteractor.cs
Labels: foundation, ios

#3021 Giskard 1.3.2 Hotfix
  Toggl.Giskard/Activities/AboutActivity.cs
  Toggl.Giskard/Activities/BrowserActivity.cs
  Toggl.Giskard/Activities/EditProjectActivity.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/ForgotPasswordActivity.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/OnboardingActivity.cs
  Toggl.Giskard/Activities/OutdatedAppActivity.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Activities/SelectClientActivity.cs
  Toggl.Giskard/Activities/SelectCountryActivity.cs
  Toggl.Giskard/Activities/SelectProjectActivity.cs
  Toggl.Giskard/Activities/SelectTagsActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Activities/SignUpActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Activities/TokenResetActivity.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Resources/values-v23/Styles.xml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Startup/SplashScreen.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#3044 Calendar descriptions
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Foundation.Tests/CalendarItemTests.cs
  Toggl.Foundation/Calendar/CalendarItem.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#3013 🐞 confirm changes inconsistency
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
Labels: ios

#3025 Switch to non-localised strings
  Toggl.Giskard/Resources/layout/SelectTimeFragment.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#3033 Add calendar settings view controller
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Settings/CalendarSettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/CalendarSettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/CalendarSettingsViewController.xib
  Toggl.Daneel/ViewSources/SelectUserCalendarsTableViewSource.cs
  Toggl.Daneel/Views/Settings/CalendarSettingsTableViewHeader.cs
  Toggl.Daneel/Views/Settings/CalendarSettingsTableViewHeader.designer.cs
  Toggl.Daneel/Views/Settings/CalendarSettingsTableViewHeader.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#3043 Fix issue when dragging up
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#3051 Filter unselected user calendars
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.Tests/Interactors/Calendar/GetCalendarItemsForDateInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs
  Toggl.Foundation/Interactors/InteractorFactory.Calendar.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: bug, foundation

#3037 Prevent rating view from leaving blank space after dismissal
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: critical, glitch, ios

#3067 Fix calendar cell label sizes
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
Labels: glitch, ios

#3070 Fix duplicate workspace name crash
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Giskard/Services/DialogService.cs
Labels: crash, critical, ios

#3075 Add notification service interface
  Toggl.Foundation/Services/INotificationService.cs
  Toggl.Multivac/Notification.cs
Labels: foundation

#3094 Add url navigation to calendar view
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation/ApplicationUrls.cs
Labels: foundation

#3027 Fix collections being modified during enumeration in SegmentedRecyclerAdapter
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: android, foundation

#3077 Display blue time labels when in edit mode
  Toggl.Daneel/Cells/Calendar/EditingHourSupplementaryView.cs
  Toggl.Daneel/Cells/Calendar/EditingHourSupplementaryView.designer.cs
  Toggl.Daneel/Cells/Calendar/EditingHourSupplementaryView.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Daneel/Views/Calendar/ICalendarCollectionViewLayoutDataSource.cs
Labels: ios

#3059 👩‍🏫 Siri project setup
  .gitignore
  Toggl.Daneel.IntentBinding/ApiDefinition.cs
  Toggl.Daneel.IntentBinding/Properties/AssemblyInfo.cs
  Toggl.Daneel.IntentBinding/StructsAndEnums.cs
  Toggl.Daneel.IntentBinding/Toggl.Daneel.IntentBinding.csproj
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen.xcodeproj/project.pbxproj
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/AppDelegate.h
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/AppDelegate.m
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Assets.xcassets/AppIcon.appiconset/Contents.json
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Assets.xcassets/Contents.json
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Base.lproj/LaunchScreen.storyboard
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Base.lproj/Main.storyboard
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Info.plist
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Intents.intentdefinition
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/ViewController.h
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/ViewController.m
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/main.m
  Toggl.Daneel.IntentStaticLib/Makefile
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib.xcodeproj/project.pbxproj
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.h
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.m
  Toggl.Daneel.IntentStaticLib/libToggl.Daneel.IntentStaticLib.a
  Toggl.Daneel.SiriExtension/Info.plist
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.sln
Labels: ios

#3086 Donating first Siri intent
  Toggl.Daneel.IntentBinding/ApiDefinition.cs
  Toggl.Daneel.IntentBinding/StructsAndEnums.cs
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Intents.intentdefinition
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib.xcodeproj/project.pbxproj
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.h
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/StopTimerIntent.m
  Toggl.Daneel.IntentStaticLib/libToggl.Daneel.IntentStaticLib.a
  Toggl.Daneel.SiriExtension/Toggl.Daneel.SiriExtension.csproj
  Toggl.Daneel/Services/IntentDonationService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation/Services/IIntentDonationService.cs
  Toggl.Foundation/TogglFoundation.cs
  Toggl.Giskard/Services/DummyIntentDonationService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  docs/siri.md
Labels: ios

#3062 Fix calendar item icons
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.designer.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
Labels: ios

#3100 Create an interactor to unschedule notifications
  Toggl.Daneel/Services/NotificationService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.Tests/Interactors/BaseInteractorTests.cs
  Toggl.Foundation.Tests/Interactors/Notifications/UnscheduleAllNotificationsInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/Toggl.Foundation.Tests.csproj
  Toggl.Foundation.Tests/TogglFoundationTests.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Definitions.cs
  Toggl.Foundation/Interactors/InteractorFactory.Notifications.cs
  Toggl.Foundation/Interactors/Notifications/UnscheduleAllNotificationsInteractor.cs
  Toggl.Foundation/Toggl.Foundation.csproj
  Toggl.Foundation/TogglFoundation.cs
  Toggl.Giskard/Services/NotificationService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: foundation

#3102 Api token persisting
  Toggl.Daneel/Services/IosLoginManager.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation/Login/LoginManager.cs
  Toggl.Giskard/Startup/Setup.cs
Labels: foundation, ios

#3098 Check for permission before reading calendar events
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Foundation.MvvmCross/Services/BaseCalendarService.cs
  Toggl.Foundation.MvvmCross/Services/IPermissionsService.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
  Toggl.Foundation/Exceptions/NotAuthorizedException.cs
  Toggl.Foundation/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs
  Toggl.Giskard/Services/CalendarService.cs
Labels: foundation

#2997 Daneel 1.9 - Zoranel
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/Views/Rating/RatingView.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Giskard/Services/DialogService.cs
Labels: ios

#3103 iOS Notification Service
  Toggl.Daneel/Extensions/NotificationExtensions.cs
  Toggl.Daneel/Services/CalendarService.cs
  Toggl.Daneel/Services/NotificationService.cs
  Toggl.Daneel/Services/PermissionsService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Foundation.MvvmCross/Extensions/ObservableExtensions.cs
  Toggl.Foundation.MvvmCross/Services/BaseCalendarService.cs
  Toggl.Foundation.MvvmCross/Services/IPermissionsService.cs
  Toggl.Foundation.MvvmCross/Services/PermissionAwareCalendarService.cs
  Toggl.Foundation.MvvmCross/Services/PermissionAwareNotificationService.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Foundation/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs
  Toggl.Foundation/Interactors/Calendar/GetUserCalendarsInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Notifications.cs
  Toggl.Foundation/Interactors/Notifications/UnscheduleAllNotificationsInteractor.cs
  Toggl.Foundation/Services/INotificationService.cs
  Toggl.Giskard/Services/CalendarService.cs
  Toggl.Giskard/Services/NotificationService.cs
  Toggl.Giskard/Services/PermissionsService.cs
  Toggl.Multivac/Notification.cs
Labels: foundation, ios

#3112 Ask for notifications permission during calendar onboarding
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
Labels: foundation, ios

#3108 Increase drag indicator size
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Cells/Calendar/CalendarItemView.xib
Labels: ios

#3120 Always exit editing mode a single tap
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#3111 Editing time constraints
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#3114 Fix calendars not being loaded in the settings view
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
Labels: foundation

#3117 Keep calendar events always on the left
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#3130 Show the Toggl logo in the nav bar title
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
Labels: ios

#3134 Add the calendar selection icon to the calendar view
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: foundation, ios
