Repository toggl/mobileapp, pull requests merged in 2018-07, with the labels that each got.

#2469 Make report pie chart grouping smart
  Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
Labels: foundation

#2558 Android onboarding phase 1 step 1
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Extensions/OnboardingExtensions.cs
  Toggl.Giskard/Extensions/PopupOffsets.cs
  Toggl.Giskard/Extensions/PopupWindowWithDefaultGravityExtenstions.cs
  Toggl.Giskard/Helper/PopupWindowFactory.cs
  Toggl.Giskard/Resources/layout/TooltipWithRightArrow.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2573 Fix putting two running time entries into the database
  Toggl.Foundation.Tests/DataSources/SingletonDataSourceTests.cs
  Toggl.Foundation.Tests/DataSources/TogglDataSourceTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/CreateEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/States/Push/UpdateEntityStateTests.cs
  Toggl.Foundation/BaseStorageExtensions.cs
  Toggl.Foundation/DataSources/BaseDataSource.cs
  Toggl.Foundation/DataSources/DataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IBaseDataSource.cs
  Toggl.Foundation/DataSources/Interfaces/IDataSource.cs
  Toggl.Foundation/DataSources/ObservableDataSource.cs
  Toggl.Foundation/DataSources/SingletonDataSource.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Sync/States/Push/BasePushEntityState.cs
  Toggl.Foundation/Sync/States/Push/CreateEntityState.cs
  Toggl.Foundation/Sync/States/Push/DeleteEntityState.cs
  Toggl.Foundation/Sync/States/Push/UpdateEntityState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
  Toggl.PrimeRadiant.Realm/BaseStorage.cs
  Toggl.PrimeRadiant.Realm/Models/IModifiableId.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
  Toggl.PrimeRadiant.Realm/Models/RealmConstructors.tt
  Toggl.PrimeRadiant.Realm/RealmAdapter.cs
  Toggl.PrimeRadiant.Realm/Repository.cs
  Toggl.PrimeRadiant.Tests/Realm/TestAdapter.cs
  Toggl.PrimeRadiant/IBaseStorage.cs
  Toggl.PrimeRadiant/IRepository.cs
  Toggl.PrimeRadiant/ISingleObjectStorage.cs
Labels: crash

#2591 Normalize app transitions
  Toggl.Giskard/Activities/AboutActivity.cs
  Toggl.Giskard/Activities/BrowserActivity.cs
  Toggl.Giskard/Activities/EditProjectActivity.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/ForgotPasswordActivity.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/OutdatedAppActivity.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Activities/SelectClientActivity.cs
  Toggl.Giskard/Activities/SelectCountryActivity.cs
  Toggl.Giskard/Activities/SelectProjectActivity.cs
  Toggl.Giskard/Activities/SelectTagsActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Activities/SignUpActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Activities/TokenResetActivity.cs
  Toggl.Giskard/Resources/anim/abc_slide_in_left.xml
  Toggl.Giskard/Resources/anim/abc_slide_in_right.xml
  Toggl.Giskard/Resources/anim/abc_slide_out_left.xml
  Toggl.Giskard/Resources/anim/abc_slide_out_right.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2595 Add billable and tags image to log
  Toggl.Daneel/Combiners/TImeEntryLogViewCellFadeViewConstraintValueCombiner.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.designer.cs
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.xib
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntryViewModel.cs
Labels: ios

#2570 Enable AOT for release builds
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#2611 🐛 Add missing awakeFromNib
  Toggl.Daneel/Views/LoginTextField.cs
Labels: ios

#2606 Fix sync scroll bug
  Toggl.Giskard/Adapters/SegmentedRecyclerAdapter.cs
Labels: android

#2600 Stop one time entry if two are running
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/DataSources/BaseDataSourceTests.cs
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/DataSources/TogglDataSourceTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.PrimeRadiant.Realm/RealmAdapter.cs
Labels: crash

#2596 Android onboarding phase 1 step 3
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Extensions/PopupWindowWithDefaultGravityExtenstions.cs
  Toggl.Giskard/Resources/layout/TooltipWithRightBottomArrow.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#2575 Onboarding Phase 2 / Step 2
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Extensions/PopupOffsets.cs
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#2629 Fix automatic login with Google
  Toggl.Giskard/Services/GoogleService.cs
Labels: android

#2604 Onboarding Phase 2 / Step 1
  Toggl.Foundation.MvvmCross/Onboarding/MainView/EditTimeEntryOnboardingStep.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SuggestionsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/SegmentedRecyclerAdapter.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/TooltipWithCenteredBottomArrow.axml
  Toggl.Giskard/Resources/layout/TooltipWithLeftTopArrow.axml
  Toggl.Giskard/Resources/layout/TooltipWithRightArrow.axml
  Toggl.Giskard/Resources/layout/TooltipWithRightBottomArrow.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Views/MainRecyclerView.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: android

#2642 Fix editable token area bug
  Toggl.Giskard/Autocomplete/AutocompleteExtensions.cs
Labels: android, critical

#2644 Fix perceived sluggishness when starting a time entry
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
Labels: android, critical

#2654 Fix issue when the continue action stays visible after swipe
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
Labels: android, glitch

#2655 Fix reveal animation crash
  Toggl.Giskard/Extensions/CircularRevealAnimation.cs
  Toggl.Giskard/Extensions/ViewExtensions.cs
Labels: android, crash

#2443 Feedback API
  Toggl.Multivac/Ensure.cs
  Toggl.Ultrawave.Tests.Integration/FeedbackApiTests.cs
  Toggl.Ultrawave.Tests/ApiClients/FeedbackApiTests.cs
  Toggl.Ultrawave/ApiClients/BaseApi.cs
  Toggl.Ultrawave/ApiClients/FeedbackApiClient.cs
  Toggl.Ultrawave/ApiClients/Interfaces/IFeedbackApi.cs
  Toggl.Ultrawave/ITogglApi.cs
  Toggl.Ultrawave/Network/Endpoints/Endpoints.cs
  Toggl.Ultrawave/Network/Endpoints/FeedbackEndpoints.cs
  Toggl.Ultrawave/TogglApi.cs
Labels: api

#2576 Refactor how the swipe actions are rendered
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Views/MainRecyclerViewLogViewHolder.cs
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
Labels: android, refactoring

#2643 Trim email
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Multivac.Tests/EmailTests.cs
  Toggl.Multivac/Email.cs
Labels: foundation, glitch

#2657 Giskard 1.0 - Carbon #2
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Autocomplete/AutocompleteExtensions.cs
  Toggl.Giskard/Extensions/CircularRevealAnimation.cs
  Toggl.Giskard/Extensions/ViewExtensions.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Services/GoogleService.cs
  Toggl.Giskard/TemplateSelectors/StartTimeEntrySuggestionsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/MainRecyclerViewTouchCallback.cs
Labels: android

#2641 🚧 Dismiss rating view after selecting main cta
  Toggl.Daneel/Views/Rating/RatingView.cs
Labels: bug, ios

#2621 Check for no-workspace in database
  Toggl.Foundation.Tests/Sync/States/Pull/NoWorkspaceExceptionsThrowingStateTests.cs
  Toggl.Foundation/Sync/States/Pull/NoWorkspaceDetectingState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: foundation, sync

#2612 🚧 Use `InputDelegate`
  Toggl.Daneel/Autocomplete/EmptyInputDelegate.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#2675 Fix get all between tests
  Toggl.Ultrawave.Tests.Integration/TimeEntriesApiTests.cs
Labels: api

#2674 Prevent edit view from opening multiple times on successive TE tap
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
Labels: android

#2679 Add observable wrapper over grouped collection
  Toggl.Foundation.MvvmCross/Collections/GroupedOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/IGroupOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/ObservableGroupedOrderedCollection.cs
  Toggl.Foundation.MvvmCross/Collections/SectionedIndex.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/GroupedOrderedCollectionTests.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/ObservableGroupedOrderedListTests.cs
Labels: foundation

#2689 Fix AppCenter initialization logic
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android, bug

#2688 🚧 Move call to external services to very beginning
  Toggl.Daneel/Startup/AppDelegate.cs
Labels: bug, ios

#2645 Fix iOS token margins
  Toggl.Daneel/Autocomplete/AutocompleteExtensions.cs
  Toggl.Daneel/Autocomplete/ProjectTextAttachment.cs
  Toggl.Daneel/Autocomplete/TagTextAttachment.cs
  Toggl.Daneel/Autocomplete/TokenTextAttachment.cs
  Toggl.Daneel/Binding/TextViewTagListTargetBinding.cs
  Toggl.Daneel/Toggl.Daneel.csproj
Labels: glitch, ios

#2610 🚧 Patch reports animation glitch
  Toggl.Daneel/Binding/ViewVisibilityWithFadeTargetBinding.cs
Labels: glitch, ios

#2681 ✨ Add build number to Setting page
  Toggl.Daneel/PlatformConstants.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/IPlatformConstants.cs
  Toggl.Giskard/PlatformConstants.cs
Labels: android, ios

#2691 Hide add to duration shortcuts when editing duration
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Resources/layout/SelectTimeDurationPage.axml
Labels: android, bug

#2579 Rxfactor login view
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIButtonRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UITextFieldRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIViewRxExtensions.cs
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/ForgotPasswordViewController.cs
  Toggl.Daneel/ViewControllers/Login.storyboard
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/ViewControllers/LoginViewController.designer.cs
  Toggl.Daneel/ViewControllers/ReactiveViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Daneel/ViewControllers/TokenResetViewController.cs
  Toggl.Daneel/Views/LoginTextField.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/ViewModels/IReactiveBindingHolder.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Giskard/Activities/LoginActivity.ViewBinds.cs
  Toggl.Giskard/Activities/LoginActivity.cs
  Toggl.Giskard/Extensions/UIExtensions.cs
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Services/OnePasswordService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/AutocompleteEditText.cs
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
  Toggl.Multivac/Password.cs
Labels: android, foundation, ios, refactoring

#2700 Improve feedback api tests
  Toggl.Ultrawave.Tests.Integration/FeedbackApiTests.cs
Labels: api

#2696 Override CloseFragmentDialog to check for nullity to avoid crashes
  Toggl.Giskard/Presenters/TogglPresenter.cs
Labels: android, crash

#2697 Make login card text and image more dimension/font friendly
  Toggl.Giskard/Resources/layout/LoginActivity.axml
Labels: android, glitch

#2706 🚧 Replace `BindTap` with a proper `targetBinding`
  Toggl.Daneel/Binding/TextViewWithPlaceholderDidBecomeFirstResponderTargetBinding.cs
  Toggl.Daneel/Extensions/ViewBindingExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/Views/TextViewWithPlaceholder.cs
Labels: glitch, ios

#2601 Fix time entries rivals resolver
  Toggl.Foundation.Tests/Sync/ConflictResolution/TimeEntryRivalsResolverTests.cs
  Toggl.Foundation/Sync/ConflictResolution/TimeEntryRivalsResolver.cs
Labels: bug, foundation

#2718 Fix crash caused by spans in different order
  Toggl.Giskard/Autocomplete/AutocompleteExtensions.cs
Labels: android

#2713 Fix main running te font scale/display size friendly
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/LinkerPleaseInclude.cs
  Toggl.Giskard/Resources/layout/MainRunningTimeEntry.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/packages.config
Labels: android, glitch

#2692 Adjust maximum modal presentation height
  Toggl.Daneel/Presentation/Transition/ModalPresentationController.cs
Labels: ios

#2711 Giskard 1.1 - Nitrogen
  Toggl.Giskard/Autocomplete/AutocompleteExtensions.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
Labels: android

#2708 Make login screen scrollable
  Toggl.Giskard/Resources/layout/LoginActivity.axml
Labels: android, glitch

#2707 Fix signup hint card layout on small phones with larger fonts
  Toggl.Giskard/Resources/layout/SignUpActivity.axml
Labels: android, glitch

#2722 Project fade out
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
Labels: android

#2727 Fix clients/tasks overlapping (+ConstraintLayout on main TE log)
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Giskard/Resources/layout/MainLogCellDescriptionOnly.axml
  Toggl.Giskard/TemplateSelectors/MainTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, bug

#2724 Login: update bottom signup card to use fixed dp font sizes
  Toggl.Giskard/Resources/layout/LoginActivity.axml
Labels: android, glitch

#2729 Fix Edit TE UI dividers
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#2725 Signup: make signup scrollable to support tiny screens and larger fonts
  Toggl.Giskard/Resources/layout/LoginActivity.axml
  Toggl.Giskard/Resources/layout/SignUpActivity.axml
Labels: android, glitch

#2738 🚧 Add snooze logic to rating view
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: bug, ios

#2721 🚧 Reload log tableView after showing rating UI
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: bug, glitch, ios

#2739 Fix main log TE ConstraintLayout client/task constraints
  Toggl.Giskard/Resources/layout/MainLogCell.axml
Labels: android, glitch

#2746 Fix description on RTL layout
  Toggl.Giskard/Resources/layout/MainLogCell.axml
Labels: android, glitch

#2748 Avoid main log adapter access during sync
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/SegmentedRecyclerAdapter.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Views/MainRecyclerView.cs
Labels: android, crash

#2761 Remove NoHistroy flag from splash screen
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android, crash

#2766 Remove NoHistory flag from splash screen (#2761)
  Toggl.Giskard/Startup/SplashScreen.cs
Labels: android

#2752 Giskard 1.2 - Oxygen
  Toggl.Giskard/Properties/AndroidManifest.xml
Labels: android

#2768 Fix randomly failing tests
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/Converters/ParametricTimeSpanToDurationValueConverter.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Converters/ParametricTimeSpanToDurationValueConverterTests.cs
Labels: android, ios

#2772 Fix workspace builder
  Toggl.Foundation/Models/Workspace.cs
Labels: foundation

#2710 Custom Feedback UI
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIApplicationRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIControlRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UITextViewRxExtensions.cs
  Toggl.Daneel/Extensions/UIKitRxExtensions/UIViewRxExtensions.cs
  Toggl.Daneel/Services/DialogService.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.designer.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/SendFeedbackViewController.xib
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/Services/FeedbackService.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/Services/IFeedbackService.cs
  Toggl.Foundation.MvvmCross/ViewModels/IReactiveBindingHolder.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/Services/FeedbackServiceTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/BaseViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SendFeedbackViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Giskard/Services/DialogService.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
Labels: ios

#2773 Enable predictive input on description in Edit TE View
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#2774 Add comments to ActivityIndicator animation methods
  Toggl.Daneel/ViewControllers/LoginViewController.cs
  Toggl.Daneel/Views/ActivityIndicatorView.cs
Labels: ios
