Repository toggl/mobileapp, pull requests merged in 2019-03, with the labels that each got.

#4494 Add useful UI test extension methods
  Toggl.Daneel.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Giskard.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#4482 Add new cs for report tests
  Toggl.Tests.UI/ReportsTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#4516 Remove the Feedback api from the data source
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Interactors/InteractorFactory.Settings.cs
Labels: foundation, refactoring

#4518 iPad: Make app universal and limit rotation to iPad only
  Toggl.Daneel/Info.plist
Labels: ios

#4495 Add UI tests for swipe to delete
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/MainTests.cs
Labels: ui-tests

#4487 🧪 ui tests for starting a manual TE
  Toggl.Daneel.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
  Toggl.Tests.UI/StartManualTimeEntryTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#4497 Refactor Rating view by using observables instead of hints
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Hints/ToggleRatingViewVisibilityHint.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Presenters/TogglPresenter.cs
Labels: android, foundation, ios, refactoring

#4520 Schedule calendar notifications on device restart
  Toggl.Giskard/BroadcastReceivers/BootCompletedBroadcastReceiver.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Services/ScheduleEventNotificationsService.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4407 Refactor EditTimeEntryViewModel and implement edit of grouped items
  Toggl.Daneel/Services/DialogServiceIos.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/Services/IDialogService.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/UpdateMultipleTimeEntriesInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/TestExtensions/FluentAssertionsExtensions.cs
  Toggl.Foundation.Tests/TestExtensions/TestSchedulerExtensions.cs
  Toggl.Foundation/DTOs/EditTimeEntryDto.cs
  Toggl.Foundation/Extensions/ThreadSafeExtensions.cs
  Toggl.Foundation/Interactors/Generic/GetMultipleByIdInteractor.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Tag.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/InteractorFactory.User.cs
  Toggl.Foundation/Interactors/TimeEntry/DeleteMultipleTimeEntriesInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/UpdateMultipleTimeEntriesInteractor.cs
  Toggl.Foundation/Interactors/User/GetCurrentUserInteractor.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Services/DialogServiceAndroid.cs
  Toggl.Multivac/Extensions/EnumerableExtensions.cs
  Toggl.Multivac/Extensions/FunctionalExtensions.cs
Labels: foundation

#4515 Remove the dependency on the shortcut creator
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests/UserAccessManager/UserAccessManagerTests.cs
  Toggl.Foundation/UserAccessManager/UserAccessManager.cs
Labels: foundation, refactoring

#4517 Remove Reports Provider
  Toggl.Foundation.MvvmCross/DataSourceExtensions.cs
  Toggl.Foundation.MvvmCross/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Foundation.Tests/Interactors/Reports/GetProjectSummaryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation/DataSources/Interfaces/ITogglDataSource.cs
  Toggl.Foundation/DataSources/TogglDataSource.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.Definitions.cs
  Toggl.Foundation/Interactors/InteractorFactory.Reports.cs
  Toggl.Foundation/Interactors/Reports/GetProjectSummaryInteractor.cs
  Toggl.Foundation/Reports/IReportsProvider.cs
  Toggl.Foundation/Reports/ReportsMemoryCache.cs
Labels: foundation, refactoring

#4527 Add base sectioned recycler adapter for Android
  Toggl.Giskard/Adapters/BaseSectionedRecyclerAdapter.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4525 Calendar header layout
  Toggl.Giskard/Fragments/CalendarFragment.ViewBinds.cs
  Toggl.Giskard/Resources/drawable/CalendarHeaderDayBackground.xml
  Toggl.Giskard/Resources/layout/CalendarFragment.axml
  Toggl.Giskard/Resources/layout/CalendarHeaderView.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4531 Add UI tests for chaning project
  Toggl.Daneel.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/ViewControllers/SelectProjectViewController.xib
  Toggl.Daneel/Views/StartTimeEntry/ProjectSuggestionViewCell.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard/Resources/layout/SelectProjectActivity.axml
  Toggl.Giskard/Resources/layout/SelectProjectActivityProjectCell.axml
  Toggl.Tests.UI/EditTimeEntryTests.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/Extensions/StartTimeEntryExtensions.cs
Labels: ui-tests

#4492 Calendroid: Calendar adapter
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Giskard/Adapters/Calendar/Anchor.cs
  Toggl.Giskard/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Giskard/Adapters/Calendar/LayoutAnchorsCalculator.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
  Toggl.Giskard/Resources/layout/CalendarEntryCell.axml
  Toggl.Giskard/Services/CalendarServiceAndroid.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/BaseRecyclerViewHolder.cs
  Toggl.Giskard/ViewHolders/CalendarEntryViewHolder.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.ScrollHelper.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.cs
  Toggl.Giskard/Views/CalendarRecyclerView.cs
Labels: android

#4540 Bind views and button in calendar header
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
  Toggl.Giskard/Resources/values/Strings.xml
Labels: android

#4455 Add diffing and animations to table views
  Toggl.Daneel/Extensions/Reactive/BaseTableViewSourceExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/SelectBeginningOfWeekViewController.cs
  Toggl.Daneel/ViewControllers/SelectClientViewController.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.cs
  Toggl.Daneel/ViewControllers/SelectDateFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectDefaultWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/Settings/CalendarSettingsViewController.cs
  Toggl.Daneel/ViewControllers/Settings/LicensesViewController.cs
  Toggl.Daneel/ViewControllers/Settings/UpcomingEventsNotificationSettingsViewController.cs
  Toggl.Daneel/ViewControllers/SyncFailuresViewController.cs
  Toggl.Daneel/ViewSources/ClientTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/TableView/BaseTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/TableView/CustomTableViewSource.cs
  Toggl.Daneel/ViewSources/ReportsTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectTagsTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectUserCalendarsTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/AnimatableSectionModel.cs
  Toggl.Foundation.MvvmCross/Collections/CollectionSection.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/Diffing.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/DuplicateItemException.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/DuplicateSectionException.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/EditEvent.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/ItemAssociatedData.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/ItemPath.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/SectionAssociatedData.cs
  Toggl.Foundation.MvvmCross/Collections/SectionModel.cs
  Toggl.Foundation.MvvmCross/Collections/SectionModelInterfaces.cs
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesGrouping.cs
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesGroupsFlattening.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/DaySummaryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/DiffingTests.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/Extensions/ChangesetExtensions.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/Extensions/ListExtensions.cs
  Toggl.Foundation.Tests/MvvmCross/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Foundation.Tests/MvvmCross/Transformations/TimeEntriesGroupingTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Foundation.Tests/TestExtensions/ITestableObserverExtensions.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
Labels: ios, wip

#4522 Change integration tests for reports totals
  Toggl.Ultrawave.Tests.Integration/TimeEntriesReportsApiTests.cs
Labels: api

#4533 Edit view - grouped time entries
  Toggl.Daneel/Extensions/Reactive/UISwitchExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UITextViewExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Transformations/ProjectTaskClientToAttributedString.cs
  Toggl.Daneel/Transformations/TagsListToAttributedString.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/Views/TextViewWithPlaceholder.cs
  Toggl.Foundation.MvvmCross/Combiners/BaseTwoValuesCombiner.cs
  Toggl.Foundation.MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombiner.cs
  Toggl.Foundation.MvvmCross/Combiners/DateTimeOffsetTimeFormatValueCombiner.cs
  Toggl.Foundation.MvvmCross/Combiners/ShowTagsValueCombiner.cs
  Toggl.Foundation.MvvmCross/ViewModels/BrowserViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarPermissionDeniedViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectCountryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/UpcomingEventsNotificationSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetDateFormatValueCombinerTests.cs
  Toggl.Foundation.Tests/MvvmCross/Combiners/DateTimeOffsetTimeFormatValueCombinerTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Foundation/Services/IRxActionFactory.cs
  Toggl.Foundation/Services/RxActionFactory.cs
  Toggl.Giskard/Startup/TogglBindingBuilder.cs
  Toggl.Multivac/Extensions/ReactiveExtensions.cs
  Toggl.Multivac/Extensions/RxAction/OutputAction.cs
Labels: ios

#4544 Add UI tests for undo delete
  Toggl.Daneel.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/Views/SnackBar.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/Exceptions/NoTimeEntryException.cs
  Toggl.Tests.UI/Exceptions/TimeEntryFoundException.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/MainTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: blocking, ui-tests

#4555 Fix bug when accepting calendar permission from the header
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
Labels: android

#4556 Set initial tab item after activity restarts
  Toggl.Giskard/Activities/MainTabBarActivity.cs
Labels: android

#4561 Hide onboarding tooltips on different fragments
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/MainTabBarActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Extensions/OnboardingExtensions.cs
  Toggl.Giskard/Fragments/MainFragment.Onboardings.cs
  Toggl.Giskard/Fragments/MainFragment.cs
Labels: android

#4452 Daneel 1.18 (Kalgan)
  Toggl.Daneel.SiriExtension.UI/Info.plist
  Toggl.Daneel.SiriExtension/Info.plist
  Toggl.Daneel/Info.plist
Labels: ios, release

#4569 Reload log when date changes to update 'Today' and 'Yesterday' headers
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: ios

#4566 Fix expansion/collapsion animations - grouped time entries
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
Labels: ios

#4583 🧠 Use Identity in MainRecyclerAdapter
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
Labels: android

#4438 Support Time Entries Groups in Edit TE View
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/EditTimeEntryActivity.Onboarding.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/SettingsActivity.cs
  Toggl.Giskard/Extensions/Reactive/CompoundButtonExtensions.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Giskard/Resources/layout/EditTimeEntryTagCell.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/TemplateSelectors/TagsListTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/StringViewHolder.cs
  Toggl.Giskard/Views/TagsListRecyclerView.cs
Labels: android

#4585 Remove unused value converter
  Toggl.Foundation.MvvmCross/Converters/DateToTitleStringValueConverter.cs
  Toggl.Foundation.Tests/MvvmCross/Converters/DateToTitleStringValueConverterTests.cs
Labels: foundation

#4480 👨‍🌾 ui test for adding te with existing client
  Toggl.Daneel.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditProjectViewController.xib
  Toggl.Daneel/ViewControllers/SelectClientViewController.xib
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
  Toggl.Daneel/ViewSources/CreateSuggestionGroupedTableViewSource.cs
  Toggl.Daneel/Views/Client/ClientViewCell.xib
  Toggl.Daneel/Views/EntityCreation/CreateEntityViewCell.cs
  Toggl.Daneel/Views/EntityCreation/CreateEntityViewCell.designer.cs
  Toggl.Daneel/Views/EntityCreation/CreateEntityViewCell.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Tests.UI/StartTimeEntryTests.cs
Labels: ui-tests

#4582 Fix editing inaccessible time entries
  Toggl.Daneel/Extensions/Reactive/UIViewExtensions.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation/Interactors/Generic/GetMultipleByIdInteractor.cs
Labels: ios

#4580 Fix select calendars layout
  Toggl.Giskard/Resources/layout/SelectUserCalendarsBase.axml
Labels: android

#4593 Fix date picker not closing
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
Labels: blocking, bug, critical, ios

#4537 Add UI tests for continuing an entry
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Tests.UI/Exceptions/NoRunningTimeEntryException.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/MainTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#4577 Handle calendar permissions when "don't ask again" was selected
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarPermissionDeniedViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarPermissionDeniedViewModelTests.cs
Labels: android

#4563 iPad: Signup view
  Toggl.Daneel/ViewControllers/SignupViewController.cs
  Toggl.Daneel/ViewControllers/SignupViewController.xib
Labels: ios

#4609 Add tracking related to Grouped Time Entries
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Foundation.Tests/AnalyticsService/StartTimeEntryEventTests.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/ContinueTimeEntryMode.cs
  Toggl.Foundation/Analytics/EditTimeEntryOrigin.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Analytics/TimeEntryStartOrigin.cs
  Toggl.Foundation/DataSources/TimeEntriesDataSource.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Giskard/Activities/MainActivity.Onboardings.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
  Toggl.Giskard/ViewHelpers/MainRecyclerViewTouchCallback.cs
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
Labels: foundation

#4554 Modal (dialog) presentation support for iPad
  Toggl.Daneel/Presentation/Transition/ModalDialogPresentationController.cs
  Toggl.Daneel/Presentation/Transition/ModalPresentationController.cs
  Toggl.Daneel/ViewControllers/KeyboardAwareViewController.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#4615 Fix calendar notifications row visibility
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Giskard/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/SettingsFragment.cs
  Toggl.Giskard/Resources/layout/SettingsFragment.axml
Labels: android

#4606 Fix android calendar settings
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Giskard/Resources/layout/CalendarSettingsActivity.axml
  Toggl.Giskard/Resources/layout/SelectUserCalendarsBase.axml
Labels: android, bug

#4620 Implement handling of UI elements for Inaccessible Workspaces
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
Labels: android

#4627 Fix GTE iOS glitch
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
Labels: ios

#4629 GTE: make collapsing and expanding button tappable area larger
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.designer.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
Labels: ios

#4608 Continue Last Entry intent
  Toggl.Daneel.IntentBinding/ApiDefinition.cs
  Toggl.Daneel.IntentBinding/StructsAndEnums.cs
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/AppDelegate.m
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Base.lproj/Intents.intentdefinition
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/Info.plist
  Toggl.Daneel.IntentCodeGen/Toggl.Daneel.IntentCodeGen/en.lproj/Intents.strings
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib.xcodeproj/project.pbxproj
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/ContinueTimerIntent.h
  Toggl.Daneel.IntentStaticLib/Toggl.Daneel.IntentStaticLib/ContinueTimerIntent.m
  Toggl.Daneel.IntentStaticLib/libToggl.Daneel.IntentStaticLib.a
  Toggl.Daneel.SiriExtension.UI/Info.plist
  Toggl.Daneel.SiriExtension.UI/IntentViewController.cs
  Toggl.Daneel.SiriExtension/ContinueTimerIntentHandler.cs
  Toggl.Daneel.SiriExtension/Info.plist
  Toggl.Daneel.SiriExtension/IntentHandler.cs
  Toggl.Daneel.SiriExtension/Toggl.Daneel.SiriExtension.csproj
  Toggl.Daneel/Services/IntentDonationServiceIos.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#4631 Make Done/Save behave differently depending on description text field focus
  Toggl.Giskard/Activities/EditTimeEntryActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Extensions/Reactive/TextViewExtensions.cs
  Toggl.Giskard/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#4624 Calendroid: Fix calendar updates
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
Labels: android, bug

#4649 Fix calendar events background and text color
  Toggl.Giskard/Services/CalendarServiceAndroid.cs
  Toggl.Giskard/ViewHolders/CalendarEntryViewHolder.cs
Labels: android

#4534 iPad: Onboarding screens
  Toggl.Daneel/ViewControllers/OnboardingViewController.cs
  Toggl.Daneel/ViewControllers/OnboardingViewController.designer.cs
  Toggl.Daneel/ViewControllers/OnboardingViewController.xib
  Toggl.Foundation/Resources.resx
Labels: ios

#4567 Daneel 1.19 (Konom)
  Toggl.Daneel.SiriExtension.UI/Info.plist
  Toggl.Daneel.SiriExtension/Info.plist
  Toggl.Daneel/Info.plist
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
Labels: ios, release

#4633 Make sure keyboard does not hide the "password reset successful" message
  Toggl.Daneel/ViewControllers/ForgotPasswordViewController.cs
Labels: ios

#4625 Calendroid: Fix calendar columns update
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
Labels: android, bug

#4654 GTE: Open change date view instead of wheel view when tapping the Start date
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
Labels: ios

#4592 Fix identity comparison for diffing
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Collections/AnimatableSectionModel.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/Diffing.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/DuplicateItemException.cs
  Toggl.Foundation.MvvmCross/Collections/Diffing/DuplicateSectionException.cs
  Toggl.Foundation.MvvmCross/Collections/SectionModelInterfaces.cs
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesGroupsFlattening.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/DaySummaryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/GroupId.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/Identity/DayHeaderKey.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/Identity/IMainLogKey.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/Identity/SingleTimeEntryKey.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/Identity/TimeEntriesGroupKey.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/DiffingTests.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/Extensions/ChangesetExtensions.cs
  Toggl.Foundation.Tests/MvvmCross/Collections/Extensions/ListExtensions.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
Labels: android, ios

#4650 Calendroid: Fix layout for short tes
  Toggl.Giskard/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Giskard/Resources/layout/CalendarEntryCell.axml
  Toggl.Giskard/ViewHolders/CalendarEntryViewHolder.cs
Labels: android, bug

#4648 iPad version: Start TE
  Toggl.Daneel/Presentation/Transition/ModalPresentationController.cs
  Toggl.Daneel/Services/DialogServiceIos.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
Labels: ios

#4659 Show start time entry view when tapping on an empty space
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
Labels: android

#4657 Fixes main log cell color when in group
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Giskard/Resources/values/Colors.xml
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
Labels: android

#4670 Fix crashes in start time entry view
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/EntityCreation/CreateEntityViewCell.xib
Labels: blocking, crash, ios

#4676 Disable going back after login
  Toggl.Giskard/Presenters/TogglPresenter.cs
Labels: android

#4679 Use the instances content provider for recurring events
  Toggl.Giskard/Services/CalendarServiceAndroid.cs
Labels: android

#4682 Fix recycling in base sectioned adapter
  Toggl.Giskard/Adapters/BaseSectionedRecyclerAdapter.cs
Labels: android

#4672 GTE: fix iOS fade in main log cells
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
Labels: ios

#4691 Fix sync tests build after modifying sync manager and data source
  Toggl.Foundation.Tests.Sync/Helpers/AppServices.cs
Labels: sync

#4693 Fix the padding and settings header label
  Toggl.Giskard/Resources/layout/SettingsActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
Labels: android

#4683 Fix link calendars button padding in Android < API 26
  Toggl.Giskard/Resources/layout/CalendarOnboardingView.axml
Labels: android

#4688 Hide calendar recycler view when onboarding is visible
  Toggl.Giskard/Fragments/CalendarFragment.cs
Labels: android, bug

#4699 Initialize data source on startup
  Toggl.Giskard/Startup/Setup.cs
Labels: android, critical

#4689 Fix android calendar events transparency and android pre-23 all white backgrounds
  Toggl.Giskard/Resources/drawable/CalendarEntryBackground.xml
  Toggl.Giskard/ViewHolders/CalendarEntryViewHolder.cs
Labels: android, bug

#4697 Fix non expandable groups
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/GroupId.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLog/GroupIdTests.cs
Labels: bug

#4678 Use Batch update in Multi TE Update interactor
  Toggl.Foundation.Tests/Interactors/TimeEntry/UpdateMultipleTimeEntriesInteractorTests.cs
  Toggl.Foundation/Diagnostics/MeasuredOperation.cs
  Toggl.Foundation/Extensions/ConflictResolutionResultExtensions.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/UpdateMultipleTimeEntriesInteractor.cs
Labels: foundation

#4705 Prevent the app from crashing when you open project selection view
  Toggl.Daneel/ViewSources/SelectProjectTableViewSource.cs
Labels: crash, ios

#4709 Save selected calendar ids on close and done actions
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
Labels: android

#4710 Fix notification unscheduling and double schedules
  Toggl.Giskard/Services/NotificationServiceAndroid.cs
Labels: android, bug

#4700 GTE: fix startup crash
  Toggl.Foundation/Interactors/User/GetCurrentUserInteractor.cs
Labels: crash, foundation

#4711 Remove Android Calendar Inspector and todos
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.Inspector.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.LayoutState.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.ScrollHelper.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.cs
Labels: android

#4713 Fix broken signup on android < 24
  Toggl.Giskard/PlatformInfoAndroid.cs
Labels: android, bug

#4731 iPad version: Edit Project
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Daneel/ViewControllers/SelectColorViewController.cs
  Toggl.Daneel/ViewControllers/SelectColorViewController.xib
  Toggl.Daneel/Views/Color/HueSaturationPickerView.cs
  Toggl.Daneel/Views/Color/ValueSliderView.cs
Labels: ios

#4739 Fix delete time entries in GTE
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/SoftDeleteMultipleTimeEntriesInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/SoftDeleteMultipleTimeEntriesInteractor.cs
Labels: foundation

#4741 Removing duplicate classes from IosCompatibilityNames.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
Labels: ios

#4581 📐iPad version: Timer page
  Toggl.Daneel/ViewControllers/MainViewController.xib
Labels: ios

#4737 GTE: Measure diffing perf #2
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Foundation/Diagnostics/MeasuredOperation.cs
Labels: ios, metrics

#4742 Fix main log screen empty view positioning after signup
  Toggl.Daneel/Views/Log/TimeEntriesEmptyLogView.xib
Labels: ios

#4751 🐛 guarding against Siri tracking crashes
  Toggl.Daneel/ViewControllers/MainViewController.cs
Labels: bug, ios

#4680 Fix project and tag creation cells in start view
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: android, blocking, bug, ios

#4746 Fix threading problem when fetching calendar items
  Toggl.Foundation/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs
Labels: android

#4486 RxFactor the Edit Project view
  Toggl.Daneel/Extensions/Reactive/UISwitchExtensions.cs
  Toggl.Daneel/Extensions/Reactive/UIViewExtensions.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/BrowserViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarPermissionDeniedViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectCountryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/UpcomingEventsNotificationSettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation/Services/IRxActionFactory.cs
  Toggl.Foundation/Services/RxActionFactory.cs
  Toggl.Foundation/Toggl.Foundation.csproj
  Toggl.Giskard/Activities/EditProjectActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditProjectActivity.cs
  Toggl.Giskard/Extensions/Reactive/LayoutParamsExtensions.cs
  Toggl.Giskard/Extensions/Reactive/ViewExtensions.cs
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/ColorSelectionViewHolder.cs
  Toggl.Giskard/Views/CircleView.cs
  Toggl.Multivac/Extensions/RxAction/BehaviorRelay.cs
  Toggl.Multivac/Extensions/RxAction/OutputAction.cs
  Toggl.Multivac/Extensions/RxAction/RxAction.cs
Labels: foundation, refactoring

#4760 💥 Fix crash in settings when no avatar picture is available
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
Labels: android

#4762 Fix month not updating in the reports calendar view
  Toggl.Giskard/Views/ReportsCalendarView.cs
Labels: android

#4725 Add release checklist template
  .github/ISSUE_TEMPLATE/e-release-checklist.md
Labels: release

#4772 Update API error messages deserialization
  Toggl.Ultrawave.Tests/Exceptions/ApiErrorResponsesTests.cs
  Toggl.Ultrawave/Exceptions/ApiException.cs
  Toggl.Ultrawave/Models/ErrorMessage.cs
  Toggl.Ultrawave/Models/ResponseError.cs
Labels: api

#4775 Fix text color in the reports calendar item
  Toggl.Giskard/ViewHolders/CalendarDayCellViewHolder.cs
Labels: android

#4786 Fix crash when updating date range in reports calendar
  Toggl.Giskard/Adapters/ReportsCalendarPagerAdapter.cs
Labels: android, crash

#4793 Fix dismissing of start time entry view
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
Labels: bug, ios

#4784 Fix VoiceOver for main screen
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/Views/Suggestions/SuggestionView.cs
Labels: bug, ios

#4808 Fix calendar crashes
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewZoomHelper.cs
Labels: crash, ios

#4800 Fix missing project label on start te vm
  Toggl.Giskard/ViewHolders/StartTimeEntry/TimeEntrySuggestionViewHolder.cs
Labels: android, bug

#4813 Use local time zone instead of a hardcoded time zone for integration tests
  Toggl.Ultrawave.Tests.Integration/Helper/User.cs
Labels: api

#4796 Fix crash in adapter when list of items is null
  Toggl.Giskard/Adapters/BaseSectionedRecyclerAdapter.cs
Labels: android, crash

#4809 Fix duration not being applied
  Toggl.Giskard/Activities/EditDurationActivity.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
Labels: android

#4821 Fix initially scrolled out of sight "create suggestions" on StartTimeEntry View
  Toggl.Giskard/Resources/layout/StartTimeEntryActivityNoEntityCell.axml
Labels: android

#4818 Make sure password reset error is hidden when it should
  Toggl.Foundation.MvvmCross/ViewModels/ForgotPasswordViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ForgotPasswordViewModelTests.cs
Labels: glitch, ios

#4778 Only show project creation error when users hit Save
  Toggl.Daneel/ViewControllers/EditProjectViewController.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditProjectViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/EditProjectActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditProjectActivity.cs
  Toggl.Giskard/Resources/layout/EditProjectActivity.axml
  Toggl.Giskard/Resources/values/Strings.xml
Labels: foundation

#4824 Fix missing FAB icon after visibility changes
  Toggl.Giskard/Extensions/FloatingActionButtonExtensions.cs
  Toggl.Giskard/Fragments/MainFragment.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4844 Fix project and tag creation cells in start view
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: android, bug, ios
