Repository toggl/mobileapp, pull requests merged in 2019-09, with the labels that each got.

#5808 Fix empty report loaded when opening the app from "Reports" tile
  Toggl.Droid/Activities/MainTabBarActivity.cs
Labels: android

#5840 Close view models without waiting for DB
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
Labels: android, ios

#5800 iPad: Fix suggestions views on iPad
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.designer.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.xib
Labels: ios

#5843 Fix a bug where the reports calendar would start at the wrong page
  Toggl.iOS/ViewControllers/ReportsCalendarViewController.cs
Labels: bug, ios

#5851 Fix edit view being deadlocked
  Toggl.Core.UI/Helper/EditTimeEntryInfo.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: android, bug

#5873 Make custom value SeekBar higher to increase touch target
  Toggl.Droid/Fragments/SelectColorFragment.cs
  Toggl.Droid/Resources/drawable/ValueSliderThumb.xml
  Toggl.Droid/Resources/layout/SelectColorFragment.axml
Labels: android

#5874 Use fully qualified debug helpers
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: bug, ios

#5876 Fix expanding tasks
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
Labels: android

#5845 Android 2.3 - Dulce de Leche
  Toggl.Core.UI/Helper/EditTimeEntryInfo.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: android, release

#5880 Tomas/project input fixes
  Toggl.Droid/Resources/layout/EditProjectActivity.axml
Labels: android

#5892 Fix animation crash
  Toggl.Droid/Resources/layout/ReportsCalendarView.axml
  Toggl.Droid/Resources/layout/ReportsFragment.axml
  Toggl.Droid/Resources/layout/SendFeedbackActivity.axml
  Toggl.Droid/Resources/layout/SettingsFragment.axml
Labels: android, bug

#5896 Set the linker to SDK Only for nightly Ad Hoc builds
  Toggl.iOS/Toggl.iOS.csproj
Labels: critical, process

#5897 Fix NullReference exceptions
  Toggl.Core.UI/ViewModels/Base/ViewModel.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
Labels: android

#5899 Fix crash in Bar Chart View
  Toggl.Droid/Views/BarChartView.cs
Labels: android

#5805 Fix reports not refreshing on settings default workspace change
  Toggl.Core.Tests/UI/ViewModels/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
Labels: foundation

#5893 🐛 Prevent RecyclerView scrolling to top when expanding tasks
  Toggl.Droid/Activities/SelectProjectActivity.cs
Labels: android, bug

#5889 Make Cell swipe actions optional
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Droid/Resources/layout/SettingsFragment.axml
  Toggl.Droid/ViewHelpers/MainRecyclerViewTouchCallback.cs
Labels: android

#5907 Update translation issue templates
  .github/ISSUE_TEMPLATE/g-translation-request.md
  .github/ISSUE_TEMPLATE/h-translation-fix-request.md
  .github/ISSUE_TEMPLATE/i-new-copy-translation-request.md
Labels: process

#5837 Implement Handoff to web app
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.iOS/Helper/Handoff.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: ios

#5885 Remove all UI test code
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
  Toggl.Droid.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Droid.Tests.UI/Configuration.cs
  Toggl.Droid.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Droid.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.Droid.Tests.UI/Extensions/LoginExtensions.cs
  Toggl.Droid.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Droid.Tests.UI/Extensions/SignUpExtensions.cs
  Toggl.Droid.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Droid.Tests.UI/Toggl.Droid.Tests.UI.csproj
  Toggl.Droid.Tests.UI/packages.config
  Toggl.Tests.UI/EditTimeEntryTests.cs
  Toggl.Tests.UI/Exceptions/EditViewAssertionException.cs
  Toggl.Tests.UI/Exceptions/NoRunningTimeEntryException.cs
  Toggl.Tests.UI/Exceptions/NoTimeEntryException.cs
  Toggl.Tests.UI/Exceptions/TimeEntryFoundException.cs
  Toggl.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.Tests.UI/Extensions/LoginExtensions.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/Extensions/SelectProjectExtensions.cs
  Toggl.Tests.UI/Extensions/SignUpExtensions.cs
  Toggl.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Tests.UI/ForgotPasswordTests.cs
  Toggl.Tests.UI/Helpers/Attributes.cs
  Toggl.Tests.UI/Helpers/User.cs
  Toggl.Tests.UI/LoginTests.cs
  Toggl.Tests.UI/MainTests.cs
  Toggl.Tests.UI/ReplTests.cs
  Toggl.Tests.UI/ReportsTests.cs
  Toggl.Tests.UI/SignUpTests.cs
  Toggl.Tests.UI/StartManualTimeEntryTests.cs
  Toggl.Tests.UI/StartTimeEntryTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
  Toggl.Tests.UI/Toggl.Tests.UI.shproj
  Toggl.iOS.Tests.UI/Configuration.cs
  Toggl.iOS.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.iOS.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.iOS.Tests.UI/Extensions/LoginExtensions.cs
  Toggl.iOS.Tests.UI/Extensions/MainExtensions.cs
  Toggl.iOS.Tests.UI/Extensions/SignUpExtensions.cs
  Toggl.iOS.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.iOS.Tests.UI/IosAccessibilityNames.cs
  Toggl.iOS.Tests.UI/Toggl.iOS.Tests.UI.csproj
  Toggl.iOS.Tests.UI/packages.config
  Toggl.sln
  build.cake
  docs/adding-ui-tests.md
  docs/running-android-ui-tests.md
  docs/running-ios-ui-tests.md
Labels: android, ios, ui-tests

#5910 Make UISwitch.Changed() extension more generic
  Toggl.iOS/Extensions/Reactive/UIControlExtensions.cs
  Toggl.iOS/Extensions/Reactive/UISwitchExtensions.cs
Labels: ios

#5883 Proper project visibility
  Toggl.Core.Tests/UI/ViewModels/EditProjectViewModelTests.cs
  Toggl.Core.UI/ViewModels/EditProjectViewModel.cs
  Toggl.Core/Interactors/Project/CreateProjectInteractor.cs
  Toggl.Core/Models/Project.cs
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Resources/layout/EditProjectActivity.axml
  Toggl.iOS/ViewControllers/EditProjectViewController.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.designer.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.xib
Labels: android, ios

#5908 Allow app to fetch archived projects
  Toggl.Core.Tests.Sync/Extensions/IProjectExtensions.cs
  Toggl.Networking.Tests.Integration/ProjectsApiTests.cs
  Toggl.Networking/ApiClients/ProjectsApi.cs
  Toggl.Networking/Network/Endpoints/ProjectEndpoints.cs
Labels: api, sync

#5916 Give this thing some space
  Toggl.Shared/Resources.resx
Labels: foundation

#5852 iOS 2.3 — Durian
  Toggl.Shared/Resources.resx
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen.xcodeproj/project.pbxproj
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/Base.lproj/Intents.intentdefinition
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/en.lproj/Intents.strings
  Toggl.iOS.IntentStaticLib/Toggl.iOS.IntentStaticLib.xcodeproj/project.pbxproj
  Toggl.iOS.IntentStaticLib/libToggl.iOS.IntentStaticLib.a
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/ViewControllers/ReportsCalendarViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: ios, release

#5902 Fix SelectableTagBaseViewModel identity
  Toggl.Core.UI/ViewModels/SelectTagsViewModel.cs
  Toggl.Core.UI/ViewModels/Selectable/SelectableTagViewModel.cs
  Toggl.Shared/Extensions/EnumerableExtensions.cs
Labels: android

#5924 Fix null reference crash in ReportsViewController.ScrollToTop
  Toggl.iOS/ViewControllers/ReportsViewController.cs
Labels: crash, ios

#5918 Prevent fragment being added twice
  Toggl.Droid/Activities/MainTabBarActivity.cs
Labels: android

#5900 Reenable background sync on Droid
  Toggl.Droid/Services/BackgroundSyncJobSchedulerService.cs
  Toggl.Droid/Services/BackgroundSyncServiceAndroid.cs
Labels: android

#5882 📐 🚧 Unify toolbars across the app
  Toggl.Droid/Activities/EditDurationActivity.cs
  Toggl.Droid/Activities/EditProjectActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Activities/SelectClientActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectClientActivity.cs
  Toggl.Droid/Activities/SelectCountryActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectCountryActivity.cs
  Toggl.Droid/Activities/SelectProjectActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectProjectActivity.cs
  Toggl.Droid/Activities/SelectTagsActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectTagsActivity.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.ViewBinds.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
  Toggl.Droid/Resources/color/ToolbarButtonTextColor.xml
  Toggl.Droid/Resources/drawable/toolbar_close.xml
  Toggl.Droid/Resources/layout/AboutActivity.axml
  Toggl.Droid/Resources/layout/CalendarSettingsActivity.axml
  Toggl.Droid/Resources/layout/EditDurationActivity.axml
  Toggl.Droid/Resources/layout/EditProjectActivity.axml
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/ForgotPasswordActivity.axml
  Toggl.Droid/Resources/layout/LicensesActivity.axml
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/layout/ReportsFragment.axml
  Toggl.Droid/Resources/layout/SelectClientActivity.axml
  Toggl.Droid/Resources/layout/SelectCountryActivity.axml
  Toggl.Droid/Resources/layout/SelectProjectActivity.axml
  Toggl.Droid/Resources/layout/SelectTagsActivity.axml
  Toggl.Droid/Resources/layout/SendFeedbackActivity.axml
  Toggl.Droid/Resources/layout/SettingsFragment.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/TokenResetActivity.axml
  Toggl.Droid/Resources/menu/DoneOrClearMenu.xml
  Toggl.Droid/Resources/menu/OneButtonMenu.xml
  Toggl.Droid/Resources/values-night/Styles.xml
  Toggl.Droid/Resources/values-notnight/Styles.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Dimen.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#5942 Fix bug when cancelling a confirmation dialog
  Toggl.iOS/Extensions/ViewControllerExtensions.cs
Labels: bug, ios

#5941 Re-enable linker all for release builds
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/Toggl.iOS.csproj
Labels: android, ios

#5960 Use attributed string for suggestions cell
  Toggl.iOS/Transformations/ProjectTaskClientToAttributedString.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.designer.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.xib
Labels: ios

#5962 Fix a null ref in the calendar collection view source
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#5970 Drop iOS 10 support
  Toggl.Core.Tests/UI/ViewModels/CalendarViewModelTests.cs
  Toggl.Core.UI/ViewModels/Calendar/CalendarPermissionDeniedViewModel.cs
  Toggl.Core.UI/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Core.UI/ViewModels/EditDurationViewModel.cs
  Toggl.Core.UI/ViewModels/EditProjectViewModel.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/ForgotPasswordViewModel.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/NoWorkspaceViewModel.cs
  Toggl.Core.UI/ViewModels/OutdatedAppViewModel.cs
  Toggl.Core.UI/ViewModels/RatingViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/SelectColorViewModel.cs
  Toggl.Core.UI/ViewModels/SelectDateTimeViewModel.cs
  Toggl.Core.UI/ViewModels/SelectTagsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/AboutViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/NotificationSettingsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/PasteFromClipboardViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/SiriShortcutsCustomTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/SiriShortcutsSelectReportPeriodViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/SiriShortcutsViewModel.cs
  Toggl.Core.UI/ViewModels/SignupViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/TermsOfServiceViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesViewModel.cs
  Toggl.Core.UI/ViewModels/TokenResetViewModel.cs
  Toggl.Core/Services/IRxActionFactory.cs
  Toggl.Core/Services/RxActionFactory.cs
  Toggl.Droid/Extensions/Reactive/ButtonExtensions.cs
  Toggl.Droid/Extensions/Reactive/ViewExtensions.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Shared/Extensions/RxAction/ViewAction.cs
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.iOS/Extensions/Reactive/UIButtonExtensions.cs
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
  Toggl.iOS/Info.plist
  Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
  Toggl.iOS/ViewControllers/EditDurationViewController.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/MainTabBarController.cs
  Toggl.iOS/ViewControllers/Settings/Models/AnnotationRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/ButtonRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/CustomRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/ISettingRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/InfoRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/NavigationRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/ToggleRow.cs
  Toggl.iOS/ViewSources/TimeEntriesLogViewSource.cs
Labels: ios

#5974 Use different app icon colors for debug and ad hoc builds
  Toggl.Droid/Resources/mipmap-anydpi-v26/ic_launcher.xml
  Toggl.Droid/Resources/values/Colors.xml
  build.cake
Labels: android

#5958 Handle drag to edit in the droid calendar
  Toggl.Droid/Fragments/CalendarFragment.ViewBinds.cs
  Toggl.Droid/Fragments/CalendarFragment.cs
  Toggl.Droid/Resources/layout/CalendarFragment.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Views/Calendar/CalendarDayView.Background.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.EditItem.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.cs
  Toggl.Shared/Extensions/TimeSpanExtensions.cs
  Toggl.iOS/Toggl.iOS.csproj
Labels: android

#5980 🚧 Disable tags interaction instead of hiding
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
Labels: ios

#5985 Add minimum duration for calendar layout calculation
  Toggl.Core.Tests/UI/Calendar/CalendarLayoutCalculatorTests.cs
  Toggl.Core.UI/Calendar/CalendarLayoutCalculator.cs
Labels: android, foundation, ios
