Repository toggl/mobileapp, pull requests merged in 2019-08, with the labels that each got.

#5686 🤖 Target Android SDK 28
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, critical

#5687 :bug: Make sure the root view controller is set synchronously
  Toggl.iOS/Presentation/IosPresenter.cs
Labels: ios

#5677 Make select toolbars single line
  Toggl.Droid/Resources/layout/SelectClientActivity.axml
  Toggl.Droid/Resources/layout/SelectProjectActivity.axml
Labels: android, up-for-grabs

#5706 Fix start time entry view not opening
  Toggl.iOS/ViewSources/StartTimeEntryTableViewSource.cs
Labels: blocking, ios

#5707 Revert "Revert "Project: Suggestion improvements (#5373)""
  Toggl.Core.Tests/Interactors/Suggestions/CalendarSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionProvidersInteractorTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionsInteractorTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/RandomForestSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Core.Tests/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core.Tests/Suggestions/SuggestionProviderContainerTests.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/Toggl.Core.UI.csproj
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/CalendarSuggestionContinuedEvent.cs
  Toggl.Core/Analytics/CalendarSuggestionProviderState.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Analytics/SuggestionsPresentedEvent.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Core/Diagnostics/MeasuredOperation.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.Suggestions.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionProvidersInteractor.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
  Toggl.Core/Suggestions/CalendarSuggestionProvider.cs
  Toggl.Core/Suggestions/Interfaces/ISuggestionProviderContainer.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
  Toggl.Core/Suggestions/Suggestion.cs
  Toggl.Core/Suggestions/SuggestionProviderContainer.cs
  Toggl.Core/Suggestions/SuggestionProviderType.cs
  Toggl.Droid/Adapters/MainSuggestionsRecyclerAdapter.cs
  Toggl.Droid/Resources/layout/MainSuggestions.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCard.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCardDescriptionOnly.axml
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/MainLogSuggestionItemViewHolder.cs
  Toggl.Droid/ViewHolders/MainLogSuggestionsListViewHolder.cs
  Toggl.Droid/packages.config
  Toggl.iOS/Startup/IosDependencyContainer.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
  Toggl.iOS/Views/Suggestions/SuggestionsView.cs
  Toggl.iOS/packages.config
  Toggl.sln
Labels: android, release

#5716 Fix linker for App Store release builds
  Toggl.iOS/Toggl.iOS.csproj
Labels: ios

#5669 🚧Improve RTL support in edit view
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.xib
  Toggl.iOS/Views/TextViewWithPlaceholder.cs
Labels: ios

#5650 Android 2.1.6 - Baklava hotfix #6
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests/Toggl.Core.Tests.csproj
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.UI/Navigation/NavigationService.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Droid/Activities/SignUpActivity.cs
  Toggl.Droid/Adapters/ReportsCalendarPagerAdapter.cs
  Toggl.Droid/Extensions/OnboardingExtensions.cs
  Toggl.Droid/Fragments/MainFragment.Onboardings.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Startup/AndroidSchedulerProvider.cs
  Toggl.Droid/Startup/HandlerScheduler.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/ViewControllers/Settings/Siri/SiriWorkflowsViewController.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
  Toggl.iOS/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: release

#5721 📐 Use project color in edit view project name
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.iOS/Transformations/ProjectTaskClientToAttributedString.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/Settings/Siri/SiriShortcutsCustomTimeEntryViewController.cs
  Toggl.iOS/Views/Settings/CustomSiriShortcutCell.cs
  Toggl.iOS/Views/StartTimeEntry/StartTimeEntryViewCell.cs
Labels: ios

#5701 Run UI updates on main thread
  Toggl.Core.Tests/UI/ViewModels/ReportsCalendarViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/ReportsCalendarViewModel.cs
Labels: bug, ios

#5724 🚧 Fix settings not opening
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.iOS/ViewControllers/MainTabBarController.cs
Labels: ios

#5734 Track long press
  Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Core.UI/Parameters/StartTimeEntryParameters.cs
  Toggl.Core.UI/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/Analytics/TimeEntryStartOrigin.cs
Labels: metrics

#5723 🌏 i18n: Extract all static strings throughout iOS
  Toggl.Core.UI/Helper/Colors.cs
  Toggl.Core/Autocomplete/Suggestions/QuerySymbolSuggestion.cs
  Toggl.Core/Interactors/Workspace/CreateDefaultWorkspaceInteractor.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Models/SiriShortcutType.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarPermissionDeniedViewController.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.designer.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.xib
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.xib
  Toggl.iOS/ViewControllers/NoWorkspaceViewController.cs
  Toggl.iOS/ViewControllers/OutdatedAppViewController.cs
  Toggl.iOS/ViewControllers/SelectProjectViewController.cs
  Toggl.iOS/ViewControllers/SelectTagsViewController.cs
  Toggl.iOS/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.xib
  Toggl.iOS/ViewControllers/Settings/Siri/PasteFromClipboardViewController.cs
  Toggl.iOS/ViewControllers/Settings/Siri/SiriShortcutViewModel.cs
  Toggl.iOS/ViewControllers/Settings/Siri/SiriShortcutsViewController.cs
  Toggl.iOS/ViewControllers/Settings/Siri/SiriWorkflowsViewController.cs
  Toggl.iOS/Views/Rating/RatingView.cs
  Toggl.iOS/Views/Rating/RatingView.xib
  Toggl.iOS/Views/Reports/ReportsBarChartCardView.cs
  Toggl.iOS/Views/Reports/ReportsHeaderView.cs
  Toggl.iOS/Views/Reports/ReportsHeaderView.designer.cs
  Toggl.iOS/Views/Reports/ReportsHeaderView.xib
  Toggl.iOS/Views/Settings/CustomSiriShortcutCell.cs
  Toggl.iOS/Views/Settings/SiriShortcutCell.cs
  Toggl.iOS/Views/StartTimeEntry/ReactiveProjectSuggestionViewCell.cs
  Toggl.iOS/Views/Tag/CreateTagViewCell.cs
Labels: foundation, ios

#5740 Fix description textfield cursor color
  Toggl.Droid/Resources/drawable/EditTextCursor.xml
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#5741 Fix token colors in the start entry description
  Toggl.Droid/Autocomplete/ProjectTokenSpan.cs
  Toggl.Droid/Autocomplete/TagsTokenSpan.cs
Labels: android

#5742 Fix save project button text color
  Toggl.Droid/Activities/EditProjectActivity.cs
Labels: android

#5705 iOS 2.2 - Cantaloupe
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/MainTabBarController.cs
  Toggl.iOS/ViewSources/StartTimeEntryTableViewSource.cs
Labels: ios, release

#5743 Fix UI tests for iOS (by updating packages)
  Toggl.Droid.Tests.UI/Toggl.Droid.Tests.UI.csproj
  Toggl.Droid.Tests.UI/packages.config
  Toggl.iOS.Tests.UI/Toggl.iOS.Tests.UI.csproj
  Toggl.iOS.Tests.UI/packages.config
Labels: ios, ui-tests

#5726 Android 2.2 - Crème brûlée
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Autocomplete/ProjectTokenSpan.cs
  Toggl.Droid/Autocomplete/TagsTokenSpan.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/drawable/EditTextCursor.xml
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android, release

#5588 Dynamic settings screen
  Toggl.Core.Tests/UI/ViewModels/SettingsViewModelTests.cs
  Toggl.Core.UI/Helper/Colors.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Cells/Settings/SettingCell.cs
  Toggl.iOS/Cells/Settings/SettingCell.designer.cs
  Toggl.iOS/Cells/Settings/SettingCell.xib
  Toggl.iOS/Cells/Settings/SettingsAnnotationCell.cs
  Toggl.iOS/Cells/Settings/SettingsAnnotationCell.designer.cs
  Toggl.iOS/Cells/Settings/SettingsAnnotationCell.xib
  Toggl.iOS/Cells/Settings/SettingsButtonCell.cs
  Toggl.iOS/Cells/Settings/SettingsButtonCell.designer.cs
  Toggl.iOS/Cells/Settings/SettingsButtonCell.xib
  Toggl.iOS/Cells/Settings/SettingsSectionHeader.cs
  Toggl.iOS/Cells/Settings/SettingsSectionHeader.designer.cs
  Toggl.iOS/Cells/Settings/SettingsSectionHeader.xib
  Toggl.iOS/Cells/Settings/SettingsSyncCell.cs
  Toggl.iOS/Cells/Settings/SettingsSyncCell.designer.cs
  Toggl.iOS/Cells/Settings/SettingsSyncCell.xib
  Toggl.iOS/DebugHelpers/ErrorTriggeringViewControllerShortcuts.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/Settings/Models/AnnotationRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/ButtonRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/CustomRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/ISettingRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/InfoRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/NavigationRow.cs
  Toggl.iOS/ViewControllers/Settings/Models/ToggleRow.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.xib
  Toggl.iOS/ViewSources/SettingsTableViewSource.cs
  Toggl.iOS/Views/ActivityIndicatorView.cs
Labels: ios

#5750 Fix crash in quick settings tiles
  Toggl.Droid/Tiles/NewTimeEntryTileService.cs
  Toggl.Droid/Tiles/ReportsTileService.cs
Labels: android

#5754 Fix billable switch in edit view
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#5749 Android 2.2.1 - Crème brûlée hotfix
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Droid/Tiles/NewTimeEntryTileService.cs
  Toggl.Droid/Tiles/ReportsTileService.cs
Labels: android, release

#5746 Don't use reflection to initialize analytics
  Toggl.Core.Tests/AnalyticsService/AnalyticsEventAttributeInitializerTests.cs
  Toggl.Core.Tests/AnalyticsService/BaseAnalyticsServiceTests.cs
  Toggl.Core/Analytics/AnalyticsEvent.cs
  Toggl.Core/Analytics/AnalyticsEventAttribute.cs
  Toggl.Core/Analytics/AnalyticsEventAttributeInitializer.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
Labels: foundation, performance

#5487 🔥Remove all tracking regarding unrepresentable dates
  Toggl.Core.UI/Transformations/DateTimeToFormattedString.cs
  Toggl.Core.UI/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Core.UI/ViewModels/EditDurationViewModel.cs
  Toggl.Core/DataSources/TimeEntriesDataSource.cs
  Toggl.Core/Exceptions/OutOfBoundsDateTimeCreatedException.cs
  Toggl.Core/Exceptions/UnrepresentableDateException.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/Views/EditDuration/WheelForegroundView.cs
Labels: metrics

#5733 Load culture info on startup
  Toggl.Core.Tests/UI/AppStartTests.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.UI/AppStart.cs
  Toggl.Core/BasePlatformInfo.cs
  Toggl.Core/Helper/Constants.cs
  Toggl.Core/IPlatformInfo.cs
  Toggl.Droid/PlatformInfoAndroid.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.iOS/PlatformInfoIos.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: android, foundation, ios

#5764 Unify Toolbar setups across the app
  Toggl.Droid/Activities/AboutActivity.cs
  Toggl.Droid/Activities/CalendarSettingsActivity.ViewBinds.cs
  Toggl.Droid/Activities/CalendarSettingsActivity.cs
  Toggl.Droid/Activities/EditDurationActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditDurationActivity.cs
  Toggl.Droid/Activities/EditProjectActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.cs
  Toggl.Droid/Activities/ReactiveActivity.cs
  Toggl.Droid/Activities/SendFeedbackActivity.cs
  Toggl.Droid/Activities/TokenResetActivity.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Fragments/ReactiveTabFragment.cs
  Toggl.Droid/Fragments/ReportsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Droid/Resources/layout/ForgotPasswordActivity.axml
Labels: android

#5763 Add Licenses page to Android
  Toggl.Droid/Activities/AboutActivity.ViewBinds.cs
  Toggl.Droid/Activities/LicensesActivity.cs
  Toggl.Droid/Extensions/Reactive/ToolbarExtensions.cs
  Toggl.Droid/Presentation/ActivityPresenter.cs
  Toggl.Droid/Resources/drawable/license_background.xml
  Toggl.Droid/Resources/layout/AboutActivity.axml
  Toggl.Droid/Resources/layout/LicensesActivity.axml
  Toggl.Droid/Resources/layout/LicensesActivityCell.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/LicenseViewHolder.cs
  Toggl.Shared/License.cs
  Toggl.iOS/Cells/Settings/LicensesHeaderViewCell.cs
Labels: android

#5762 Unify naming across our droid namespace declarations
  Toggl.Droid/Resources/layout/AbcCreateEntityCell.axml
  Toggl.Droid/Resources/layout/EditDurationActivity.axml
  Toggl.Droid/Resources/layout/EditProjectActivity.axml
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/EditTimeEntryTagCell.axml
  Toggl.Droid/Resources/layout/ForgotPasswordActivity.axml
  Toggl.Droid/Resources/layout/LoginActivity.axml
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/layout/MainLogCell.axml
  Toggl.Droid/Resources/layout/MainRunningTimeEntry.axml
  Toggl.Droid/Resources/layout/MainSuggestions.axml
  Toggl.Droid/Resources/layout/MainUserFeedbackCard.axml
  Toggl.Droid/Resources/layout/NoWorkspaceFragment.axml
  Toggl.Droid/Resources/layout/OutdatedAppActivity.axml
  Toggl.Droid/Resources/layout/ReportsCalendarFragmentDayCell.axml
  Toggl.Droid/Resources/layout/ReportsFragment.axml
  Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml
  Toggl.Droid/Resources/layout/ReportsFragmentWorkspaceName.axml
  Toggl.Droid/Resources/layout/SelectBeginningOfWeekFragmentCell.axml
  Toggl.Droid/Resources/layout/SelectClientActivity.axml
  Toggl.Droid/Resources/layout/SelectClientActivityCell.axml
  Toggl.Droid/Resources/layout/SelectColorFragment.axml
  Toggl.Droid/Resources/layout/SelectCountryActivity.axml
  Toggl.Droid/Resources/layout/SelectCountryActivityCountryCell.axml
  Toggl.Droid/Resources/layout/SelectDateFormatFragmentCell.axml
  Toggl.Droid/Resources/layout/SelectDurationFormatFragment.axml
  Toggl.Droid/Resources/layout/SelectDurationFormatFragmentCell.axml
  Toggl.Droid/Resources/layout/SelectProjectActivity.axml
  Toggl.Droid/Resources/layout/SelectProjectActivityTaskCell.axml
  Toggl.Droid/Resources/layout/SelectTagsActivity.axml
  Toggl.Droid/Resources/layout/SelectTagsActivityCell.axml
  Toggl.Droid/Resources/layout/SelectWorkspaceFragmentCell.axml
  Toggl.Droid/Resources/layout/SettingsFragment.axml
  Toggl.Droid/Resources/layout/SignUpActivity.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityQuerySymbolCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTagCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTaskCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTimeEntryCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTimeEntryWithPartialContentCell.axml
  Toggl.Droid/Resources/layout/TermsOfServiceFragment.axml
  Toggl.Droid/Resources/layout/TokenResetActivity.axml
  Toggl.Droid/Resources/layout/TooltipWithCenteredBottomArrow.axml
  Toggl.Droid/Resources/layout/TooltipWithLeftTopArrow.axml
  Toggl.Droid/Resources/layout/TooltipWithRightArrow.axml
  Toggl.Droid/Resources/layout/TooltipWithRightBottomArrow.axml
  Toggl.Droid/Resources/layout/TooltipWithRightTopArrow.axml
  Toggl.Droid/Resources/menu/CalendarSettingsMenu.xml
  Toggl.Droid/Resources/menu/GenericSaveMenu.xml
  Toggl.Droid/Resources/menu/SendFeedbackMenu.xml
Labels: android

#5683 Add the localization framework doc
  .github/ISSUE_TEMPLATE/g-translation-request.md
  .github/ISSUE_TEMPLATE/h-translation-fix-request.md
  docs/internationalization/localization-framework.md
Labels: process

#5671 Add a resx translation guide
  docs/internationalization/how-to-contribute-with-translations.md
Labels: process

#5694 Add issue and pr templates for new copy translations
  .github/ISSUE_TEMPLATE/i-new-copy-translation-request.md
  .github/PULL_REQUEST_TEMPLATE/new-copy-translation-pull-request-template.md
Labels: process

#5627 Add Edit TE View assertion method for the UI tests
  Toggl.Droid.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Droid.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Tests.UI/Exceptions/EditViewAssertionException.cs
  Toggl.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
  Toggl.iOS.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.iOS.Tests.UI/IosAccessibilityNames.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.xib
Labels: ui-tests

#5755 Fix localization docs
  docs/localization.md
Labels: process

#5767 Improve bailout code
  Toggl.Droid/Activities/AboutActivity.ViewBinds.cs
  Toggl.Droid/Activities/AboutActivity.cs
  Toggl.Droid/Activities/CalendarSettingsActivity.ViewBinds.cs
  Toggl.Droid/Activities/CalendarSettingsActivity.cs
  Toggl.Droid/Activities/EditDurationActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditDurationActivity.cs
  Toggl.Droid/Activities/EditProjectActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.ViewBinds.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.ViewBinds.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.cs
  Toggl.Droid/Activities/LicensesActivity.cs
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Activities/OutdatedAppActivity.cs
  Toggl.Droid/Activities/ReactiveActivity.cs
  Toggl.Droid/Activities/SelectClientActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectClientActivity.cs
  Toggl.Droid/Activities/SelectCountryActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectCountryActivity.cs
  Toggl.Droid/Activities/SelectProjectActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectProjectActivity.cs
  Toggl.Droid/Activities/SelectTagsActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectTagsActivity.cs
  Toggl.Droid/Activities/SendFeedbackActivity.ViewBinds.cs
  Toggl.Droid/Activities/SendFeedbackActivity.cs
  Toggl.Droid/Activities/SignUpActivity.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.ViewBinds.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
  Toggl.Droid/Activities/TokenResetActivity.ViewBinds.cs
  Toggl.Droid/Activities/TokenResetActivity.cs
  Toggl.Droid/Extensions/Reactive/ToolbarExtensions.cs
  Toggl.Droid/Presentation/ActivityTransitions.cs
  Toggl.Droid/Toggl.Droid.csproj
  docs/app-lifecycle/startup-android.md
Labels: android

#5775 Fix cursor position when holding backspace
  Toggl.iOS/Autocomplete/AutocompleteExtensions.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#5784 Fix droid reports calendar selected period label
  Toggl.Droid/Views/ReportsCalendarView.cs
  Toggl.Shared/Extensions/CalendarMonthExtensions.cs
Labels: android, bug

#5783 Improve the suggestions observable
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
Labels: android

#5788 Fix stop time entry onboarding crash
  Toggl.Droid/Extensions/OnboardingExtensions.cs
Labels: android, bug

#5789 Fix missing beginning of week translation
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Droid/ViewHolders/BeginningOfWeekViewHolder.cs
  Toggl.Shared.Tests/Extensions/BeginningOfWeekExtensionsTests.cs
  Toggl.Shared/Extensions/BeginningOfWeekExtensions.cs
  Toggl.iOS/Views/Settings/DayOfWeekViewCell.cs
Labels: android, bug, ios

#5758 iOS 2.2.1 Cantaloupe hotfix
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: ios, release

#5802 Fix text field focus when activity starts
  Toggl.Droid/Activities/SelectProjectActivity.cs
  Toggl.Droid/Activities/SelectTagsActivity.cs
Labels: android

#5801 Move all text and adapter bindings to .ViewBinds
  Toggl.Droid/Activities/TokenResetActivity.ViewBinds.cs
  Toggl.Droid/Activities/TokenResetActivity.cs
  Toggl.Droid/Fragments/CalendarFragment.ViewBinds.cs
  Toggl.Droid/Fragments/CalendarFragment.cs
  Toggl.Droid/Fragments/CalendarPermissionDeniedFragment.ViewBinds.cs
  Toggl.Droid/Fragments/CalendarPermissionDeniedFragment.cs
  Toggl.Droid/Fragments/MainFragment.ViewBinds.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Fragments/NoWorkspaceFragment.ViewBinds.cs
  Toggl.Droid/Fragments/NoWorkspaceFragment.cs
  Toggl.Droid/Fragments/SelectBeginningOfWeekFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SelectBeginningOfWeekFragment.cs
  Toggl.Droid/Fragments/SelectColorFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SelectColorFragment.cs
  Toggl.Droid/Fragments/SelectDateFormatFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SelectDateFormatFragment.cs
  Toggl.Droid/Fragments/SelectDurationFormatFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SelectDurationFormatFragment.cs
  Toggl.Droid/Fragments/SelectUserCalendarsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SelectUserCalendarsFragment.cs
  Toggl.Droid/Fragments/SelectWorkspaceFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SelectWorkspaceFragment.cs
  Toggl.Droid/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Droid/Fragments/TermsOfServiceFragment.ViewBinds.cs
  Toggl.Droid/Fragments/TermsOfServiceFragment.cs
  Toggl.Droid/Fragments/UpcomingEventsNotificationSettingsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/UpcomingEventsNotificationSettingsFragment.cs
Labels: android

#5794 Fix system's autocomplete on start view
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#5816 🐛 Fix project placeholder visibility
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
Labels: android

#5818 🐛 Remove billable switch ripple effect on appbar tap
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml
Labels: android

#5825 Fix bad ReportsFragmentHeader bad merge
  Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml
Labels: android, glitch

#5834 Fix a bug where the reports view wouldn't show the placeholder
  Toggl.iOS/ViewSources/Generic/TableView/BaseTableViewSource.cs
  Toggl.iOS/ViewSources/ReportsTableViewSource.cs
Labels: bug, ios

#5559 Smooth reports loading
  Toggl.Core.Tests/UI/ViewModels/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.iOS/Extensions/Reactive/UIActivityIndicatorViewExtensions.cs
  Toggl.iOS/Extensions/Reactive/UIButtonExtensions.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/Views/Reports/ReportsHeaderView.cs
  Toggl.iOS/Views/Reports/ReportsOverviewCardView.cs
Labels: ios

#5836 Replace '\n' with actual new lines
  Toggl.Shared/Resources.resx
Labels: android, bug, ios
