Repository toggl/mobileapp, pull requests merged in 2019-12, with the labels that each got.

#6744 Add copy for back buttons
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
Labels: foundation

#6742 Fix Japanese copy about support being offered in English only
  Toggl.Shared/Resources.ja.resx
Labels: foundation

#6734 Change the Start button to an image view
  Toggl.iOS/Extensions/Reactive/UIButtonExtensions.cs
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
Labels: bug, ios

#6764 Fix back button localization
  Toggl.iOS/ViewControllers/Reactive/ReactiveNavigationController.cs
  Toggl.iOS/ViewControllers/Settings/AboutViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: ios

#6762 Confirm calendar destructive actions
  Toggl.Core.Tests/UI/ViewModels/CalendarContextualMenuViewModelTests.cs
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
Labels: android, foundation, ios

#6767 Fix the "Done" button localization in Settigns
  Toggl.iOS/ViewControllers/Reactive/ReactiveNavigationController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: ios

#6754 Android Calendar zoom
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.cs
  Toggl.Droid/Fragments/CalendarFragment.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.Background.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.cs
Labels: android

#6737 Fix ios11 modals position
  Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
Labels: blocking, glitch, ios

#6753 🎨 Add barchart view
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportBarChartElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportProjectsBarChartElementTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
  Toggl.Droid/Adapters/ReportsRecyclerAdapterOld.cs
  Toggl.Droid/Resources/layout/ReportsBarChartElement.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/Reports/ReportBarChartViewHolder.cs
  Toggl.Droid/Views/BarChartView.cs
Labels: android

#6745 📊 Reports: new Bar Chart cell
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsBarChartElement.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.xib
  Toggl.iOS/Extensions/ColorAssets.cs
  Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartFilled.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartFilledPlaceholder.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartTotal.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartTotalPlaceholder.colorset/Contents.json
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
  Toggl.iOS/Views/Reports/BarLegendLabel.cs
  Toggl.iOS/Views/Reports/BarView.cs
  Toggl.iOS/Views/Reports/ReportsBarChartCardView.cs
Labels: ios

#6774 Improve bindings in the password reset activity
  Toggl.Droid/Activities/ForgotPasswordActivity.cs
Labels: android

#6752 ✨ Add DateRange picker View Model
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerMonthInfo.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.Shortcuts.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core/Models/ReportPeriod.cs
  Toggl.Shared/DateRange.cs
  Toggl.Shared/Extensions/DateTimeExtensions.cs
Labels: foundation

#6778 🐛Fix auth card bottom padding
  Toggl.Droid/Activities/LoginActivity.ViewBinds.cs
  Toggl.Droid/Activities/SignUpActivity.ViewBinds.cs
  Toggl.Droid/Resources/layout/LoginActivity.axml
  Toggl.Droid/Resources/layout/SignUpActivity.axml
  Toggl.Droid/Resources/values/Styles.xml
Labels: android

#6777 Fix localization of the duration counter
  Toggl.Core.Tests/UI/AppStartTests.cs
  Toggl.Core.Tests/UI/DiscardCultureChanges.cs
  Toggl.Core.UI/AppStart.cs
Labels: bug, ios

#6780 Fix autocomplete search hints
  Toggl.Core.Tests/ResourcesTests.cs
  Toggl.Core/Autocomplete/Suggestions/QuerySymbolSuggestion.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/SelectProjectViewController.cs
Labels: android, ios

#6781 Reports: Remove old stackview contents
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.cs
Labels: bug, ios

#6782 🎨 Add cells for no data and error states
  Toggl.iOS/Cells/Reports/ReportsErrorCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsErrorCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsErrorCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsNoDataCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsNoDataCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsNoDataCollectionViewCell.xib
  Toggl.iOS/Resources/Images.xcassets/icErrorBadData.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/icErrorBadData.imageset/error_baddata-1.png
  Toggl.iOS/Resources/Images.xcassets/icErrorBadData.imageset/error_baddata-2.png
  Toggl.iOS/Resources/Images.xcassets/icErrorBadData.imageset/error_baddata.png
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewCompactLayout.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewRegularLayout.cs
Labels: ios

#6746 Android 2.8 Ischoklad
  Toggl.Core.Tests/UI/AppStartTests.cs
  Toggl.Core.Tests/UI/DiscardCultureChanges.cs
  Toggl.Core.UI/AppStart.cs
  Toggl.Droid/Activities/LoginActivity.ViewBinds.cs
  Toggl.Droid/Activities/SignUpActivity.ViewBinds.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/layout/LoginActivity.axml
  Toggl.Droid/Resources/layout/SignUpActivity.axml
  Toggl.Droid/Resources/values/Styles.xml
Labels: android, release

#6628 Main log refactor
  Toggl.Core.Tests/UI/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Core.Tests/UI/ViewModels/LogItemViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Core.UI/Extensions/MainLogSectionExtensions.cs
  Toggl.Core.UI/Extensions/TimeEntryExtensions.cs
  Toggl.Core.UI/Helper/ContinueTimeEntryInfo.cs
  Toggl.Core.UI/Transformations/TimeEntriesGroupsFlattening.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/DaySummaryViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/DayHeaderKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/IMainLogKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/SingleTimeEntryKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/SuggestionKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/SuggestionsSectionKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/TimeEntriesGroupKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/Identity/UserFeedbackKey.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/MainLogItemViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/MainLogSectionViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/SuggestionLogItemViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/SuggestionsHeaderViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/TimeEntryLogItemViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/UserFeedbackViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesViewModel.cs
  Toggl.Droid/Adapters/MainLogRecyclerAdapter.cs
  Toggl.Droid/Adapters/MainRecyclerAdapter.cs
  Toggl.Droid/Adapters/ReactiveSectionedRecyclerAdapter.cs
  Toggl.Droid/Fragments/MainFragment.Onboardings.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Resources/layout/MainLogSuggestionsHeader.axml
  Toggl.Droid/Resources/layout/MainSuggestions.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCard.axml
  Toggl.Droid/Resources/layout/MainUserFeedbackCard.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHelpers/MainRecyclerViewTouchCallback.cs
  Toggl.Droid/ViewHelpers/TimeEntryViewData.cs
  Toggl.Droid/ViewHolders/MainLog/MainLogCellViewHolder.cs
  Toggl.Droid/ViewHolders/MainLog/MainLogSectionViewHolder.cs
  Toggl.Droid/ViewHolders/MainLog/MainLogSuggestionItemViewHolder.cs
  Toggl.Droid/ViewHolders/MainLog/MainLogSuggestionSectionViewHolder.cs
  Toggl.Droid/ViewHolders/MainLog/MainLogUserFeedbackViewHolder.cs
  Toggl.Droid/ViewHolders/MainLogSectionViewHolder.cs
  Toggl.Droid/ViewHolders/MainLogSuggestionItemViewHolder.cs
  Toggl.Droid/ViewHolders/MainLogSuggestionsListViewHolder.cs
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.iOS/Transformations/ProjectTaskClientToAttributedString.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewSources/TimeEntriesLogViewSource.cs
Labels: android, refactoring

#6721 iOS 2.8 - Indian Plum
  Toggl.Storage.Tests/Settings/SettingsStorageTests.cs
  Toggl.Storage/Settings/SettingsStorage.cs
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Extensions/Reactive/UIButtonExtensions.cs
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
  Toggl.iOS/Info.plist
  Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
  Toggl.iOS/ViewControllers/Reactive/ReactiveNavigationController.cs
  Toggl.iOS/ViewControllers/Settings/AboutViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: release

#6775 Make data sources faster
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests/DataSources/BaseDataSourceTests.cs
  Toggl.Core.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Core.Tests/DataSources/TogglDataSourceTests.cs
  Toggl.Core.Tests/Interactors/BaseInteractorTests.cs
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
  Toggl.Core/DataSources/ObservableDataSource.cs
  Toggl.Core/DataSources/TimeEntriesDataSource.cs
  Toggl.Core/DataSources/TogglDataSource.cs
  Toggl.Core/DataSources/WorkspacesDataSource.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
  Toggl.iOS/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: android, foundation, ios, wip

#6784 Android widget improvements
  Toggl.Droid/Resources/layout/SuggestionsWidgetItem.axml
  Toggl.Droid/Resources/layout/TimeEntryWidget.axml
  Toggl.Droid/Widgets/TimeEntryWidgetDefaultFormFactor.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
Labels: android

#6787 📆 Add DateRangePicker for android
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerMonthInfo.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.Shortcuts.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Droid/Adapters/DateRangePickerMonthsPagerAdapter.cs
  Toggl.Droid/Extensions/PointExtensions.cs
  Toggl.Droid/Extensions/Reactive/PagerViewExtensions.cs
  Toggl.Droid/Extensions/ViewExtensions.cs
  Toggl.Droid/Fragments/DateRangePickerFragment.ViewBinds.cs
  Toggl.Droid/Fragments/DateRangePickerFragment.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Presentation/DialogFragmentPresenter.cs
  Toggl.Droid/Resources/layout/DatePickerShortcutCell.axml
  Toggl.Droid/Resources/layout/DateRangePicker.axml
  Toggl.Droid/Resources/layout/DateRangePickerMonthView.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/DateRangePicker/DateRangePickerShortcutViewHolder.cs
  Toggl.Droid/Views/DateRangePickerMonthView.cs
  Toggl.Droid/Views/PieChartView.cs
  Toggl.Shared.Tests/MathTests.cs
  Toggl.Shared/DateRange.cs
  Toggl.Shared/Extensions/ReactiveExtensions.cs
  Toggl.Shared/Math.cs
  Toggl.Shared/Point.cs
  Toggl.iOS/Extensions/PointExtensions.cs
  Toggl.iOS/Views/Reports/PieChartView.cs
Labels: android

#6790 🍩 Reports: iOS donut chart
  Toggl.Shared/Resources.Designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.xib
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/ReportsViewController.xib
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
  Toggl.iOS/Views/Reports/DonutChartView.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewCompactLayout.cs
Labels: ios

#6796 🍩 Fix some more things for 🍩 chart
  Toggl.Droid/Resources/layout/ReportDonutLegendItem.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Views/DonutChartView.cs
Labels: android

#6789 Move day specific styles and colors to base res folder
  Toggl.Droid/Resources/values-notnight/Colors.xml
  Toggl.Droid/Resources/values-notnight/Styles.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#6799 🐛 Fix bottom layout for Android 10 non-gesture
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#6803 🍩 Make very small slices still take some space
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementTests.cs
  Toggl.Core.UI/ViewModels/Reports/DonutChartGrouping.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.Segments.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
  Toggl.Droid/Views/DonutChartView.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.cs
  Toggl.iOS/Views/Reports/DonutChartView.cs
Labels: android, foundation, ios

#6810 Rename an extension method
  Toggl.iOS/Extensions/PointExtensions.cs
  Toggl.iOS/Views/EditDuration/WheelForegroundView.cs
Labels: ios

#6806 🐛 Makes the label show the shortcut name if the range is appropri…
  Toggl.Core.Tests/Mocks/Services/MockCalendarShortcutsService.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/Models/CalendarShortcut.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/Services/CalendarShortcuts/CalendarShortcutsService.Shortcuts.cs
  Toggl.Core.UI/Services/CalendarShortcuts/CalendarShortcutsService.cs
  Toggl.Core.UI/Services/CalendarShortcuts/ICalendarShortcutsService.cs
  Toggl.Core.UI/UIDependencyContainer.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.Shortcuts.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
Labels: foundation

#6800 Android 2.8.1 ischoklad
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#6809 Wheel: Emit events only due to user interaction
  Toggl.iOS/Views/EditDuration/WheelForegroundView.cs
Labels: glitch, ios

#6791 Track report events
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/ReportsCalendarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/ReportsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/Parameters/ReportsDateRangeParameter.cs
  Toggl.Core.UI/Services/CalendarShortcuts/CalendarShortcutsService.Shortcuts.cs
  Toggl.Core.UI/ViewModels/DateRangePicker/DateRangePickerViewModel.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportFilter.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProcessData.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModelOld.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarLastMonthQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarLastWeekQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarLastYearQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarThisMonthQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarThisWeekQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarThisYearQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarTodayQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarYesterdayQuickSelectShortcut.cs
  Toggl.Core.UI/ViewModels/ReportsCalendarViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/DataRangeSelectionSource.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: foundation

#6819 🎨 Use the correct color for x-axis labels
  Toggl.Droid/Views/BarChartView.cs
Labels: android

#6811 Include client name in suggestions comparisons
  Toggl.Core/Suggestions/Suggestion.cs
Labels: foundation

#6786 Reduce iOS app size
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.csproj
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.SiriExtension/packages.config
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS.TimerWidgetExtension/packages.config
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/packages.config
Labels: ios

#6822 🔥Old Android code
  Toggl.Droid/Adapters/ReportsCalendarPagerAdapter.cs
  Toggl.Droid/Adapters/ReportsCalendarRecyclerAdapter.cs
  Toggl.Droid/Adapters/ReportsCalendarShortcutAdapter.cs
  Toggl.Droid/Adapters/ReportsRecyclerAdapterOld.cs
  Toggl.Droid/Fragments/ReportsCalendarFragment.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Resources/layout/ReportEmptyElement.axml
  Toggl.Droid/Resources/layout/ReportsCalendar.axml
  Toggl.Droid/Resources/layout/ReportsCalendarFragmentDayCell.axml
  Toggl.Droid/Resources/layout/ReportsCalendarFragmentPage.axml
  Toggl.Droid/Resources/layout/ReportsCalendarView.axml
  Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml
  Toggl.Droid/Resources/layout/ReportsFragmentItem.axml
  Toggl.Droid/Resources/layout/ReportsFragmentWorkspaceName.axml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHelpers/BarChartData.cs
  Toggl.Droid/ViewHelpers/BarChartDayLabel.cs
  Toggl.Droid/ViewHelpers/ReportsSummaryData.cs
  Toggl.Droid/ViewHolders/CalendarDayCellViewHolder.cs
  Toggl.Droid/ViewHolders/Reports/ReportEmptyElementViewHolder.cs
  Toggl.Droid/ViewHolders/ReportsCalendarShortcutCellViewHolder.cs
  Toggl.Droid/ViewHolders/ReportsHeaderCellViewHolder.cs
  Toggl.Droid/ViewHolders/ReportsItemCellViewHolder.cs
  Toggl.Droid/ViewHolders/ReportsWorkspaceNameViewHolderOld.cs
  Toggl.Droid/Views/BarChartView.cs
  Toggl.Droid/Views/CalendarRecyclerView.cs
  Toggl.Droid/Views/ReportsCalendarDayView.cs
  Toggl.Droid/Views/ReportsCalendarRecyclerView.cs
  Toggl.Droid/Views/ReportsCalendarView.cs
Labels: android

#6825 Make iOS debug build times much faster
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS/Toggl.iOS.csproj
Labels: ios

#6829 🎨 Add dropdown next to report period description
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
Labels: foundation

#6823 Invalidate layout only on collectionview's width changes
  Toggl.iOS/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: ios

#6830 Remove old android calendar leftovers
  Toggl.Droid/Adapters/Calendar/Anchor.cs
  Toggl.Droid/Adapters/Calendar/AnchorData.cs
  Toggl.Droid/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Droid/Adapters/Calendar/LayoutAnchorsCalculator.cs
  Toggl.Droid/Resources/drawable/CalendarEntryBackground.xml
  Toggl.Droid/Resources/layout/CalendarEntryCell.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/CalendarEntryViewHolder.cs
  Toggl.Droid/Views/Calendar/CalendarLayoutManager.AnchorInfo.cs
  Toggl.Droid/Views/Calendar/CalendarLayoutManager.AnchorSavedState.cs
  Toggl.Droid/Views/Calendar/CalendarLayoutManager.LayoutState.cs
  Toggl.Droid/Views/Calendar/CalendarLayoutManager.Recycler.cs
  Toggl.Droid/Views/Calendar/CalendarLayoutManager.ScrollHelper.cs
  Toggl.Droid/Views/Calendar/CalendarLayoutManager.cs
Labels: android

#6385 Add comments to our RESX
  Toggl.Droid/Activities/EditDurationActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectTagsActivity.ViewBinds.cs
  Toggl.Droid/ViewHolders/MainLog/MainLogUserFeedbackViewHolder.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
  Toggl.iOS.TimerWidgetExtension/TodayViewController.cs
  Toggl.iOS/Cells/MainLog/UserFeedbackTableViewCell.cs
  Toggl.iOS/ViewControllers/EditDurationViewController.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.iOS/ViewControllers/Settings/Siri/PasteFromClipboardViewController.cs
Labels: process

#6831 📐 Make the error views centered
  Toggl.Droid/Resources/layout/ReportErrorElement.axml
  Toggl.Droid/Resources/layout/ReportNoDataElement.axml
Labels: android

#6832 🍩 Android DonutChart interaction
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartDonutElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsDonutChartElement.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
  Toggl.Droid/Extensions/ColorExtensions.cs
  Toggl.Droid/Extensions/PaintExtensions.cs
  Toggl.Droid/Resources/layout/ReportDonutChartDonutElement.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Views/BarChartView.cs
  Toggl.Droid/Views/DonutChart/DonutChartView.Slice.cs
  Toggl.Droid/Views/DonutChart/DonutChartView.SliceSelectionAnimator.cs
  Toggl.Droid/Views/DonutChart/DonutChartView.SlicesCollection.cs
  Toggl.Droid/Views/DonutChart/DonutChartView.cs
  Toggl.Droid/Views/DonutChartView.cs
  Toggl.Shared/Extensions/StringExtensions.cs
  Toggl.Shared/Math.cs
  Toggl.Shared/Point.cs
Labels: android

#6837 Fix navbar overlap in token reset
  Toggl.Droid/Activities/LoginActivity.ViewBinds.cs
  Toggl.Droid/Activities/MainTabBarActivity.ViewBinds.cs
  Toggl.Droid/Activities/ReactiveActivity.cs
  Toggl.Droid/Activities/SignUpActivity.ViewBinds.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.ViewBinds.cs
  Toggl.Droid/Activities/TokenResetActivity.ViewBinds.cs
  Toggl.Droid/Extensions/SnackbarExtensions.cs
  Toggl.Droid/Extensions/ViewExtensions.cs
Labels: android

#6838 📐 Increase touch target by adding padding
  Toggl.Droid/Resources/layout/LoginActivity.axml
Labels: android

#6839 Fix job intent services & separate android services from our services
  Toggl.Droid/BroadcastReceivers/BootCompletedBroadcastReceiver.cs
  Toggl.Droid/Extensions/ActivityExtensions.cs
  Toggl.Droid/Services/BackgroundSyncServiceAndroid.cs
  Toggl.Droid/Services/ScheduleEventNotificationsService.cs
  Toggl.Droid/SystemServices/BackgroundSyncJobSchedulerService.cs
  Toggl.Droid/SystemServices/JobServicesConstants.cs
  Toggl.Droid/SystemServices/ScheduleEventNotificationsService.cs
  Toggl.Droid/SystemServices/SyncJobService.cs
  Toggl.Droid/SystemServices/TogglFirebaseIIDService.cs
  Toggl.Droid/SystemServices/TogglFirebaseMessagingService.cs
  Toggl.Droid/SystemServices/WidgetsAnalyticsService.cs
  Toggl.Droid/SystemServices/WidgetsForegroundService.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Widgets/SuggestionsWidget.cs
  Toggl.Droid/Widgets/SuggestionsWidgetListFormFactor.cs
  Toggl.Droid/Widgets/TimeEntryWidget.cs
  Toggl.Droid/Widgets/TimeEntryWidgetStartStopButtonFormFactor.cs
Labels: android

#6833 Fix a bug in a "hack" to reject autocompletion when using Kanji
  Toggl.iOS/Extensions/TextViewExtensions.cs
  Toggl.iOS/ViewControllers/SelectTagsViewController.cs
Labels: bug, ios

#6813 Differentiate siri shortcuts titles
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/Base.lproj/Intents.intentdefinition
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/en.lproj/Intents.strings
  Toggl.iOS.IntentStaticLib/Makefile
  Toggl.iOS.IntentStaticLib/libToggl.iOS.IntentStaticLib.a
Labels: ios

#6691 Add nullable ref types to the shared lib
  Toggl.Shared/CalendarMonth.cs
  Toggl.Shared/Color.cs
  Toggl.Shared/DateFormat.cs
  Toggl.Shared/DateTimeOffsetRange.cs
  Toggl.Shared/Either.cs
  Toggl.Shared/Extensions/DictionaryExtensions.cs
  Toggl.Shared/Extensions/EnumerableExtensions.cs
  Toggl.Shared/Extensions/FunctionalExtensions.cs
  Toggl.Shared/Extensions/RandomExtensions.cs
  Toggl.Shared/Extensions/ReactiveExtensions.cs
  Toggl.Shared/Extensions/RxAction/BehaviorRelay.cs
  Toggl.Shared/Extensions/RxAction/InputAction.cs
  Toggl.Shared/Extensions/RxAction/OutputAction.cs
  Toggl.Shared/Extensions/RxAction/RxAction.cs
  Toggl.Shared/Extensions/RxAction/ViewAction.cs
  Toggl.Shared/Extensions/StringExtensions.cs
  Toggl.Shared/Option.cs
  Toggl.Shared/PushNotificationsToken.cs
  Toggl.Shared/Toggl.Shared.csproj
Labels: foundation

#6841 ✅ Reports-Rewrite related tests
  Toggl.Core.Tests/UI/ViewModels/Reports/BarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportBarChartElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementDonutTests.DonutChartGrouping.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementDonutTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementLegendItemTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportElementBaseTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportErrorElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportNoDataElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportProjectsBarChartElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportProjectsDonutChartLegendItemElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportSummaryElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportWorkspaceNameElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/DonutChartGrouping.cs
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartDonutElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.Segments.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportErrorElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportNoDataElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportSummaryElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportWorkspaceNameElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
Labels: tests

#6794 Hardware keyboard support for iOS
  Toggl.Core/Analytics/EditTimeEntryOrigin.cs
  Toggl.Core/Analytics/TimeEntryStopOrigin.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/Common/SelectorViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/Common/SelectorViewController.cs
  Toggl.iOS/ViewControllers/EditDurationViewController.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/EditProjectViewController.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/MainTabBarController.cs
  Toggl.iOS/ViewControllers/MainViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.cs
  Toggl.iOS/ViewControllers/ReportsViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/ViewControllers/SelectClientViewController.cs
  Toggl.iOS/ViewControllers/SelectColorViewController.cs
  Toggl.iOS/ViewControllers/SelectDateTimeViewController.cs
  Toggl.iOS/ViewControllers/SelectDefaultWorkspaceViewController.cs
  Toggl.iOS/ViewControllers/SelectProjectViewController.cs
  Toggl.iOS/ViewControllers/SelectTagsViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#6843 Fix widget names
  Toggl.Droid/Resources/values-ja/strings.xml
  Toggl.Droid/Resources/values/Strings.xml
  Toggl.Droid/Tiles/NewTimeEntryTileService.cs
  Toggl.Droid/Tiles/ReportsTileService.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Widgets/SuggestionsWidget.cs
  Toggl.Droid/Widgets/TimeEntryWidget.cs
Labels: android

#6853 ⌨ Reports: re-enable Handoff and Keyboard shortcuts
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core/Analytics/DataRangeSelectionSource.cs
  Toggl.Core/Models/DateRangePeriod.cs
  Toggl.iOS/ViewControllers/ReportsViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
Labels: ios

#6856 Refactor the creation of the root vc
  Toggl.iOS/Presentation/IosPresenter.cs
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/ViewControllers/LoginViewController.cs
Labels: ios, refactoring

#6861 Fix calendar editing hours flicker when resizing TE
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
Labels: glitch, ios

#6846 Translate iOS keyboard shortcuts commands
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.KeyCommands.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.KeyCommands.cs
Labels: ios

#6852 Fix selecting projects with the same name but different clients
  Toggl.Core/Autocomplete/Span/ISpan.cs
  Toggl.Core/Autocomplete/Span/ProjectSpan.cs
  Toggl.Core/Autocomplete/Span/TagSpan.cs
  Toggl.Core/Autocomplete/Span/TextSpan.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
  Toggl.Droid/Autocomplete/AutocompleteExtensions.cs
Labels: android

#6868 Fix dialog fragments presentation crash
  Toggl.Droid/Extensions/ActivityExtensions.cs
  Toggl.Droid/Presentation/DialogFragmentPresenter.cs
Labels: android, crash

#6866 Reports: Fix WS selection button on compact layouts
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewCompactLayout.cs
Labels: glitch, ios
