Repository toggl/mobileapp, pull requests merged in 2019-02, with the labels that each got.

#4147 Android Wheel Component
  Toggl.Giskard/Extensions/ContextExtensions.cs
  Toggl.Giskard/Extensions/DrawableExtensions.cs
  Toggl.Giskard/Extensions/MotionEventExtensions.cs
  Toggl.Giskard/Extensions/PointExtensions.cs
  Toggl.Giskard/Helper/VibratorExtensions.cs
  Toggl.Giskard/Resources/drawable/ic_play.xml
  Toggl.Giskard/Resources/drawable/ic_stop.xml
  Toggl.Giskard/Resources/values/Attrs.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/EditDuration/Shapes/Arc.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Cap.cs
  Toggl.Giskard/Views/EditDuration/Shapes/ClockDial.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Dot.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Wheel.cs
  Toggl.Giskard/Views/EditDuration/WheelBackgroundView.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.InputFilter.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
  Toggl.Giskard/Views/EditDuration/WheelForegroundView.cs
Labels: android

#4330 Fix sync tests build
  Toggl.Foundation.Tests.Sync/Helpers/AppServices.cs
Labels: bug, sync

#4328 Prepare time entry cells for grouping
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogHeaderView.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogHeaderView.designer.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogHeaderView.xib
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.designer.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/Views/Log/TimeEntriesLogViewCell.xib
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#4339 Fix calendar onboarding UI
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.xib
Labels: ios

#4346 Merge ReloadTableViewSource and BaseTableViewSource
  Toggl.Daneel/Cells/BaseTableViewCell.cs
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/SelectUserCalendarsViewController.cs
  Toggl.Daneel/ViewControllers/SelectClientViewController.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.cs
  Toggl.Daneel/ViewControllers/SelectDateFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectDefaultWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/SelectDurationFormatViewController.cs
  Toggl.Daneel/ViewControllers/SelectWorkspaceViewController.cs
  Toggl.Daneel/ViewControllers/Settings/CalendarSettingsViewController.cs
  Toggl.Daneel/ViewControllers/SyncFailuresViewController.cs
  Toggl.Daneel/ViewSources/ClientTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/TableView/BaseTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/TableView/CustomTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/TableView/ReloadTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectUserCalendarsTableViewSource.cs
Labels: ios

#4355 Time entries log reloading
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogHeaderView.cs
  Toggl.Daneel/Extensions/Binders/ReactiveTableViewBinder.cs
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewSources/Generic/MutableSectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/Generic/ReactiveSectionedListTableViewSource.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Daneel/Views/Log/RefreshControl.cs
  Toggl.Foundation.MvvmCross/Toggl.Foundation.MvvmCross.csproj
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/DaySummaryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/TimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/Interactors/TimeEntry/ObserveAllTimeEntriesVisibleToTheUserInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Foundation/Interactors/IInteractorFactory.cs
  Toggl.Foundation/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Foundation/Interactors/TimeEntry/GetAllTimeEntriesVisibleToTheUserInteractor.cs
  Toggl.Foundation/Interactors/TimeEntry/ObserveAllTimeEntriesVisibleToTheUserInteractor.cs
  Toggl.Giskard/Activities/MainActivity.Onboardings.cs
  Toggl.Giskard/Activities/MainActivity.cs
Labels: ios

#4363 Group TEs by similarity
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesLogTransformation.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/TimeEntriesGroupViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/TimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Transformations/TimeEntriesLogTrasnformationTests.cs
Labels: foundation

#4366 Fix Realm exception when accessing tags
  Toggl.Foundation/Interactors/TimeEntry/GetAllTimeEntriesVisibleToTheUserInteractor.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
Labels: blocking

#4356 Remove description length limit
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/StartTimeEntryViewController.xib
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Helper/Constants.cs
Labels: ios

#4369 📐 Add Welcome View Margin
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
Labels: ios

#4281 Sort clients in select client view
  Toggl.Foundation.MvvmCross/ViewModels/SelectClientViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectClientViewModelTests.cs
Labels: foundation

#4378 Change parameters type for EditTimeEntryViewModel
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
Labels: foundation

#4333 🚧 Optimize the clean-up loop for cleaning inaccessible entities
  Toggl.Foundation.Tests/Sync/States/CleanUp/CheckForInaccessibleWorkspacesTests.cs
  Toggl.Foundation/Sync/States/CleanUp/CheckForInaccessibleWorkspacesState.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: foundation, sync

#4379 Convert the SettingsActivity into a Fragment
  Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Giskard/Fragments/ReactiveFragment.cs
  Toggl.Giskard/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/SettingsFragment.cs
  Toggl.Giskard/Resources/layout/SettingsFragment.axml
  Toggl.Giskard/Resources/layout/SettingsFragmentWorkspaceCell.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4382 Fix calendar selection bug
  Toggl.Daneel/Cells/Calendar/SelectableUserCalendarViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableUserCalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
Labels: bug, ios

#4384 Transform ReportsActivity into a Fragment
  Toggl.Foundation.MvvmCross/ViewModels/ReportsHostViewModel.cs
  Toggl.Giskard/Activities/ReportsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Adapters/ReportsRecyclerAdapter.cs
  Toggl.Giskard/Fragments/ReactiveFragment.cs
  Toggl.Giskard/Fragments/ReportsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/ReportsFragment.cs
  Toggl.Giskard/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/ReportsFragment.axml
  Toggl.Giskard/Resources/layout/ReportsFragmentHeader.axml
  Toggl.Giskard/Resources/layout/ReportsFragmentItem.axml
  Toggl.Giskard/Resources/layout/ReportsFragmentWorkspaceName.axml
  Toggl.Giskard/TemplateSelectors/ReportsTemplateSelector.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/ReportsItemCellViewHolder.cs
Labels: android

#4373 Teach all settings observables to drive
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
Labels: ios

#4380 Allow same project name if associated with different client.
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
Labels: foundation

#4392 Cherry Pick #3857: Implement services needed for the android calendar
  Toggl.Daneel/Services/CalendarServiceIos.cs
  Toggl.Foundation.MvvmCross/Services/PermissionAwareCalendarService.cs
  Toggl.Giskard/Activities/ReactiveActivity.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Services/CalendarServiceAndroid.cs
  Toggl.Giskard/Services/PermissionsServiceAndroid.cs
Labels: android, ios

#4391 Calendroid: Empty calendar fragment
  Toggl.Giskard/Fragments/CalendarFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
  Toggl.Giskard/Resources/layout/CalendarFragment.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4390 Transform MainActivity into a Fragment
  Toggl.Foundation.MvvmCross/ViewModels/MainHostViewModel.cs
  Toggl.Giskard/Activities/MainActivity.ViewBinds.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Fragments/MainFragment.Onboardings.cs
  Toggl.Giskard/Fragments/MainFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/MainFragment.cs
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/MainFragment.axml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4308 Android Edit duration view
  Toggl.Foundation.MvvmCross/Helper/TemporalInconsistency.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
  Toggl.Giskard/Activities/EditDurationActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditDurationActivity.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Resources/drawable/ic_separator_dot.xml
  Toggl.Giskard/Resources/drawable/picker_header_background.xml
  Toggl.Giskard/Resources/layout/EditDurationActivity.axml
  Toggl.Giskard/Resources/menu/GenericSaveMenu.xml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHelpers/DatePickerListener.cs
  Toggl.Giskard/ViewHelpers/TimePickerListener.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Cap.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Dot.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
  Toggl.Giskard/Views/EditDuration/WheelForegroundView.cs
Labels: android

#4402 Merge develop back into Grouped TEs branch
  Toggl.Foundation.MvvmCross/Helper/TemporalInconsistency.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectProjectViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation/Models/Tag.cs
  Toggl.Giskard/Activities/EditDurationActivity.ViewBinds.cs
  Toggl.Giskard/Activities/EditDurationActivity.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Resources/drawable/ic_separator_dot.xml
  Toggl.Giskard/Resources/drawable/picker_header_background.xml
  Toggl.Giskard/Resources/layout/EditDurationActivity.axml
  Toggl.Giskard/Resources/menu/GenericSaveMenu.xml
  Toggl.Giskard/Resources/values/Styles.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHelpers/DatePickerListener.cs
  Toggl.Giskard/ViewHelpers/TimePickerListener.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Cap.cs
  Toggl.Giskard/Views/EditDuration/Shapes/Dot.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
  Toggl.Giskard/Views/EditDuration/WheelForegroundView.cs
  Toggl.Ultrawave.Tests/Models/TagTests.cs
  Toggl.Ultrawave/Models/Tag.cs
Labels: blocking

#4396 Decrease haptic feedback amount in calendar
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#4400 Remove all select time vm related code
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeParameters.cs
  Toggl.Foundation.MvvmCross/Parameters/SelectTimeResultsParameters.cs
  Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SelectTimeViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectTimeViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Giskard/Activities/EditTimeEntryActivity.cs
  Toggl.Giskard/Activities/StartTimeEntryActivity.cs
  Toggl.Giskard/Adapters/SelectTimePagerAdapter.cs
  Toggl.Giskard/Bindings/DatePickerBoundariesTargetBinding.cs
  Toggl.Giskard/Fragments/SelectTimeFragment.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Resources/layout/SelectDateTimeDurationTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectDateTimeStartTimeTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectDateTimeStopTimeTabHeader.axml
  Toggl.Giskard/Resources/layout/SelectStartDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectStopDateTimeEditorPage.axml
  Toggl.Giskard/Resources/layout/SelectTimeDurationPage.axml
  Toggl.Giskard/Resources/layout/SelectTimeFragment.axml
  Toggl.Giskard/Startup/SetupTargetFactories.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/NonSwipingViewPager.cs
  Toggl.Giskard/Views/TogglDroidDatePicker.cs
  Toggl.Giskard/Views/TogglDroidTimePicker.cs
Labels: android, foundation

#4367 Grouped TEs on main log
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Extensions/Reactive/UITableViewExtensions.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Foundation.MvvmCross/Extensions/TimeEntryExtensions.cs
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesCollapsing.cs
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesGrouping.cs
  Toggl.Foundation.MvvmCross/Transformations/TimeEntriesLogTransformation.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/GroupId.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/LogItemVisualizationIntent.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/TimeEntriesGroupViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLog/TimeEntryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Foundation.Tests/MvvmCross/Transformations/TimeEntriesGroupingTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LogItemViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntryViewModelTests.cs
  Toggl.Foundation/Extensions/TimeEntryExtensions.cs
  Toggl.Foundation/Models/FoundationConstructors.cs
  Toggl.Giskard/Activities/MainActivity.Onboardings.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Adapters/MainRecyclerAdapter.cs
  Toggl.Giskard/Adapters/ReactiveSectionedRecyclerAdapter.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHelpers/MainRecyclerViewTouchCallback.cs
  Toggl.Giskard/ViewHelpers/TimeEntryCollectionViewModel.cs
  Toggl.Giskard/ViewHelpers/TimeEntryViewData.cs
  Toggl.Giskard/ViewHolders/MainLogCellViewHolder.cs
  Toggl.Giskard/ViewHolders/MainLogSectionViewHolder.cs
Labels: ios

#4381 Delete groups of time entries with swipe gesture
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/Views/SnackBar.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/ViewHelpers/TimeEntryViewData.cs
Labels: ios

#4415 Use strategy for equality checks in BaseRecyclerAdapter's Diffing algorithm.
  Toggl.Foundation.MvvmCross/Interfaces/IDiffableByIdentifier.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarBaseQuickSelectShortcut.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendar/ReportsCalendarDayViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableBeginningOfWeekViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableClientViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableColorViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableCountryViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableDateFormatViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableDurationFormatViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableWorkspaceViewModel.cs
  Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BasePushEntityStateTests.cs
  Toggl.Foundation.Tests/Sync/TestConfigurator.cs
  Toggl.Foundation/Analytics/SyncAnalyticsExtensions.cs
  Toggl.Giskard/Adapters/BaseRecyclerAdapter.cs
  Toggl.Giskard/Adapters/DiffingStrategies/EquatableDiffingStrategy.cs
  Toggl.Giskard/Adapters/DiffingStrategies/IDiffingStrategy.cs
  Toggl.Giskard/Adapters/DiffingStrategies/IdentifierEqualityDiffingStrategy.cs
  Toggl.Giskard/Adapters/SimpleAdapter.cs
  Toggl.Giskard/Extensions/Reactive/RecyclerAdapterExtensions.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Multivac/Ensure.cs
  Toggl.Multivac/Extensions/TypeExtensions.cs
Labels: android

#4409 Improve tests
  Toggl.Foundation.Tests/DataSources/TimeEntriesDataSourceTests.cs
  Toggl.Foundation.Tests/Interactors/Workspace/ObserveAllWorkspacesInteractorTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/EditDurationViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ForgotPasswordViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/NoWorkspaceViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/OnboardingViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/Reports/ReportsBarChartViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsCalendarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/ReportsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectClientViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectCountryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SendFeedbackViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.Foundation.Tests/Sync/StateMachineOrchestratorTests.cs
  Toggl.Foundation.Tests/Sync/SyncStateQueueTests.cs
  Toggl.Foundation.Tests/TestExtensions/ITestableObserverExtensions.cs
  Toggl.Foundation.Tests/TestExtensions/ListOfSyncStateExtensions.cs
  Toggl.Foundation.Tests/TogglFoundationTests.cs
  Toggl.Multivac.Tests/ColorTests.cs
Labels: foundation

#4364 Daneel 1.17 (Amiga)
  Toggl.Daneel.SiriExtension.UI/Info.plist
  Toggl.Daneel.SiriExtension/Info.plist
  Toggl.Daneel/Cells/Calendar/SelectableUserCalendarViewCell.cs
  Toggl.Daneel/Extensions/LabelExtensions.cs
  Toggl.Daneel/Info.plist
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableUserCalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
Labels: ios, release

#4414 Run ViewDestroy lifecycle event on modals
  Toggl.Daneel/Presentation/TogglPresenter.cs
Labels: bug, ios

#4420 Calendar onboarding view
  Toggl.Giskard/Resources/drawable-hdpi/calendar_onboarding.png
  Toggl.Giskard/Resources/drawable-mdpi/calendar_onboarding.png
  Toggl.Giskard/Resources/drawable-xhdpi/calendar_onboarding.png
  Toggl.Giskard/Resources/drawable-xxhdpi/calendar_onboarding.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/calendar_onboarding.png
  Toggl.Giskard/Resources/drawable/BlueButton.axml
  Toggl.Giskard/Resources/layout/CalendarOnboardingView.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4416 Track sync duration
  Toggl.Foundation.MvvmCross/FoundationExtensions.cs
  Toggl.Foundation.Tests.Sync/Helpers/AppServices.cs
  Toggl.Foundation.Tests/Sync/DeadlockTests.cs
  Toggl.Foundation.Tests/Sync/LeakyBucketTests.cs
  Toggl.Foundation.Tests/Sync/SyncManagerTests.cs
  Toggl.Foundation/Analytics/BaseAnalyticsService.cs
  Toggl.Foundation/Analytics/IAnalyticsService.cs
  Toggl.Foundation/Diagnostics/MeasuredOperation.cs
  Toggl.Foundation/Sync/LeakyBucket.cs
  Toggl.Foundation/Sync/SyncManager.cs
  Toggl.Foundation/TogglSyncManagerFactory.cs
Labels: metrics, sync

#4399 Calendroid: initial recycler view
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Foundation/Resources.Designer.cs
  Toggl.Foundation/Resources.resx
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/Views/CalendarRecyclerView.cs
Labels: android

#4421 Start TE: Select Existing Project
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Tests.UI/StartTimeEntryTests.cs
Labels: ui-tests

#4397 Android bottom navigation bar
  Toggl.Daneel/Services/RemoteConfigServiceIos.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Daneel/ViewControllers/MainTabBarController.cs
  Toggl.Foundation.MvvmCross/App.cs
  Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
  Toggl.Foundation.MvvmCross/NavigationService.cs
  Toggl.Foundation.MvvmCross/Services/IForkingNavigationService.cs
  Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainHostViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/ReportsHostViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/AppStartTests.cs
  Toggl.Foundation.Tests/MvvmCross/BaseMvvmCrossTests.cs
  Toggl.Foundation.Tests/MvvmCross/FoundationExtensionsTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs
  Toggl.Foundation/Services/IRemoteConfigService.cs
  Toggl.Giskard/Activities/MainActivity.ViewBinds.cs
  Toggl.Giskard/Activities/MainActivity.cs
  Toggl.Giskard/Activities/MainTabBarActivity.ViewBinds.cs
  Toggl.Giskard/Activities/MainTabBarActivity.cs
  Toggl.Giskard/Activities/ReportsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/ReportsActivity.cs
  Toggl.Giskard/Extensions/FragmentManagerExtensions.cs
  Toggl.Giskard/Extensions/Reactive/BottomNavigationViewExtensions.cs
  Toggl.Giskard/Fragments/MainFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/MainFragment.cs
  Toggl.Giskard/Fragments/ReactiveFragment.cs
  Toggl.Giskard/Fragments/ReportsFragment.cs
  Toggl.Giskard/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/SettingsFragment.cs
  Toggl.Giskard/Presenters/TogglPresenter.cs
  Toggl.Giskard/Resources/color/MainTabBarItemTextColor.xml
  Toggl.Giskard/Resources/drawable-hdpi/calendar_light.png
  Toggl.Giskard/Resources/drawable-mdpi/calendar_light.png
  Toggl.Giskard/Resources/drawable-xhdpi/calendar_light.png
  Toggl.Giskard/Resources/drawable-xxhdpi/calendar_light.png
  Toggl.Giskard/Resources/drawable-xxxhdpi/calendar_light.png
  Toggl.Giskard/Resources/layout/MainActivity.axml
  Toggl.Giskard/Resources/layout/MainFragment.axml
  Toggl.Giskard/Resources/layout/MainTabBarActivity.axml
  Toggl.Giskard/Resources/layout/ReportsActivity.axml
  Toggl.Giskard/Resources/layout/ReportsFragment.axml
  Toggl.Giskard/Resources/menu/MainTabBarBottomMenu.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Services/RemoteConfigServiceAndroid.cs
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/packages.config
Labels: android

#4080 Add select country UI tests
  Toggl.Daneel.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel/ViewControllers/SelectCountryViewController.xib
  Toggl.Daneel/ViewControllers/SignupViewController.xib
  Toggl.Daneel/Views/CountrySelection/CountryViewCell.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard.Tests.UI/Extensions/AppQueryExtensions.cs
  Toggl.Tests.UI/SignUpTests.cs
Labels: android, ios, ui-tests

#4422 💚 Fix UI test
  Toggl.Tests.UI/StartTimeEntryTests.cs
Labels: ui-tests

#4428 Fix bug that caused the total time to always be 0
  Toggl.Foundation.MvvmCross/ViewModels/Reports/ReportsViewModel.cs
Labels: bug, foundation

#4405 Giskard 1.11 (Chlorine)
  Toggl.Giskard/Properties/AndroidManifest.xml
Labels: android, release

#4442 Giskard 1.11.1 (Chlorine Hotfix)
  Toggl.Giskard/Properties/AndroidManifest.xml
Labels: android, release

#4441 Use older api for Lollipop support
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
Labels: android, bug

#4440 🐛Fix Calendar crash when creating TimeEntries
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
Labels: crash, ios

#4413 🚧 Add NoProject UI Test
  Toggl.Tests.UI/StartTimeEntryTests.cs
Labels: ui-tests

#4444 Giskard 1.11.1 (Chlorine Hotfix)
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
Labels: android, release

#4431 Select calendars fragment
  Toggl.Daneel/Cells/Calendar/UserCalendarListHeaderViewCell.cs
  Toggl.Daneel/ViewSources/SelectUserCalendarsTableViewSource.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/UserCalendarSourceViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableUserCalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelTests.cs
  Toggl.Giskard/Adapters/BaseSectionedRecyclerAdapter.cs
  Toggl.Giskard/Adapters/UserCalendarsRecyclerAdapter.cs
  Toggl.Giskard/Extensions/Reactive/ButtonExtensions.cs
  Toggl.Giskard/Extensions/Reactive/RecyclerAdapterExtensions.cs
  Toggl.Giskard/Fragments/ReactiveDialogFragment.cs
  Toggl.Giskard/Fragments/SelectUserCalendarsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/SelectUserCalendarsFragment.cs
  Toggl.Giskard/Resources/color/BlueLinkTextColor.xml
  Toggl.Giskard/Resources/layout/SelectUserCalendarsFragment.axml
  Toggl.Giskard/Resources/layout/UserCalendarHeader.axml
  Toggl.Giskard/Resources/layout/UserCalendarItem.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/BaseRecyclerViewHolder.cs
  Toggl.Giskard/ViewHolders/UserCalendarHeaderViewHolder.cs
  Toggl.Giskard/ViewHolders/UserCalendarViewHolder.cs
Labels: android

#4466 Fix sign up
  Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
Labels: bug

#4461 Show calendar onboarding
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs
  Toggl.Giskard/Fragments/CalendarFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
  Toggl.Giskard/Resources/layout/CalendarFragment.axml
Labels: android

#4471 Add new cs for edit time entry tests
  Toggl.Tests.UI/EditTimeEntryTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#4460 Smart reminders fragment
  Toggl.Daneel/Cells/Settings/UpcomingEventsOptionCell.cs
  Toggl.Daneel/ViewControllers/Settings/UpcomingEventsNotificationSettingsViewController.cs
  Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableCalendarNotificationsOptionViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/UpcomingEventsNotificationSettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/UpcomingEventsNotificationSettingsViewModelTests.cs
  Toggl.Giskard/Adapters/SelectCalendarNotificationsOptionAdapter.cs
  Toggl.Giskard/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/SettingsFragment.cs
  Toggl.Giskard/Fragments/UpcomingEventsNotificationSettingsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/UpcomingEventsNotificationSettingsFragment.cs
  Toggl.Giskard/Resources/layout/SelectCalendarNotificationsOptionItem.axml
  Toggl.Giskard/Resources/layout/SettingsFragment.axml
  Toggl.Giskard/Resources/layout/UpcomingEventsNotificationSettingsFragment.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/SelectCalendarNotificationsOptionViewHolder.cs
Labels: android

#4472 Calendar permission denied fragment
  Toggl.Giskard/Fragments/CalendarPermissionDeniedFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/CalendarPermissionDeniedFragment.cs
  Toggl.Giskard/Resources/layout/CalendarPermissionDeniedFragment.axml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4266 ✨ Calendar zoom
  Toggl.Daneel/Cells/Calendar/CalendarItemView.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewAutoScrollHelper.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewZoomHelper.cs
Labels: ios

#4479 Calendroid: Fix notification scheduler
  Toggl.Giskard/BroadcastReceivers/SmartAlertCalendarEventBroadcastReceiver.cs
  Toggl.Giskard/Services/NotificationServiceAndroid.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4481 📝 add information about the ui test apk architecture
  docs/running-android-ui-tests.md
Labels: ui-tests

#4484 Add UI test for editing time entry description
  Toggl.Daneel.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs
  Toggl.Daneel.Tests.UI/Toggl.Daneel.Tests.UI.csproj
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Giskard.Tests.UI/Extensions/EditTimeEntryExtensions.cs
  Toggl.Giskard.Tests.UI/Toggl.Giskard.Tests.UI.csproj
  Toggl.Giskard/Resources/layout/MainLogCell.axml
  Toggl.Tests.UI/EditTimeEntryTests.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
Labels: ui-tests

#4425 Calendroid: Calendar layout manager
  Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs
  Toggl.Foundation/Helper/Constants.cs
  Toggl.Giskard/Adapters/Calendar/Anchor.cs
  Toggl.Giskard/Adapters/Calendar/AnchorData.cs
  Toggl.Giskard/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Giskard/Fragments/CalendarFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
  Toggl.Giskard/Resources/drawable/CalendarEntryBackground.xml
  Toggl.Giskard/Resources/layout/CalendarEntryCell.axml
  Toggl.Giskard/Resources/layout/CalendarFragment.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/AnchorViewHolder.cs
  Toggl.Giskard/ViewHolders/CalendarEntryViewHolder.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.AnchorInfo.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.AnchorSavedState.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.Inspector.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.LayoutState.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.Recycler.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.ScrollHelper.cs
  Toggl.Giskard/Views/Calendar/CalendarLayoutManager.cs
  Toggl.Giskard/Views/CalendarRecyclerView.cs
Labels: android

#4485 Calendar settings activity
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Foundation.MvvmCross/ViewModels/MainTabBarViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarSettingsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SelectUserCalendarsViewModelTests.cs
  Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs
  Toggl.Giskard/Activities/CalendarSettingsActivity.ViewBinds.cs
  Toggl.Giskard/Activities/CalendarSettingsActivity.cs
  Toggl.Giskard/Fragments/SettingsFragment.cs
  Toggl.Giskard/Resources/layout/CalendarSettingsActivity.axml
  Toggl.Giskard/Resources/layout/SelectUserCalendarsBase.axml
  Toggl.Giskard/Resources/layout/SelectUserCalendarsFragment.axml
  Toggl.Giskard/Resources/menu/CalendarSettingsMenu.xml
  Toggl.Giskard/Resources/values/Strings.xml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Multivac/Extensions/HashSetExtensions.cs
  Toggl.PrimeRadiant/Settings/SettingsStorage.cs
Labels: android
