Repository toggl/mobileapp, pull requests merged in 2019-07, with the labels that each got.

#5512 Remove avatar from settings
  Toggl.Core.Tests/UI/ViewModels/SettingsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.User.cs
  Toggl.Core/Interactors/User/GetUserAvatarInteractor.cs
  Toggl.Droid/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Droid/Resources/layout/SettingsFragment.axml
Labels: android

#5513 :fire: Remove 3-step onboarding
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.iOS/Presentation/RootPresenter.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
  Toggl.iOS/ViewControllers/OnboardingViewController.designer.cs
Labels: ios

#5373 🔮 Project: Suggestion improvements
  Toggl.Core.Tests/Interactors/Suggestions/CalendarSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionProvidersInteractorTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionsInteractorTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/RandomForestSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Core.Tests/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core.Tests/Suggestions/SuggestionProviderContainerTests.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/Toggl.Core.UI.csproj
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/CalendarSuggestionContinuedEvent.cs
  Toggl.Core/Analytics/CalendarSuggestionProviderState.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Analytics/SuggestionsPresentedEvent.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Core/Diagnostics/MeasuredOperation.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.Suggestions.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionProvidersInteractor.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
  Toggl.Core/Suggestions/CalendarSuggestionProvider.cs
  Toggl.Core/Suggestions/Interfaces/ISuggestionProviderContainer.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
  Toggl.Core/Suggestions/Suggestion.cs
  Toggl.Core/Suggestions/SuggestionProviderContainer.cs
  Toggl.Core/Suggestions/SuggestionProviderType.cs
  Toggl.Droid/Adapters/MainSuggestionsRecyclerAdapter.cs
  Toggl.Droid/Resources/layout/MainSuggestions.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCard.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCardDescriptionOnly.axml
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/MainLogSuggestionItemViewHolder.cs
  Toggl.Droid/ViewHolders/MainLogSuggestionsListViewHolder.cs
  Toggl.Droid/packages.config
  Toggl.iOS/Startup/IosDependencyContainer.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
  Toggl.iOS/Views/Suggestions/SuggestionsView.cs
  Toggl.iOS/packages.config
  Toggl.sln
Labels: blocking

#5515 Unify workspace pickers
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Droid/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Droid/Resources/layout/SettingsFragment.axml
  Toggl.Droid/Resources/layout/SettingsFragmentWorkspaceCell.axml
  Toggl.Droid/Resources/values/Strings.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#5516 Remove background overdraw from our views
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Activities/SelectProjectActivity.cs
  Toggl.Droid/Resources/layout/CalendarSettingsActivity.axml
  Toggl.Droid/Resources/layout/EditProjectActivity.axml
  Toggl.Droid/Resources/layout/ReportsFragment.axml
  Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml
  Toggl.Droid/Resources/layout/SelectProjectActivity.axml
  Toggl.Droid/Resources/layout/SettingsFragment.axml
  Toggl.Droid/Resources/values/Styles.xml
Labels: android

#5522 Morphing FAB animation
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Droid/Extensions/CircularRevealAnimation.cs
  Toggl.Droid/Fragments/MainFragment.ViewBinds.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Presentation/RunningTimeEntrySheetBehavior.cs
  Toggl.Droid/Resources/animator/Collapse.xml
  Toggl.Droid/Resources/animator/Expand.xml
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/layout/MainRunningTimeEntry.axml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#5529 Remove swipe onboarding
  Toggl.Core.UI/Onboarding/MainView/SwipeLeftOnboardingStep.cs
  Toggl.Core.UI/Onboarding/MainView/SwipeRightOnboardingStep.cs
  Toggl.Droid/Extensions/OnboardingExtensions.cs
  Toggl.Droid/Fragments/MainFragment.Onboardings.cs
  Toggl.Droid/ViewHolders/MainLogCellViewHolder.cs
  Toggl.iOS/Extensions/OnboardingExtensions.cs
  Toggl.iOS/Extensions/TimeEntriesLogViewCellExtensions.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
Labels: android, ios

#5530 Minor code cleanup
  Toggl.Droid/Extensions/ViewExtensions.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/OnboardingViewController.xib
Labels: refactoring

#5532 🚧 Add missing using
  Toggl.iOS/Startup/AppDelegate.Analytics.cs
  Toggl.iOS/ViewControllers/SignupViewController.cs
Labels: release

#5536 🎨 Make single day selection always a circle
  Toggl.Droid/ViewHolders/CalendarDayCellViewHolder.cs
  Toggl.Droid/Views/ReportsCalendarDayView.cs
Labels: android, glitch

#5535 Consolidate the toolbar heights
  Toggl.Droid/Resources/layout/CalendarFragment.axml
  Toggl.Droid/Resources/layout/CalendarHeaderView.axml
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/layout/ReportsFragment.axml
Labels: android

#5537 🚧 Add CFBundleDiplayName to info.plist
  Toggl.iOS/Info.plist
Labels: ios, release

#5550 Fix back button in forgot password view
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs
Labels: ios

#5554 ✨ Add an empty widget
  Toggl.Droid/Resources/layout/TimeEntryWidget.axml
  Toggl.Droid/Resources/xml/TimeEntryWidgetProvider.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Widgets/TimeEntryWidget.cs
Labels: android

#5557 ✨ Add an empty widget
  Toggl.Droid/Resources/layout/TimeEntryWidget.axml
  Toggl.Droid/Resources/xml/TimeEntryWidgetProvider.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Widgets/TimeEntryWidget.cs
Labels: android

#5534 Add ripples, ripples everywhere on droid
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Droid/Fragments/MainFragment.ViewBinds.cs
  Toggl.Droid/Resources/layout/AbcCreateEntityCell.axml
  Toggl.Droid/Resources/layout/EditDurationActivity.axml
  Toggl.Droid/Resources/layout/EditProjectActivity.axml
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/layout/MainLogCell.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCard.axml
  Toggl.Droid/Resources/layout/SelectProjectActivityProjectCell.axml
  Toggl.Droid/Resources/layout/SelectProjectActivityTaskCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityProjectCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityQuerySymbolCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTagCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTaskCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTimeEntryCell.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTimeEntryWithPartialContentCell.axml
Labels: android

#5552 Add today extension
  Toggl.iOS.TimerWidgetExtension/Entitlements.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/MainInterface.storyboard
  Toggl.iOS.TimerWidgetExtension/TodayViewController.cs
  Toggl.iOS.TimerWidgetExtension/TodayViewController.designer.cs
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.sln
  build.cake
Labels: ios

#5562 Adds widget install/uninstall event
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: foundation

#5560 🚧 Filter random forest TEs for description or project
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
Labels: foundation, release

#5519 Android 2.1 - Baklava
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Services/AnalyticsServiceAndroid.cs
  Toggl.Droid/Services/FirebaseStopwatchProviderAndroid.cs
Labels: android, release

#5564 Implement timer widget design
  Toggl.iOS.TimerWidgetExtension/MainInterface.storyboard
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/Contents.json
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStart.imageset/Contents.json
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStart.imageset/play.png
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStart.imageset/play@2x-1.png
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStart.imageset/play@3x.png
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStop.imageset/Contents.json
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStop.imageset/stop.png
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStop.imageset/stop@2x.png
  Toggl.iOS.TimerWidgetExtension/Resources/Images.xcassets/icStop.imageset/stop@3x.png
  Toggl.iOS.TimerWidgetExtension/TodayViewController.designer.cs
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
Labels: ios

#5452 Split manual testing template into automated and manual tests
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
Labels: process

#5466 Add tips for writing good UI tests to UI test docs
  docs/adding-ui-tests.md
Labels: process

#5563 Track iOS widget (un)installs
  Toggl.iOS.ExtensionKit/Extensions/DateExtensions.cs
  Toggl.iOS.ExtensionKit/SharedStorage.cs
  Toggl.iOS.ExtensionKit/Toggl.iOS.ExtensionKit.csproj
  Toggl.iOS.SiriExtension/ContinueTimerIntentHandler.cs
  Toggl.iOS.SiriExtension/Helper/APIHelper.cs
  Toggl.iOS.SiriExtension/StartTimerFromClipboardIntentHandler.cs
  Toggl.iOS.SiriExtension/StartTimerIntentHandler.cs
  Toggl.iOS.SiriExtension/StopTimerIntentHandler.cs
  Toggl.iOS.TimerWidgetExtension/TodayViewController.cs
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS.TimerWidgetExtension/packages.config
  Toggl.iOS/Services/PrivateSharedStorageServiceIos.cs
  Toggl.iOS/Startup/AppDelegate.Background.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.sln
Labels: ios

#5575 Move api client to ExtensionKit
  Toggl.iOS.ExtensionKit/Exceptions/NoRunningEntryException.cs
  Toggl.iOS.ExtensionKit/Helper/APIHelper.cs
  Toggl.iOS.ExtensionKit/Models/TimeEntry.cs
  Toggl.iOS.ExtensionKit/Toggl.iOS.ExtensionKit.csproj
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/ContinueTimerIntentHandler.cs
  Toggl.iOS.SiriExtension/IntentHandler.cs
  Toggl.iOS.SiriExtension/StartTimerFromClipboardIntentHandler.cs
  Toggl.iOS.SiriExtension/StartTimerIntentHandler.cs
  Toggl.iOS.SiriExtension/StopTimerIntentHandler.cs
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
Labels: ios

#5579 ♻ Fix sync on startup
  Toggl.Core.UI/AppStart.cs
  Toggl.Droid/Startup/SplashScreen.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: android, bug, critical, ios

#5589 ✅ Make the tests use the simulator selected in the IDE
  Toggl.iOS.Tests.UI/Configuration.cs
Labels: ios, ui-tests

#5587 ✅ Delete app before each test
  Toggl.iOS.Tests.UI/Configuration.cs
Labels: ios, ui-tests

#5528 iOS 2.1 Blackberry
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/Startup/AppDelegate.Analytics.cs
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs
  Toggl.iOS/ViewControllers/SignupViewController.cs
Labels: ios, release

#5581 iOS 2.1.1 - Blackberry hotfix
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
Labels: ios, release

#5577 ⚡ Report installation state
  Toggl.Droid/Services/JobServicesConstants.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Widgets/Services/InstallationStateReportService.cs
  Toggl.Droid/Widgets/TimeEntryWidget.cs
Labels: android

#5580 📝 Add check for full-sync on app start to manual tests template
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
Labels: process

#5541 📝 Fully qualify the types in the #if-s
  Toggl.Droid/Services/AnalyticsServiceAndroid.cs
  Toggl.Droid/Services/FirebaseStopwatchProviderAndroid.cs
  Toggl.iOS/Services/FirebaseStopwatchProviderIos.cs
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/SignupViewController.cs
Labels: android, ios

#5542 🚧 Rename FB remote config parameters
  Toggl.Core/Services/IUpdateRemoteConfigCacheService.cs
  Toggl.Droid/Resources/xml/RemoteConfigDefaults.xml
  Toggl.iOS/RemoteConfigDefaults.plist
  Toggl.iOS/Toggl.iOS.csproj
Labels: foundation

#5600 Update packages so UI tests can be run with Cake
  Toggl.Core.Tests/Toggl.Core.Tests.csproj
  Toggl.Droid.Tests.UI/Toggl.Droid.Tests.UI.csproj
  Toggl.Droid.Tests.UI/packages.config
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.sln
Labels: ui-tests

#5544 Spider improvements
  Toggl.iOS/Views/SpiderOnARopeView.cs
Labels: ios

#5601 Don't abort UI tests after first failure when running from Cake
  build.cake
Labels: ui-tests

#5605 Add Cake build configurations for iOS and Android UI tests
  build.cake
Labels: ui-tests

#5567 Fix accessibility for main view
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Core/Services/IAccessibilityService.cs
  Toggl.Core/Suggestions/Suggestion.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Services/AccessibilityServiceAndroid.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogHeaderView.cs
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
  Toggl.iOS/Services/AccessibilityServiceIos.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/MainTabBarController.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
  Toggl.iOS/Views/AccessibilityAwareView.cs
  Toggl.iOS/Views/SnackBar.cs
  Toggl.iOS/Views/SnackBar.xib
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
  Toggl.iOS/Views/Suggestions/SuggestionsView.cs
Labels: ios

#5609 Fix some UI tests
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.iOS/Views/StartTimeEntry/ReactiveProjectSuggestionViewCell.xib
Labels: ios, ui-tests

#5608 Stop restarting the iOS simulator on every test run
  Toggl.iOS.Tests.UI/Configuration.cs
Labels: ios, ui-tests

#5598 🚧Make sure none of the providers failing blocks the suggestions
  Toggl.Core.Tests/Interactors/Suggestions/CalendarSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/RandomForestSuggestionProviderTests.cs
  Toggl.Core/Suggestions/CalendarSuggestionProvider.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
  Toggl.Shared/Extensions/ReactiveExtensions.cs
Labels: foundation, glitch

#5568 Add Android widget design
  Toggl.Droid/Resources/drawable/RoundedButton.xml
  Toggl.Droid/Resources/layout/TimeEntryWidget.axml
  Toggl.Droid/Resources/layout/TimeEntryWidgetSmall.axml
  Toggl.Droid/Resources/xml/TimeEntryWidgetProvider.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Widgets/TimeEntryWidget.cs
Labels: android

#5612 Remove onboarding UI tests
  Toggl.Tests.UI/OnboardingTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#5606 🚧 Filter out TEs with archived project
  Toggl.Core.Tests/Interactors/Suggestions/RandomForestSuggestionProviderTests.cs
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
Labels: foundation

#5616 🚧Do not perform animation if not needed
  Toggl.iOS/Extensions/OnboardingExtensions.cs
Labels: ios

#5614 Fix sync tests
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests.Sync/Scenarios/PushNotificationsTokens/PushesTheFirstTokenToTheServer.cs
  Toggl.Core.Tests.Sync/Scenarios/PushNotificationsTokens/PushesTokenToTheServerAgainWhenItChanges.cs
  Toggl.Core.Tests.Sync/Scenarios/PushNotificationsTokens/RemovesInvalidToken.cs
Labels: sync

#5621 ♻ Revert to waiting for initialize to complete
  Toggl.Core.UI/Navigation/NavigationService.cs
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: bug

#5623 Don't show suggestions with archived projects
  Toggl.Core.Tests/Interactors/AutocompleteSuggestions/GetTimeEntriesAutocompleteSuggestionsInteractorTests.cs
  Toggl.Core/Interactors/AutocompleteSuggestions/GetTimeEntriesAutocompleteSuggestions.cs
Labels: foundation

#5171 Add restriction checking
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
Labels: process

#5590 Fix missing characters when inputting text during UI tests
  Toggl.Droid.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/Extensions/StartTimeEntryExtensions.cs
  Toggl.Tests.UI/StartTimeEntryTests.cs
  Toggl.iOS.Tests.UI/Extensions/StartTimeEntryExtensions.cs
Labels: ios, ui-tests

#5625 Show archived status in time entry group
  Toggl.Core.Tests/UI/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Core.UI/Transformations/TimeEntriesGroupsFlattening.cs
Labels: foundation

#5624 Don't create tag with duplicated names
  Toggl.Core.Tests/Interactors/Tag/CreateTagInteractorTests.cs
  Toggl.Core.UI/ViewModels/SelectTagsViewModel.cs
  Toggl.Core/Interactors/Tag/CreateTagInteractor.cs
Labels: foundation

#5642 Replace all uses of SynchronizationContext.Current
  Toggl.Droid/Extensions/OnboardingExtensions.cs
  Toggl.Droid/Fragments/MainFragment.Onboardings.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.iOS/Extensions/OnboardingExtensions.cs
Labels: android, ios

#5647 🔥 Remove unused file
  Toggl.iOS/Services/ITopViewControllerProvider.cs
  Toggl.iOS/Toggl.iOS.csproj
Labels: ios

#5655 Make reports header image fit on large display settings
  Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml
Labels: android

#5646 🚧 Track paired apple watches
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.iOS/Services/WatchService.cs
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/Toggl.iOS.csproj
Labels: ios

#5660 Close android calendar cursors
  Toggl.Droid/Services/CalendarServiceAndroid.cs
Labels: android

#5673 Fix Bitrise builds
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/Toggl.iOS.csproj
Labels: android, ios

#5610 Track if app is launched with accessibility enabled
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: metrics

#5641 Track delete time entry source
  Toggl.Core.Tests/UI/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/TimeEntriesViewModelTests.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/DeleteTimeEntryOrigin.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: foundation, metrics

#5538 Use taptic feedback on start button long press
  Toggl.iOS/Extensions/Reactive/UIButtonExtensions.cs
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: ios

#5656 Make Login UI tests AAA
  Toggl.Droid.Tests.UI/Extensions/LoginExtensions.cs
  Toggl.Tests.UI/Extensions/LoginExtensions.cs
  Toggl.Tests.UI/Extensions/OnboardingExtensions.cs
  Toggl.Tests.UI/Extensions/SignUpExtensions.cs
  Toggl.Tests.UI/ForgotPasswordTests.cs
  Toggl.Tests.UI/LoginTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
  Toggl.iOS.Tests.UI/Extensions/LoginExtensions.cs
Labels: ui-tests

#5668 Track edit time entry view close reason
  Toggl.Core.Tests/UI/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/EditViewCloseReason.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: foundation, metrics

#5663 Add translation request templates
  .github/ISSUE_TEMPLATE/g-translation-request.md
  .github/PULL_REQUEST_TEMPLATE/translation-pull-request-template.md
Labels: process

#5659 Enable strict mode logging for debug builds
  Toggl.Droid/Startup/TogglApplication.cs
Labels: android

#5664 Add fix translation request templates
  .github/ISSUE_TEMPLATE/h-translation-fix-request.md
  .github/PULL_REQUEST_TEMPLATE/translation-fix-pull-request-template.md
Labels: process

#5639 🚧 Fix group TE height adjustment glitch
  Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/Views/TextViewWithPlaceholder.cs
Labels: ios

#5658 📐 Fix textfield constraints
  Toggl.iOS/ViewControllers/SelectProjectViewController.xib
Labels: glitch, ios

#5674 Prefer MainQueue over InvokeOnMainThread
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
  Toggl.iOS/Presentation/IosPresenter.cs
  Toggl.iOS/Services/BackgroundSyncServiceIos.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: ios
