Repository toggl/mobileapp, pull requests merged in 2019-11, with the labels that each got.

#6429 📐 Calendar dark mode
  Toggl.iOS/Cells/Calendar/CalendarItemView.xib
  Toggl.iOS/Cells/Calendar/CalendarWeeklyViewDayCollectionViewCell.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.xib
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.xib
Labels: ios

#6438 Reduce the size of iOS artifacts
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS/Toggl.iOS.csproj
Labels: ios

#6430 Fix calendar week stripe over scroll on beginning of week changes
  Toggl.Droid/Fragments/CalendarFragment.cs
Labels: android, bug

#6427 Add test cases for the widgets
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
Labels: android, ios

#6363 Fix contextual menu skipped tests
  Toggl.Core.Tests/Interactors/TimeEntry/ContinueTimeEntryFromMainLogInteractorTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/DeleteTimeEntryInteractorTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/StopTimeEntryInteractorTests.cs
  Toggl.Core.Tests/UI/ViewModels/CalendarContextualMenuViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/CalendarDayViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Core/Interactors/TimeEntry/ContinueTimeEntryFromMainLogInteractor.cs
  Toggl.Core/Interactors/TimeEntry/CreateTimeEntryInteractor.cs
  Toggl.Core/Interactors/TimeEntry/DeleteMultipleTimeEntriesInteractor.cs
  Toggl.Core/Interactors/TimeEntry/DeleteTimeEntryInteractor.cs
  Toggl.Core/Interactors/TimeEntry/StopTimeEntryInteractor.cs
  Toggl.Core/Interactors/TimeEntry/UpdateTimeEntryInteractor.cs
Labels: foundation

#6411 Skip event text drawing when event width is too narrow
  Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs
Labels: android, bug

#6436 Fix sync failure caused by aggregate exception
  Toggl.Core.Tests/Sync/States/Push/BaseStates/BasePushEntityStateTests.cs
  Toggl.Core/Sync/States/Push/BasePushEntityState.cs
Labels: android, bug, ios

#6440 Fix zombie time entries
  Toggl.Core.Tests/Interactors/TimeEntry/SoftDeleteMultipleTimeEntriesInteractorTests.cs
  Toggl.Core/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Core/Interactors/TimeEntry/SoftDeleteMultipleTimeEntriesInteractor.cs
Labels: critical

#6204 Fix crash in settings view
  Toggl.Core.Tests/UI/ViewModels/SettingsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
Labels: foundation

#6441 🚧 Add dismiss CTMenu when tapping outside
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
  Toggl.iOS/Views/Calendar/CalendarCollectionViewContextualMenuDismissHelper.cs
Labels: ios

#6447 🚧 Fix crashes
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#6463 🚧 Use New TE CTMenu
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
  Toggl.iOS/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
  Toggl.iOS/Views/Calendar/CalendarCollectionViewEditItemHelper.cs
Labels: ios

#6464 Hook up daily tracked time label in calendar pt2
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs
Labels: ios

#6462 Fix default dark mode usage on pre-Q devices
  Toggl.Droid/Startup/TogglApplication.cs
Labels: android, bug

#6467 🚧 Add long press analytic event
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
  Toggl.Core/Analytics/CalendarTimeEntryCreatedType.cs
Labels: foundation

#6406 iOS 2.6 - Grapefruit
  Toggl.iOS.Shared/Toggl.iOS.Shared.csproj
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS/Info.plist
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.sln
  build.cake
Labels: ios, release

#6471 Fix incorrect usage of Clamp to determine modal view offset
  Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
Labels: crash, ios

#6422 Fix long press handling on iOS
  Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs
Labels: ios

#6481 🚧 Update UI when deleting in CTMenu
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#6477 💄 Fix current time supplementary view stilling touches from underling cells
  Toggl.iOS/Cells/Calendar/CurrentTimeSupplementaryView.cs
Labels: ios

#6475 iOS 2.6.1 Grapefruit hotfix
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
Labels: ios, release

#6423 Fix tab bar items on iOS 13.0 onwards
  Toggl.iOS/ViewControllers/MainTabBarController.cs
Labels: ios

#6390 Android 2.6 - Gelato
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#6487 Unify the behaviour of UISwitch
  Toggl.iOS/Cells/Calendar/SelectableUserCalendarViewCell.cs
  Toggl.iOS/Extensions/Reactive/UISwitchExtensions.cs
  Toggl.iOS/ViewControllers/Calendar/SelectUserCalendarsViewController.cs
  Toggl.iOS/ViewControllers/Settings/CalendarSettingsViewController.cs
  Toggl.iOS/ViewSources/SelectUserCalendarsTableViewSource.cs
Labels: ios

#6490 🚧 Fix delete glitch
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
Labels: ios

#6493 Update iOS widget data when the app syncs in background
  Toggl.iOS/Startup/AppDelegate.Background.cs
  Toggl.iOS/Startup/AppDelegate.PushNotifications.cs
Labels: ios

#6492 💄 Minor tweaks to the cal project code
  Toggl.Core.UI/Calendar/CalendarLayoutCalculator.cs
  Toggl.iOS/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
Labels: foundation, ios

#6510 ❔ Add the Option type
  Toggl.Shared.Tests/OptionTests.cs
  Toggl.Shared/Option.cs
Labels: foundation

#6511 Remove yellow overlay when autocompleting
  Toggl.Droid/Resources/values-v26/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#6514 Support english copy
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/Settings/SendFeedbackViewController.cs
Labels: android, foundation, ios

#6513 Draw behind navigation
  Toggl.Droid/Activities/MainTabBarActivity.ViewBinds.cs
  Toggl.Droid/Activities/ReactiveActivity.cs
  Toggl.Droid/Extensions/ActivityExtensions.cs
  Toggl.Droid/Extensions/ViewExtensions.cs
  Toggl.Droid/Resources/values-night-v23/Styles.xml
  Toggl.Droid/Resources/values-night/Environment.xml
  Toggl.Droid/Resources/values-notnight-v27/Styles.xml
  Toggl.Droid/Resources/values-v23/Styles.xml
  Toggl.Droid/Resources/values-v27/Styles.xml
  Toggl.Droid/Resources/values-v29/Styles.xml
  Toggl.Droid/Resources/values/Environment.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#6515 Tomas/calendar visual fixups
  Toggl.Droid/Activities/SettingsActivity.cs
  Toggl.Droid/Resources/drawable/ic_settings.xml
Labels: android

#6512 Use string resources for day names and initials
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Shared.Tests/Extensions/BeginningOfWeekExtensionsTests.cs
  Toggl.Shared/Extensions/BeginningOfWeekExtensions.cs
  Toggl.Shared/Extensions/DayOfWeekExtensions.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: foundation

#6526 Bind calendar bg hours to 24hours user prefs
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.Background.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.cs
Labels: android, bug

#6528 Move calendar colors to asset file
  Toggl.Core.UI/Helper/Colors.cs
  Toggl.iOS/Cells/Calendar/CalendarWeeklyViewDayCollectionViewCell.cs
  Toggl.iOS/Extensions/ColorAssets.cs
  Toggl.iOS/Resources/Colors.xcassets/CalendarContinueAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarCopyAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarDeleteAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarDiscardAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarEditAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarHeaderLabel.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarSaveAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarSelectedTodayBackground.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarStartAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarStopAction.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarUnavailableDayText.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/CalendarUnselectedTodayText.colorset/Contents.json
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.iOS/Views/Calendar/CalendarContextualMenuActionView.cs
Labels: ios

#6516 Update widgets when running BG sync
  Toggl.Droid/Services/BackgroundSyncJobSchedulerService.cs
  Toggl.Droid/Services/SyncJobService.cs
Labels: android

#6540 Update AppCenter
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/packages.config
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/packages.config
Labels: dependencies, metrics

#6544 Migrate Time Entry interactors to Task<T>
  Toggl.Core.Tests/Interactors/TimeEntry/ContinueTimeEntryFromMainLogInteractorTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/ContinueTimeEntryInteractorTests.cs
  Toggl.Core.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Core.Tests/UI/ViewModels/CalendarContextualMenuViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/Extensions/TimeEntryExtensions.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Core/Interactors/TimeEntry/ContinueMostRecentTimeEntryInteractor.cs
  Toggl.Core/Interactors/TimeEntry/ContinueTimeEntryFromMainLogInteractor.cs
  Toggl.Core/Interactors/TimeEntry/ContinueTimeEntryInteractor.cs
Labels: foundation

#6479 Bumped up targetSdkVersion to 29
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android

#6559 Improve long press to show error triggering view
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: ios

#6560 Remove the Upcast extension method
  Toggl.Networking/ApiClients/ClientsApi.cs
  Toggl.Networking/ApiClients/LocationApi.cs
  Toggl.Networking/ApiClients/PreferencesApi.cs
  Toggl.Networking/ApiClients/ProjectsApi.cs
  Toggl.Networking/ApiClients/TagsApi.cs
  Toggl.Networking/ApiClients/TasksApi.cs
  Toggl.Networking/ApiClients/TimeEntriesApi.cs
  Toggl.Networking/ApiClients/UserApi.cs
  Toggl.Networking/ApiClients/WorkspacesApi.cs
  Toggl.Shared/Extensions/TaskExtensions.cs
Labels: refactoring

#6552 🦴 ReportsViewModel barebone
  Toggl.Core.Tests/UI/ViewModels/ReportsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/IReportElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModelOld.cs
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Shared/Extensions/ReactiveExtensions.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/ViewControllers/MainTabBarController.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/ViewSources/ReportsTableViewSource.cs
  Toggl.iOS/Views/Reports/ReportsBarChartCardView.cs
  Toggl.iOS/Views/Reports/ReportsHeaderView.cs
  Toggl.iOS/Views/Reports/ReportsOverviewCardView.cs
Labels: foundation

#6556 Add more calendar tests to the testing issue template
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
Labels: process

#6577 Keep the cursor position when changing the duration in the edit view
  Toggl.iOS/Views/TextViewWithPlaceholder.cs
Labels: ios

#6527 Update Google and Firebase packages
  Toggl.iOS/Services/FetchRemoteConfigServiceIos.cs
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.GoogleTokenProvider.cs
  Toggl.iOS/packages.config
Labels: ios

#6581 Fix calendar contextual menu actions icon bg colors
  Toggl.Droid/Resources/drawable/ic_copy.xml
  Toggl.Droid/Resources/layout/ContextualMenuActionCell.axml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/ViewHolders/CalendarMenuActionCellViewHolder.cs
Labels: android, bug

#6590 Implement the rest of the ReportsViewModel backbone
  Toggl.Core.Tests/TestExtensions/ITestableObserverExtensions.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/CompositeReportElement.cs
  Toggl.Core.UI/ViewModels/Reports/IReportElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartDonutElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportElementBase.cs
  Toggl.Core.UI/ViewModels/Reports/ReportErrorElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportFilter.cs
  Toggl.Core.UI/ViewModels/Reports/ReportNoDataElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportSummaryElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModelOld.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.Reports.cs
  Toggl.Core/Interactors/Reports/GetTotalsInteractor.cs
  Toggl.Networking.Tests/Models/Reports/ProjectSummaryTests.cs
  Toggl.Networking.Tests/Models/Reports/ProjectsSummaryTests.cs
  Toggl.Networking/Models/Reports/ProjectSummary.cs
  Toggl.Shared/Models/Reports/IProjectSummary.cs
Labels: foundation

#6548 📝 Add an issue template for 'other' issues
  .github/ISSUE_TEMPLATE/d-regular-issue.md
  .github/ISSUE_TEMPLATE/e-manual-test-template.md
  .github/ISSUE_TEMPLATE/f-release-checklist.md
  .github/ISSUE_TEMPLATE/g-refactor-proposal.md
  .github/ISSUE_TEMPLATE/h-translation-request.md
  .github/ISSUE_TEMPLATE/i-translation-fix-request.md
  .github/ISSUE_TEMPLATE/j-new-copy-translation-request.md
Labels: process

#6617 Fix enabled calendars not saving for the first time
  Toggl.Core.UI/ViewModels/Settings/CalendarSettingsViewModel.cs
Labels: bug, ios

#6618 Improve startup time: Remove unnecessary recreation of WidgetsService on startup
  Toggl.Core.UI/UIDependencyContainer.cs
Labels: ios, performance

#6602 Fix main log time entry margins/constraints
  Toggl.Droid/Resources/layout/MainLogCell.axml
Labels: android, glitch

#6601 Cherry pick #6581 for android 2.7
  Toggl.Droid/Resources/drawable/ic_copy.xml
  Toggl.Droid/Resources/layout/ContextualMenuActionCell.axml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/ViewHolders/CalendarMenuActionCellViewHolder.cs
Labels: android, bug

#6621 Fix ClassNotFound exception
  Toggl.Droid/LinkerPleaseInclude.cs
Labels: android

#6613 ⚙ Implements a ReportsFragment to utilize the new VM
  Toggl.Core.Tests/Generators/ViewModelTypeDataAttribute.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Fragments/ReportsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
Labels: android

#6623 🐛 Prevent crash when user taps Stop multiple times in the widget
  Toggl.Droid/Services/WidgetsForegroundService.cs
Labels: android, crash

#6622 Cherry pick #6602 for android 2.7
  Toggl.Droid/Resources/layout/MainLogCell.axml
Labels: android, bug

#6597 Fix disappearing FAB glitch
  Toggl.Droid/Extensions/FloatingActionButtonExtensions.cs
  Toggl.Droid/Fragments/MainFragment.cs
Labels: android

#6625 Cherry pick #6597 for android 2.7
  Toggl.Droid/Extensions/FloatingActionButtonExtensions.cs
  Toggl.Droid/Fragments/MainFragment.cs
Labels: android, bug

#6629 Contextual menu improvements
  Toggl.Droid/Extensions/LayoutParamsExtensions.cs
  Toggl.Droid/Extensions/ViewExtensions.cs
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.ViewBinds.cs
  Toggl.Droid/Resources/layout/CalendarDayFragmentPage.axml
Labels: android

#6631 Improve Wheel rainbow contrast
  Toggl.Core.UI/Helper/Colors.cs
Labels: android, ios

#6630 Drop usage of goneMargin in favor of guidelines
  Toggl.Droid/Resources/layout/MainLogCell.axml
Labels: android, glitch

#6624 Fix tag symbol not disappearing after tag creation
  Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
Labels: bug, foundation, ios

#6627 Fix fragment not added crash
  Toggl.Droid/Activities/MainTabBarActivity.cs
Labels: android

#6632 ✨ Implement the list to show the report segments
  Toggl.Core.Tests/UI/ViewModels/Reports/SummaryReportElementTests.cs
  Toggl.Core.UI/ViewModels/Reports/IReportElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartDonutElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportElementBase.cs
  Toggl.Core.UI/ViewModels/Reports/ReportErrorElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportNoDataElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportSummaryElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportWorkspaceNameElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/SummaryReportElement.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
  Toggl.Droid/Adapters/ReportsRecyclerAdapterOld.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Resources/layout/ReportEmptyElement.axml
  Toggl.Droid/Resources/layout/ReportWorkspaceNameElement.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/Reports/ReportElementViewHolder.cs
  Toggl.Droid/ViewHolders/Reports/ReportEmptyElementViewHolder.cs
  Toggl.Droid/ViewHolders/Reports/ReportWorkspaceNameViewHolder.cs
  Toggl.Droid/ViewHolders/ReportsWorkspaceNameViewHolderOld.cs
Labels: android

#6638 January campaign: Add storage methods
  Toggl.Storage/Settings/IOnboardingStorage.cs
  Toggl.Storage/Settings/SettingsStorage.cs
Labels: android, ios

#6641 January campaign: Analytic events
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: android, ios

#6636 Fix copy of the signup terms
  Toggl.Core.Tests/ResourcesTests.cs
  Toggl.Core.UI/ViewModels/TermsOfServiceViewModel.cs
  Toggl.Droid/Extensions/SpannableExtensions.cs
  Toggl.Droid/Fragments/TermsOfServiceFragment.ViewBinds.cs
  Toggl.Droid/Fragments/TermsOfServiceFragment.cs
  Toggl.Droid/Resources/layout/TermsOfServiceFragment.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/TermsOfServiceViewController.cs
Labels: android, ios

#6637 January campaign: Remote config
  Toggl.Core.Tests/Services/UpdateRemoteConfigCacheServiceTests.cs
  Toggl.Core/Extensions/RemoteConfigExtensions.cs
  Toggl.Core/Services/IFetchRemoteConfigService.cs
  Toggl.Core/Services/IRemoteConfigService.cs
  Toggl.Core/Services/IUpdateRemoteConfigCacheService.cs
  Toggl.Core/Services/RemoteConfigService.cs
  Toggl.Core/Services/UpdateRemoteConfigCacheService.cs
  Toggl.Droid/Resources/xml/RemoteConfigDefaults.xml
  Toggl.Droid/Services/FetchRemoteConfigServiceAndroid.cs
  Toggl.Shared.Tests/January2020CampaignConfigurationTests.cs
  Toggl.Shared/January2020CampaignConfiguration.cs
  Toggl.iOS/RemoteConfigDefaults.plist
  Toggl.iOS/Services/FetchRemoteConfigServiceIos.cs
Labels: android, ios

#6648 Fix background color for tasks
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTaskCell.axml
Labels: android

#6650 Disable FCM in debug builds on iOS
  Toggl.iOS/Services/PushNotificationsTokenServiceIos.cs
  Toggl.iOS/Startup/AppDelegate.PushNotifications.cs
Labels: ios

#6643 January campaign: View Model
  Toggl.Core.Tests/UI/ViewModels/January2020CampaignViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/January2020CampaignViewModel.cs
Labels: android, ios

#6651 Update docs to display correct links to translation issue templates
  docs/internationalization/how-to-contribute-with-translations.md
  docs/internationalization/localization-framework.md
Labels: process

#6654 January campaign: A/B campaign message
  Toggl.Core.UI/ViewModels/January2020CampaignViewModel.cs
Labels: android, ios

#6561 Android 2.7 - Hanakazura (花かずら)
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/layout/MainLogCell.axml
Labels: android, release

#6535 iOS 2.7 - Honeydew
  Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Core.UI/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Info.plist
Labels: ios, release

#6669 ✨ Report Donut Chart Element
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartDonutElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
Labels: foundation

#6645 January campaign: Navigate to the popup
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
Labels: android, ios

#6592 Fix null description problems in the UI
  Toggl.Core.Tests/Models/TimeEntriesTests.cs
  Toggl.Core/Models/FoundationConstructors.cs
Labels: crash

#6659 January campaign: Android
  Toggl.Droid/Fragments/January2020CampaignFragment.cs
  Toggl.Droid/Presentation/DialogFragmentPresenter.cs
  Toggl.Droid/Resources/drawable-hdpi/pinata.png
  Toggl.Droid/Resources/drawable-mdpi/pinata.png
  Toggl.Droid/Resources/drawable-xhdpi/pinata.png
  Toggl.Droid/Resources/drawable-xxhdpi/pinata.png
  Toggl.Droid/Resources/drawable-xxxhdpi/pinata.png
  Toggl.Droid/Resources/layout/January2020CampaignFragment.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: android

#6653 January campaign: iOS
  Toggl.iOS/Presentation/ModalDialogPresenter.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/pinata.png
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/pinata@2x.png
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/pinata@3x.png
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/January2020CampaignViewController.cs
  Toggl.iOS/ViewControllers/January2020CampaignViewController.designer.cs
  Toggl.iOS/ViewControllers/January2020CampaignViewController.xib
Labels: ios

#6652 Migrate to C# 8
  Toggl.Core.Tests.Sync/Toggl.Core.Tests.Sync.csproj
  Toggl.Core.Tests/Toggl.Core.Tests.csproj
  Toggl.Core.UI/Toggl.Core.UI.csproj
  Toggl.Core.UI/Transformations/TimeEntriesGroupsFlattening.cs
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarMenuAction.cs
  Toggl.Core.UI/ViewModels/Selectable/SelectableClientViewModel.cs
  Toggl.Core.UI/ViewModels/Selectable/SelectableColorViewModel.cs
  Toggl.Core.UI/ViewModels/Selectable/SelectableCountryViewModel.cs
  Toggl.Core.UI/ViewModels/Selectable/SelectableTagViewModel.cs
  Toggl.Core.UI/ViewModels/Selectable/SelectableWorkspaceViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/GroupId.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Core/Autocomplete/Suggestions/NoEntityInfoMessage.cs
  Toggl.Core/Autocomplete/Suggestions/ProjectSuggestion.cs
  Toggl.Core/Autocomplete/Suggestions/QuerySymbolSuggestion.cs
  Toggl.Core/Autocomplete/Suggestions/TagSuggestion.cs
  Toggl.Core/Autocomplete/Suggestions/TaskSuggestion.cs
  Toggl.Core/Autocomplete/Suggestions/TimeEntrySuggestion.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
  Toggl.Core/Toggl.Core.csproj
  Toggl.Droid/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Networking.Tests.Integration/Toggl.Networking.Tests.Integration.csproj
  Toggl.Networking.Tests/Toggl.Networking.Tests.csproj
  Toggl.Networking/Toggl.Networking.csproj
  Toggl.Shared.Tests/EnsureTests.cs
  Toggl.Shared.Tests/Toggl.Shared.Tests.csproj
  Toggl.Shared/CalendarMonth.cs
  Toggl.Shared/Color.cs
  Toggl.Shared/DateTimeOffsetRange.cs
  Toggl.Shared/Extensions/EnumerableExtensions.cs
  Toggl.Shared/HashCode.cs
  Toggl.Shared/Toggl.Shared.csproj
  Toggl.Storage.Realm/Toggl.Storage.Realm.csproj
  Toggl.Storage.Tests/Settings/SettingsStorageTests.cs
  Toggl.Storage.Tests/Toggl.Storage.Tests.csproj
  Toggl.Storage/Toggl.Storage.csproj
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.csproj
  Toggl.iOS.IntentBinding/Toggl.iOS.IntentBinding.csproj
  Toggl.iOS.Shared/Toggl.iOS.Shared.csproj
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS/Toggl.iOS.csproj
  build.cake
Labels: foundation

#6670 Create and inject the services needed for the queries project
  Toggl.Core.Tests.Sync/Helpers/Storage.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Storage.Realm/Database.cs
  Toggl.Storage.Realm/Queries/RealmQueryFactory.cs
  Toggl.Storage.Realm/RealmConfigurator.cs
  Toggl.Storage/Queries/IQuery.cs
  Toggl.Storage/Queries/IQueryFactory.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
Labels: foundation, storage

#6595 Start button animation while being pressed
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: ios

#6588 Move the eye icon into the password text field
  Toggl.iOS/ViewControllers/SignupViewController.cs
  Toggl.iOS/ViewControllers/SignupViewController.designer.cs
  Toggl.iOS/ViewControllers/SignupViewController.xib
Labels: ios

#6673 Fix crash when trying to access non existent calendar item's contextual menu
  Toggl.Droid/Views/Calendar/CalendarDayView.cs
Labels: android, bug

#6671 Add i18n section to the PR template
  .github/pull_request_template.md
Labels: process

#6678 Add base class for query tests
  Toggl.Storage.Tests/Realm/Queries/QueryTests.cs
Labels: tests

#6681 Fix settings insets
  Toggl.Droid/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Droid/Activities/SettingsActivity.cs
  Toggl.Droid/Resources/layout/SettingsActivity.axml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#6683 📐 Vertically center TE creation text edit
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
Labels: android

#6685 📐 Fix bottom inset for duration card
  Toggl.Droid/Activities/StartTimeEntryActivity.ViewBinds.cs
Labels: android

#6633 Update widget when PN triggered sync updates the database
  Toggl.iOS.Shared/SharedStorage.TimeEntries.cs
  Toggl.iOS.Shared/SharedStorage.cs
  Toggl.iOS.TimerWidgetExtension/TodayViewController.cs
Labels: ios

#6688 Clarify manual release tests for onboarding steps
  .github/ISSUE_TEMPLATE/e-manual-test-template.md
Labels: process

#6539 Consolidate Widgets packages
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/packages.config
  Toggl.Networking/Toggl.Networking.csproj
  Toggl.iOS.Shared/Toggl.iOS.Shared.csproj
  Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS.SiriExtension/packages.config
  Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj
  Toggl.iOS.TimerWidgetExtension/packages.config
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/packages.config
Labels: dependencies, ios

#6680 Add bar chart elements
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
Labels: foundation

#6702 💚 Fix donut grouping and add tests
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportProjectsDonutChartElementTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
Labels: foundation

#6705 Make Japanese localization selection less strict
  Toggl.Core.Tests/ResourcesTests.cs
  Toggl.Core.Tests/UI/AppStartTests.cs
  Toggl.Core.Tests/UI/DiscardCultureChanges.cs
  Toggl.Core.UI/AppStart.cs
  Toggl.Core/Helper/Constants.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Toggl.Shared.csproj
Labels: android, foundation, ios

#6640 January campaign: Shared code + iOS UI + Android UI
  Toggl.Core.Tests/Services/UpdateRemoteConfigCacheServiceTests.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/January2020CampaignViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/January2020CampaignViewModel.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Extensions/RemoteConfigExtensions.cs
  Toggl.Core/Services/IFetchRemoteConfigService.cs
  Toggl.Core/Services/IRemoteConfigService.cs
  Toggl.Core/Services/IUpdateRemoteConfigCacheService.cs
  Toggl.Core/Services/RemoteConfigService.cs
  Toggl.Core/Services/UpdateRemoteConfigCacheService.cs
  Toggl.Droid/Fragments/January2020CampaignFragment.cs
  Toggl.Droid/Presentation/DialogFragmentPresenter.cs
  Toggl.Droid/Resources/drawable-hdpi/pinata.png
  Toggl.Droid/Resources/drawable-mdpi/pinata.png
  Toggl.Droid/Resources/drawable-xhdpi/pinata.png
  Toggl.Droid/Resources/drawable-xxhdpi/pinata.png
  Toggl.Droid/Resources/drawable-xxxhdpi/pinata.png
  Toggl.Droid/Resources/layout/January2020CampaignFragment.axml
  Toggl.Droid/Resources/xml/RemoteConfigDefaults.xml
  Toggl.Droid/Services/FetchRemoteConfigServiceAndroid.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Shared.Tests/January2020CampaignConfigurationTests.cs
  Toggl.Shared/January2020CampaignConfiguration.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/Settings/IOnboardingStorage.cs
  Toggl.Storage/Settings/SettingsStorage.cs
  Toggl.iOS/Presentation/ModalDialogPresenter.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/RemoteConfigDefaults.plist
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/pinata.png
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/pinata@2x.png
  Toggl.iOS/Resources/Images.xcassets/pinata.imageset/pinata@3x.png
  Toggl.iOS/Services/FetchRemoteConfigServiceIos.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/January2020CampaignViewController.cs
  Toggl.iOS/ViewControllers/January2020CampaignViewController.designer.cs
  Toggl.iOS/ViewControllers/January2020CampaignViewController.xib
Labels: android, ios

#6711 Fix widget analytics events handling
  Toggl.iOS.Shared/SharedStorage.cs
Labels: ios

#6704 Possible fix for a crash in the calendar
  Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs
Labels: bug, ios

#6644 Reports: A new reports view controller
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsErrorCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsErrorCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsErrorCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsNoDataCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsNoDataCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsNoDataCollectionViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsSummaryCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsSummaryCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsSummaryCollectionViewCell.xib
  Toggl.iOS/Presentation/RootPresenter.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/MainTabBarController.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/ViewControllers/ReportsViewController.designer.cs
  Toggl.iOS/ViewControllers/ReportsViewController.xib
  Toggl.iOS/ViewControllers/ReportsViewControllerOld.cs
  Toggl.iOS/ViewControllers/ReportsViewControllerOld.designer.cs
  Toggl.iOS/ViewControllers/ReportsViewControllerOld.xib
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewCompactLayout.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewRegularLayout.cs
Labels: ios

#6580 Fix the problem with holding backspace in the start view
  Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Core/Autocomplete/TextFieldInfo.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
  Toggl.iOS/Autocomplete/AutocompleteExtensions.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: glitch, ios

#6710 ✅ Add tests for bar chart elements
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportBarChartElementTests.cs
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportProjectsBarChartElementTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportBarChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsBarChartElement.cs
Labels: foundation

#6720 Implement a hacky yet efficient solution to the autocorrect issue
  Toggl.iOS/Extensions/TextViewExtensions.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#6715 🍩 Add DonutChart Android UI control
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportDonutChartElementTests.cs
  Toggl.Core.UI/Helper/Colors.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartLegendItemElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsDonutChartElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsDonutChartLegendItemElement.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
  Toggl.Droid/Resources/layout/ReportDonutChartDonutElement.axml
  Toggl.Droid/Resources/layout/ReportDonutLegendItem.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/Reports/ReportDonutChartDonutViewHolder.cs
  Toggl.Droid/ViewHolders/Reports/ReportDonutChartLegendItemViewHolder.cs
  Toggl.Droid/Views/DonutChartView.cs
Labels: android

#6712 Remove strings that are only used in Analytics
  Toggl.Core.Tests/Sync/States/Push/CreateEntityStateTests.cs
  Toggl.Core.Tests/Sync/States/Push/DeleteEntityStateTests.cs
  Toggl.Core.Tests/Sync/States/Push/UpdateEntityStateTests.cs
  Toggl.Core/Sync/States/Push/BasePushEntityState.cs
  Toggl.Core/Sync/States/Push/CreateEntityState.cs
  Toggl.Core/Sync/States/Push/DeleteEntityState.cs
  Toggl.Core/Sync/States/Push/UpdateEntityState.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
Labels: foundation, metrics

#6730 Fix potential memory issues
  Toggl.Droid/Views/DonutChartView.cs
Labels: android

#6700 Firebase Remote Config: Avoid using ActivateFetched which is obsolete
  Toggl.iOS/Services/FetchRemoteConfigServiceIos.cs
Labels: ios

#6687 Android 2.7.1 - Hanakazura (花かずら) hotfix
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#6725 ✨ Add No data and Error states
  Toggl.Core.UI/ViewModels/Reports/ReportErrorElement.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
  Toggl.Droid/Resources/layout/ReportErrorElement.axml
  Toggl.Droid/Resources/layout/ReportNoDataElement.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/Reports/ReportErrorElementViewHolder.cs
  Toggl.Droid/ViewHolders/Reports/ReportNoDataElementViewHolder.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: android

#6719 📊 Reports: new iOS report summary cell
  Toggl.iOS/Cells/Reports/ReportsSummaryCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsSummaryCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsSummaryCollectionViewCell.xib
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
Labels: ios

#6731 Fix start view bottom bar
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: bug, ios

#6732 Load calendar views lazily
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.ViewBinds.cs
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.cs
  Toggl.Droid/Fragments/CalendarFragment.cs
  Toggl.Droid/Resources/layout/CalendarDayFragmentPage.axml
  Toggl.Droid/Resources/layout/CalendarDayViewPageFragmentContextualMenu.axml
  Toggl.Droid/Resources/layout/CalendarDayViewPageFragmentDayView.axml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#6738 🐛 Fix Snackbar bottom padding
  Toggl.Droid/Extensions/SnackbarExtensions.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Toggl.Droid.csproj
Labels: android
