Repository toggl/mobileapp, pull requests merged in 2019-06, with the labels that each got.

#5201 📐 Tweak some UI to look normal on large font/display settings
  Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml
  Toggl.Droid/Resources/layout/StartTimeEntryActivityTimeEntryCell.axml
  Toggl.Droid/Views/BarChartView.cs
Labels: android

#5299 Update suggestions UI on Android
  Toggl.Core/Suggestions/Suggestion.cs
  Toggl.Droid/Adapters/MainSuggestionsRecyclerAdapter.cs
  Toggl.Droid/Resources/layout/MainSuggestionsCard.axml
  Toggl.Droid/Resources/layout/MainSuggestionsCardDescriptionOnly.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/MainLogSuggestionItemViewHolder.cs
  Toggl.Droid/ViewHolders/MainLogSuggestionsListViewHolder.cs
Labels: android

#5280 iOS push notifications setup
  Toggl.iOS/Entitlements.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/Startup/AppDelegate.Notifications.cs
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/Toggl.iOS.csproj
  build.cake
Labels: ios

#5244 Do a fresh start when re-opening the app after the application process was killed
  Toggl.Droid/Activities/AboutActivity.cs
  Toggl.Droid/Activities/BrowserActivity.cs
  Toggl.Droid/Activities/CalendarSettingsActivity.cs
  Toggl.Droid/Activities/EditDurationActivity.cs
  Toggl.Droid/Activities/EditProjectActivity.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.cs
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Activities/OutdatedAppActivity.cs
  Toggl.Droid/Activities/ReactiveActivity.cs
  Toggl.Droid/Activities/SelectClientActivity.cs
  Toggl.Droid/Activities/SelectCountryActivity.cs
  Toggl.Droid/Activities/SelectProjectActivity.cs
  Toggl.Droid/Activities/SelectTagsActivity.cs
  Toggl.Droid/Activities/SendFeedbackActivity.cs
  Toggl.Droid/Activities/SignUpActivity.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
  Toggl.Droid/Activities/TokenResetActivity.cs
Labels: android, crash, mvexit

#5304 🚧 Calendar suggestion provider
  Toggl.Core.Tests/Interactors/Suggestions/CalendarSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionsInteractorTests.cs
  Toggl.Core/Interactors/InteractorFactory.Suggestions.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
  Toggl.Core/Suggestions/CalendarSuggestionProvider.cs
  Toggl.Core/Suggestions/Suggestion.cs
  Toggl.Core/Suggestions/SuggestionProviderType.cs
Labels: foundation

#5305 🚧Add debug helper for suggstion
  Toggl.Core/Suggestions/Suggestion.cs
  Toggl.Droid/ViewHolders/MainLogSuggestionItemViewHolder.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
Labels: android, foundation, ios

#5303 Implement IPushNotificationsTokenService for droid
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Services/PushNotificationsTokenServiceAndroid.cs
  Toggl.Droid/Services/TogglFirebaseIIDService.cs
  Toggl.Droid/Services/TogglFirebaseMessagingService.cs
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#5308 Fix Siri intent for reports with date range
  Toggl.Core.UI/Navigation/IPresentationChange.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.iOS/Presentation/RootPresenter.cs
  Toggl.iOS/Startup/AppDelegate.Siri.cs
Labels: ios, mvexit

#5315 Make SetTheme the first call in SignupActivity
  Toggl.Droid/Activities/SignUpActivity.cs
Labels: android

#5306 Allow non-descriptive TEs in suggestions
  Toggl.Core.Tests/Interactors/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
Labels: foundation

#5321 🚧 Enforce provider type
  Toggl.Core.Tests/Interactors/TimeEntry/CreateTimeEntryInteractorTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core/Suggestions/CalendarSuggestionProvider.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
  Toggl.Core/Suggestions/Suggestion.cs
Labels: foundation

#5313 Improvements in AppStart class
  Toggl.Core.Tests/UI/AppStartTests.cs
  Toggl.Core.UI/AccessLevel.cs
  Toggl.Core.UI/AppStart.cs
  Toggl.Droid/Startup/SplashScreen.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: foundation, mvexit

#5310 Add generic sync interactor
  Toggl.Core.Tests/Interactors/Sync/RunSyncInteractorTests.cs
  Toggl.Core/Diagnostics/MeasuredOperation.cs
  Toggl.Core/Interactors/InteractorFactory.Sync.cs
  Toggl.Core/Interactors/Sync/RunSyncInteractor.cs
Labels: foundation

#5327 Reflect new release names in checklist
  .github/ISSUE_TEMPLATE/e-release-checklist.md
Labels: mvexit

#5316 Add SubscribeToPushNotificationsInteractor
  Toggl.Core.Tests/Interactors/PushNotifications/SubscribeToPushNotificationsInteractorTests.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.PushNotifications.cs
  Toggl.Core/Interactors/PushNotifications/PushNotificationTokenKeys.cs
  Toggl.Core/Interactors/PushNotifications/SubscribeToPushNotificationsInteractor.cs
Labels: foundation

#5323 Add continue time entry interactor
  Toggl.Core.Tests/Interactors/TimeEntry/ContinueTimeEntryInteractorTests.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/ContinueTimeEntryOrigin.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Interactors/TimeEntry/ContinueTimeEntryInteractor.cs
Labels: foundation, metrics

#5334 Resubscribe to pushes on token changes
  Toggl.Droid/Services/TogglFirebaseIIDService.cs
Labels: android

#5287 iOS release 1.22 (Terminus)
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
Labels: release

#5341 Track continue time entry
  Toggl.Core.Tests/Interactors/TimeEntry/ContinueTimeEntryFromMainLogInteractorTests.cs
  Toggl.Core.Tests/UI/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Core.Tests/UI/ViewModels/LogItemViewModelTests.cs
  Toggl.Core.UI/Extensions/TimeEntryExtensions.cs
  Toggl.Core.UI/Helper/ContinueTimeEntryInfo.cs
  Toggl.Core.UI/Transformations/TimeEntriesGroupsFlattening.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesViewModel.cs
  Toggl.Core/Analytics/ContinueTimeEntryOrigin.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Core/Interactors/TimeEntry/ContinueTimeEntryFromMainLogInteractor.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: android, foundation, ios, metrics

#5234 Document Siri Workflows
  .firebaserc
  docs/siri/create-new-intent.md
  docs/siri/update-workflows.md
  docs/siri/workflow-screen.png
  firebase.json
  public/README.md
  public/adhoc/dictate.shortcut
  public/adhoc/done.shortcut
  public/adhoc/focus.shortcut
  public/adhoc/pomodoro.shortcut
  public/dev/dictate.shortcut
  public/dev/done.shortcut
  public/dev/focus.shortcut
  public/dev/pomodoro.shortcut
  public/dev/workflows.json
  public/dictate.shortcut
  public/done.shortcut
  public/focus.shortcut
  public/pomodoro.shortcut
  public/workflows.json
Labels: ios

#5346 Decompose UserAccessManager.CheckIfLoggedIn responsibilities
  Toggl.Core.Tests/UI/AppStartTests.cs
  Toggl.Core.Tests/UserAccessManager/UserAccessManagerTests.cs
  Toggl.Core.UI/AppStart.cs
  Toggl.Core/UserAccessManager/IUserAccessManager.cs
  Toggl.Core/UserAccessManager/UserAccessManager.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: android, foundation, ios, refactoring

#5322 Suggestions analytics
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLocator.cs
  Toggl.Core.UI/Toggl.Core.UI.csproj
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/CalendarSuggestionContinuedEvent.cs
  Toggl.Core/Analytics/CalendarSuggestionProviderState.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Analytics/SuggestionPresentedEvent.cs
Labels: foundation

#5336 API endpoint: POST FCM token
  Toggl.Networking.Tests.Integration/PushServicesApiTests.cs
  Toggl.Networking/ApiClients/PushServicesApi.cs
  Toggl.Networking/Network/Endpoints/PushServicesEndpoints.cs
Labels: api

#5337 API endpoint: unsubscribe from push notifications
  Toggl.Networking.Tests.Integration/PushServicesApiTests.cs
  Toggl.Networking/ApiClients/PushServicesApi.cs
Labels: api

#5338 🚧Remove duplicate suggestions
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionProvidersInteractorTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionsInteractorTests.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.Suggestions.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionProvidersInteractor.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
Labels: foundation

#5350 Use only synced TEs for suggestions
  Toggl.Core.Tests/Interactors/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
Labels: foundation

#5328 Sync FCM token
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests/Sync/States/Push/SyncPushNotificationsTokenStateTests.cs
  Toggl.Core.Tests/Sync/SyncGraphTests.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Core/Sync/States/Push/SyncPushNotificationsTokenState.cs
  Toggl.Core/TogglSyncManagerFactory.cs
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.cs
Labels: sync

#5333 Sync on droid pushes
  Toggl.Droid/LinkerPleaseInclude.cs
  Toggl.Droid/Services/TogglFirebaseMessagingService.cs
  Toggl.Droid/Startup/ApplicationLifecycleObserver.cs
  Toggl.Droid/Startup/SplashScreen.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/packages.config
Labels: android

#5366 🔍 Track distinct workspace count in suggestions presented
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Core/Analytics/SuggestionsPresentedEvent.cs
Labels: foundation

#5368 Re-implement sync of FCM token
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests/Properties/AssemblyInfo.cs
  Toggl.Core.Tests/Sync/States/Push/SyncPushNotificationsTokenStateTests.cs
  Toggl.Core.Tests/Sync/SyncGraphTests.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Core/Interactors/PushNotifications/SubscribeToPushNotificationsInteractor.cs
  Toggl.Core/Sync/States/Push/SyncPushNotificationsTokenState.cs
  Toggl.Core/TogglSyncManagerFactory.cs
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.cs
Labels: sync

#5376 Fix empty view in reports while loading
  Toggl.iOS/ViewControllers/ReportsViewController.cs
Labels: ios

#5369 🚧Add stopwatch to most used suggestion provider
  Toggl.Core.Tests/Interactors/Suggestions/MostUsedTimeEntrySuggestionProviderTests.cs
  Toggl.Core/Diagnostics/MeasuredOperation.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionProvidersInteractor.cs
  Toggl.Core/Suggestions/MostUsedTimeEntrySuggestionProvider.cs
Labels: foundation

#5384 Fix sync graph generation
  Toggl.Core.Tests/Properties/AssemblyInfo.cs
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.cs
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.csproj
Labels: blocking

#5365 Display project & task placeholders
  Toggl.Core.Tests/UI/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Core.Tests/UI/ViewModels/EditTimeEntryViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/LogItemViewModelTests.cs
  Toggl.Core.UI/Extensions/TimeEntryExtensions.cs
  Toggl.Core.UI/Transformations/TimeEntriesGroupsFlattening.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/SiriShortcutsCustomTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/TimeEntriesLog/LogItemViewModel.cs
  Toggl.Core/Extensions/ThreadSafeExtensions.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Adapters/MainRecyclerAdapter.cs
  Toggl.Droid/Extensions/TimeEntryExtensions.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Resources/drawable/text_placeholder.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHelpers/TimeEntryViewData.cs
  Toggl.Droid/Views/VerticallyCenteredImageSpan.cs
Labels: android

#5370 Add analytics to push initiated syncs
  Toggl.Core.Tests/Interactors/Sync/RunSyncInteractorTests.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Diagnostics/MeasuredOperation.cs
  Toggl.Core/Interactors/InteractorFactory.Sync.cs
  Toggl.Core/Interactors/Sync/PushNotificationSyncSourceState.cs
  Toggl.Core/Interactors/Sync/RunSyncInteractor.cs
  Toggl.Core/Sync/States/PullTimeEntries/TimeEntriesAnalyticsState.cs
  Toggl.Core/TogglSyncManagerFactory.cs
Labels: wip

#5354 Android 2.0 Release Candidate 2 - Alfajor
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/PasteFromClipboardViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/Siri/SiriShortcutsCustomTimeEntryViewModel.cs
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#5379 Resend FCM token every N days
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests/Interactors/PushNotifications/SubscribeToPushNotificationsInteractorTests.cs
  Toggl.Core.Tests/Sync/States/Push/SyncPushNotificationsTokenStateTests.cs
  Toggl.Core.Tests/Sync/SyncGraphTests.cs
  Toggl.Core/Interactors/InteractorFactory.PushNotifications.cs
  Toggl.Core/Interactors/PushNotifications/PushNotificationTokenKeys.cs
  Toggl.Core/Interactors/PushNotifications/SubscribeToPushNotificationsInteractor.cs
  Toggl.Core/Sync/States/Push/SyncPushNotificationsTokenState.cs
  Toggl.Core/TogglSyncManagerFactory.cs
Labels: sync

#5374 ⏱ Recalculate suggestions periodically
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: foundation

#5395 Move bindings after views attachment
  Toggl.Droid/Fragments/CalendarFragment.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
Labels: android

#5377 Use remote when deciding to handle push notifications
  Toggl.Core/Extensions/RemoteConfigExtensions.cs
  Toggl.Core/Services/IRemoteConfigService.cs
  Toggl.Droid/Resources/xml/RemoteConfigDefaults.xml
  Toggl.Droid/Services/RemoteConfigServiceAndroid.cs
  Toggl.Droid/Services/TogglFirebaseMessagingService.cs
  Toggl.Shared/PushNotificationsConfiguration.cs
  Toggl.iOS/RemoteConfigDefaults.plist
  Toggl.iOS/Services/RemoteConfigServiceIos.cs
  Toggl.iOS/Startup/AppDelegate.Notifications.cs
Labels: android, ios

#5386 Essentials browsing
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.Tests/UI/ViewModels/AboutViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/BrowserViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/OutdatedAppViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SettingsViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/TermsOfServiceViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/Parameters/BrowserParameters.cs
  Toggl.Core.UI/Services/IBrowserService.cs
  Toggl.Core.UI/UIDependencyContainer.cs
  Toggl.Core.UI/ViewModels/BrowserViewModel.cs
  Toggl.Core.UI/ViewModels/OutdatedAppViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/AboutViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Core.UI/ViewModels/TermsOfServiceViewModel.cs
  Toggl.Core/BasePlatformInfo.cs
  Toggl.Core/IPlatformInfo.cs
  Toggl.Droid/Activities/BrowserActivity.cs
  Toggl.Droid/PlatformInfoAndroid.cs
  Toggl.Droid/Presentation/ActivityPresenter.cs
  Toggl.Droid/Resources/layout/BrowserActivity.axml
  Toggl.Droid/Services/BrowserServiceAndroid.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/PlatformInfoIos.cs
  Toggl.iOS/Presentation/NavigationPresenter.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/Services/BrowserServiceIos.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/BrowserViewController.cs
Labels: android, foundation, ios

#5398 Fix EditTimeEntry OnStop crash
  Toggl.Droid/Activities/EditTimeEntryActivity.Onboarding.cs
Labels: android, crash

#5396 Run ui updates in the main thread
  Toggl.Droid/Adapters/BaseRecyclerAdapter.cs
  Toggl.Droid/Adapters/ReportsCalendarPagerAdapter.cs
Labels: android

#5415 Display placeholders for projects and tasks
  Toggl.iOS/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.iOS/Transformations/ProjectTaskClientToAttributedString.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
Labels: ios

#5420 Replace app icons again
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_1024pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_20pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_20pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_20pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_29pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_29pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_29pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_40pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_40pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_40pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_60pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_60pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_76pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_76pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_83.5@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_1024pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_20pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_20pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_20pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_29pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_29pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_29pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_40pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_40pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_40pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_60pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_60pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_76pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_76pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_83.5@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-114x114.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-120x120.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-152x152.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-167x167.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-180x180.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-58x58.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-80x80.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-87x87.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/toggl-app-icon-1024x1024.png
Labels: ios

#5423 Fix select no default workspace nav
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Droid/Fragments/SelectDefaultWorkspaceFragment.cs
Labels: android, foundation

#5416 Remove throttling from reports calendar
  Toggl.Droid/Fragments/ReportsFragment.cs
Labels: android

#5421 Update tag names in release checklist
  .github/ISSUE_TEMPLATE/e-release-checklist.md
Labels: process

#5408 Android 2.0.1 - Alfajor hotfix
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.Onboarding.cs
  Toggl.Droid/Adapters/BaseRecyclerAdapter.cs
  Toggl.Droid/Adapters/ReportsCalendarPagerAdapter.cs
  Toggl.Droid/Fragments/CalendarFragment.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Fragments/SelectDefaultWorkspaceFragment.cs
  Toggl.Droid/Fragments/SettingsFragment.cs
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#5412 🚧 Add userCalendar filtering and sort by offset ABS to calendar suggestions provider
  Toggl.Core.Tests/Interactors/Suggestions/CalendarSuggestionProviderTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionProvidersInteractorTests.cs
  Toggl.Core/Interactors/InteractorFactory.Suggestions.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionProvidersInteractor.cs
  Toggl.Core/Suggestions/CalendarSuggestionProvider.cs
Labels: foundation

#5427 Introduce Flatten method
  Toggl.Core.Tests/Interactors/AutocompleteSuggestions/GetProjectsAutocompleteSuggestionsInteractorTests.cs
  Toggl.Core.Tests/Interactors/AutocompleteSuggestions/GetTimeEntriesAutocompleteSuggestionsInteractorTests.cs
  Toggl.Core.Tests/UI/Transformations/TimeEntriesFlatenningTests.cs
  Toggl.Core.UI/Calendar/CalendarLayoutCalculator.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core/DataSources/SingletonDataSource.cs
  Toggl.Core/DataSources/TimeEntriesDataSource.cs
  Toggl.Core/Interactors/Reports/GetProjectSummaryInteractor.cs
  Toggl.Core/Sync/States/CleanUp/DeleteInaccessibleEntityState.cs
  Toggl.Core/Sync/States/CleanUp/DeleteUnnecessaryProjectPlaceholdersState.cs
  Toggl.Core/Sync/States/Pull/DeleteInaccessibleRunningTimeEntryState.cs
  Toggl.Core/Sync/States/Pull/DetectGainingAccessToWorkspacesState.cs
  Toggl.Core/Sync/States/Pull/DetectLosingAccessToWorkspacesState.cs
  Toggl.Core/Sync/States/Pull/MarkWorkspacesAsInaccessibleState.cs
  Toggl.Core/Sync/States/Pull/PersistNewWorkspacesState.cs
  Toggl.Core/Sync/States/Pull/TryFetchInaccessibleProjectsState.cs
  Toggl.Core/Sync/States/Push/MarkEntityAsUnsyncableState.cs
  Toggl.Shared/Extensions/EnumerableExtensions.cs
  Toggl.Shared/Extensions/ReactiveExtensions.cs
  Toggl.Shared/Extensions/RxAction/RxAction.cs
Labels: refactoring

#5430 🚧 Improve suggestion recalculation
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SuggestionsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/SuggestionsViewModel.cs
Labels: foundation

#5399 Restore navigation to AboutViewModel
  Toggl.iOS/Presentation/NavigationPresenter.cs
Labels: glitch, ios

#5378 FCM sync tests
  Toggl.Core.Tests.Sync/ComplexSyncTest.cs
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests.Sync/Helpers/Server.cs
  Toggl.Core.Tests.Sync/Scenarios/LosingAccessToWorkspace/InaccessibleEntitiesOutOfSyncAreNotDeletedInCleanUpLoop.cs
  Toggl.Core.Tests.Sync/Scenarios/LosingAccessToWorkspace/WorkspacesAndRelatedInSyncInaccessibleEntitiesAreDeletedInCleanUpLoop.cs
  Toggl.Core.Tests.Sync/Scenarios/PushNotificationsTokens/PushesTheFirstTokenToTheServer.cs
  Toggl.Core.Tests.Sync/Scenarios/PushNotificationsTokens/PushesTokenToTheServerAgainWhenItChanges.cs
  Toggl.Core.Tests.Sync/Scenarios/PushNotificationsTokens/RemovesInvalidToken.cs
  Toggl.Core.Tests.Sync/Scenarios/SyncLight/FetchAllTimeEntriesAndCreateWorkspacePlaceholderAndDetectNewWorkspaceLater.cs
  Toggl.Core.Tests.Sync/Scenarios/SyncLight/FetchesAllTimeEntries.cs
  Toggl.Core.Tests.Sync/Scenarios/SyncLight/FetchesAllTimeEntriesAndCreatesAllPlaceholders.cs
  Toggl.Core.Tests.Sync/Scenarios/SyncLight/FetchesAllTimeEntriesWithRelationships.cs
  Toggl.Core.Tests.Sync/State/ServerState.cs
  Toggl.Networking.Tests.Integration/PushServicesApiTests.cs
  Toggl.Networking/ApiClients/Interfaces/IPushServicesApi.cs
  Toggl.Networking/ApiClients/PushServicesApi.cs
  Toggl.Networking/Network/Endpoints/PushServicesEndpoints.cs
Labels: sync

#5449 Fix wrongly reporting sync failed to users
  Toggl.Droid/Fragments/MainFragment.cs
Labels: android, glitch

#5411 Handle remote config push notifications subscription
  Toggl.Core.Tests/Interactors/PushNotifications/UnsubscribeFromPushNotificationsInteractorTests.cs
  Toggl.Core.Tests/Interactors/UserAccess/LogoutInteractorTests.cs
  Toggl.Core.Tests/Sync/States/Push/SyncPushNotificationsTokenStateTests.cs
  Toggl.Core.Tests/Sync/SyncGraphTests.cs
  Toggl.Core/Extensions/RemoteConfigExtensions.cs
  Toggl.Core/Interactors/PushNotifications/UnsubscribeFromPushNotificationsInteractor.cs
  Toggl.Core/Sync/States/Push/SyncPushNotificationsTokenState.cs
  Toggl.Core/TogglSyncManagerFactory.cs
  Toggl.Droid/Services/PushNotificationsTokenServiceAndroid.cs
  Toggl.Droid/Services/RemoteConfigServiceAndroid.cs
  Toggl.Droid/Services/TogglFirebaseIIDService.cs
  Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.cs
  Toggl.iOS/Services/RemoteConfigServiceIos.cs
  Toggl.iOS/Startup/AppDelegate.Notifications.cs
Labels: android, foundation, ios, on-hold, sync

#5447 Store dates using unix time
  Toggl.Core/Services/KeyValueStorage.cs
Labels: foundation

#5389 Split ViewModel loading and Initialization
  Toggl.Core.Tests/Generators/ViewModelTypeDataAttribute.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.UI/Navigation/NavigationService.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Droid/Startup/SplashScreen.DeepLink.cs
  Toggl.Droid/Startup/SplashScreen.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: android, foundation, ios, refactoring

#5371 Update AppCenter package
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/packages.config
Labels: ios

#5414 Add links to the Toggl API
  docs/api.md
Labels: api

#5418 Release: Daneel 2.0 - Apple
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_1024pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_20pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_20pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_20pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_29pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_29pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_29pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_40pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_40pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_40pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_60pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_60pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_76pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_76pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-adhoc.appiconset/icon_83.5@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_1024pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_20pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_20pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_20pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_29pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_29pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_29pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_40pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_40pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_40pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_60pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_60pt@3x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_76pt.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_76pt@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon-debug.appiconset/icon_83.5@2x.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-114x114.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-120x120.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-152x152.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-167x167.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-180x180.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-58x58.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-80x80.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-87x87.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/toggl-app-icon-1024x1024.png
  Toggl.iOS/Info.plist
  Toggl.iOS/Presentation/NavigationPresenter.cs
Labels: ios, release

#5458 Fix cake substitutions for iOS adhoc builds
  build.cake
Labels: ios

#5459 📦 Detect the install location
  Toggl.Core.Tests/Interactors/Settings/SendFeedbackInteractorTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/ApplicationInstallLocation.cs
  Toggl.Core/BasePlatformInfo.cs
  Toggl.Core/IPlatformInfo.cs
  Toggl.Core/Interactors/Settings/SendFeedbackInteractor.cs
  Toggl.Droid/PlatformInfoAndroid.cs
Labels: android

#5454 Update playservices droid adhoc cake replacements
  Toggl.Droid/google-services.json
  build.cake
Labels: android

#5468 Fix crash in onboarding step
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: ios

#5451 Sync light refetching: don't sync every time
  Toggl.Core.Tests/Sync/States/PullTimeEntries/CreatePlaceholdersStateTests.cs
  Toggl.Core.Tests/Sync/States/PullTimeEntries/DetectPlaceholdersWereCreatedStateTests.cs
  Toggl.Core/Sync/States/PullTimeEntries/CreatePlaceholdersState.cs
  Toggl.Core/Sync/States/PullTimeEntries/CreatePlaceholdersStateFactory.cs
  Toggl.Core/Sync/States/PullTimeEntries/DetectPlaceholdersWereCreatedState.cs
  Toggl.Core/TogglSyncManagerFactory.cs
Labels: sync

#5455 Schedule push notifications handling
  Toggl.Droid/Extensions/ActivityExtensions.cs
  Toggl.Droid/Helper/ApiAvailability.cs
  Toggl.Droid/Services/JobServicesConstants.cs
  Toggl.Droid/Services/SyncJobService.cs
  Toggl.Droid/Services/TogglFirebaseMessagingService.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#5448 Remove needless code from Scheduler
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Startup/AndroidSchedulerProvider.cs
  Toggl.Droid/Startup/HandlerScheduler.cs
Labels: android

#5478 Fix crash in default workspace fragment
  Toggl.Droid/Fragments/SelectDefaultWorkspaceFragment.ViewBinds.cs
Labels: android

#5482 Fix padding on Lollipop devices
  Toggl.Droid/Fragments/ReactiveDialogFragment.cs
Labels: android, glitch

#5480 Add droid specific push notification docs
  docs/push-notifications.md
Labels: android

#5481 Make fragments undismassible
  Toggl.Droid/Fragments/NoWorkspaceFragment.cs
  Toggl.Droid/Fragments/SelectDefaultWorkspaceFragment.cs
  Toggl.Droid/Presentation/DialogFragmentPresenter.cs
Labels: android, glitch

#5467 Release: iOS 2.0.1 - Apple hotfix
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/Services/IntentDonationService.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.designer.cs
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.xib
Labels: ios, release

#5489 Fix disappearing running/idle notifications
  Toggl.Droid/BroadcastReceivers/SmartAlertCalendarEventBroadcastReceiver.cs
  Toggl.Droid/Services/NotificationServiceAndroid.cs
Labels: android

#5462 Separate remote config reading and update
  Toggl.Core.Tests/Services/BackgroundServiceTests.cs
  Toggl.Core.Tests/Services/UpdateRemoteConfigCacheServiceTests.cs
  Toggl.Core.Tests/Sync/States/Push/SyncPushNotificationsTokenStateTests.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/ViewModels/BaseViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/UIDependencyContainer.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/DependencyContainer.cs
  Toggl.Core/Experiments/RatingViewExperiment.cs
  Toggl.Core/Extensions/RemoteConfigExtensions.cs
  Toggl.Core/Services/BackgroundService.cs
  Toggl.Core/Services/IFetchRemoteConfigService.cs
  Toggl.Core/Services/IRemoteConfigService.cs
  Toggl.Core/Services/IUpdateRemoteConfigCacheService.cs
  Toggl.Core/Services/RemoteConfigService.cs
  Toggl.Core/Services/UpdateRemoteConfigCacheService.cs
  Toggl.Core/Sync/States/Push/SyncPushNotificationsTokenState.cs
  Toggl.Droid/Services/FetchRemoteConfigServiceAndroid.cs
  Toggl.Droid/Services/RemoteConfigServiceAndroid.cs
  Toggl.Droid/Services/SyncJobService.cs
  Toggl.Droid/Services/TogglFirebaseIIDService.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Startup/TogglApplication.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/Services/FetchRemoteConfigServiceIos.cs
  Toggl.iOS/Services/RemoteConfigServiceIos.cs
  Toggl.iOS/Startup/AppDelegate.Notifications.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
  Toggl.iOS/Toggl.iOS.csproj
Labels: android, foundation, ios, refactoring, sync

#5485 🚧 Replace bgImages in walkthrough with code generated images
  Toggl.iOS/Resources/Images.xcassets/bgNoiseBlue.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/bgNoiseBlue.imageset/bgNoiseBlue.png
  Toggl.iOS/Resources/Images.xcassets/bgNoiseBlue.imageset/bgNoiseBlue@2x.png
  Toggl.iOS/Resources/Images.xcassets/bgNoiseBlue.imageset/bgNoiseBlue@3x.png
  Toggl.iOS/Resources/Images.xcassets/bgNoisePurple.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/bgNoisePurple.imageset/bgNoisePurple.png
  Toggl.iOS/Resources/Images.xcassets/bgNoisePurple.imageset/bgNoisePurple@2x.png
  Toggl.iOS/Resources/Images.xcassets/bgNoisePurple.imageset/bgNoisePurple@3x.png
  Toggl.iOS/Resources/Images.xcassets/bgNoiseYellow.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/bgNoiseYellow.imageset/bgNoiseYellow.png
  Toggl.iOS/Resources/Images.xcassets/bgNoiseYellow.imageset/bgNoiseYellow@2x.png
  Toggl.iOS/Resources/Images.xcassets/bgNoiseYellow.imageset/bgNoiseYellow@3x.png
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
  Toggl.iOS/ViewControllers/OnboardingViewController.designer.cs
  Toggl.iOS/ViewControllers/OnboardingViewController.xib
Labels: ios

#5433 Allow app to be installed in an SD card
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android

#5505 💄Suggestion minor fixes
  Toggl.Core/Analytics/CalendarSuggestionContinuedEvent.cs
  Toggl.Core/Analytics/SuggestionsPresentedEvent.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
  Toggl.Core/Suggestions/RandomForestSuggestionProvider.cs
  Toggl.iOS/Views/Suggestions/SuggestionView.cs
Labels: foundation

#5488 Error triggering screen
  Toggl.Droid/DebugHelpers/ErrorTriggeringFragment.cs
  Toggl.Droid/DebugHelpers/ErrorTriggeringFragmentShortcut.cs
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/DebugHelpers/ErrorTriggeringViewController.cs
  Toggl.iOS/DebugHelpers/ErrorTriggeringViewControllerShortcuts.cs
  Toggl.iOS/Toggl.iOS.csproj
Labels: android, ios

#5508 Fix reports reloading
  Toggl.Core.Tests/UI/ViewModels/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
Labels: foundation

#5502 Revamp token reset vc
  Toggl.iOS/ViewControllers/TokenResetViewController.cs
  Toggl.iOS/ViewControllers/TokenResetViewController.designer.cs
  Toggl.iOS/ViewControllers/TokenResetViewController.xib
Labels: ios

#5493 :memo: Improve refactor proposal template
  .github/ISSUE_TEMPLATE/f-refactor-proposal.md
Labels: process
