Repository toggl/mobileapp, pull requests merged in 2019-04, with the labels that each got.

#4832 iPad version: Reports
  Toggl.Daneel/Cells/BaseReportsCardView.cs
  Toggl.Daneel/Presentation/TogglPresenter.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/ReportsCalendarViewController.cs
  Toggl.Daneel/ViewControllers/ReportsCalendarViewController.xib
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.designer.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
  Toggl.Daneel/ViewSources/ReportsCalendarCollectionViewSource.cs
  Toggl.Daneel/ViewSources/ReportsCalendarQuickSelectCollectionViewSource.cs
  Toggl.Daneel/ViewSources/ReportsTableViewSource.cs
  Toggl.Daneel/Views/Reports/ReportsBarChartCardView.cs
  Toggl.Daneel/Views/Reports/ReportsBarChartCardView.designer.cs
  Toggl.Daneel/Views/Reports/ReportsBarChartCardView.xib
  Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.designer.cs
  Toggl.Daneel/Views/Reports/ReportsHeaderView.xib
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.cs
  Toggl.Daneel/Views/Reports/ReportsLegendViewCell.xib
  Toggl.Daneel/Views/Reports/ReportsOverviewCardView.cs
  Toggl.Daneel/Views/Reports/ReportsOverviewCardView.designer.cs
  Toggl.Daneel/Views/Reports/ReportsOverviewCardView.xib
  Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendarViewModel.cs
Labels: ios

#4848 iPad: assorted visual glitch fixes
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewControllers/Settings/NotificationSettingsViewController.xib
Labels: ios

#4768 Release 1.12 - Argon
  Toggl.Giskard/Activities/EditDurationActivity.cs
  Toggl.Giskard/Adapters/BaseSectionedRecyclerAdapter.cs
  Toggl.Giskard/Adapters/ReportsCalendarPagerAdapter.cs
  Toggl.Giskard/Extensions/FloatingActionButtonExtensions.cs
  Toggl.Giskard/Fragments/MainFragment.cs
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Resources/layout/StartTimeEntryActivityNoEntityCell.axml
  Toggl.Giskard/Toggl.Giskard.csproj
  Toggl.Giskard/ViewHolders/StartTimeEntry/TimeEntrySuggestionViewHolder.cs
  Toggl.Giskard/Views/EditDuration/WheelDurationInput.cs
Labels: android, release

#4634 iPad: Timer page cells
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.designer.cs
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/MainViewController.xib
  Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.designer.cs
  Toggl.Daneel/Views/Suggestions/SuggestionView.xib
  Toggl.Daneel/Views/Suggestions/SuggestionsView.cs
  Toggl.Foundation/Extensions/ObservableExtensions.cs
Labels: ios

#4718 iPad: Edit TE Screen
  Toggl.Daneel/Extensions/Reactive/UIViewControllerExtensions.cs
  Toggl.Daneel/Presentation/Transition/ModalPresentationController.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/EditDurationViewController.cs
  Toggl.Daneel/ViewControllers/EditDurationViewController.xib
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.designer.cs
  Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib
  Toggl.Daneel/ViewControllers/SelectClientViewController.cs
  Toggl.Daneel/ViewControllers/SelectProjectViewController.cs
  Toggl.Daneel/ViewControllers/SelectProjectViewController.xib
  Toggl.Daneel/ViewControllers/SelectTagsViewController.cs
  Toggl.Daneel/ViewControllers/SelectWorkspaceViewController.cs
  Toggl.Daneel/ViewSources/ClientTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectProjectTableViewSource.cs
  Toggl.Daneel/ViewSources/SelectTagsTableViewSource.cs
  Toggl.Foundation.MvvmCross/Helper/Color.cs
Labels: ios

#4825 Daneel Release 1.20 - Ifni
  Toggl.Daneel.SiriExtension.UI/Info.plist
  Toggl.Daneel.SiriExtension/Info.plist
  Toggl.Daneel/Info.plist
  Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Labels: ios, release

#4887 📐 Fix labels position
  Toggl.Daneel/Cells/TimeEntriesLog/TimeEntriesLogViewCell.xib
Labels: ios

#4878 Browser view padding
  Toggl.Giskard/Properties/AndroidManifest.xml
  Toggl.Giskard/Resources/layout/BrowserActivity.axml
Labels: android

#4877 Scroll to top when tapping selected Tab
  Toggl.Daneel/Presentation/IScrollableToTop.cs
  Toggl.Daneel/Toggl.Daneel.csproj
  Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.Daneel/ViewControllers/MainTabBarController.cs
  Toggl.Daneel/ViewControllers/MainViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Giskard/Activities/MainTabBarActivity.cs
  Toggl.Giskard/Fragments/CalendarFragment.cs
  Toggl.Giskard/Fragments/MainFragment.cs
  Toggl.Giskard/Fragments/ReportsFragment.cs
  Toggl.Giskard/Fragments/SettingsFragment.ViewBinds.cs
  Toggl.Giskard/Fragments/SettingsFragment.cs
  Toggl.Giskard/Presentation/IScrollableToTop.cs
  Toggl.Giskard/Presentation/TogglPresenter.cs
  Toggl.Giskard/Resources/layout/SettingsFragment.axml
  Toggl.Giskard/Startup/Setup.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, ios

#4892 Fix Android builds on new stack
  Toggl.Giskard/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android, blocking

#4910 Fix Android builds on new stack on 1.13
  Toggl.Giskard/Adapters/Calendar/CalendarAdapter.cs
  Toggl.Giskard/Toggl.Giskard.csproj
Labels: android

#4912 Fix bug in syncing
  Toggl.Daneel/LinkerPleaseInclude.cs
Labels: bug, critical, ios

#4916 Introduce our own navigation service
  Toggl.Core.Tests.Sync/Helpers/AppServices.cs
  Toggl.Core.Tests/TestDependencyContainer.cs
  Toggl.Core.Tests/UI/BaseMvvmCrossTests.cs
  Toggl.Core.Tests/UI/Services/ErrorHandlingServiceTests.cs
  Toggl.Core.Tests/UI/ViewModelLocatorTests.cs
  Toggl.Core.Tests/UI/ViewModels/SelectDateFormatViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SelectUserCalendarsViewModelBaseTests.cs
  Toggl.Core.UI/App.cs
  Toggl.Core.UI/Navigation/INavigationService.cs
  Toggl.Core.UI/Navigation/NavigationService.cs
  Toggl.Core.UI/Navigation/ViewModelLocator.cs
  Toggl.Core.UI/Services/ErrorHandlingService.cs
  Toggl.Core.UI/UIDependencyContainer.cs
  Toggl.Core.UI/ViewModels/BrowserViewModel.cs
  Toggl.Core.UI/ViewModels/Calendar/CalendarPermissionDeniedViewModel.cs
  Toggl.Core.UI/ViewModels/Calendar/CalendarViewModel.cs
  Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModel.cs
  Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs
  Toggl.Core.UI/ViewModels/EditDurationViewModel.cs
  Toggl.Core.UI/ViewModels/EditProjectViewModel.cs
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/ForgotPasswordViewModel.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core.UI/ViewModels/NoWorkspaceViewModel.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Core.UI/ViewModels/RatingViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Core.UI/ViewModels/SelectBeginningOfWeekViewModel.cs
  Toggl.Core.UI/ViewModels/SelectClientViewModel.cs
  Toggl.Core.UI/ViewModels/SelectColorViewModel.cs
  Toggl.Core.UI/ViewModels/SelectCountryViewModel.cs
  Toggl.Core.UI/ViewModels/SelectDateFormatViewModel.cs
  Toggl.Core.UI/ViewModels/SelectDateTimeViewModel.cs
  Toggl.Core.UI/ViewModels/SelectDefaultWorkspaceViewModel.cs
  Toggl.Core.UI/ViewModels/SelectDurationFormatViewModel.cs
  Toggl.Core.UI/ViewModels/SelectProjectViewModel.cs
  Toggl.Core.UI/ViewModels/SelectTagsViewModel.cs
  Toggl.Core.UI/ViewModels/SelectWorkspaceViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/AboutViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/CalendarSettingsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/NotificationSettingsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SendFeedbackViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Core.UI/ViewModels/Settings/UpcomingEventsNotificationSettingsViewModel.cs
  Toggl.Core.UI/ViewModels/SignupViewModel.cs
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Core.UI/ViewModels/TermsOfServiceViewModel.cs
  Toggl.Core.UI/ViewModels/TokenResetViewModel.cs
  Toggl.Daneel/Startup/AppDelegate.cs
  Toggl.Daneel/Startup/IosDependencyContainer.cs
  Toggl.Daneel/Startup/Setup.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Startup/Setup.cs
Labels: foundation, refactoring

#4917 Make iOS builds sanic again!
  Toggl.sln
  build.cake
Labels: ios

#4927 iPad: Fix modal dialog positioning
  Toggl.Daneel/Presentation/Transition/ModalDialogPresentationController.cs
Labels: bug, ios

#4930 iPad: Fix T&C view sizing
  Toggl.Daneel/Presentation/Transition/ModalDialogPresentationController.cs
  Toggl.Daneel/ViewControllers/TermsOfServiceViewController.cs
Labels: ios

#4931 iPad: Fix onboarding crash
  Toggl.Daneel/ViewControllers/OnboardingViewController.cs
Labels: ios

#4932 iPad: Fix bug that caused action dismiss action sheets to break
  Toggl.Daneel/Services/DialogServiceIos.cs
Labels: ios

#4938 iPad: Make the Select WS button bigger
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
Labels: ios

#4921 🚧 Fix 1password crash on iPad
  Toggl.Daneel/Services/OnePasswordServiceIos.cs
  Toggl.Daneel/Startup/IosDependencyContainer.cs
  Toggl.Daneel/ViewControllers/LoginViewController.cs
Labels: ios

#4945 Giskard 1.13.1 - Hotfix
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Activities/ReactiveActivity.cs
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#4941 iPad: Better reports sizing
  Toggl.Daneel/ViewControllers/ReportsViewController.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.designer.cs
  Toggl.Daneel/ViewControllers/ReportsViewController.xib
Labels: ios

#4558 Add UI test for removing project
  Toggl.Droid.Tests.UI/AndroidAccessibilityNames.cs
  Toggl.Tests.UI/EditTimeEntryTests.cs
  Toggl.Tests.UI/Extensions/MainExtensions.cs
  Toggl.Tests.UI/Extensions/SelectProjectExtensions.cs
  Toggl.Tests.UI/MainTests.cs
  Toggl.Tests.UI/Toggl.Tests.UI.projitems
Labels: ui-tests

#4940 Recreate lazy data source instance on login and logout
  Toggl.Core/DependencyContainer.cs
Labels: bug, foundation

#4948 🕷 fix the spider when device changes orientation
  Toggl.Daneel/Views/SpiderOnARopeView.cs
Labels: ios

#4949 Remove unused method
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
Labels: foundation

#4946 Android 1.13.2 - Hotfix
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android, release

#4951 Giskard 1.13.3 - Hotfix
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android, release

#4956 iPad: remove unneeded Giskard files
  Toggl.Giskard.Tests/Resources/Resource.designer.cs
  Toggl.Giskard/Resources/Resource.designer.cs
Labels: ios

#4958 iPad: The Ultimate Mergeback
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: ios

#4915 Fix crash in the wheel view when endTime < startTime
  Toggl.Daneel/Views/EditDuration/WheelForegroundView.cs
  Toggl.Droid/Views/EditDuration/WheelForegroundView.cs
Labels: android, bug, ios

#4965 Track everything we control in the droid handler scheduler
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.Droid/Startup/AndroidSchedulerProvider.cs
  Toggl.Droid/Startup/HandlerScheduler.cs
Labels: android

#4981 🐛 Replace Context.GetColor with ContextCompat.GetColor to avoid crashes on Android Api Pre-23
  Toggl.Droid/ViewHolders/MainLogCellViewHolder.cs
Labels: android, crash

#4969 🏂Add new Siri intent - create entry from clipboard
  Toggl.Core/Services/IIntentDonationService.cs
  Toggl.Droid/Services/NoopIntentDonationServiceAndroid.cs
  Toggl.iOS.IntentBinding/ApiDefinition.cs
  Toggl.iOS.IntentBinding/StructsAndEnums.cs
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/Base.lproj/Intents.intentdefinition
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/Info.plist
  Toggl.iOS.IntentCodeGen/Toggl.iOS.IntentCodeGen/en.lproj/Intents.strings
  Toggl.iOS.IntentStaticLib/Toggl.iOS.IntentStaticLib.xcodeproj/project.pbxproj
  Toggl.iOS.IntentStaticLib/Toggl.iOS.IntentStaticLib/StartTimerFromClipboardIntent.h
  Toggl.iOS.IntentStaticLib/Toggl.iOS.IntentStaticLib/StartTimerFromClipboardIntent.m
  Toggl.iOS.IntentStaticLib/libToggl.iOS.IntentStaticLib.a
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension.UI/IntentViewController.cs
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.SiriExtension/IntentHandler.cs
  Toggl.iOS.SiriExtension/StartTimerFromClipboardIntentHandler.cs
  Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj
  Toggl.iOS/Services/IntentDonationServiceIos.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
Labels: ios

#4966 Improve project and tag creation cell unit tests
  Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs
Labels: foundation

#4968 Giskard 1.13.4 - Potassium Hotfix
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#4990 Use our dep container instead of Mvx
  Toggl.Droid/Activities/EditTimeEntryActivity.cs
Labels: android, crash, critical

#4993 🐛 Fix crashing in main log
  Toggl.Core.Tests/UI/ViewModels/MainTabBarViewModelTests.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
Labels: android, crash

#4998 :construction: Add basic presenter infra
  Toggl.Core.UI/Navigation/IPresenter.cs
  Toggl.Core.UI/Navigation/NavigationInfo.cs
  Toggl.Droid/Presentation/AndroidPresenter.cs
  Toggl.iOS/Presentation/IosPresenter.cs
Labels: android, ios

#4934 Adds grouped entry + RTL section + additional tests
  .github/ISSUE_TEMPLATE/d-manual-test-template.md
Labels: ui-tests

#4964 Daneel Release 1.21 — Iss
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-152x152.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-167x167.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57.png
  Toggl.iOS/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76.png
  Toggl.iOS/Info.plist
  Toggl.iOS/Startup/AppDelegate.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/SignupViewController.cs
Labels: ios, release

#4995 Fix reports "this week" label
  Toggl.Core.Tests/UI/ViewModels/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Shared.Tests/DateTimeOffsetExtensionsTests.cs
  Toggl.Shared/Extensions/DateTimeOffsetExtensions.cs
Labels: bug, foundation

#4988 Giskard 1.14 - Calcium
  Toggl.Droid/Activities/EditDurationActivity.cs
  Toggl.Droid/Extensions/MotionEventExtensions.cs
  Toggl.Droid/Extensions/PointExtensions.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Views/EditDuration/Shapes/ClockDial.cs
  Toggl.Droid/Views/EditDuration/Shapes/Dot.cs
  Toggl.Droid/Views/EditDuration/WheelForegroundView.cs
Labels: android, release
