Repository toggl/mobileapp, pull requests merged in 2020-03, with the labels that each got.

#7140 iOS 2.12: Mango
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Info.plist
Labels: ios, release

#7107 Add the droid onboarding screen
  Toggl.Droid/Activities/OnboardingActivity.ViewBinds.cs
  Toggl.Droid/Activities/OnboardingActivity.cs
  Toggl.Droid/Presentation/ActivityPresenter.cs
  Toggl.Droid/Resources/drawable/contained_button.xml
  Toggl.Droid/Resources/drawable/outline_button.xml
  Toggl.Droid/Resources/drawable/raised_button.xml
  Toggl.Droid/Resources/layout/OnboardingActivity.axml
  Toggl.Droid/Resources/raw/togglman.mp4
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.iOS/ViewControllers/SignupViewController.cs
Labels: android

#7138 Create TOS & Country screen for Android
  Toggl.Droid/Activities/BaseTermsAndCountryActivity.ViewBinds.cs
  Toggl.Droid/Activities/BaseTermsAndCountryActivity.cs
  Toggl.Droid/Activities/TermsAndCountryFullActivity.cs
  Toggl.Droid/Activities/TermsAndCountryModalActivity.cs
  Toggl.Droid/Presentation/ActivityPresenter.cs
  Toggl.Droid/Resources/drawable/country_picker_outline.xml
  Toggl.Droid/Resources/drawable/ic_dropdown.xml
  Toggl.Droid/Resources/drawable/modal_activity_background.xml
  Toggl.Droid/Resources/layout/TermsAndCountryActivity.axml
  Toggl.Droid/Resources/layout/TermsAndCountryModalActivity.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#7135 🚧 Add firebase setUserId to analytics
  Toggl.Core.Tests/Interactors/UserAccess/LogoutInteractorTests.cs
  Toggl.Core.Tests/UI/ViewModels/LoginViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Interactors/UserAccess/LogoutInteractor.cs
  Toggl.Droid/Services/AnalyticsServiceAndroid.cs
  Toggl.iOS/Services/AnalyticsServiceIos.cs
Labels: foundation, metrics

#7152 Handle errors in siri shortcuts view
  Toggl.iOS/Services/IntentDonationService.cs
Labels: ios

#7149 Create new email signup screen for Android
  Toggl.Core.Tests/UI/ViewModels/OldSignUpViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/OldSignUpViewModel.cs
  Toggl.Core.UI/ViewModels/SignUpViewModel.cs
  Toggl.Droid/Activities/SignUpActivity.ViewBinds.cs
  Toggl.Droid/Activities/SignUpActivity.cs
  Toggl.Droid/Extensions/Reactive/EditTextExtensions.cs
  Toggl.Droid/Extensions/Reactive/ToolbarExtensions.cs
  Toggl.Droid/Presentation/ActivityPresenter.cs
  Toggl.Droid/Resources/color/outline_text_input_color.xml
  Toggl.Droid/Resources/layout/SignUpActivity.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values-v26/Styles.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/packages.config
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: android

#7160 Fix "Add a project and tags on the fly" onboarding flickering tooltip
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
Labels: android, bug

#7161 Fix calendar settings overlapping bottom nav
  Toggl.Droid/Activities/CalendarSettingsActivity.ViewBinds.cs
Labels: android, bug

#7162 Add ripple to token reset activity sign out button
  Toggl.Droid/Resources/layout/TokenResetActivity.axml
Labels: android

#7164 Fix date format slash string
  Toggl.Shared.Tests/DateFormatTests.cs
  Toggl.Shared/DateFormat.cs
Labels: android, bug

#7165 Don't show fragments until the activity is started
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Extensions/ActivityExtensions.cs
  Toggl.Droid/Presentation/ViewModelCache.cs
Labels: android, crash

#7150 Use AsDriver and DistinctUntilChanged in SignUpViewModel
  Toggl.Core.Tests/UI/ViewModels/SignUpViewModelTests.cs
  Toggl.Core.UI/ViewModels/SignUpViewModel.cs
  Toggl.iOS/ViewControllers/SignUpViewController.cs
Labels: foundation, ios

#7167 Send fullname if possible on sign up with Apple
  Toggl.Core.Tests/UI/ViewModels/LoginViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SignupViewModelTests.cs
  Toggl.Core.Tests/UserAccessManager/UserAccessManagerTests.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/SignupViewModel.cs
  Toggl.Core.UI/Views/IThirdPartyTokenProvider.cs
  Toggl.Core/Helper/ThirdPartyLoginInfo.cs
  Toggl.Core/UserAccessManager/IUserAccessManager.cs
  Toggl.Core/UserAccessManager/UserAccessManager.cs
  Toggl.Droid/Activities/ReactiveActivity.ThirdPartyTokenProvider.cs
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.PermissionHandler.cs
  Toggl.Droid/Fragments/ReactiveDialogFragment.cs
  Toggl.Droid/Fragments/ReactiveTabFragment.cs
  Toggl.Networking.Tests/ApiClients/UserApiTests.cs
  Toggl.Networking/ApiClients/Interfaces/IUserApi.cs
  Toggl.Networking/ApiClients/UserApi.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.cs
  Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.ThirdPartyTokenProvider.cs
Labels: foundation, ios

#7142 Create email login screen for iOS
  Toggl.Core.Tests/UI/ViewModels/EmailLoginViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/EmailLoginViewModel.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core/UserAccessManager/UserAccessManager.cs
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Extensions/Reactive/UIViewControllerExtensions.cs
  Toggl.iOS/Presentation/OnboardingPresenter.cs
  Toggl.iOS/Presentation/PageSheetPresenter.cs
  Toggl.iOS/Presentation/RootPresenter.cs
  Toggl.iOS/Presentation/ViewControllerLocator.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/Login.storyboard
  Toggl.iOS/ViewControllers/LoginViewController.cs
  Toggl.iOS/ViewControllers/LoginViewController.designer.cs
  Toggl.iOS/ViewControllers/LoginViewController.xib
  Toggl.iOS/ViewControllers/SignUpViewController.cs
Labels: ios

#7148 Android 2.12 - Manju
  Toggl.Droid/Activities/CalendarSettingsActivity.ViewBinds.cs
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Activities/StartTimeEntryActivity.cs
  Toggl.Droid/Extensions/ActivityExtensions.cs
  Toggl.Droid/Presentation/ViewModelCache.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/layout/TokenResetActivity.axml
  Toggl.Shared.Tests/DateFormatTests.cs
  Toggl.Shared/DateFormat.cs
Labels: android, release

#7159 Add new analytics events
  Toggl.Core.Tests/UI/ViewModels/LoginViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SignUpViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/TermsAndCountryViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/SignUpViewModel.cs
  Toggl.Core.UI/ViewModels/TermsAndCountryViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: foundation

#7169 Fix integration tests
  Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedEndpointBaseTests.cs
  Toggl.Networking.Tests.Integration/BaseTests/AuthenticatedGetEndpointBaseTests.cs
  Toggl.Networking.Tests.Integration/Properties/AssemblyInfo.cs
  Toggl.Networking.Tests.Integration/TimeEntriesApiTests.cs
Labels: tests

#7062 Calendar visual fixes
  Toggl.iOS/Cells/Calendar/CurrentTimeSupplementaryView.xib
  Toggl.iOS/Cells/Calendar/EditingHourSupplementaryView.xib
  Toggl.iOS/Cells/Calendar/HourSupplementaryView.xib
  Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs
Labels: glitch, ios

#7171 Add the onboarding pages
  Toggl.Droid/Activities/OnboardingActivity.ViewBinds.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Extensions/ColorAssets.cs
  Toggl.iOS/Resources/Colors.xcassets/OnboardingPage1BackgroundColor.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/OnboardingPage2BackgroundColor.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/OnboardingPage3BackgroundColor.colorset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_eyeball.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_eyeball.imageset/eyeball@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand@3x.png
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/periscope@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/pupil@2x.png
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
  Toggl.iOS/ViewControllers/OnboardingViewController.designer.cs
  Toggl.iOS/ViewControllers/OnboardingViewController.xib
  Toggl.iOS/Views/Onboarding/OnboardingPageView.cs
  Toggl.iOS/Views/Onboarding/OnboardingPageView.xib
  Toggl.iOS/Views/Onboarding/OnboardingStepView.designer.cs
  Toggl.iOS/Views/Onboarding/PeriscopeView.cs
  Toggl.iOS/Views/Onboarding/VideoView.cs
Labels: ios

#7173 🚧 Fix keyboardAware VCs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/KeyboardAwareViewController.cs
  Toggl.iOS/ViewControllers/Settings/SendFeedbackViewController.cs
  Toggl.iOS/ViewControllers/Settings/Siri/SiriShortcutsCustomTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Labels: ios

#7175 Add loading view
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.iOS/Resources/spinner-dark.gif
  Toggl.iOS/Resources/spinner-light.gif
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
  Toggl.iOS/Views/Onboarding/OnboardingLoadingView.cs
Labels: ios

#7177 Fix dark mode in iOS onboarding
  Toggl.iOS/ViewControllers/LoginViewController.xib
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.xib
  Toggl.iOS/ViewControllers/SignupViewController.xib
Labels: ios

#7180 Update onboarding assets
  Toggl.iOS/Resources/Images.xcassets/ic_eyeball.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_eyeball.imageset/eyeball.png
  Toggl.iOS/Resources/Images.xcassets/ic_eyeball.imageset/eyeball@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_eyeball.imageset/eyeball@3x.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand-1.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand@2x-1.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand@3x-1.png
  Toggl.iOS/Resources/Images.xcassets/ic_hand.imageset/ic_hand@3x.png
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/periscope.png
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/periscope@2x-1.png
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/periscope@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_periscope.imageset/periscope@3x.png
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/pupil.png
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/pupil@2x-1.png
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/pupil@2x.png
  Toggl.iOS/Resources/Images.xcassets/ic_pupil.imageset/pupil@3x.png
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/Views/Onboarding/PeriscopeView.cs
Labels: ios

#7181 Update onboarding copy
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: foundation

#7168 Add new onboarding email login screen for Android
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core/UserAccessManager/UserAccessManager.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.ViewBinds.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.cs
  Toggl.Droid/Activities/LoginActivity.ViewBinds.cs
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Droid/Activities/SignUpActivity.ViewBinds.cs
  Toggl.Droid/Resources/layout/ForgotPasswordActivity.axml
  Toggl.Droid/Resources/layout/LoginActivity.axml
  Toggl.Droid/Resources/layout/SignUpActivity.axml
  Toggl.Networking/Network/Credentials.cs
  Toggl.Shared/Password.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
Labels: android

#7187 Fix sign up bug
  Toggl.Core.Tests/UI/ViewModels/SignUpViewModelTests.cs
  Toggl.Core.UI/ViewModels/SignUpViewModel.cs
  Toggl.iOS/ViewControllers/LoginViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.designer.cs
  Toggl.iOS/ViewControllers/SignUpViewController.xib
  Toggl.iOS/ViewControllers/SignupViewController.designer.cs
  Toggl.iOS/ViewControllers/SignupViewController.xib
Labels: foundation, ios

#7174 Add actual onboarding slides
  Toggl.Droid/Activities/OnboardingActivity.ViewBinds.cs
  Toggl.Droid/Activities/OnboardingActivity.cs
  Toggl.Droid/Fragments/Onboarding/OnboardingFirstSlideFragment.ViewBinds.cs
  Toggl.Droid/Fragments/Onboarding/OnboardingFirstSlideFragment.cs
  Toggl.Droid/Fragments/Onboarding/OnboardingSecondSlideFragment.ViewBinds.cs
  Toggl.Droid/Fragments/Onboarding/OnboardingSecondSlideFragment.cs
  Toggl.Droid/Fragments/Onboarding/OnboardingThirdSlideFragment.ViewBinds.cs
  Toggl.Droid/Fragments/Onboarding/OnboardingThirdSlideFragment.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Resources/drawable-hdpi/onboarding_slide2_periscope.png
  Toggl.Droid/Resources/drawable-hdpi/onboarding_slide2_pupil.png
  Toggl.Droid/Resources/drawable-ldpi/onboarding_slide2_periscope.png
  Toggl.Droid/Resources/drawable-ldpi/onboarding_slide2_pupil.png
  Toggl.Droid/Resources/drawable-mdpi/onboarding_slide2_periscope.png
  Toggl.Droid/Resources/drawable-mdpi/onboarding_slide2_pupil.png
  Toggl.Droid/Resources/drawable-xhdpi/onboarding_slide2_periscope.png
  Toggl.Droid/Resources/drawable-xhdpi/onboarding_slide2_pupil.png
  Toggl.Droid/Resources/drawable-xhdpi/onboarding_slide3.png
  Toggl.Droid/Resources/drawable-xxhdpi/onboarding_slide2_periscope.png
  Toggl.Droid/Resources/drawable-xxhdpi/onboarding_slide2_pupil.png
  Toggl.Droid/Resources/drawable-xxhdpi/onboarding_slide3.png
  Toggl.Droid/Resources/drawable-xxxhdpi/onboarding_slide2_periscope.png
  Toggl.Droid/Resources/drawable-xxxhdpi/onboarding_slide2_pupil.png
  Toggl.Droid/Resources/drawable-xxxhdpi/onboarding_slide3.png
  Toggl.Droid/Resources/drawable/tab_indicator.xml
  Toggl.Droid/Resources/drawable/tab_indicator_deselected.xml
  Toggl.Droid/Resources/layout/OnboardingActivity.axml
  Toggl.Droid/Resources/layout/OnboardingFirstSlideFragment.axml
  Toggl.Droid/Resources/layout/OnboardingSecondSlideFragment.axml
  Toggl.Droid/Resources/layout/OnboardingThirdSlideFragment.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/packages.config
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: android

#7190 🐛 Fix infinite looping in TextObservers
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Droid/Activities/SignUpActivity.cs
Labels: android

#7189 Fix tags & project selection activities bottom margins
  Toggl.Droid/Activities/SelectProjectActivity.ViewBinds.cs
  Toggl.Droid/Activities/SelectTagsActivity.ViewBinds.cs
Labels: android, bug

#7188 Fix status bars on onboarding and ToS & Country activities
  Toggl.Droid/Activities/TermsAndCountryModalActivity.cs
  Toggl.Droid/Resources/layout/OnboardingActivity.axml
  Toggl.Droid/Resources/layout/TermsAndCountryModalActivity.axml
  Toggl.Droid/Resources/values/Styles.xml
Labels: android, glitch

#7212 Fix ToS & Country welcome message copy
  Toggl.Droid/Activities/BaseTermsAndCountryActivity.ViewBinds.cs
  Toggl.Droid/Activities/TermsAndCountryFullActivity.cs
  Toggl.Droid/Activities/TermsAndCountryModalActivity.cs
  Toggl.Droid/Fragments/TermsOfServiceFragment.ViewBinds.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/TermsAndCountryViewController.cs
  Toggl.iOS/ViewControllers/TermsOfServiceViewController.cs
Labels: android

#7213 Apply forgot password screen feedback
  Toggl.Core.UI/ViewModels/ForgotPasswordViewModel.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.ViewBinds.cs
  Toggl.Droid/Activities/ForgotPasswordActivity.cs
  Toggl.Droid/Resources/layout/ForgotPasswordActivity.axml
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs
Labels: android

#7205 Fix designs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/Extensions/ColorAssets.cs
  Toggl.iOS/Resources/Colors.xcassets/IconTint.colorset/Contents.json
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.designer.cs
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib
  Toggl.iOS/ViewControllers/LoginViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.cs
Labels: ios

#7200 Fix stuck animation in onboarding
  Toggl.iOS/Views/Onboarding/PeriscopeView.cs
Labels: ios

#7210 Fix google signup
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.iOS/Presentation/NavigationPresenter.cs
Labels: ios

#7221 Fix missing onboarding loading background
  Toggl.Droid/Activities/OnboardingActivity.ViewBinds.cs
  Toggl.Droid/Activities/OnboardingActivity.cs
  Toggl.Droid/Resources/layout/OnboardingActivity.axml
Labels: android, glitch

#7219 Apply login & signup feedback
  Toggl.Droid/Activities/LoginActivity.ViewBinds.cs
  Toggl.Droid/Activities/LoginActivity.cs
  Toggl.Droid/Activities/SignUpActivity.cs
  Toggl.Droid/Helper/TextHelpers.cs
  Toggl.Droid/Resources/layout/LoginActivity.axml
  Toggl.Droid/Resources/layout/SignUpActivity.axml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Shared/Resources.resx
Labels: android

#7225 Fix loading animation
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
Labels: foundation

#7226 Cherry pick iOS fixes
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SignUpViewModelTests.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Core.UI/ViewModels/SignUpViewModel.cs
  Toggl.iOS/Presentation/NavigationPresenter.cs
  Toggl.iOS/ViewControllers/LoginViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.designer.cs
  Toggl.iOS/ViewControllers/SignUpViewController.xib
  Toggl.iOS/ViewControllers/SignupViewController.designer.cs
  Toggl.iOS/ViewControllers/SignupViewController.xib
Labels: android

#7229 Track onboarding continue with email event
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
Labels: metrics

#7220 Apply onboarding feedback
  Toggl.Droid/Fragments/Onboarding/OnboardingFirstSlideFragment.ViewBinds.cs
  Toggl.Droid/Resources/drawable-hdpi/togglman.png
  Toggl.Droid/Resources/drawable-mdpi/togglman.png
  Toggl.Droid/Resources/drawable-xhdpi/togglman.png
  Toggl.Droid/Resources/drawable-xxhdpi/togglman.png
  Toggl.Droid/Resources/drawable-xxxhdpi/toggman.png
  Toggl.Droid/Resources/layout/OnboardingFirstSlideFragment.axml
  Toggl.Droid/Resources/raw/togglman.mp4
  Toggl.Droid/Resources/values/Styles.xml
  Toggl.Droid/Toggl.Droid.csproj
Labels: android

#7227 Fix keyboard in email login and signup flow
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.designer.cs
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib
  Toggl.iOS/ViewControllers/LoginViewController.cs
  Toggl.iOS/ViewControllers/LoginViewController.designer.cs
  Toggl.iOS/ViewControllers/LoginViewController.xib
  Toggl.iOS/ViewControllers/SignUpViewController.cs
  Toggl.iOS/ViewControllers/SignUpViewController.designer.cs
  Toggl.iOS/ViewControllers/SignUpViewController.xib
  Toggl.iOS/ViewControllers/SignupViewController.designer.cs
  Toggl.iOS/ViewControllers/SignupViewController.xib
  Toggl.iOS/Views/Onboarding/OnboardingPageView.xib
Labels: ios

#7237 🔥 Remove label fixed width
  Toggl.iOS/ViewControllers/EditDurationViewController.xib
Labels: ios

#7239 Fix dark mode in forgot password view
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib
Labels: ios

#7240 Fix onboarding font size and constraints
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib
  Toggl.iOS/ViewControllers/LoginViewController.xib
  Toggl.iOS/ViewControllers/SignUpViewController.xib
  Toggl.iOS/ViewControllers/SignupViewController.xib
  Toggl.iOS/ViewControllers/TermsAndCountryViewController.cs
  Toggl.iOS/ViewControllers/TermsAndCountryViewController.xib
  Toggl.iOS/Views/Onboarding/OnboardingPageView.cs
  Toggl.iOS/Views/Onboarding/OnboardingPageView.xib
Labels: ios

#7242 Track onboarding carousel analytics
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.UI/Models/OnboardingScrollParameters.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.Core/Analytics/OnboardingScrollAction.cs
  Toggl.Core/Analytics/OnboardingScrollDirection.cs
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
Labels: foundation, ios, metrics

#7232 Fix query text span ctor invocation on AutocompleteExtensions:AsImmutableSpans
  Toggl.Droid/Autocomplete/AutocompleteExtensions.cs
Labels: android, crash

#7244 Fix missing togglman.png file on drawable-xxxhdpi
  Toggl.Droid/Resources/drawable-xxxhdpi/togglman.png
Labels: android, bug

#7245 💄 Fix reports segment colors
  Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartFilled.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartTotal.colorset/Contents.json
Labels: ios

#7248 Fix copy, buttons and dark mode in onboarding
  Toggl.Core.UI/ViewModels/TermsAndCountryViewModel.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib
  Toggl.iOS/ViewControllers/TermsAndCountryViewController.cs
  Toggl.iOS/ViewControllers/TermsAndCountryViewController.designer.cs
  Toggl.iOS/ViewControllers/TermsAndCountryViewController.xib
Labels: ios

#7250 Fix crash in iOS 12
  Toggl.iOS/Extensions/Reactive/UIViewControllerExtensions.cs
Labels: ios

#7251 Replace nonBillable hex transparency with a solid color
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
Labels: android, glitch

#7230 Fix calendar view scroll to start
  Toggl.Droid/Fragments/CalendarFragment.cs
Labels: android, crash

#7243 Easen up splashscreen transition
  Toggl.Core.Tests/UI/ViewModels/TokenResetViewModelTests.cs
  Toggl.Core.UI/ViewModels/TokenResetViewModel.cs
  Toggl.Droid/Activities/OnboardingActivity.cs
  Toggl.Droid/Activities/TokenResetActivity.cs
  Toggl.Droid/Startup/SplashScreen.cs
  Toggl.iOS/ViewControllers/TokenResetViewController.cs
Labels: android, bug

#7264 Fix orientation request crash on api 26
  Toggl.Droid/Activities/TermsAndCountryModalActivity.cs
Labels: android, crash
