Repository toggl/mobileapp, pull requests merged in 2020-06, with the labels that each got.

#7457 First round of bug fixes for sync pull
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.Sync.cs
  Toggl.Core/Interactors/Sync/PullDataInteractor.cs
  Toggl.Storage.Realm/Models/RealmConstructors.cs
  Toggl.Storage.Realm/Queries/ProcessPullResultQuery.cs
  Toggl.Storage.Realm/RealmConfigurator.cs
  Toggl.Storage.Realm/SinceParameterStorage.cs
Labels: sync

#7461 🔖 Include Sync Pull (v2) into the syncing algorithm
  Toggl.Core/Sync/v2/SyncManagerV2.cs
Labels: sync

#7467 Start onboarding time entry after authentication
  Toggl.Core.Tests/Interactors/TimeEntry/CreateOnboardingTimeEntryIfNeededInteractorTests.cs
  Toggl.Core.Tests/UI/ViewModels/LoginViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/SignUpViewModelTests.cs
  Toggl.Core.UI/ViewModels/LoginViewModel.cs
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Core.UI/ViewModels/SignUpViewModel.cs
  Toggl.Core/Analytics/TimeEntryStartOrigin.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.TimeEntry.cs
  Toggl.Core/Interactors/TimeEntry/CreateOnboardingTimeEntryIfNeededInteractor.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/Settings/IOnboardingStorage.cs
  Toggl.Storage/Settings/SettingsStorage.cs
Labels: foundation

#7474 Make Preferences and User 3-way-mergeable
  Toggl.Core.Tests/Mocks/MockPreferences.cs
  Toggl.Core.Tests/Mocks/MockUser.cs
  Toggl.Core/DataSources/PreferencesDataSource.cs
  Toggl.Core/DataSources/TimeEntriesDataSource.cs
  Toggl.Core/DataSources/UserDataSource.cs
  Toggl.Core/Models/FoundationModels.Backups.cs
  Toggl.Core/Models/Preferences.cs
  Toggl.Networking/Models/Preferences.Backup.cs
  Toggl.Networking/Models/Preferences.cs
  Toggl.Networking/Models/User.Backup.cs
  Toggl.Shared/Models/IPreferences.Backup.cs
  Toggl.Shared/Models/IPreferences.cs
  Toggl.Shared/Models/IUser.Backup.cs
  Toggl.Shared/Models/IUser.cs
  Toggl.Shared/TimeFormat.cs
  Toggl.Storage.Realm/Models/RealmPreferences.Backup.cs
  Toggl.Storage.Realm/Models/RealmTimeEntry.Backup.cs
  Toggl.Storage.Realm/Models/RealmUser.Backup.cs
  Toggl.Storage.Realm/Queries/ProcessPullResultQuery.cs
  Toggl.Storage.Realm/RealmConfigurator.cs
Labels: sync

#7480 Implement currently running time entry tooltip
  Toggl.Core.UI/Helper/OnboardingConstants.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/OnboardingCondition.cs
  Toggl.Storage/Settings/IOnboardingStorage.cs
  Toggl.Storage/Settings/SettingsStorage.cs
  Toggl.iOS/Extensions/ColorAssets.cs
  Toggl.iOS/Extensions/OnboardingExtensions.cs
  Toggl.iOS/Resources/Colors.xcassets/OnboardingTooltipBackground.colorset/Contents.json
  Toggl.iOS/Resources/Colors.xcassets/OnboardingTooltipTextColor.colorset/Contents.json
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
  Toggl.iOS/Views/TriangleView.cs
Labels: foundation, ios

#7483 Use Stopwatch instead of TimeService for measurements
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/PerformanceMeasurement.cs
  Toggl.Droid/Services/AnalyticsServiceAndroid.cs
  Toggl.Droid/Startup/AndroidDependencyContainer.cs
  Toggl.iOS/Services/AnalyticsServiceIos.cs
  Toggl.iOS/Startup/IosDependencyContainer.cs
Labels: sync

#7484 Make running time entry tooltip conform to specs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Storage/OnboardingCondition.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: foundation, ios

#7455 Fix keyboard covering duration edit text
  Toggl.Droid/Activities/EditDurationActivity.cs
Labels: android, glitch

#7488 Dismiss running time entry tooltip after tapping on a time entry
  Toggl.Core.UI/ViewModels/MainViewModel.cs
Labels: foundation

#7491 Update running time entry tooltip copy
  Toggl.Shared/Resources.resx
Labels: foundation

#7495 Add the Here Is Your Entry tooltip
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Droid/Fragments/MainFragment.ViewBinds.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Resources/drawable/background_tooltip.xml
  Toggl.Droid/Resources/drawable/shape_diamond.xml
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Views/TooltipLayout.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
Labels: android

#7490 Implement tooltip: "Tapping here will start the timer"
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/OnboardingCondition.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
  Toggl.iOS/Views/TriangleView.cs
Labels: foundation, ios

#7509 Fix running time entry tooltip not disappearing after stopping the entry
  Toggl.Core.UI/ViewModels/MainViewModel.cs
Labels: foundation

#7500 Add the projects tooltip in the edit view
  Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/OnboardingCondition.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.designer.cs
  Toggl.iOS/ViewControllers/EditTimeEntryViewController.xib
  Toggl.iOS/Views/TriangleView.cs
Labels: foundation, ios

#7489 Avoid sync status bar hiding automatically
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.iOS/Views/Log/RefreshControl.cs
Labels: ios

#7505 Implement the android tooltip: "Tapping here will start the timer"
  Toggl.Droid/Fragments/MainFragment.ViewBinds.cs
  Toggl.Droid/Fragments/MainFragment.cs
  Toggl.Droid/Resources/layout/MainFragment.axml
  Toggl.Droid/Resources/layout/TooltipWithCenteredBottomArrow.axml
  Toggl.Droid/Resources/layout/TooltipWithRightBottomArrow.axml
  Toggl.Droid/Resources/values/Attrs.xml
  Toggl.Droid/Views/TooltipLayout.cs
Labels: android

#7492 Apply color transformations to reports
  Toggl.Droid/ViewHolders/Reports/ReportDonutChartLegendItemViewHolder.cs
  Toggl.Droid/Views/DonutChart/DonutChartView.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartLegendCollectionViewCell.cs
  Toggl.iOS/Views/Reports/DonutChartView.cs
Labels: android, ios

#7528 Add projects tooltip in the start view
  Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/OnboardingCondition.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.designer.cs
  Toggl.iOS/ViewControllers/StartTimeEntryViewController.xib
Labels: foundation, ios

#7542 Fix three way merge
  Toggl.Storage.Realm/Models/RealmTimeEntry.cs
  Toggl.Storage.Realm/Queries/ProcessPullResultQuery.cs
  Toggl.Storage.Realm/Sync/BackupHelper.cs
Labels: bug

#7539 Implement the "Youve created your first entry" tooltip
  Toggl.Core.UI/Helper/OnboardingConstants.cs
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/OnboardingCondition.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
  Toggl.iOS/ViewSources/TimeEntriesLogViewSource.cs
  Toggl.iOS/Views/TriangleView.cs
Labels: foundation, ios

#7530 Implement stop time entry tooltip
  Toggl.Core.UI/ViewModels/MainViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Storage/OnboardingCondition.cs
  Toggl.Storage/Settings/IOnboardingStorage.cs
  Toggl.Storage/Settings/SettingsStorage.cs
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
Labels: foundation, ios

#7555 Use per-property backup flag for Time Entries
  Toggl.Core.Tests/Mocks/MockTimeEntry.cs
  Toggl.Core/DataSources/TimeEntriesDataSource.cs
  Toggl.Core/Models/FoundationConstructors.cs
  Toggl.Core/Models/FoundationModels.Backups.cs
  Toggl.Networking.Tests/Sync/Push/PushActionsTests.cs
  Toggl.Networking/Models/TimeEntry.Backup.cs
  Toggl.Shared/Models/ITimeEntry.Backup.cs
  Toggl.Storage.Realm/Models/RealmConstructors.cs
  Toggl.Storage.Realm/Models/RealmTimeEntry.Backup.cs
  Toggl.Storage.Realm/Models/RealmTimeEntry.cs
  Toggl.iOS.Shared/Models/TimeEntry.cs
Labels: sync

#7554 Prevent suggestions until there are at least 5 time entries
  Toggl.Core.Tests/Interactors/Suggestions/GetSuggestionsInteractorTests.cs
  Toggl.Core/Interactors/Suggestions/GetSuggestionsInteractor.cs
Labels: foundation

#7558 ♻ Sync status for each property
  Toggl.Core.Tests/Mocks/MockPreferences.cs
  Toggl.Core.Tests/Mocks/MockTimeEntry.cs
  Toggl.Core.Tests/Mocks/MockUser.cs
  Toggl.Core/DataSources/PreferencesDataSource.cs
  Toggl.Core/DataSources/TimeEntriesDataSource.cs
  Toggl.Core/DataSources/UserDataSource.cs
  Toggl.Core/Models/FoundationConstructors.cs
  Toggl.Core/Models/FoundationModels.Backups.cs
  Toggl.Core/Models/Preferences.cs
  Toggl.Core/Sync/ConflictResolution/TimeEntryRivalsResolver.cs
  Toggl.Networking.Tests/Sync/Push/PushActionsTests.cs
  Toggl.Networking/Models/Preferences.Backup.cs
  Toggl.Networking/Models/TimeEntry.Backup.cs
  Toggl.Networking/Models/User.Backup.cs
  Toggl.Networking/Sync/Push/Serialization/PartiallySerializableTimeEntry.cs
  Toggl.Shared/Models/IPreferences.Backup.cs
  Toggl.Shared/Models/ITimeEntry.Backup.cs
  Toggl.Shared/Models/IUser.Backup.cs
  Toggl.Shared/PropertySyncStatus.cs
  Toggl.Storage.Realm/Models/RealmConstructors.cs
  Toggl.Storage.Realm/Models/RealmPreferences.Backup.cs
  Toggl.Storage.Realm/Models/RealmPreferences.cs
  Toggl.Storage.Realm/Models/RealmTimeEntry.Backup.cs
  Toggl.Storage.Realm/Models/RealmTimeEntry.cs
  Toggl.Storage.Realm/Models/RealmUser.Backup.cs
  Toggl.Storage.Realm/Models/RealmUser.cs
  Toggl.Storage.Realm/Queries/ProcessPullResultQuery.cs
  Toggl.Storage.Realm/Queries/ProcessPushResultQuery.cs
  Toggl.Storage.Realm/Sync/BackupHelper.cs
  Toggl.Storage.Realm/Sync/ThreeWayMerge.cs
  Toggl.iOS.Shared/Models/TimeEntry.cs
Labels: blocking

#7566 ✍ Add more log output to debug android errors
  Toggl.Core/Sync/v2/SyncManagerV2.cs
  Toggl.Droid/Startup/SplashScreen.cs
Labels: sync

#7569 Fix workspace ID/project ID mismatch in TE serialization
  Toggl.Networking/Sync/Push/Serialization/PartiallySerializableTimeEntry.cs
Labels: bug

#7571 Fix deserializing and persisting workspace features
  Toggl.Networking/Sync/Pull/IResponse.cs
  Toggl.Networking/Sync/Pull/Response.cs
  Toggl.Storage.Realm/Models/RealmConstructors.cs
  Toggl.Storage.Realm/Models/RealmWorkspaceFeatureCollection.cs
  Toggl.Storage.Realm/Queries/ProcessPullResultQuery.cs
Labels: bug

#7574 🔥 Remove logs on startup
  Toggl.Droid/Startup/SplashScreen.cs
Labels: android, sync

#7573 Implement autoscrolling for view pagers
  Toggl.Core.UI/ViewModels/OnboardingViewModel.cs
  Toggl.Droid/Activities/OnboardingActivity.ViewBinds.cs
  Toggl.Droid/Activities/OnboardingActivity.cs
  Toggl.Droid/Resources/layout/OnboardingActivity.axml
  Toggl.iOS/ViewControllers/OnboardingViewController.cs
Labels: android, ios
