Repository toggl/mobileapp, pull requests merged in 2020-09, with the labels that each got.

#7741 📐 Calendar item fixes based on feedback
  Toggl.iOS/Cells/Calendar/CalendarItemView.xib
  Toggl.iOS/Transformations/CalendarProjectTaskClientToAttributedString.cs
Labels: coral-capybara

#7740 👨‍🎨 Redesign calendar items on Android
  Toggl.Droid/Extensions/StaticLayoutExtensions.cs
  Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.cs
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Resources/values/Dimen.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/Views/Calendar/CalendarDayView.Background.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.EditItem.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.cs
Labels: coral-capybara

#7742 📅 Add calendar icon again
  Toggl.iOS/Cells/Calendar/CalendarItemView.cs
  Toggl.iOS/Cells/Calendar/CalendarItemView.designer.cs
  Toggl.iOS/Cells/Calendar/CalendarItemView.xib
Labels: coral-capybara

#7744 🐛 Fix bug when trying to edit calendar items
  Toggl.Droid/Fragments/CalendarFragment.cs
Labels: coral-capybara

#7747 📵 Disable external calendars sync for the upcoming release
  Toggl.Core.Tests/Interactors/ExternalCalendars/SyncExternalCalendarsInteractorTests.cs
  Toggl.Core/Interactors/ExternalCalendars/SyncExternalCalendarsInteractor.cs
Labels: coral-capybara

#7750 iOS 2.19 - Tomato
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Info.plist
Labels: ios, release

#7751 Android 2.19 - Tiramisu
  Toggl.Droid/Properties/AndroidManifest.xml
Labels: android, release

#7754 Add empty state for the billable/non-billable bar chart in the reports
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/ViewModels/Reports/ReportProjectsBarChartPlaceholderElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.fr.resx
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.pt.resx
  Toggl.Shared/Resources.resx
  Toggl.iOS/Cells/Reports/ReportsBarChartPlaceholderCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartPlaceholderCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsBarChartPlaceholderCollectionViewCell.xib
  Toggl.iOS/Presentation/TabPresenter.cs
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewCompactLayout.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewRegularLayout.cs
Labels: foundation, ios

#7755 Release/android 2.19.1 tiramisu hotfix
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs
Labels: android, release

#7756 Release/ios 2.19.1 tomato hotfix
  Toggl.Shared/Resources.fr.resx
  Toggl.Shared/Resources.ja.resx
  Toggl.Shared/Resources.pt.resx
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Cells/Calendar/CalendarItemView.cs
  Toggl.iOS/Info.plist
Labels: ios, release

#7734 Add change date range tooltip in the Reports view
  Toggl.Core.Tests/UI/ViewModels/Reports/ReportsViewModelTests.cs
  Toggl.Core.UI/Navigation/ViewModelLoader.cs
  Toggl.Core.UI/ViewModels/MainTabBarViewModel.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.Storage/OnboardingCondition.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
  Toggl.iOS/ViewControllers/ReportsViewController.designer.cs
  Toggl.iOS/ViewControllers/ReportsViewController.xib
Labels: ios

#7761 🚧 Finish/fix external calendars sync
  Toggl.Core.Tests/Interactors/ExternalCalendars/PullExternalCalendarEventsInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/PullExternalCalendarsInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/SyncExternalCalendarsInteractorTests.cs
  Toggl.Core.Tests/UI/Services/PermissionAwareCalendarServiceTests.cs
  Toggl.Core.UI/Services/PermissionAwareCalendarService.cs
  Toggl.Core/Calendar/CalendarItem.cs
  Toggl.Core/Interactors/ExternalCalendars/PullExternalCalendarEventsInteractor.cs
  Toggl.Core/Interactors/ExternalCalendars/PullExternalCalendarsInteractor.cs
  Toggl.Core/Interactors/ExternalCalendars/SyncExternalCalendarsInteractor.cs
  Toggl.Core/Models/Calendar/ExternalCalendar.cs
  Toggl.Core/Models/Calendar/ExternalCalendarEvent.cs
  Toggl.Droid/Services/CalendarServiceAndroid.cs
  Toggl.Networking.Tests/Models/Calendar/ExternalCalendarEventsPageTests.cs
  Toggl.Networking.Tests/Models/Calendar/ExternalCalendarsPageTests.cs
  Toggl.Networking/ApiClients/ExternalCalendarsApi.cs
  Toggl.Networking/ApiClients/Interfaces/IExternalCalendarsApi.cs
  Toggl.Networking/Helpers/BaseUrls.cs
  Toggl.Networking/Models/Calendar/CalendarIntegration.cs
  Toggl.Networking/Models/Calendar/ExternalCalendar.cs
  Toggl.Networking/Models/Calendar/ExternalCalendarEvent.cs
  Toggl.Networking/Network/Integrations/CalendarEndpoints.cs
  Toggl.Networking/Network/Integrations/Endpoints.cs
  Toggl.Shared/Models/Calendar/ICalendarIntegration.cs
  Toggl.Shared/Models/Calendar/IExternalCalendar.cs
  Toggl.Shared/Models/Calendar/IExternalCalendarEvent.cs
  Toggl.Storage.Realm/Models/Calendar/RealmExternalCalendar.cs
  Toggl.Storage.Realm/Models/Calendar/RealmExternalCalendarEvent.cs
  Toggl.Storage.Realm/RealmConfigurator.cs
  Toggl.Storage/Models/Calendar/IDatabaseExternalCalendar.cs
Labels: coral-capybara

#7762 Add new empty state for Donut chart in Reports
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartPlaceholderElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportDonutChartPlaceholderIllustrationElement.cs
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Droid/Properties/AndroidManifest.xml
  Toggl.Shared/Resources.Designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartPlaceholderCollectionViewCell.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartPlaceholderCollectionViewCell.designer.cs
  Toggl.iOS/Cells/Reports/ReportsDonutChartPlaceholderCollectionViewCell.xib
  Toggl.iOS/Resources/Images.xcassets/Image-2.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/pieChartIllustration.imageset/Contents.json
  Toggl.iOS/Resources/Images.xcassets/pieChartIllustration.imageset/Pie.png
  Toggl.iOS/Resources/Images.xcassets/pieChartIllustration.imageset/Pie@2x.png
  Toggl.iOS/Resources/Images.xcassets/pieChartIllustration.imageset/Pie@3x.png
  Toggl.iOS/Toggl.iOS.csproj
  Toggl.iOS/ViewSources/ReportsCollectionViewSource.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewCompactLayout.cs
  Toggl.iOS/Views/Reports/ReportsCollectionViewRegularLayout.cs
Labels: ios

#7764 Add Recommend Toggl Track to others button
  Toggl.Core.UI/ViewModels/Settings/SettingsViewModel.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
  Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs
Labels: ios

#7765 Add analytics to tap on Get Tracking
  Toggl.Core/Analytics/BaseAnalyticsService.cs
  Toggl.Core/Analytics/IAnalyticsService.cs
  Toggl.iOS/ViewControllers/ReportsViewController.cs
Labels: foundation, ios

#7770 iOS 2.19.3 - Tomato hot fix
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.designer.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.xib
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
Labels: ios, release

#7763 📅 Show events from selected calendars
  Toggl.Core.Tests/CalendarItemTests.cs
  Toggl.Core.Tests/Interactors/Calendar/GetCalendarItemsForDateInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/PullExternalCalendarEventsInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/SyncExternalCalendarsInteractorTests.cs
  Toggl.Core.Tests/Interactors/Notifications/ScheduleEventNotificationsInteractorTests.cs
  Toggl.Core.Tests/Interactors/Suggestions/CalendarSuggestionProviderTests.cs
  Toggl.Core.Tests/UI/Calendar/CalendarLayoutCalculatorTests.cs
  Toggl.Core.Tests/UI/Services/PermissionAwareCalendarServiceTests.cs
  Toggl.Core.Tests/UI/ViewModels/CalendarContextualMenuViewModelTests.cs
  Toggl.Core.Tests/UI/ViewModels/CalendarDayViewModelTests.cs
  Toggl.Core.UI/Calendar/CalendarLayoutCalculator.cs
  Toggl.Core.UI/Services/PermissionAwareCalendarService.cs
  Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs
  Toggl.Core/Calendar/CalendarItem.cs
  Toggl.Core/Calendar/CalendarItemSource.cs
  Toggl.Core/Extensions/CalendarItemExtensions.cs
  Toggl.Core/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs
  Toggl.Droid/Services/CalendarServiceAndroid.cs
  Toggl.Droid/Views/Calendar/CalendarDayView.cs
  Toggl.Networking.Tests/Models/Calendar/ExternalCalendarEventsPageTests.cs
  Toggl.Networking/Models/Calendar/ExternalCalendarEvent.cs
  Toggl.iOS/Cells/Calendar/CalendarItemView.cs
  Toggl.iOS/Services/CalendarServiceIos.cs
Labels: coral-capybara

#7773 Add recommend Toggl to others setting for Android
  Toggl.Droid/Activities/SettingsActivity.ViewBinds.cs
  Toggl.Droid/Activities/SettingsActivity.cs
Labels: android

#7771 Add red badge to reports tab in Android
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Fragments/MainFragment.cs
Labels: android

#7775 🚧 Add the interactors to sync the selected calendars
  Toggl.Core.Tests/Interactors/ExternalCalendars/PushSelectedExternalCalendarsInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/SetExternalCalendarSelectedInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/SyncExternalCalendarsInteractorTests.cs
  Toggl.Core.Tests/UI/Services/PermissionAwareCalendarServiceTests.cs
  Toggl.Core/Interactors/ExternalCalendars/PushSelectedExternalCalendarsInteractor.cs
  Toggl.Core/Interactors/ExternalCalendars/SetExternalCalendarSelectedInteractor.cs
  Toggl.Core/Interactors/ExternalCalendars/SyncExternalCalendarsInteractor.cs
  Toggl.Core/Interactors/IInteractorFactory.cs
  Toggl.Core/Interactors/InteractorFactory.ExternalCalendars.cs
  Toggl.Core/Models/Calendar/ExternalCalendar.cs
  Toggl.Core/Models/Calendar/IThreadSafeExternalCalendar.cs
  Toggl.Networking/ApiClients/ExternalCalendarsApi.cs
  Toggl.Networking/ApiClients/Interfaces/IExternalCalendarsApi.cs
  Toggl.Networking/Network/Integrations/CalendarEndpoints.cs
  Toggl.Storage.Realm/Models/Calendar/RealmExternalCalendar.cs
  Toggl.Storage/Models/Calendar/IDatabaseExternalCalendar.cs
  Toggl.iOS/Startup/AppDelegate.cs
Labels: coral-capybara

#7781 🐛 Fix edge case of removing duplicated events
  Toggl.Core.Tests/Interactors/ExternalCalendars/PullExternalCalendarEventsInteractorTests.cs
  Toggl.Core.Tests/Interactors/ExternalCalendars/SyncExternalCalendarsInteractorTests.cs
  Toggl.Core.Tests/UI/Services/PermissionAwareCalendarServiceTests.cs
  Toggl.Core.UI/Services/PermissionAwareCalendarService.cs
  Toggl.Core/Calendar/CalendarItem.cs
  Toggl.Core/Models/Calendar/ExternalCalendarEvent.cs
  Toggl.Droid/Services/CalendarServiceAndroid.cs
  Toggl.Networking.Tests/Models/Calendar/ExternalCalendarEventsPageTests.cs
  Toggl.Networking/Models/Calendar/ExternalCalendarEvent.cs
  Toggl.Shared/Models/Calendar/IExternalCalendarEvent.cs
  Toggl.Storage.Realm/Models/Calendar/RealmExternalCalendarEvent.cs
  Toggl.iOS/Services/CalendarServiceIos.cs
Labels: coral-capybara

#7784 Merge develop into project/calendar-integration
  Toggl.iOS.SiriExtension.UI/Info.plist
  Toggl.iOS.SiriExtension/Info.plist
  Toggl.iOS.TimerWidgetExtension/Info.plist
  Toggl.iOS/Info.plist
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.designer.cs
  Toggl.iOS/ViewControllers/Calendar/CalendarViewController.xib
  Toggl.iOS/ViewControllers/MainViewController.cs
  Toggl.iOS/ViewControllers/MainViewController.designer.cs
  Toggl.iOS/ViewControllers/MainViewController.xib
Labels: coral-capybara

#7783 🐛 Handle exception when pushing external calendars
  Toggl.Core.Tests/Interactors/ExternalCalendars/PushSelectedExternalCalendarsInteractorTests.cs
  Toggl.Core/Interactors/ExternalCalendars/PushSelectedExternalCalendarsInteractor.cs
Labels: coral-capybara

#7787 🎨 Visual fixes from feedback
  Toggl.Droid/Resources/layout/ExternalCalendarsCardInfoView.axml
  Toggl.Droid/Resources/layout/ExternalCalendarsMainSectionHeader.axml
  Toggl.Droid/Resources/layout/NativeCalendarsMainSectionHeader.axml
  Toggl.Droid/Resources/layout/NativeCalendarsToggleIntegrationView.axml
  Toggl.Droid/Resources/layout/UserCalendarHeader.axml
  Toggl.Droid/Resources/layout/UserCalendarItem.axml
  Toggl.Droid/Resources/values-night/Colors.xml
  Toggl.iOS/Cells/Calendar/Settings/ExternalCalendarsCardInfoViewCell.xib
  Toggl.iOS/Resources/Colors.xcassets/CalendarSettingsCardBackground.colorset/Contents.json
Labels: coral-capybara

#7779 Add empty states views in Reports for Android
  Toggl.Droid/Activities/MainTabBarActivity.cs
  Toggl.Droid/Adapters/ReportsAdapter.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Resources/drawable-hdpi/pie_chart_illustration.png
  Toggl.Droid/Resources/drawable-ldpi/pie_chart_illustration.png
  Toggl.Droid/Resources/drawable-mdpi/pie_chart_illustration.png
  Toggl.Droid/Resources/drawable-xhdpi/pie_chart_illustration.png
  Toggl.Droid/Resources/drawable-xxhdpi/pie_chart_illustration.png
  Toggl.Droid/Resources/layout/ReportAdvancedOnWebCard.axml
  Toggl.Droid/Resources/layout/ReportBarChartPlaceholderElement.axml
  Toggl.Droid/Resources/layout/ReportDonutChartPlaceholderElement.axml
  Toggl.Droid/Resources/values/Attrs.xml
  Toggl.Droid/Resources/values/Colors.xml
  Toggl.Droid/Toggl.Droid.csproj
  Toggl.Droid/ViewHolders/Reports/ReportBarChartPlaceholderViewHolder.cs
  Toggl.Droid/ViewHolders/Reports/ReportDonutChartPlaceholderViewHolder.cs
  Toggl.Droid/Views/BarChartView.cs
  Toggl.Shared/Resources.Designer.cs
  Toggl.Shared/Resources.resx
Labels: android

#7788 Fix background colors
  Toggl.iOS/Cells/MainLog/TimeEntriesLogViewCell.xib
  Toggl.iOS/Cells/Reports/ReportsBarChartCollectionViewCell.xib
Labels: glitch, ios

#7782 Make OnboardingConditionKey value names consistent
  Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
  Toggl.Storage/OnboardingCondition.cs
Labels: amber-alpaca, foundation

#7786 Rename Toggl to Toggl Track in string resources
  Toggl.Shared/Resources.resx
Labels: amber-alpaca, foundation

#7772 Add date range tooltip for Android
  Toggl.Droid/Fragments/ReportsFragment.ViewBinds.cs
  Toggl.Droid/Fragments/ReportsFragment.cs
  Toggl.Droid/Resources/layout/ReportsFragment.axml
  Toggl.Droid/Resources/layout/TooltipWithCenteredTopArrow.xml
  Toggl.Droid/Resources/layout/TooltipWithLeftTopArrow.axml
  Toggl.Droid/Views/TooltipLayout.cs
  Toggl.Shared/Resources.resx
Labels: amber-alpaca, android

#7797 Add Japanese translations for Onboarding 3.0
  Toggl.Shared/Resources.ja.resx
Labels: amber-alpaca, foundation
